In [1]:
# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  MaD-CoRN: Deepfake Detection    
# ║
# ║  Paper: "MaD-CoRN: an efficient and lightweight deepfake detection          ║
# ║          approach using convolutional reservoir network"                    ║
# ╚══════════════════════════════════════════════════════════════════════════════╝
#
# USAGE IN JUPYTER
# ────────────────
# 1. pip install torch torchvision scikit-learn pillow numpy pandas
# 2. Set CONFIG below (data_dir, epochs, batch_size, etc.)
# 3. Run All Cells
#
# DATASET LAYOUT expected at data_dir:
#   celeb_df/
#       real/          ← or Celeb-real/, YouTube-real/
#           frame_001.jpg  ...
#       fake/          ← or Celeb-synthesis/
#           frame_001.jpg  ...
#
# OR pass csv_path pointing to a CSV with columns: path, label (0=real 1=fake)

In [1]:
#FF++ with balance configuration -- oversampling real data with augmentation techniques
!pip install scikit-learn torch torchvision tqdm pandas pillow

import os, io, json, math, time, random, warnings
import numpy as np
import pandas as pd
from dataclasses import dataclass, asdict
from PIL import Image, ImageFile

warnings.filterwarnings("ignore")
ImageFile.LOAD_TRUNCATED_IMAGES = True

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader, TensorDataset
import torchvision.transforms as T
from torch.cuda.amp import GradScaler, autocast

from tqdm.auto import tqdm
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score, accuracy_score

# ============================================================
# CONFIG
# ============================================================

CONFIG = dict(
    metadata_csv="/home/jovyan/.cache/kagglehub/datasets/xdxd003/ff-c23/versions/1/ffpp_preprocessed/metadata.csv",

    resolutions=[128, 224, 256, 384],
    image_size_for_model=224,

    epochs=15,
    batch_size=32,
    lr=1e-3,
    weight_decay=1e-4,
    label_smoothing=0.05,
    warmup_epochs=3,

    base_ch=32,

    num_workers=0,
    seed=42,
    save_dir="./mad_corn_results_ffpp_balanced",
    device="auto",
    smoke_test=False,
)

# ============================================================
# HELPERS
# ============================================================

def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

def auto_device(requested):
    if requested != "auto":
        return torch.device(requested)
    return torch.device("cuda" if torch.cuda.is_available() else "cpu")

set_seed(CONFIG["seed"])
DEVICE = auto_device(CONFIG["device"])
os.makedirs(CONFIG["save_dir"], exist_ok=True)

print("Torch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
print("Device:", DEVICE)

# ============================================================
# RESULT CLASSES
# ============================================================

@dataclass
class EpochResult:
    epoch: int
    train_loss: float
    train_acc: float
    train_auc: float
    val_acc: float
    val_auc: float
    precision: float
    recall: float
    f1: float
    uncertain_rate: float
    lr: float

@dataclass
class TestResult:
    model_name: str
    accuracy: float
    auc: float
    precision: float
    recall: float
    f1: float
    uncertain_rate: float

@dataclass
class ResolutionResult:
    resolution: int
    accuracy: float
    auc: float
    fast_pct: float
    medium_pct: float
    full_pct: float

@dataclass
class InferenceResult:
    mode: str
    time_per_image_ms: float
    fps: float

@dataclass
class TrainingTimeResult:
    model_type: str
    minutes: float
    hours: float

# ============================================================
# MODEL
# ============================================================

class ConvBNReLU(nn.Module):
    def __init__(self, in_ch, out_ch, kernel=3, stride=1, padding=1, groups=1):
        super().__init__()
        self.block = nn.Sequential(
            nn.Conv2d(in_ch, out_ch, kernel, stride, padding, groups=groups, bias=False),
            nn.BatchNorm2d(out_ch),
            nn.ReLU6(inplace=True),
        )

    def forward(self, x):
        return self.block(x)

class DepthwiseSeparable(nn.Module):
    def __init__(self, in_ch, out_ch, stride=1):
        super().__init__()
        self.dw = ConvBNReLU(in_ch, in_ch, kernel=3, stride=stride, padding=1, groups=in_ch)
        self.pw = ConvBNReLU(in_ch, out_ch, kernel=1, padding=0)

    def forward(self, x):
        return self.pw(self.dw(x))

class ConvReservoir(nn.Module):
    def __init__(self, in_ch, reservoir_ch=64, spectral_radius=0.9):
        super().__init__()
        self.input_proj = nn.Conv2d(in_ch, reservoir_ch, kernel_size=1, bias=False)
        self.input_bn = nn.BatchNorm2d(reservoir_ch)

        W = torch.randn(reservoir_ch, reservoir_ch, 3, 3)
        W = W / (W.abs().max() + 1e-8) * spectral_radius
        self.register_buffer("W_res", W)

        self.readout = nn.Sequential(
            nn.Conv2d(reservoir_ch, reservoir_ch, kernel_size=1, bias=False),
            nn.BatchNorm2d(reservoir_ch),
            nn.ReLU6(inplace=True),
        )

    def forward(self, x):
        h = F.relu(self.input_bn(self.input_proj(x)))
        h_res = torch.tanh(F.conv2d(h, self.W_res, padding=1))
        return self.readout(h + h_res)

class ChannelAttention(nn.Module):
    def __init__(self, channels, reduction=4):
        super().__init__()
        mid = max(channels // reduction, 8)
        self.gate = nn.Sequential(
            nn.AdaptiveAvgPool2d(1),
            nn.Flatten(),
            nn.Linear(channels, mid),
            nn.ReLU(inplace=True),
            nn.Linear(mid, channels),
            nn.Sigmoid(),
        )

    def forward(self, x):
        w = self.gate(x).view(x.size(0), x.size(1), 1, 1)
        return x * w

class SpatialAttention(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = nn.Conv2d(2, 1, kernel_size=7, padding=3, bias=False)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        avg = x.mean(dim=1, keepdim=True)
        mx, _ = x.max(dim=1, keepdim=True)
        return x * self.sigmoid(self.conv(torch.cat([avg, mx], dim=1)))

class MultiScaleAttentionBlock(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()
        b_ch = out_ch // 3

        self.branch1 = DepthwiseSeparable(in_ch, b_ch)
        self.branch2 = nn.Sequential(
            DepthwiseSeparable(in_ch, b_ch),
            DepthwiseSeparable(b_ch, b_ch),
        )
        self.branch3 = nn.Sequential(
            DepthwiseSeparable(in_ch, b_ch),
            DepthwiseSeparable(b_ch, b_ch),
            DepthwiseSeparable(b_ch, b_ch),
        )

        self.fuse = ConvBNReLU(b_ch * 3, out_ch, kernel=1, padding=0)
        self.ca = ChannelAttention(out_ch)
        self.sa = SpatialAttention()

    def forward(self, x):
        f = self.fuse(torch.cat([self.branch1(x), self.branch2(x), self.branch3(x)], dim=1))
        return self.sa(self.ca(f))

class MaDCoRN(nn.Module):
    def __init__(self, in_ch=3, num_classes=2, base_ch=32):
        super().__init__()
        c = base_ch

        self.stem = nn.Sequential(
            ConvBNReLU(in_ch, c, kernel=3, stride=2, padding=1),
            ConvBNReLU(c, c * 2, kernel=3, stride=1, padding=1),
        )

        self.mad1 = MultiScaleAttentionBlock(c * 2, c * 4)
        self.mad2 = MultiScaleAttentionBlock(c * 4, c * 4)
        self.res1 = ConvReservoir(c * 4, c * 4)
        self.down1 = nn.Conv2d(c * 4, c * 4, kernel_size=3, stride=2, padding=1, bias=False)

        self.mad3 = MultiScaleAttentionBlock(c * 4, c * 8)
        self.mad4 = MultiScaleAttentionBlock(c * 8, c * 8)
        self.res2 = ConvReservoir(c * 8, c * 8)
        self.down2 = nn.Conv2d(c * 8, c * 8, kernel_size=3, stride=2, padding=1, bias=False)

        self.mad5 = MultiScaleAttentionBlock(c * 8, c * 16)
        self.mad6 = MultiScaleAttentionBlock(c * 16, c * 16)
        self.res3 = ConvReservoir(c * 16, c * 16)

        self.pool = nn.AdaptiveAvgPool2d(1)
        self.head = nn.Sequential(
            nn.Flatten(),
            nn.Linear(c * 16, 256),
            nn.ReLU(inplace=True),
            nn.Dropout(0.4),
            nn.Linear(256, num_classes),
        )

        self._init_weights()

    def _init_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, mode="fan_out", nonlinearity="relu")
            elif isinstance(m, nn.BatchNorm2d):
                nn.init.ones_(m.weight)
                nn.init.zeros_(m.bias)
            elif isinstance(m, nn.Linear):
                nn.init.trunc_normal_(m.weight, std=0.02)
                if m.bias is not None:
                    nn.init.zeros_(m.bias)

    def forward(self, x):
        x = self.stem(x)
        x = self.down1(self.res1(self.mad2(self.mad1(x))))
        x = self.down2(self.res2(self.mad4(self.mad3(x))))
        x = self.res3(self.mad6(self.mad5(x)))
        return self.head(self.pool(x))

    def count_parameters(self):
        total = sum(p.numel() for p in self.parameters())
        frozen = sum(p.numel() for p in self.parameters() if not p.requires_grad)
        return total, frozen

def freeze_reservoir_weights(model):
    for name, param in model.named_parameters():
        if "W_res" in name:
            param.requires_grad_(False)

# ============================================================
# DATASET
# ============================================================

class AddGaussianNoise:
    def __init__(self, std=0.01):
        self.std = std

    def __call__(self, t):
        return t + torch.randn_like(t) * self.std

class JPEGCompression:
    def __init__(self, quality_range=(60, 95)):
        self.lo, self.hi = quality_range

    def __call__(self, img):
        q = random.randint(self.lo, self.hi)
        buf = io.BytesIO()
        img.save(buf, format="JPEG", quality=q)
        buf.seek(0)
        return Image.open(buf).copy()

_MEAN = [0.485, 0.456, 0.406]
_STD = [0.229, 0.224, 0.225]

def build_transforms(source_resolution, split="train", image_size_for_model=224):
    if split == "train":
        return T.Compose([
            T.Resize((source_resolution, source_resolution)),
            T.Resize((image_size_for_model + 16, image_size_for_model + 16)),
            T.RandomCrop(image_size_for_model),
            T.RandomHorizontalFlip(p=0.5),
            T.RandomVerticalFlip(p=0.1),
            T.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.1, hue=0.05),
            T.RandomGrayscale(p=0.05),
            T.RandomApply([T.GaussianBlur(kernel_size=3)], p=0.15),
            JPEGCompression(quality_range=(60, 95)),
            T.ToTensor(),
            AddGaussianNoise(std=0.01),
            T.Normalize(_MEAN, _STD),
        ])

    return T.Compose([
        T.Resize((source_resolution, source_resolution)),
        T.Resize((image_size_for_model, image_size_for_model)),
        T.ToTensor(),
        T.Normalize(_MEAN, _STD),
    ])

def load_ffpp_dataframes(cfg):
    df = pd.read_csv(cfg["metadata_csv"])

    required = {"frame_path", "split", "label", "label_name", "video_id"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"metadata.csv missing columns: {missing}")

    df = df[df["frame_path"].apply(os.path.exists)].reset_index(drop=True)

    print("\nLoaded FF++ metadata")
    print("Total usable frames:", len(df))

    for split in ["Train", "Val", "Test"]:
        sdf = df[df["split"].str.lower() == split.lower()]
        real = int((sdf["label"] == 0).sum())
        fake = int((sdf["label"] == 1).sum())
        videos = sdf["video_id"].nunique()
        print(f"{split}: real={real}, fake={fake}, total={len(sdf)}, videos={videos}")

    train_full = df[df["split"].str.lower() == "train"].reset_index(drop=True)
    val_df = df[df["split"].str.lower() == "val"].reset_index(drop=True)
    test_df = df[df["split"].str.lower() == "test"].reset_index(drop=True)

    return train_full, val_df, test_df

def make_oversampled_train_df(train_df, seed=42):
    real_df = train_df[train_df["label"] == 0].copy()
    fake_df = train_df[train_df["label"] == 1].copy()

    real_os = real_df.sample(
        n=len(fake_df),
        replace=True,
        random_state=seed
    ).copy()

    real_os["is_oversampled_real"] = True
    fake_df["is_oversampled_real"] = False

    oversampled_df = (
        pd.concat([real_os, fake_df])
        .sample(frac=1, random_state=seed)
        .reset_index(drop=True)
    )

    print("\nOversampled train set")
    print(oversampled_df["label_name"].value_counts())
    print("Total oversampled train samples:", len(oversampled_df))
    print("Oversampled real rows:", int(oversampled_df["is_oversampled_real"].sum()))

    return oversampled_df

def make_balanced_train_df(train_df, seed=42):
    real_df = train_df[train_df["label"] == 0]
    fake_df = train_df[train_df["label"] == 1]

    n = min(len(real_df), len(fake_df))

    real_bal = real_df.sample(n=n, random_state=seed)
    fake_bal = fake_df.sample(n=n, random_state=seed)

    balanced_df = (
        pd.concat([real_bal, fake_bal])
        .sample(frac=1, random_state=seed)
        .reset_index(drop=True)
    )

    print("\nBalanced train set by undersampling")
    print(balanced_df["label_name"].value_counts())
    print("Total balanced train samples:", len(balanced_df))

    return balanced_df

def df_to_samples(df):
    return [(row["frame_path"], int(row["label"])) for _, row in df.iterrows()]

class MultiResolutionFFPPDataset(Dataset):
    def __init__(self, base_samples, resolutions, split="train", image_size_for_model=224):
        self.base_samples = list(base_samples)
        self.resolutions = list(resolutions)
        self.split = split
        self.image_size_for_model = image_size_for_model

        self.transforms = {
            res: build_transforms(res, split=split, image_size_for_model=image_size_for_model)
            for res in self.resolutions
        }

        if split == "train":
            self.samples = [(path, label, None) for path, label in self.base_samples]
        else:
            self.samples = [
                (path, label, res)
                for path, label in self.base_samples
                for res in self.resolutions
            ]

        n_real = sum(1 for _, label in self.base_samples if label == 0)
        n_fake = len(self.base_samples) - n_real

        print(
            f"[{split}] base: real={n_real:,}, fake={n_fake:,}, total={len(self.base_samples):,} | "
            f"effective={len(self.samples):,}"
        )

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        path, label, resolution = self.samples[idx]

        if resolution is None:
            resolution = random.choice(self.resolutions)

        try:
            img = Image.open(path).convert("RGB")
        except Exception:
            img = Image.fromarray(np.zeros((resolution, resolution, 3), dtype=np.uint8))

        x = self.transforms[resolution](img)
        y = torch.tensor(label, dtype=torch.long)

        return x, y

    def subset_for_resolution(self, resolution):
        return SingleResolutionView(
            self.base_samples,
            resolution,
            image_size_for_model=self.image_size_for_model,
        )

    @property
    def base_count(self):
        return len(self.base_samples)

    @property
    def expanded_count(self):
        return len(self.samples)

class SingleResolutionView(Dataset):
    def __init__(self, base_samples, resolution, image_size_for_model=224):
        self.base_samples = list(base_samples)
        self.resolution = resolution
        self.transform = build_transforms(
            resolution,
            split="val",
            image_size_for_model=image_size_for_model,
        )

    def __len__(self):
        return len(self.base_samples)

    def __getitem__(self, idx):
        path, label = self.base_samples[idx]

        try:
            img = Image.open(path).convert("RGB")
        except Exception:
            img = Image.fromarray(np.zeros((self.resolution, self.resolution, 3), dtype=np.uint8))

        x = self.transform(img)
        y = torch.tensor(label, dtype=torch.long)

        return x, y

def _make_loader(dataset, batch_size, num_workers, shuffle, drop_last):
    return DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,
        num_workers=num_workers,
        pin_memory=(DEVICE.type == "cuda"),
        persistent_workers=False,
    )

def print_dataset_summary(split_datasets, resolutions):
    print("\nDataset size summary")
    for name in ["train", "val", "test"]:
        ds = split_datasets[name]
        print(
            f"{name.title():<5} | base={ds.base_count:,}, "
            f"effective={ds.expanded_count:,}, resolutions={resolutions}"
        )

    print("\nStrategy:")
    print("  Train: balanced undersampled train set + one random source resolution per image per epoch")
    print("  Val:   original val set + all requested source resolutions per image")
    print("  Test:  original test set + all requested source resolutions per image")
    print(f"  Model input tensor size: (3, {CONFIG['image_size_for_model']}, {CONFIG['image_size_for_model']})")

def make_dataloaders(cfg):
    train_full_df, val_df, test_df = load_ffpp_dataframes(cfg)
    train_balanced_df = make_oversampled_train_df(train_full_df, seed=cfg["seed"])
    train_samples = df_to_samples(train_balanced_df)
    val_samples = df_to_samples(val_df)
    test_samples = df_to_samples(test_df)

    resolutions = list(cfg["resolutions"])

    split_datasets = {
        "train": MultiResolutionFFPPDataset(
            train_samples,
            resolutions,
            split="train",
            image_size_for_model=cfg["image_size_for_model"],
        ),
        "val": MultiResolutionFFPPDataset(
            val_samples,
            resolutions,
            split="val",
            image_size_for_model=cfg["image_size_for_model"],
        ),
        "test": MultiResolutionFFPPDataset(
            test_samples,
            resolutions,
            split="test",
            image_size_for_model=cfg["image_size_for_model"],
        ),
    }

    print_dataset_summary(split_datasets, resolutions)

    loaders = {
        "train": _make_loader(
            split_datasets["train"],
            cfg["batch_size"],
            cfg["num_workers"],
            shuffle=True,
            drop_last=True,
        ),
        "val": _make_loader(
            split_datasets["val"],
            cfg["batch_size"],
            cfg["num_workers"],
            shuffle=False,
            drop_last=False,
        ),
        "test": _make_loader(
            split_datasets["test"],
            cfg["batch_size"],
            cfg["num_workers"],
            shuffle=False,
            drop_last=False,
        ),
    }

    meta = {
        "train_full_df": train_full_df,
        "train_balanced_df": train_balanced_df,
        "val_df": val_df,
        "test_df": test_df,
    }

    return {
        "loaders": loaders,
        "datasets": split_datasets,
        "meta": meta,
    }

def make_smoke_loader(resolution, n=200, bs=8):
    imgs = torch.randn(n, 3, CONFIG["image_size_for_model"], CONFIG["image_size_for_model"])
    labels = torch.randint(0, 2, (n,))
    return DataLoader(TensorDataset(imgs, labels), batch_size=bs, shuffle=True)

# ============================================================
# TRAINING
# ============================================================

def compute_uncertain_rate(probs, threshold=0.65):
    conf = probs.max(axis=1)
    return float(np.mean(conf < threshold) * 100)

def run_epoch(model, loader, criterion, optimizer, device, scaler=None, is_train=True, desc=None):
    model.train(is_train)

    total_loss = 0.0
    seen = 0
    all_probs, all_preds, all_labels = [], [], []

    pbar = tqdm(
        loader,
        total=len(loader) if hasattr(loader, "__len__") else None,
        desc=desc or ("Train" if is_train else "Eval"),
        leave=False,
        dynamic_ncols=True,
        mininterval=0.5,
    )

    with torch.set_grad_enabled(is_train):
        for imgs, labels in pbar:
            imgs = imgs.to(device, non_blocking=True)
            labels = labels.to(device, non_blocking=True)

            if is_train:
                optimizer.zero_grad(set_to_none=True)

            if is_train and scaler:
                with autocast():
                    logits = model(imgs)
                    loss = criterion(logits, labels)

                scaler.scale(loss).backward()
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                scaler.step(optimizer)
                scaler.update()

            else:
                logits = model(imgs)
                loss = criterion(logits, labels)

                if is_train:
                    loss.backward()
                    torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                    optimizer.step()

            probs = torch.softmax(logits.float(), dim=1).detach().cpu().numpy()
            preds = probs.argmax(axis=1)

            all_probs.append(probs)
            all_preds.append(preds)
            all_labels.append(labels.detach().cpu().numpy())

            batch_n = len(labels)
            total_loss += loss.item() * batch_n
            seen += batch_n

            pbar.set_postfix(loss=f"{loss.item():.4f}", samples=f"{seen:,}")

    all_probs = np.vstack(all_probs)
    all_preds = np.concatenate(all_preds)
    all_labels = np.concatenate(all_labels)

    acc = accuracy_score(all_labels, all_preds)

    try:
        auc = roc_auc_score(all_labels, all_probs[:, 1])
    except ValueError:
        auc = 0.5

    precision = precision_score(all_labels, all_preds, zero_division=0)
    recall = recall_score(all_labels, all_preds, zero_division=0)
    f1 = f1_score(all_labels, all_preds, zero_division=0)
    uncertain_rate = compute_uncertain_rate(all_probs)

    return {
        "loss": total_loss / max(seen, 1),
        "acc": acc,
        "auc": auc,
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "uncertain_rate": uncertain_rate,
        "probs": all_probs,
        "preds": all_preds,
        "labels": all_labels,
    }

class Trainer:
    def __init__(self, model, train_loader, val_loader, test_loader, device, cfg, ckpt_path):
        self.model = model.to(device)
        self.train_loader = train_loader
        self.val_loader = val_loader
        self.test_loader = test_loader
        self.device = device
        self.epochs = cfg["epochs"]
        self.ckpt_path = ckpt_path
        self.model_name = "MaD-CoRN-FFPP-Balanced"

        self.criterion = nn.CrossEntropyLoss(label_smoothing=cfg["label_smoothing"])

        self.optimizer = optim.AdamW(
            [p for p in model.parameters() if p.requires_grad],
            lr=cfg["lr"],
            weight_decay=cfg["weight_decay"],
        )

        total_steps = self.epochs
        warmup_steps = cfg["warmup_epochs"]

        def lr_lambda(epoch):
            if epoch < warmup_steps:
                return max(1e-8, epoch / max(1, warmup_steps))
            prog = (epoch - warmup_steps) / max(1, total_steps - warmup_steps)
            return 0.5 * (1.0 + math.cos(math.pi * prog))

        self.scheduler = optim.lr_scheduler.LambdaLR(self.optimizer, lr_lambda)
        self.scaler = GradScaler() if device.type == "cuda" else None
        self.epoch_results = []

    def train(self):
        best_auc = -1.0
        t0 = time.time()

        for epoch in range(1, self.epochs + 1):
            tr = run_epoch(
                self.model,
                self.train_loader,
                self.criterion,
                self.optimizer,
                self.device,
                self.scaler,
                is_train=True,
                desc=f"Epoch {epoch}/{self.epochs} [train]",
            )

            with torch.no_grad():
                vl = run_epoch(
                    self.model,
                    self.val_loader,
                    self.criterion,
                    None,
                    self.device,
                    None,
                    is_train=False,
                    desc=f"Epoch {epoch}/{self.epochs} [val]",
                )

            self.scheduler.step()
            lr_now = self.optimizer.param_groups[0]["lr"]

            er = EpochResult(
                epoch=epoch,
                train_loss=tr["loss"],
                train_acc=tr["acc"],
                train_auc=tr["auc"],
                val_acc=vl["acc"],
                val_auc=vl["auc"],
                precision=vl["precision"],
                recall=vl["recall"],
                f1=vl["f1"],
                uncertain_rate=vl["uncertain_rate"],
                lr=lr_now,
            )

            self.epoch_results.append(er)

            print(
                f"Epoch {epoch:3d}/{self.epochs} | "
                f"Loss {er.train_loss:.4f} | "
                f"Tr Acc {er.train_acc:.4f} AUC {er.train_auc:.4f} | "
                f"Val Acc {er.val_acc:.4f} AUC {er.val_auc:.4f} | "
                f"P {er.precision:.4f} R {er.recall:.4f} F1 {er.f1:.4f} | "
                f"Unc {er.uncertain_rate:.1f}% | LR {lr_now:.2e}"
            )

            if vl["auc"] > best_auc:
                best_auc = vl["auc"]
                torch.save(self.model.state_dict(), self.ckpt_path)
                print(f"Checkpoint saved. Val AUC = {best_auc:.4f}")

        return self.epoch_results, (time.time() - t0) / 60

    def evaluate(self, loader=None, load_best=True):
        if load_best and os.path.exists(self.ckpt_path):
            self.model.load_state_dict(torch.load(self.ckpt_path, map_location=self.device))

        loader = loader or self.test_loader

        with torch.no_grad():
            r = run_epoch(
                self.model,
                loader,
                self.criterion,
                None,
                self.device,
                None,
                is_train=False,
                desc="Test evaluation",
            )

        return TestResult(
            model_name=self.model_name,
            accuracy=r["acc"],
            auc=r["auc"],
            precision=r["precision"],
            recall=r["recall"],
            f1=r["f1"],
            uncertain_rate=r["uncertain_rate"],
        )

# ============================================================
# EVAL / TIMING
# ============================================================

@torch.no_grad()
def measure_inference(model, resolution, device, image_size_for_model=224, batch_size=32, n_warmup=20, n_runs=200):
    model.eval()
    results = []

    for bs, label in [(1, "Single"), (batch_size, f"Batch={batch_size}")]:
        dummy = torch.randn(bs, 3, image_size_for_model, image_size_for_model, device=device)

        for _ in range(n_warmup):
            model(dummy)

        if device.type == "cuda":
            torch.cuda.synchronize()

        t0 = time.perf_counter()

        for _ in range(n_runs):
            model(dummy)

        if device.type == "cuda":
            torch.cuda.synchronize()

        elapsed = time.perf_counter() - t0
        total = bs * n_runs

        results.append(
            InferenceResult(
                mode=f"Source Res={resolution} {label}",
                time_per_image_ms=elapsed / total * 1000,
                fps=total / elapsed,
            )
        )

    return results

@torch.no_grad()
def evaluate_by_resolution(model, loader, device, resolution):
    model.eval()

    all_probs, all_labels = [], []
    buckets = {"fast": 0, "medium": 0, "full": 0}
    total = 0

    pbar = tqdm(
        loader,
        total=len(loader) if hasattr(loader, "__len__") else None,
        desc=f"Resolution {resolution} eval",
        leave=False,
        dynamic_ncols=True,
        mininterval=0.5,
    )

    for imgs, labels in pbar:
        imgs = imgs.to(device, non_blocking=True)
        bs = imgs.size(0)

        if device.type == "cuda":
            torch.cuda.synchronize()

        t0 = time.perf_counter()
        logits = model(imgs)

        if device.type == "cuda":
            torch.cuda.synchronize()

        ms = (time.perf_counter() - t0) / bs * 1000

        probs = torch.softmax(logits.float(), dim=1).cpu().numpy()

        all_probs.append(probs)
        all_labels.append(labels.numpy())

        if ms < 5:
            buckets["fast"] += bs
        elif ms < 20:
            buckets["medium"] += bs
        else:
            buckets["full"] += bs

        total += bs
        pbar.set_postfix(samples=f"{total:,}", ms_per_img=f"{ms:.3f}")

    all_probs = np.vstack(all_probs)
    all_labels = np.concatenate(all_labels)
    preds = all_probs.argmax(axis=1)

    acc = accuracy_score(all_labels, preds)

    try:
        auc = roc_auc_score(all_labels, all_probs[:, 1])
    except ValueError:
        auc = 0.5

    return ResolutionResult(
        resolution=resolution,
        accuracy=acc,
        auc=auc,
        fast_pct=buckets["fast"] / max(total, 1) * 100,
        medium_pct=buckets["medium"] / max(total, 1) * 100,
        full_pct=buckets["full"] / max(total, 1) * 100,
    )

# ============================================================
# REPORTING
# ============================================================

def _table(headers, rows, title=""):
    col_w = [
        max(len(str(h)), max((len(str(r[i])) for r in rows), default=0))
        for i, h in enumerate(headers)
    ]

    sep = "+" + "+".join("-" * (w + 2) for w in col_w) + "+"
    hdr = "|" + "|".join(f" {h:<{w}} " for h, w in zip(headers, col_w)) + "|"

    body = [
        "|" + "|".join(f" {str(v):<{w}} " for v, w in zip(r, col_w)) + "|"
        for r in rows
    ]

    out = [sep, hdr, sep] + body + [sep]

    if title:
        out.insert(0, title.center(len(sep)))
        out.insert(1, "")

    return "\n".join(out)

def print_training_table(ers):
    h = [
        "Epoch", "Train Loss", "Train Acc", "Train AUC",
        "Val Acc", "Val AUC", "Precision", "Recall", "F1",
        "Uncertain Rate (%)"
    ]

    rows = [
        [
            e.epoch,
            f"{e.train_loss:.4f}",
            f"{e.train_acc:.4f}",
            f"{e.train_auc:.4f}",
            f"{e.val_acc:.4f}",
            f"{e.val_auc:.4f}",
            f"{e.precision:.4f}",
            f"{e.recall:.4f}",
            f"{e.f1:.4f}",
            f"{e.uncertain_rate:.2f}",
        ]
        for e in ers
    ]

    t = _table(h, rows, "Training Periods Results")
    print(t)
    return t

def print_test_table(trs):
    h = ["Model", "Accuracy", "AUC", "Precision", "Recall", "F1", "Uncertain Rate (%)"]

    rows = [
        [
            r.model_name,
            f"{r.accuracy:.4f}",
            f"{r.auc:.4f}",
            f"{r.precision:.4f}",
            f"{r.recall:.4f}",
            f"{r.f1:.4f}",
            f"{r.uncertain_rate:.2f}",
        ]
        for r in trs
    ]

    t = _table(h, rows, "Test Results")
    print(t)
    return t

def print_resolution_table(rrs):
    h = ["Resolution", "Accuracy", "AUC", "Fast (%)", "Medium (%)", "Full (%)"]

    rows = [
        [
            r.resolution,
            f"{r.accuracy:.4f}",
            f"{r.auc:.4f}",
            f"{r.fast_pct:.2f}",
            f"{r.medium_pct:.2f}",
            f"{r.full_pct:.2f}",
        ]
        for r in rrs
    ]

    t = _table(h, rows, "Accuracy Based on Resolution")
    print(t)
    return t

def print_inference_table(irs):
    h = ["Mode", "Time per Image (ms)", "FPS"]

    rows = [
        [r.mode, f"{r.time_per_image_ms:.3f}", f"{r.fps:.1f}"]
        for r in irs
    ]

    t = _table(h, rows, "Inference Time")
    print(t)
    return t

def print_training_time_table(tts):
    h = ["Model Type", "min", "hrs"]

    rows = [
        [r.model_type, f"{r.minutes:.1f}", f"{r.hours:.2f}"]
        for r in tts
    ]

    t = _table(h, rows, "Training Time")
    print(t)
    return t

def save_all_results(epoch_results, test_results, res_results, inf_results, tt_results, save_dir, meta):
    os.makedirs(save_dir, exist_ok=True)

    data = {
        "epoch_results": [asdict(e) for e in epoch_results],
        "test_results": [asdict(t) for t in test_results],
        "res_results": [asdict(r) for r in res_results],
        "inference": [asdict(i) for i in inf_results],
        "training_time": [asdict(t) for t in tt_results],
    }

    with open(os.path.join(save_dir, "mad_corn_results.json"), "w") as f:
        json.dump(data, f, indent=2)

    for name, rows in data.items():
        if rows:
            pd.DataFrame(rows).to_csv(os.path.join(save_dir, f"mad_corn_{name}.csv"), index=False)

    train_full_df = meta["train_full_df"]
    train_balanced_df = meta["train_balanced_df"]
    val_df = meta["val_df"]
    test_df = meta["test_df"]

    experiment_summary = pd.DataFrame([{
        "Experiment Name": "MaD-CoRN Balanced Train",
        "Dataset": "FaceForensics++ C23",
        "Train Samples Original": len(train_full_df),
        "Train Samples Used Balanced": len(train_balanced_df),
        "Validation Samples": len(val_df),
        "Test Samples": len(test_df),
        "Train Real Used": int((train_balanced_df["label"] == 0).sum()),
        "Train Fake Used": int((train_balanced_df["label"] == 1).sum()),
        "Validation Real": int((val_df["label"] == 0).sum()),
        "Validation Fake": int((val_df["label"] == 1).sum()),
        "Test Real": int((test_df["label"] == 0).sum()),
        "Test Fake": int((test_df["label"] == 1).sum()),
        "Balancing Method": "Train-only undersampling of fake class to match real class",
        "Resolutions Used": str(CONFIG["resolutions"]),
        "Input Modalities": "RGB",
        "RGB Shape": f"(3, {CONFIG['image_size_for_model']}, {CONFIG['image_size_for_model']})",
        "Device": str(DEVICE),
        "CUDA Available": torch.cuda.is_available(),
        "Framework": "PyTorch",
        "Torch Version": torch.__version__,
        "Balancing Method": "Train-only oversampling of real class with replacement to match fake class"
    }])

    experiment_summary.to_csv(os.path.join(save_dir, "experiment_summary.csv"), index=False)

    print("\nExperiment Summary")
    display(experiment_summary)

    print("\nResults saved to:", save_dir)

def print_full_report(epoch_results, test_results, res_results, inf_results, tt_results, save_dir, meta):
    div = "=" * 100

    print("\n" + div)
    print("MaD-CoRN EXPERIMENT RESULTS".center(100, "="))
    print(div)

    print("\n[1] TRAINING PERIODS RESULTS")
    print_training_table(epoch_results)

    print("\n[2] TEST RESULTS")
    print_test_table(test_results)

    print("\n[3] ACCURACY BASED ON RESOLUTION")
    print_resolution_table(res_results)

    print("\n[4] INFERENCE TIME")
    print_inference_table(inf_results)

    print("\n[5] TRAINING TIME")
    print_training_time_table(tt_results)

    save_all_results(epoch_results, test_results, res_results, inf_results, tt_results, save_dir, meta)

# ============================================================
# PIPELINE
# ============================================================

def run_pipeline(cfg):
    set_seed(cfg["seed"])
    device = auto_device(cfg["device"])
    os.makedirs(cfg["save_dir"], exist_ok=True)

    print("\n" + "=" * 70)
    print("MaD-CoRN Pipeline FF++ Balanced Train")
    print("Device:", device)
    print("Source resolutions:", cfg["resolutions"])
    print("Model input size:", cfg["image_size_for_model"])
    print("Epochs:", cfg["epochs"])
    print("Smoke test:", cfg["smoke_test"])
    print("=" * 70)

    model = MaDCoRN(in_ch=3, num_classes=2, base_ch=cfg["base_ch"])
    freeze_reservoir_weights(model)

    total, frozen = model.count_parameters()
    trainable = total - frozen
    print(f"\nModel params: {total:,} total | {trainable:,} trainable | {frozen:,} frozen")

    split_datasets = None
    meta = None

    if cfg["smoke_test"]:
        print("\nSMOKE TEST")
        bs = cfg["batch_size"]
        train_loader = make_smoke_loader(cfg["image_size_for_model"], n=320, bs=bs)
        val_loader = make_smoke_loader(cfg["image_size_for_model"], n=80, bs=bs)
        test_loader = make_smoke_loader(cfg["image_size_for_model"], n=80, bs=bs)
        cfg = {**cfg, "epochs": min(cfg["epochs"], 3)}
        meta = {
            "train_full_df": pd.DataFrame(),
            "train_balanced_df": pd.DataFrame(),
            "val_df": pd.DataFrame(),
            "test_df": pd.DataFrame(),
        }
    else:
        print("\nLoading FF++ dataset...")
        data_bundle = make_dataloaders(cfg)
        split_datasets = data_bundle["datasets"]
        train_loader = data_bundle["loaders"]["train"]
        val_loader = data_bundle["loaders"]["val"]
        test_loader = data_bundle["loaders"]["test"]
        meta = data_bundle["meta"]

    ckpt_path = os.path.join(cfg["save_dir"], "mad_corn_ffpp_balanced_multires.pt")

    print("\n" + "-" * 60)
    print("TRAINING")
    print("-" * 60)

    trainer = Trainer(
        model,
        train_loader,
        val_loader,
        test_loader,
        device,
        cfg,
        ckpt_path,
    )

    epoch_results, training_min = trainer.train()

    print(f"\nTraining done: {training_min:.1f} min ({training_min / 60:.2f} hrs)")

    print("\n" + "-" * 60)
    print("TEST EVALUATION ON COMBINED MULTI-RES TEST SET")
    print("-" * 60)

    test_result = trainer.evaluate(test_loader, load_best=True)
    test_results = [test_result]

    print("\n" + "-" * 60)
    print("PER-RESOLUTION BREAKDOWN")
    print("-" * 60)

    res_results = []
    inf_results = []

    for res in tqdm(cfg["resolutions"], desc="Resolution sweep", dynamic_ncols=True):
        print(f"\nResolution {res}")

        if cfg["smoke_test"]:
            res_loader = make_smoke_loader(cfg["image_size_for_model"], n=80, bs=cfg["batch_size"])
        else:
            res_ds = split_datasets["test"].subset_for_resolution(res)
            res_loader = DataLoader(
                res_ds,
                batch_size=cfg["batch_size"],
                shuffle=False,
                num_workers=cfg["num_workers"],
                pin_memory=(device.type == "cuda"),
                persistent_workers=False,
            )

        rr = evaluate_by_resolution(model, res_loader, device, res)
        res_results.append(rr)

        print(
            f"Acc={rr.accuracy:.4f} AUC={rr.auc:.4f} "
            f"Fast={rr.fast_pct:.2f}% Medium={rr.medium_pct:.2f}% Full={rr.full_pct:.2f}%"
        )

        infs = measure_inference(
            model,
            res,
            device,
            image_size_for_model=cfg["image_size_for_model"],
            batch_size=cfg["batch_size"],
        )
        inf_results.extend(infs)

        for ir in infs:
            print(f"{ir.mode}: {ir.time_per_image_ms:.3f} ms/img | {ir.fps:.1f} FPS")

    tt_results = [
        TrainingTimeResult(
            model_type="MaD-CoRN FF++ balanced train multi-resolution training",
            minutes=training_min,
            hours=training_min / 60,
        )
    ]

    print_full_report(
        epoch_results,
        test_results,
        res_results,
        inf_results,
        tt_results,
        cfg["save_dir"],
        meta,
    )

    return {
        "epoch_results": epoch_results,
        "test_results": test_results,
        "res_results": res_results,
        "inf_results": inf_results,
        "tt_results": tt_results,
        "model": model,
        "trainer": trainer,
        "split_datasets": split_datasets,
        "meta": meta,
    }

results = run_pipeline(CONFIG)

Collecting scikit-learn
  Using cached scikit_learn-1.8.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (11 kB)
Collecting torch
  Using cached torch-2.11.0-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (29 kB)
Collecting torchvision
  Using cached torchvision-0.26.0-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.11/site-packages (4.66.4)
Collecting pandas
  Using cached pandas-3.0.2-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting pillow
  Using cached pillow-12.2.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (8.8 kB)
Collecting numpy>=1.24.1 (from scikit-learn)
  Using cached numpy-2.4.4-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting scipy>=1.10.0 (from scikit-learn)
  Using cached scipy-1.17.1-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting filelock (from torch)
  Using cached filelock-3.29.0-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: typing-extensions>=4.10.0 in /opt/conda/lib/python3.11/site-packages (from torch) (4.12.2)
Requirement already satisfied: setuptools<82 in /opt/conda/lib/python3.11/site-packages (from torch) (71.0.4)
Collecting sympy>=1.13.3 (from torch)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx>=2.5.1 (from torch)
  Using cached networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.11/site-packages (from torch) (3.1.4)
Collecting fsspec>=0.8.5 (from torch)
  Using cached fsspec-2026.4.0-py3-none-any.whl.metadata (10 kB)
Collecting cuda-toolkit==13.0.2 (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch)
  Using cached cuda_toolkit-13.0.2-py2.py3-none-any.whl.metadata (9.4 kB)
Collecting cuda-bindings<14,>=13.0.3 (from torch)
  Using cached cuda_bindings-13.2.0-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (2.3 kB)
Collecting nvidia-cudnn-cu13==9.19.0.56 (from torch)
  Using cached nvidia_cudnn_cu13-9.19.0.56-py3-none-manylinux_2_27_x86_64.whl.metadata (1.9 kB)
Collecting nvidia-cusparselt-cu13==0.8.0 (from torch)
  Using cached nvidia_cusparselt_cu13-0.8.0-py3-none-manylinux2014_x86_64.whl.metadata (12 kB)
Collecting nvidia-nccl-cu13==2.28.9 (from torch)
  Using cached nvidia_nccl_cu13-2.28.9-py3-none-manylinux_2_18_x86_64.whl.metadata (2.0 kB)
Collecting nvidia-nvshmem-cu13==3.4.5 (from torch)
  Using cached nvidia_nvshmem_cu13-3.4.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.1 kB)
Collecting triton==3.6.0 (from torch)
  Using cached triton-3.6.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cublas==13.1.0.3.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch)
  Using cached nvidia_cublas-13.1.0.3-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-runtime==13.0.96.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch)
  Using cached nvidia_cuda_runtime-13.0.96-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufft==12.0.0.61.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch)
  Using cached nvidia_cufft-12.0.0.61-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cufile==1.15.1.6.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch)
  Using cached nvidia_cufile-1.15.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-cupti==13.0.85.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch)
  Using cached nvidia_cuda_cupti-13.0.85-py3-none-manylinux_2_25_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-curand==10.4.0.35.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch)
  Using cached nvidia_curand-10.4.0.35-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cusolver==12.0.4.66.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch)
  Using cached nvidia_cusolver-12.0.4.66-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparse==12.6.3.3.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch)
  Using cached nvidia_cusparse-12.6.3.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvjitlink==13.0.88.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch)
  Using cached nvidia_nvjitlink-13.0.88-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-nvrtc==13.0.88.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch)
  Using cached nvidia_cuda_nvrtc-13.0.88-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-nvtx==13.0.85.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch)
  Using cached nvidia_nvtx-13.0.85-py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl.metadata (1.8 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.11/site-packages (from pandas) (2.9.0)
Collecting cuda-pathfinder~=1.1 (from cuda-bindings<14,>=13.0.3->torch)
  Using cached cuda_pathfinder-1.5.4-py3-none-any.whl.metadata (1.9 kB)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.11/site-packages (from jinja2->torch) (2.1.5)
Using cached scikit_learn-1.8.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (9.1 MB)
Using cached torch-2.11.0-cp311-cp311-manylinux_2_28_x86_64.whl (530.6 MB)
Using cached cuda_toolkit-13.0.2-py2.py3-none-any.whl (2.4 kB)
Using cached nvidia_cudnn_cu13-9.19.0.56-py3-none-manylinux_2_27_x86_64.whl (366.1 MB)
Using cached nvidia_cusparselt_cu13-0.8.0-py3-none-manylinux2014_x86_64.whl (169.9 MB)
Using cached nvidia_nccl_cu13-2.28.9-py3-none-manylinux_2_18_x86_64.whl (196.5 MB)
Using cached nvidia_nvshmem_cu13-3.4.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (60.4 MB)
Using cached triton-3.6.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (188.2 MB)
Using cached nvidia_cublas-13.1.0.3-py3-none-manylinux_2_27_x86_64.whl (423.1 MB)
Using cached nvidia_cuda_cupti-13.0.85-py3-none-manylinux_2_25_x86_64.whl (10.7 MB)
Using cached nvidia_cuda_nvrtc-13.0.88-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (90.2 MB)
Using cached nvidia_cuda_runtime-13.0.96-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (2.2 MB)
Using cached nvidia_cufft-12.0.0.61-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (214.1 MB)
Using cached nvidia_cufile-1.15.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.2 MB)
Using cached nvidia_curand-10.4.0.35-py3-none-manylinux_2_27_x86_64.whl (59.5 MB)
Using cached nvidia_cusolver-12.0.4.66-py3-none-manylinux_2_27_x86_64.whl (200.9 MB)
Using cached nvidia_cusparse-12.6.3.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (145.9 MB)
Using cached nvidia_nvjitlink-13.0.88-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (40.7 MB)
Using cached nvidia_nvtx-13.0.85-py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl (148 kB)
Using cached torchvision-0.26.0-cp311-cp311-manylinux_2_28_x86_64.whl (7.5 MB)
Using cached pandas-3.0.2-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (11.3 MB)
Using cached pillow-12.2.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (7.1 MB)
Using cached cuda_bindings-13.2.0-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (6.3 MB)
Using cached fsspec-2026.4.0-py3-none-any.whl (203 kB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached networkx-3.6.1-py3-none-any.whl (2.1 MB)
Using cached numpy-2.4.4-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.9 MB)
Using cached scipy-1.17.1-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (35.3 MB)
Using cached sympy-1.14.0-py3-none-any.whl (6.3 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Using cached filelock-3.29.0-py3-none-any.whl (39 kB)
Using cached cuda_pathfinder-1.5.4-py3-none-any.whl (51 kB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Installing collected packages: nvidia-cusparselt-cu13, mpmath, cuda-toolkit, triton, threadpoolctl, sympy, pillow, nvidia-nvtx, nvidia-nvshmem-cu13, nvidia-nvjitlink, nvidia-nccl-cu13, nvidia-curand, nvidia-cufile, nvidia-cuda-runtime, nvidia-cuda-nvrtc, nvidia-cuda-cupti, nvidia-cublas, numpy, networkx, joblib, fsspec, filelock, cuda-pathfinder, scipy, pandas, nvidia-cusparse, nvidia-cufft, nvidia-cudnn-cu13, cuda-bindings, scikit-learn, nvidia-cusolver, torch, torchvision
Successfully installed cuda-bindings-13.2.0 cuda-pathfinder-1.5.4 cuda-toolkit-13.0.2 filelock-3.29.0 fsspec-2026.4.0 joblib-1.5.3 mpmath-1.3.0 networkx-3.6.1 numpy-2.4.4 nvidia-cublas-13.1.0.3 nvidia-cuda-cupti-13.0.85 nvidia-cuda-nvrtc-13.0.88 nvidia-cuda-runtime-13.0.96 nvidia-cudnn-cu13-9.19.0.56 nvidia-cufft-12.0.0.61 nvidia-cufile-1.15.1.6 nvidia-curand-10.4.0.35 nvidia-cusolver-12.0.4.66 nvidia-cusparse-12.6.3.3 nvidia-cusparselt-cu13-0.8.0 nvidia-nccl-cu13-2.28.9 nvidia-nvjitlink-13.0.88 nvidia-nvshmem-cu13-3.4.5 nvidia-nvtx-13.0.85 pandas-3.0.2 pillow-12.2.0 scikit-learn-1.8.0 scipy-1.17.1 sympy-1.14.0 threadpoolctl-3.6.0 torch-2.11.0 torchvision-0.26.0 triton-3.6.0
Torch: 2.11.0+cu130
CUDA available: True
Device: cuda

======================================================================
MaD-CoRN Pipeline FF++ Balanced Train
Device: cuda
Source resolutions: [128, 224, 256, 384]
Model input size: 224
Epochs: 15
Smoke test: False
======================================================================

Model params: 3,428,062 total | 3,428,062 trainable | 0 frozen

Loading FF++ dataset...

Loaded FF++ metadata
Total usable frames: 55953
Train: real=6400, fake=38356, total=44756, videos=5600
Val: real=800, fake=4800, total=5600, videos=700
Test: real=800, fake=4797, total=5597, videos=700

Oversampled train set
label_name
Fake    38356
Real    38356
Name: count, dtype: int64
Total oversampled train samples: 76712
Oversampled real rows: 38356
[train] base: real=38,356, fake=38,356, total=76,712 | effective=76,712
[val] base: real=800, fake=4,800, total=5,600 | effective=22,400
[test] base: real=800, fake=4,797, total=5,597 | effective=22,388

Dataset size summary
Train | base=76,712, effective=76,712, resolutions=[128, 224, 256, 384]
Val   | base=5,600, effective=22,400, resolutions=[128, 224, 256, 384]
Test  | base=5,597, effective=22,388, resolutions=[128, 224, 256, 384]

Strategy:
  Train: balanced undersampled train set + one random source resolution per image per epoch
  Val:   original val set + all requested source resolutions per image
  Test:  original test set + all requested source resolutions per image
  Model input tensor size: (3, 224, 224)

------------------------------------------------------------
TRAINING
------------------------------------------------------------

Epoch   1/15 | Loss 0.6956 | Tr Acc 0.4999 AUC 0.4990 | Val Acc 0.1429 AUC 0.5096 | P 0.0000 R 0.0000 F1 0.0000 | Unc 100.0% | LR 3.33e-04
Checkpoint saved. Val AUC = 0.5096

Epoch   2/15 | Loss 0.6846 | Tr Acc 0.5376 AUC 0.5496 | Val Acc 0.3495 AUC 0.5958 | P 0.9048 R 0.2694 F1 0.4152 | Unc 80.2% | LR 6.67e-04
Checkpoint saved. Val AUC = 0.5958

Epoch   3/15 | Loss 0.6701 | Tr Acc 0.5635 AUC 0.5746 | Val Acc 0.3206 AUC 0.5519 | P 0.9024 R 0.2326 F1 0.3698 | Unc 82.1% | LR 1.00e-03

Epoch   4/15 | Loss 0.6656 | Tr Acc 0.5666 AUC 0.5739 | Val Acc 0.2745 AUC 0.5677 | P 0.9706 R 0.1583 F1 0.2723 | Unc 89.4% | LR 9.83e-04

Epoch   5/15 | Loss 0.6601 | Tr Acc 0.5726 AUC 0.5767 | Val Acc 0.2827 AUC 0.5626 | P 0.9503 R 0.1721 F1 0.2915 | Unc 86.8% | LR 9.33e-04

Epoch   6/15 | Loss 0.6552 | Tr Acc 0.5748 AUC 0.5766 | Val Acc 0.3136 AUC 0.5764 | P 0.9326 R 0.2147 F1 0.3490 | Unc 85.0% | LR 8.54e-04

Epoch   7/15 | Loss 0.6525 | Tr Acc 0.5785 AUC 0.5805 | Val Acc 0.2825 AUC 0.5680 | P 0.9505 R 0.1719 F1 0.2911 | Unc 86.4% | LR 7.50e-04

Epoch   8/15 | Loss 0.6493 | Tr Acc 0.5804 AUC 0.5781 | Val Acc 0.3345 AUC 0.5585 | P 0.9220 R 0.2443 F1 0.3862 | Unc 82.5% | LR 6.29e-04

Epoch   9/15 | Loss 0.6479 | Tr Acc 0.5823 AUC 0.5819 | Val Acc 0.3003 AUC 0.5666 | P 0.9421 R 0.1957 F1 0.3241 | Unc 85.4% | LR 5.00e-04

Epoch  10/15 | Loss 0.6454 | Tr Acc 0.5840 AUC 0.5865 | Val Acc 0.2727 AUC 0.5604 | P 0.9709 R 0.1561 F1 0.2690 | Unc 86.5% | LR 3.71e-04

Epoch  11/15 | Loss 0.6433 | Tr Acc 0.5862 AUC 0.5850 | Val Acc 0.2769 AUC 0.5612 | P 0.9481 R 0.1654 F1 0.2817 | Unc 85.7% | LR 2.50e-04

Epoch  12/15 | Loss 0.6419 | Tr Acc 0.5883 AUC 0.5892 | Val Acc 0.2756 AUC 0.5347 | P 0.9036 R 0.1734 F1 0.2909 | Unc 85.1% | LR 1.46e-04

Epoch  13/15 | Loss 0.6402 | Tr Acc 0.5914 AUC 0.5936 | Val Acc 0.2699 AUC 0.5289 | P 0.8811 R 0.1713 F1 0.2868 | Unc 84.2% | LR 6.70e-05

Epoch  14/15 | Loss 0.6384 | Tr Acc 0.5939 AUC 0.5955 | Val Acc 0.2732 AUC 0.5145 | P 0.8626 R 0.1809 F1 0.2991 | Unc 83.6% | LR 1.70e-05

Epoch  15/15 | Loss 0.6377 | Tr Acc 0.5949 AUC 0.5962 | Val Acc 0.2734 AUC 0.5118 | P 0.8601 R 0.1819 F1 0.3003 | Unc 83.4% | LR 0.00e+00

Training done: 798.6 min (13.31 hrs)

------------------------------------------------------------
TEST EVALUATION ON COMBINED MULTI-RES TEST SET
------------------------------------------------------------

------------------------------------------------------------
PER-RESOLUTION BREAKDOWN
------------------------------------------------------------

Resolution sweep:   0%|          | 0/4 [00:00<?, ?it/s]

Resolution 128

Resolution 128 eval:   0%|          | 0/175 [00:00<?, ?it/s]
Resolution 128 eval:   0%|          | 0/175 [00:00<?, ?it/s, ms_per_img=1.777, samples=32]
Resolution 128 eval:   0%|          | 0/175 [00:00<?, ?it/s, ms_per_img=1.774, samples=64]
Resolution 128 eval:   1%|          | 2/175 [00:00<00:53,  3.24it/s, ms_per_img=1.774, samples=64]
Resolution 128 eval:   1%|          | 2/175 [00:01<00:53,  3.24it/s, ms_per_img=1.773, samples=96]
Resolution 128 eval:   1%|          | 2/175 [00:01<00:53,  3.24it/s, ms_per_img=1.776, samples=128]
Resolution 128 eval:   2%|▏         | 4/175 [00:01<01:07,  2.53it/s, ms_per_img=1.776, samples=128]
Resolution 128 eval:   2%|▏         | 4/175 [00:01<01:07,  2.53it/s, ms_per_img=1.774, samples=160]
Resolution 128 eval:   2%|▏         | 4/175 [00:02<01:07,  2.53it/s, ms_per_img=1.774, samples=192]
Resolution 128 eval:   3%|▎         | 6/175 [00:02<01:01,  2.73it/s, ms_per_img=1.774, samples=192]
Resolution 128 eval:   3%|▎         | 6/175 [00:02<01:01,  2.73it/s, ms_per_img=1.775, samples=224]
Resolution 128 eval:   3%|▎         | 6/175 [00:02<01:01,  2.73it/s, ms_per_img=1.774, samples=256]
Resolution 128 eval:   3%|▎         | 6/175 [00:02<01:01,  2.73it/s, ms_per_img=1.776, samples=288]
Resolution 128 eval:   5%|▌         | 9/175 [00:02<00:51,  3.21it/s, ms_per_img=1.776, samples=288]
Resolution 128 eval:   5%|▌         | 9/175 [00:03<00:51,  3.21it/s, ms_per_img=1.773, samples=320]
Resolution 128 eval:   5%|▌         | 9/175 [00:03<00:51,  3.21it/s, ms_per_img=1.775, samples=352]
Resolution 128 eval:   6%|▋         | 11/175 [00:03<01:00,  2.73it/s, ms_per_img=1.775, samples=352]
Resolution 128 eval:   6%|▋         | 11/175 [00:04<01:00,  2.73it/s, ms_per_img=1.775, samples=384]
Resolution 128 eval:   6%|▋         | 11/175 [00:04<01:00,  2.73it/s, ms_per_img=1.773, samples=416]
Resolution 128 eval:   7%|▋         | 13/175 [00:04<00:53,  3.00it/s, ms_per_img=1.773, samples=416]
Resolution 128 eval:   7%|▋         | 13/175 [00:04<00:53,  3.00it/s, ms_per_img=1.777, samples=448]
Resolution 128 eval:   7%|▋         | 13/175 [00:04<00:53,  3.00it/s, ms_per_img=1.775, samples=480]
Resolution 128 eval:   9%|▊         | 15/175 [00:04<00:49,  3.24it/s, ms_per_img=1.775, samples=480]
Resolution 128 eval:   9%|▊         | 15/175 [00:05<00:49,  3.24it/s, ms_per_img=1.775, samples=512]
Resolution 128 eval:   9%|▊         | 15/175 [00:05<00:49,  3.24it/s, ms_per_img=1.773, samples=544]
Resolution 128 eval:  10%|▉         | 17/175 [00:05<00:48,  3.26it/s, ms_per_img=1.773, samples=544]
Resolution 128 eval:  10%|▉         | 17/175 [00:05<00:48,  3.26it/s, ms_per_img=1.774, samples=576]
Resolution 128 eval:  10%|▉         | 17/175 [00:06<00:48,  3.26it/s, ms_per_img=1.776, samples=608]
Resolution 128 eval:  10%|▉         | 17/175 [00:06<00:48,  3.26it/s, ms_per_img=1.776, samples=640]
Resolution 128 eval:  11%|█▏        | 20/175 [00:06<00:45,  3.44it/s, ms_per_img=1.776, samples=640]
Resolution 128 eval:  11%|█▏        | 20/175 [00:06<00:45,  3.44it/s, ms_per_img=1.774, samples=672]
Resolution 128 eval:  11%|█▏        | 20/175 [00:07<00:45,  3.44it/s, ms_per_img=1.775, samples=704]
Resolution 128 eval:  13%|█▎        | 22/175 [00:07<00:46,  3.32it/s, ms_per_img=1.775, samples=704]
Resolution 128 eval:  13%|█▎        | 22/175 [00:07<00:46,  3.32it/s, ms_per_img=1.773, samples=736]
Resolution 128 eval:  13%|█▎        | 22/175 [00:07<00:46,  3.32it/s, ms_per_img=1.773, samples=768]
Resolution 128 eval:  14%|█▎        | 24/175 [00:07<00:46,  3.26it/s, ms_per_img=1.773, samples=768]
Resolution 128 eval:  14%|█▎        | 24/175 [00:07<00:46,  3.26it/s, ms_per_img=1.777, samples=800]
Resolution 128 eval:  14%|█▎        | 24/175 [00:08<00:46,  3.26it/s, ms_per_img=1.776, samples=832]
Resolution 128 eval:  15%|█▍        | 26/175 [00:08<00:44,  3.33it/s, ms_per_img=1.776, samples=832]
Resolution 128 eval:  15%|█▍        | 26/175 [00:08<00:44,  3.33it/s, ms_per_img=1.774, samples=864]
Resolution 128 eval:  15%|█▍        | 26/175 [00:08<00:44,  3.33it/s, ms_per_img=1.774, samples=896]
Resolution 128 eval:  16%|█▌        | 28/175 [00:08<00:45,  3.20it/s, ms_per_img=1.774, samples=896]
Resolution 128 eval:  16%|█▌        | 28/175 [00:09<00:45,  3.20it/s, ms_per_img=1.774, samples=928]
Resolution 128 eval:  16%|█▌        | 28/175 [00:09<00:45,  3.20it/s, ms_per_img=1.774, samples=960]
Resolution 128 eval:  17%|█▋        | 30/175 [00:09<00:46,  3.09it/s, ms_per_img=1.774, samples=960]
Resolution 128 eval:  17%|█▋        | 30/175 [00:09<00:46,  3.09it/s, ms_per_img=1.773, samples=992]
Resolution 128 eval:  17%|█▋        | 30/175 [00:10<00:46,  3.09it/s, ms_per_img=1.774, samples=1,024]
Resolution 128 eval:  18%|█▊        | 32/175 [00:10<00:47,  2.98it/s, ms_per_img=1.774, samples=1,024]
Resolution 128 eval:  18%|█▊        | 32/175 [00:11<00:47,  2.98it/s, ms_per_img=1.773, samples=1,056]
Resolution 128 eval:  18%|█▊        | 32/175 [00:12<00:47,  2.98it/s, ms_per_img=1.775, samples=1,088]
Resolution 128 eval:  19%|█▉        | 34/175 [00:12<01:21,  1.73it/s, ms_per_img=1.775, samples=1,088]
Resolution 128 eval:  19%|█▉        | 34/175 [00:14<01:21,  1.73it/s, ms_per_img=1.774, samples=1,120]
Resolution 128 eval:  19%|█▉        | 34/175 [00:15<01:21,  1.73it/s, ms_per_img=1.774, samples=1,152]
Resolution 128 eval:  21%|██        | 36/175 [00:15<01:54,  1.22it/s, ms_per_img=1.774, samples=1,152]
Resolution 128 eval:  21%|██        | 36/175 [00:15<01:54,  1.22it/s, ms_per_img=1.772, samples=1,184]
Resolution 128 eval:  21%|██        | 37/175 [00:15<01:46,  1.30it/s, ms_per_img=1.772, samples=1,184]
Resolution 128 eval:  21%|██        | 37/175 [00:16<01:46,  1.30it/s, ms_per_img=1.775, samples=1,216]
Resolution 128 eval:  21%|██        | 37/175 [00:16<01:46,  1.30it/s, ms_per_img=1.774, samples=1,248]
Resolution 128 eval:  22%|██▏       | 39/175 [00:16<01:30,  1.51it/s, ms_per_img=1.774, samples=1,248]
Resolution 128 eval:  22%|██▏       | 39/175 [00:17<01:30,  1.51it/s, ms_per_img=1.776, samples=1,280]
Resolution 128 eval:  23%|██▎       | 40/175 [00:17<01:27,  1.55it/s, ms_per_img=1.776, samples=1,280]
Resolution 128 eval:  23%|██▎       | 40/175 [00:18<01:27,  1.55it/s, ms_per_img=1.771, samples=1,312]
Resolution 128 eval:  23%|██▎       | 41/175 [00:18<01:31,  1.46it/s, ms_per_img=1.771, samples=1,312]
Resolution 128 eval:  23%|██▎       | 41/175 [00:19<01:31,  1.46it/s, ms_per_img=1.772, samples=1,344]
Resolution 128 eval:  24%|██▍       | 42/175 [00:19<01:39,  1.33it/s, ms_per_img=1.772, samples=1,344]
Resolution 128 eval:  24%|██▍       | 42/175 [00:20<01:39,  1.33it/s, ms_per_img=1.772, samples=1,376]
Resolution 128 eval:  25%|██▍       | 43/175 [00:20<01:47,  1.23it/s, ms_per_img=1.772, samples=1,376]
Resolution 128 eval:  25%|██▍       | 43/175 [00:20<01:47,  1.23it/s, ms_per_img=1.774, samples=1,408]
Resolution 128 eval:  25%|██▌       | 44/175 [00:20<01:38,  1.32it/s, ms_per_img=1.774, samples=1,408]
Resolution 128 eval:  25%|██▌       | 44/175 [00:21<01:38,  1.32it/s, ms_per_img=1.774, samples=1,440]
Resolution 128 eval:  26%|██▌       | 45/175 [00:21<01:33,  1.39it/s, ms_per_img=1.774, samples=1,440]
Resolution 128 eval:  26%|██▌       | 45/175 [00:22<01:33,  1.39it/s, ms_per_img=1.772, samples=1,472]
Resolution 128 eval:  26%|██▋       | 46/175 [00:22<01:36,  1.34it/s, ms_per_img=1.772, samples=1,472]
Resolution 128 eval:  26%|██▋       | 46/175 [00:23<01:36,  1.34it/s, ms_per_img=1.774, samples=1,504]
Resolution 128 eval:  27%|██▋       | 47/175 [00:23<01:39,  1.29it/s, ms_per_img=1.774, samples=1,504]
Resolution 128 eval:  27%|██▋       | 47/175 [00:23<01:39,  1.29it/s, ms_per_img=1.773, samples=1,536]
Resolution 128 eval:  27%|██▋       | 48/175 [00:23<01:28,  1.43it/s, ms_per_img=1.773, samples=1,536]
Resolution 128 eval:  27%|██▋       | 48/175 [00:24<01:28,  1.43it/s, ms_per_img=1.772, samples=1,568]
Resolution 128 eval:  28%|██▊       | 49/175 [00:24<01:28,  1.42it/s, ms_per_img=1.772, samples=1,568]
Resolution 128 eval:  28%|██▊       | 49/175 [00:25<01:28,  1.42it/s, ms_per_img=1.774, samples=1,600]
Resolution 128 eval:  29%|██▊       | 50/175 [00:25<01:39,  1.26it/s, ms_per_img=1.774, samples=1,600]
Resolution 128 eval:  29%|██▊       | 50/175 [00:26<01:39,  1.26it/s, ms_per_img=1.773, samples=1,632]
Resolution 128 eval:  29%|██▉       | 51/175 [00:26<01:34,  1.31it/s, ms_per_img=1.773, samples=1,632]
Resolution 128 eval:  29%|██▉       | 51/175 [00:27<01:34,  1.31it/s, ms_per_img=1.773, samples=1,664]
Resolution 128 eval:  30%|██▉       | 52/175 [00:27<01:42,  1.20it/s, ms_per_img=1.773, samples=1,664]
Resolution 128 eval:  30%|██▉       | 52/175 [00:27<01:42,  1.20it/s, ms_per_img=1.774, samples=1,696]
Resolution 128 eval:  30%|██▉       | 52/175 [00:28<01:42,  1.20it/s, ms_per_img=1.772, samples=1,728]
Resolution 128 eval:  31%|███       | 54/175 [00:28<01:25,  1.42it/s, ms_per_img=1.772, samples=1,728]
Resolution 128 eval:  31%|███       | 54/175 [00:29<01:25,  1.42it/s, ms_per_img=1.774, samples=1,760]
Resolution 128 eval:  31%|███▏      | 55/175 [00:29<01:29,  1.34it/s, ms_per_img=1.774, samples=1,760]
Resolution 128 eval:  31%|███▏      | 55/175 [00:29<01:29,  1.34it/s, ms_per_img=1.774, samples=1,792]
Resolution 128 eval:  32%|███▏      | 56/175 [00:29<01:21,  1.46it/s, ms_per_img=1.774, samples=1,792]
Resolution 128 eval:  32%|███▏      | 56/175 [00:30<01:21,  1.46it/s, ms_per_img=1.773, samples=1,824]
Resolution 128 eval:  33%|███▎      | 57/175 [00:30<01:21,  1.45it/s, ms_per_img=1.773, samples=1,824]
Resolution 128 eval:  33%|███▎      | 57/175 [00:30<01:21,  1.45it/s, ms_per_img=1.774, samples=1,856]
Resolution 128 eval:  33%|███▎      | 57/175 [00:31<01:21,  1.45it/s, ms_per_img=1.774, samples=1,888]
Resolution 128 eval:  34%|███▎      | 59/175 [00:31<01:16,  1.52it/s, ms_per_img=1.774, samples=1,888]
Resolution 128 eval:  34%|███▎      | 59/175 [00:31<01:16,  1.52it/s, ms_per_img=1.773, samples=1,920]
Resolution 128 eval:  34%|███▎      | 59/175 [00:32<01:16,  1.52it/s, ms_per_img=1.773, samples=1,952]
Resolution 128 eval:  35%|███▍      | 61/175 [00:32<01:11,  1.58it/s, ms_per_img=1.773, samples=1,952]
Resolution 128 eval:  35%|███▍      | 61/175 [00:33<01:11,  1.58it/s, ms_per_img=1.774, samples=1,984]
Resolution 128 eval:  35%|███▌      | 62/175 [00:33<01:08,  1.64it/s, ms_per_img=1.774, samples=1,984]
Resolution 128 eval:  35%|███▌      | 62/175 [00:33<01:08,  1.64it/s, ms_per_img=1.773, samples=2,016]
Resolution 128 eval:  36%|███▌      | 63/175 [00:33<01:06,  1.68it/s, ms_per_img=1.773, samples=2,016]
Resolution 128 eval:  36%|███▌      | 63/175 [00:34<01:06,  1.68it/s, ms_per_img=1.774, samples=2,048]
Resolution 128 eval:  37%|███▋      | 64/175 [00:34<01:10,  1.57it/s, ms_per_img=1.774, samples=2,048]
Resolution 128 eval:  37%|███▋      | 64/175 [00:35<01:10,  1.57it/s, ms_per_img=1.774, samples=2,080]
Resolution 128 eval:  37%|███▋      | 65/175 [00:35<01:19,  1.38it/s, ms_per_img=1.774, samples=2,080]
Resolution 128 eval:  37%|███▋      | 65/175 [00:36<01:19,  1.38it/s, ms_per_img=1.776, samples=2,112]
Resolution 128 eval:  38%|███▊      | 66/175 [00:36<01:15,  1.44it/s, ms_per_img=1.776, samples=2,112]
Resolution 128 eval:  38%|███▊      | 66/175 [00:36<01:15,  1.44it/s, ms_per_img=1.773, samples=2,144]
Resolution 128 eval:  38%|███▊      | 67/175 [00:36<01:16,  1.40it/s, ms_per_img=1.773, samples=2,144]
Resolution 128 eval:  38%|███▊      | 67/175 [00:37<01:16,  1.40it/s, ms_per_img=1.775, samples=2,176]
Resolution 128 eval:  39%|███▉      | 68/175 [00:37<01:15,  1.41it/s, ms_per_img=1.775, samples=2,176]
Resolution 128 eval:  39%|███▉      | 68/175 [00:38<01:15,  1.41it/s, ms_per_img=1.775, samples=2,208]
Resolution 128 eval:  39%|███▉      | 69/175 [00:38<01:11,  1.47it/s, ms_per_img=1.775, samples=2,208]
Resolution 128 eval:  39%|███▉      | 69/175 [00:39<01:11,  1.47it/s, ms_per_img=1.773, samples=2,240]
Resolution 128 eval:  40%|████      | 70/175 [00:39<01:26,  1.21it/s, ms_per_img=1.773, samples=2,240]
Resolution 128 eval:  40%|████      | 70/175 [00:40<01:26,  1.21it/s, ms_per_img=1.774, samples=2,272]
Resolution 128 eval:  41%|████      | 71/175 [00:40<01:32,  1.12it/s, ms_per_img=1.774, samples=2,272]
Resolution 128 eval:  41%|████      | 71/175 [00:41<01:32,  1.12it/s, ms_per_img=1.773, samples=2,304]
Resolution 128 eval:  41%|████      | 72/175 [00:41<01:35,  1.08it/s, ms_per_img=1.773, samples=2,304]
Resolution 128 eval:  41%|████      | 72/175 [00:42<01:35,  1.08it/s, ms_per_img=1.773, samples=2,336]
Resolution 128 eval:  42%|████▏     | 73/175 [00:42<01:43,  1.02s/it, ms_per_img=1.773, samples=2,336]
Resolution 128 eval:  42%|████▏     | 73/175 [00:43<01:43,  1.02s/it, ms_per_img=1.773, samples=2,368]
Resolution 128 eval:  42%|████▏     | 74/175 [00:43<01:37,  1.04it/s, ms_per_img=1.773, samples=2,368]
Resolution 128 eval:  42%|████▏     | 74/175 [00:44<01:37,  1.04it/s, ms_per_img=1.775, samples=2,400]
Resolution 128 eval:  43%|████▎     | 75/175 [00:44<01:49,  1.10s/it, ms_per_img=1.775, samples=2,400]
Resolution 128 eval:  43%|████▎     | 75/175 [00:45<01:49,  1.10s/it, ms_per_img=1.772, samples=2,432]
Resolution 128 eval:  43%|████▎     | 76/175 [00:45<01:48,  1.09s/it, ms_per_img=1.772, samples=2,432]
Resolution 128 eval:  43%|████▎     | 76/175 [00:47<01:48,  1.09s/it, ms_per_img=1.774, samples=2,464]
Resolution 128 eval:  44%|████▍     | 77/175 [00:47<01:48,  1.11s/it, ms_per_img=1.774, samples=2,464]
Resolution 128 eval:  44%|████▍     | 77/175 [00:48<01:48,  1.11s/it, ms_per_img=1.774, samples=2,496]
Resolution 128 eval:  45%|████▍     | 78/175 [00:48<01:55,  1.19s/it, ms_per_img=1.774, samples=2,496]
Resolution 128 eval:  45%|████▍     | 78/175 [00:50<01:55,  1.19s/it, ms_per_img=1.772, samples=2,528]
Resolution 128 eval:  45%|████▌     | 79/175 [00:50<02:09,  1.35s/it, ms_per_img=1.772, samples=2,528]
Resolution 128 eval:  45%|████▌     | 79/175 [00:50<02:09,  1.35s/it, ms_per_img=1.773, samples=2,560]
Resolution 128 eval:  46%|████▌     | 80/175 [00:50<01:45,  1.11s/it, ms_per_img=1.773, samples=2,560]
Resolution 128 eval:  46%|████▌     | 80/175 [00:51<01:45,  1.11s/it, ms_per_img=1.773, samples=2,592]
Resolution 128 eval:  46%|████▋     | 81/175 [00:51<01:33,  1.01it/s, ms_per_img=1.773, samples=2,592]
Resolution 128 eval:  46%|████▋     | 81/175 [00:52<01:33,  1.01it/s, ms_per_img=1.772, samples=2,624]
Resolution 128 eval:  47%|████▋     | 82/175 [00:52<01:21,  1.13it/s, ms_per_img=1.772, samples=2,624]
Resolution 128 eval:  47%|████▋     | 82/175 [00:53<01:21,  1.13it/s, ms_per_img=1.773, samples=2,656]
Resolution 128 eval:  47%|████▋     | 83/175 [00:53<01:32,  1.01s/it, ms_per_img=1.773, samples=2,656]
Resolution 128 eval:  47%|████▋     | 83/175 [00:55<01:32,  1.01s/it, ms_per_img=1.772, samples=2,688]
Resolution 128 eval:  48%|████▊     | 84/175 [00:55<01:56,  1.28s/it, ms_per_img=1.772, samples=2,688]
Resolution 128 eval:  48%|████▊     | 84/175 [00:57<01:56,  1.28s/it, ms_per_img=1.774, samples=2,720]
Resolution 128 eval:  49%|████▊     | 85/175 [00:57<02:09,  1.43s/it, ms_per_img=1.774, samples=2,720]
Resolution 128 eval:  49%|████▊     | 85/175 [00:58<02:09,  1.43s/it, ms_per_img=1.776, samples=2,752]
Resolution 128 eval:  49%|████▉     | 86/175 [00:58<02:05,  1.41s/it, ms_per_img=1.776, samples=2,752]
Resolution 128 eval:  49%|████▉     | 86/175 [00:59<02:05,  1.41s/it, ms_per_img=1.774, samples=2,784]
Resolution 128 eval:  50%|████▉     | 87/175 [00:59<01:57,  1.33s/it, ms_per_img=1.774, samples=2,784]
Resolution 128 eval:  50%|████▉     | 87/175 [01:00<01:57,  1.33s/it, ms_per_img=1.772, samples=2,816]
Resolution 128 eval:  50%|█████     | 88/175 [01:00<01:37,  1.12s/it, ms_per_img=1.772, samples=2,816]
Resolution 128 eval:  50%|█████     | 88/175 [01:01<01:37,  1.12s/it, ms_per_img=1.773, samples=2,848]
Resolution 128 eval:  51%|█████     | 89/175 [01:01<01:31,  1.06s/it, ms_per_img=1.773, samples=2,848]
Resolution 128 eval:  51%|█████     | 89/175 [01:01<01:31,  1.06s/it, ms_per_img=1.773, samples=2,880]
Resolution 128 eval:  51%|█████▏    | 90/175 [01:01<01:18,  1.08it/s, ms_per_img=1.773, samples=2,880]
Resolution 128 eval:  51%|█████▏    | 90/175 [01:02<01:18,  1.08it/s, ms_per_img=1.772, samples=2,912]
Resolution 128 eval:  52%|█████▏    | 91/175 [01:02<01:09,  1.21it/s, ms_per_img=1.772, samples=2,912]
Resolution 128 eval:  52%|█████▏    | 91/175 [01:03<01:09,  1.21it/s, ms_per_img=1.773, samples=2,944]
Resolution 128 eval:  53%|█████▎    | 92/175 [01:03<01:07,  1.23it/s, ms_per_img=1.773, samples=2,944]
Resolution 128 eval:  53%|█████▎    | 92/175 [01:03<01:07,  1.23it/s, ms_per_img=1.774, samples=2,976]
Resolution 128 eval:  53%|█████▎    | 93/175 [01:03<01:05,  1.25it/s, ms_per_img=1.774, samples=2,976]
Resolution 128 eval:  53%|█████▎    | 93/175 [01:04<01:05,  1.25it/s, ms_per_img=1.774, samples=3,008]
Resolution 128 eval:  54%|█████▎    | 94/175 [01:04<01:00,  1.33it/s, ms_per_img=1.774, samples=3,008]
Resolution 128 eval:  54%|█████▎    | 94/175 [01:05<01:00,  1.33it/s, ms_per_img=1.773, samples=3,040]
Resolution 128 eval:  54%|█████▍    | 95/175 [01:05<01:05,  1.23it/s, ms_per_img=1.773, samples=3,040]
Resolution 128 eval:  54%|█████▍    | 95/175 [01:06<01:05,  1.23it/s, ms_per_img=1.774, samples=3,072]
Resolution 128 eval:  55%|█████▍    | 96/175 [01:06<01:02,  1.27it/s, ms_per_img=1.774, samples=3,072]
Resolution 128 eval:  55%|█████▍    | 96/175 [01:06<01:02,  1.27it/s, ms_per_img=1.772, samples=3,104]
Resolution 128 eval:  55%|█████▌    | 97/175 [01:06<00:55,  1.40it/s, ms_per_img=1.772, samples=3,104]
Resolution 128 eval:  55%|█████▌    | 97/175 [01:07<00:55,  1.40it/s, ms_per_img=1.773, samples=3,136]
Resolution 128 eval:  56%|█████▌    | 98/175 [01:07<01:00,  1.27it/s, ms_per_img=1.773, samples=3,136]
Resolution 128 eval:  56%|█████▌    | 98/175 [01:09<01:00,  1.27it/s, ms_per_img=1.775, samples=3,168]
Resolution 128 eval:  57%|█████▋    | 99/175 [01:09<01:20,  1.06s/it, ms_per_img=1.775, samples=3,168]
Resolution 128 eval:  57%|█████▋    | 99/175 [01:11<01:20,  1.06s/it, ms_per_img=1.773, samples=3,200]
Resolution 128 eval:  57%|█████▋    | 100/175 [01:11<01:35,  1.28s/it, ms_per_img=1.773, samples=3,200]
Resolution 128 eval:  57%|█████▋    | 100/175 [01:12<01:35,  1.28s/it, ms_per_img=1.776, samples=3,232]
Resolution 128 eval:  58%|█████▊    | 101/175 [01:12<01:39,  1.35s/it, ms_per_img=1.776, samples=3,232]
Resolution 128 eval:  58%|█████▊    | 101/175 [01:14<01:39,  1.35s/it, ms_per_img=1.774, samples=3,264]
Resolution 128 eval:  58%|█████▊    | 102/175 [01:14<01:36,  1.33s/it, ms_per_img=1.774, samples=3,264]
Resolution 128 eval:  58%|█████▊    | 102/175 [01:14<01:36,  1.33s/it, ms_per_img=1.774, samples=3,296]
Resolution 128 eval:  59%|█████▉    | 103/175 [01:14<01:24,  1.17s/it, ms_per_img=1.774, samples=3,296]
Resolution 128 eval:  59%|█████▉    | 103/175 [01:15<01:24,  1.17s/it, ms_per_img=1.774, samples=3,328]
Resolution 128 eval:  59%|█████▉    | 104/175 [01:15<01:14,  1.04s/it, ms_per_img=1.774, samples=3,328]
Resolution 128 eval:  59%|█████▉    | 104/175 [01:16<01:14,  1.04s/it, ms_per_img=1.774, samples=3,360]
Resolution 128 eval:  60%|██████    | 105/175 [01:16<01:03,  1.10it/s, ms_per_img=1.774, samples=3,360]
Resolution 128 eval:  60%|██████    | 105/175 [01:16<01:03,  1.10it/s, ms_per_img=1.773, samples=3,392]
Resolution 128 eval:  61%|██████    | 106/175 [01:16<00:56,  1.22it/s, ms_per_img=1.773, samples=3,392]
Resolution 128 eval:  61%|██████    | 106/175 [01:17<00:56,  1.22it/s, ms_per_img=1.773, samples=3,424]
Resolution 128 eval:  61%|██████    | 107/175 [01:17<00:50,  1.36it/s, ms_per_img=1.773, samples=3,424]
Resolution 128 eval:  61%|██████    | 107/175 [01:17<00:50,  1.36it/s, ms_per_img=1.773, samples=3,456]
Resolution 128 eval:  62%|██████▏   | 108/175 [01:17<00:47,  1.42it/s, ms_per_img=1.773, samples=3,456]
Resolution 128 eval:  62%|██████▏   | 108/175 [01:18<00:47,  1.42it/s, ms_per_img=1.773, samples=3,488]

Acc=0.3459 AUC=0.5467 Fast=100.00% Medium=0.00% Full=0.00%

Resolution sweep:  25%|██▌       | 1/4 [02:37<07:52, 157.46s/it]

Source Res=128 Single: 5.916 ms/img | 169.0 FPS
Source Res=128 Batch=32: 1.782 ms/img | 561.1 FPS

Resolution 224

Resolution 224 eval:   0%|          | 0/175 [00:00<?, ?it/s]
Resolution 224 eval:   0%|          | 0/175 [00:00<?, ?it/s, ms_per_img=1.774, samples=32]
Resolution 224 eval:   1%|          | 1/175 [00:00<02:49,  1.03it/s, ms_per_img=1.774, samples=32]
Resolution 224 eval:   1%|          | 1/175 [00:02<02:49,  1.03it/s, ms_per_img=1.774, samples=64]
Resolution 224 eval:   1%|          | 2/175 [00:02<03:15,  1.13s/it, ms_per_img=1.774, samples=64]
Resolution 224 eval:   1%|          | 2/175 [00:04<03:15,  1.13s/it, ms_per_img=1.774, samples=96]
Resolution 224 eval:   2%|▏         | 3/175 [00:04<04:09,  1.45s/it, ms_per_img=1.774, samples=96]
Resolution 224 eval:   2%|▏         | 3/175 [00:05<04:09,  1.45s/it, ms_per_img=1.774, samples=128]
Resolution 224 eval:   2%|▏         | 4/175 [00:05<04:21,  1.53s/it, ms_per_img=1.774, samples=128]
Resolution 224 eval:   2%|▏         | 4/175 [00:07<04:21,  1.53s/it, ms_per_img=1.774, samples=160]
Resolution 224 eval:   3%|▎         | 5/175 [00:07<04:09,  1.47s/it, ms_per_img=1.774, samples=160]
Resolution 224 eval:   3%|▎         | 5/175 [00:08<04:09,  1.47s/it, ms_per_img=1.775, samples=192]
Resolution 224 eval:   3%|▎         | 6/175 [00:08<04:07,  1.47s/it, ms_per_img=1.775, samples=192]
Resolution 224 eval:   3%|▎         | 6/175 [00:09<04:07,  1.47s/it, ms_per_img=1.777, samples=224]
Resolution 224 eval:   4%|▍         | 7/175 [00:09<03:27,  1.24s/it, ms_per_img=1.777, samples=224]
Resolution 224 eval:   4%|▍         | 7/175 [00:10<03:27,  1.24s/it, ms_per_img=1.773, samples=256]
Resolution 224 eval:   5%|▍         | 8/175 [00:10<03:03,  1.10s/it, ms_per_img=1.773, samples=256]
Resolution 224 eval:   5%|▍         | 8/175 [00:10<03:03,  1.10s/it, ms_per_img=1.776, samples=288]
Resolution 224 eval:   5%|▌         | 9/175 [00:10<02:47,  1.01s/it, ms_per_img=1.776, samples=288]
Resolution 224 eval:   5%|▌         | 9/175 [00:12<02:47,  1.01s/it, ms_per_img=1.774, samples=320]
Resolution 224 eval:   6%|▌         | 10/175 [00:12<03:04,  1.12s/it, ms_per_img=1.774, samples=320]
Resolution 224 eval:   6%|▌         | 10/175 [00:14<03:04,  1.12s/it, ms_per_img=1.773, samples=352]
Resolution 224 eval:   6%|▋         | 11/175 [00:14<03:40,  1.34s/it, ms_per_img=1.773, samples=352]
Resolution 224 eval:   6%|▋         | 11/175 [00:14<03:40,  1.34s/it, ms_per_img=1.773, samples=384]
Resolution 224 eval:   6%|▋         | 11/175 [00:15<03:40,  1.34s/it, ms_per_img=1.774, samples=416]
Resolution 224 eval:   7%|▋         | 13/175 [00:15<02:53,  1.07s/it, ms_per_img=1.774, samples=416]
Resolution 224 eval:   7%|▋         | 13/175 [00:16<02:53,  1.07s/it, ms_per_img=1.774, samples=448]
Resolution 224 eval:   8%|▊         | 14/175 [00:16<02:32,  1.05it/s, ms_per_img=1.774, samples=448]
Resolution 224 eval:   8%|▊         | 14/175 [00:16<02:32,  1.05it/s, ms_per_img=1.777, samples=480]
Resolution 224 eval:   9%|▊         | 15/175 [00:16<02:17,  1.16it/s, ms_per_img=1.777, samples=480]
Resolution 224 eval:   9%|▊         | 15/175 [00:17<02:17,  1.16it/s, ms_per_img=1.774, samples=512]
Resolution 224 eval:   9%|▉         | 16/175 [00:17<02:10,  1.22it/s, ms_per_img=1.774, samples=512]
Resolution 224 eval:   9%|▉         | 16/175 [00:18<02:10,  1.22it/s, ms_per_img=1.776, samples=544]
Resolution 224 eval:  10%|▉         | 17/175 [00:18<02:19,  1.13it/s, ms_per_img=1.776, samples=544]
Resolution 224 eval:  10%|▉         | 17/175 [00:19<02:19,  1.13it/s, ms_per_img=1.775, samples=576]
Resolution 224 eval:  10%|█         | 18/175 [00:19<02:27,  1.07it/s, ms_per_img=1.775, samples=576]
Resolution 224 eval:  10%|█         | 18/175 [00:20<02:27,  1.07it/s, ms_per_img=1.777, samples=608]
Resolution 224 eval:  11%|█         | 19/175 [00:20<02:08,  1.22it/s, ms_per_img=1.777, samples=608]
Resolution 224 eval:  11%|█         | 19/175 [00:21<02:08,  1.22it/s, ms_per_img=1.773, samples=640]
Resolution 224 eval:  11%|█▏        | 20/175 [00:21<02:14,  1.15it/s, ms_per_img=1.773, samples=640]
Resolution 224 eval:  11%|█▏        | 20/175 [00:21<02:14,  1.15it/s, ms_per_img=1.774, samples=672]
Resolution 224 eval:  12%|█▏        | 21/175 [00:21<02:04,  1.23it/s, ms_per_img=1.774, samples=672]
Resolution 224 eval:  12%|█▏        | 21/175 [00:22<02:04,  1.23it/s, ms_per_img=1.774, samples=704]
Resolution 224 eval:  13%|█▎        | 22/175 [00:22<02:04,  1.23it/s, ms_per_img=1.774, samples=704]
Resolution 224 eval:  13%|█▎        | 22/175 [00:23<02:04,  1.23it/s, ms_per_img=1.773, samples=736]
Resolution 224 eval:  13%|█▎        | 23/175 [00:23<02:05,  1.21it/s, ms_per_img=1.773, samples=736]
Resolution 224 eval:  13%|█▎        | 23/175 [00:24<02:05,  1.21it/s, ms_per_img=1.776, samples=768]
Resolution 224 eval:  14%|█▎        | 24/175 [00:24<02:10,  1.16it/s, ms_per_img=1.776, samples=768]
Resolution 224 eval:  14%|█▎        | 24/175 [00:25<02:10,  1.16it/s, ms_per_img=1.773, samples=800]
Resolution 224 eval:  14%|█▍        | 25/175 [00:25<02:07,  1.18it/s, ms_per_img=1.773, samples=800]
Resolution 224 eval:  14%|█▍        | 25/175 [00:25<02:07,  1.18it/s, ms_per_img=1.776, samples=832]
Resolution 224 eval:  15%|█▍        | 26/175 [00:25<01:54,  1.31it/s, ms_per_img=1.776, samples=832]
Resolution 224 eval:  15%|█▍        | 26/175 [00:26<01:54,  1.31it/s, ms_per_img=1.776, samples=864]
Resolution 224 eval:  15%|█▌        | 27/175 [00:26<01:56,  1.27it/s, ms_per_img=1.776, samples=864]
Resolution 224 eval:  15%|█▌        | 27/175 [00:27<01:56,  1.27it/s, ms_per_img=1.775, samples=896]
Resolution 224 eval:  16%|█▌        | 28/175 [00:27<01:54,  1.28it/s, ms_per_img=1.775, samples=896]
Resolution 224 eval:  16%|█▌        | 28/175 [00:28<01:54,  1.28it/s, ms_per_img=1.774, samples=928]
Resolution 224 eval:  17%|█▋        | 29/175 [00:28<01:53,  1.29it/s, ms_per_img=1.774, samples=928]
Resolution 224 eval:  17%|█▋        | 29/175 [00:29<01:53,  1.29it/s, ms_per_img=1.773, samples=960]
Resolution 224 eval:  17%|█▋        | 30/175 [00:29<01:52,  1.29it/s, ms_per_img=1.773, samples=960]
Resolution 224 eval:  17%|█▋        | 30/175 [00:29<01:52,  1.29it/s, ms_per_img=1.775, samples=992]
Resolution 224 eval:  18%|█▊        | 31/175 [00:29<01:44,  1.38it/s, ms_per_img=1.775, samples=992]
Resolution 224 eval:  18%|█▊        | 31/175 [00:30<01:44,  1.38it/s, ms_per_img=1.773, samples=1,024]
Resolution 224 eval:  18%|█▊        | 32/175 [00:30<02:03,  1.16it/s, ms_per_img=1.773, samples=1,024]
Resolution 224 eval:  18%|█▊        | 32/175 [00:31<02:03,  1.16it/s, ms_per_img=1.774, samples=1,056]
Resolution 224 eval:  19%|█▉        | 33/175 [00:31<01:50,  1.28it/s, ms_per_img=1.774, samples=1,056]
Resolution 224 eval:  19%|█▉        | 33/175 [00:32<01:50,  1.28it/s, ms_per_img=1.775, samples=1,088]
Resolution 224 eval:  19%|█▉        | 34/175 [00:32<02:13,  1.06it/s, ms_per_img=1.775, samples=1,088]
Resolution 224 eval:  19%|█▉        | 34/175 [00:34<02:13,  1.06it/s, ms_per_img=1.775, samples=1,120]
Resolution 224 eval:  20%|██        | 35/175 [00:34<02:35,  1.11s/it, ms_per_img=1.775, samples=1,120]
Resolution 224 eval:  20%|██        | 35/175 [00:35<02:35,  1.11s/it, ms_per_img=1.774, samples=1,152]
Resolution 224 eval:  21%|██        | 36/175 [00:35<02:52,  1.24s/it, ms_per_img=1.774, samples=1,152]
Resolution 224 eval:  21%|██        | 36/175 [00:36<02:52,  1.24s/it, ms_per_img=1.775, samples=1,184]
Resolution 224 eval:  21%|██        | 36/175 [00:36<02:52,  1.24s/it, ms_per_img=1.775, samples=1,216]
Resolution 224 eval:  22%|██▏       | 38/175 [00:36<01:57,  1.17it/s, ms_per_img=1.775, samples=1,216]
Resolution 224 eval:  22%|██▏       | 38/175 [00:37<01:57,  1.17it/s, ms_per_img=1.774, samples=1,248]
Resolution 224 eval:  22%|██▏       | 39/175 [00:37<01:45,  1.29it/s, ms_per_img=1.774, samples=1,248]
Resolution 224 eval:  22%|██▏       | 39/175 [00:37<01:45,  1.29it/s, ms_per_img=1.775, samples=1,280]
Resolution 224 eval:  23%|██▎       | 40/175 [00:37<01:39,  1.36it/s, ms_per_img=1.775, samples=1,280]
Resolution 224 eval:  23%|██▎       | 40/175 [00:38<01:39,  1.36it/s, ms_per_img=1.775, samples=1,312]
Resolution 224 eval:  23%|██▎       | 41/175 [00:38<01:35,  1.40it/s, ms_per_img=1.775, samples=1,312]
Resolution 224 eval:  23%|██▎       | 41/175 [00:39<01:35,  1.40it/s, ms_per_img=1.778, samples=1,344]
Resolution 224 eval:  24%|██▍       | 42/175 [00:39<01:57,  1.13it/s, ms_per_img=1.778, samples=1,344]
Resolution 224 eval:  24%|██▍       | 42/175 [00:40<01:57,  1.13it/s, ms_per_img=1.775, samples=1,376]
Resolution 224 eval:  25%|██▍       | 43/175 [00:40<01:49,  1.20it/s, ms_per_img=1.775, samples=1,376]
Resolution 224 eval:  25%|██▍       | 43/175 [00:41<01:49,  1.20it/s, ms_per_img=1.778, samples=1,408]
Resolution 224 eval:  25%|██▌       | 44/175 [00:41<01:44,  1.26it/s, ms_per_img=1.778, samples=1,408]
Resolution 224 eval:  25%|██▌       | 44/175 [00:41<01:44,  1.26it/s, ms_per_img=1.777, samples=1,440]
Resolution 224 eval:  26%|██▌       | 45/175 [00:41<01:37,  1.34it/s, ms_per_img=1.777, samples=1,440]
Resolution 224 eval:  26%|██▌       | 45/175 [00:42<01:37,  1.34it/s, ms_per_img=1.775, samples=1,472]
Resolution 224 eval:  26%|██▋       | 46/175 [00:42<01:32,  1.40it/s, ms_per_img=1.775, samples=1,472]
Resolution 224 eval:  26%|██▋       | 46/175 [00:43<01:32,  1.40it/s, ms_per_img=1.776, samples=1,504]
Resolution 224 eval:  27%|██▋       | 47/175 [00:43<01:49,  1.17it/s, ms_per_img=1.776, samples=1,504]
Resolution 224 eval:  27%|██▋       | 47/175 [00:44<01:49,  1.17it/s, ms_per_img=1.775, samples=1,536]
Resolution 224 eval:  27%|██▋       | 48/175 [00:44<01:49,  1.16it/s, ms_per_img=1.775, samples=1,536]
Resolution 224 eval:  27%|██▋       | 48/175 [00:45<01:49,  1.16it/s, ms_per_img=1.773, samples=1,568]
Resolution 224 eval:  28%|██▊       | 49/175 [00:45<01:57,  1.08it/s, ms_per_img=1.773, samples=1,568]
Resolution 224 eval:  28%|██▊       | 49/175 [00:46<01:57,  1.08it/s, ms_per_img=1.775, samples=1,600]
Resolution 224 eval:  29%|██▊       | 50/175 [00:46<02:01,  1.03it/s, ms_per_img=1.775, samples=1,600]
Resolution 224 eval:  29%|██▊       | 50/175 [00:47<02:01,  1.03it/s, ms_per_img=1.776, samples=1,632]
Resolution 224 eval:  29%|██▉       | 51/175 [00:47<01:47,  1.16it/s, ms_per_img=1.776, samples=1,632]
Resolution 224 eval:  29%|██▉       | 51/175 [00:48<01:47,  1.16it/s, ms_per_img=1.775, samples=1,664]
Resolution 224 eval:  30%|██▉       | 52/175 [00:48<01:43,  1.18it/s, ms_per_img=1.775, samples=1,664]
Resolution 224 eval:  30%|██▉       | 52/175 [00:48<01:43,  1.18it/s, ms_per_img=1.773, samples=1,696]
Resolution 224 eval:  30%|███       | 53/175 [00:48<01:39,  1.22it/s, ms_per_img=1.773, samples=1,696]
Resolution 224 eval:  30%|███       | 53/175 [00:49<01:39,  1.22it/s, ms_per_img=1.776, samples=1,728]
Resolution 224 eval:  31%|███       | 54/175 [00:49<01:36,  1.25it/s, ms_per_img=1.776, samples=1,728]
Resolution 224 eval:  31%|███       | 54/175 [00:50<01:36,  1.25it/s, ms_per_img=1.775, samples=1,760]
Resolution 224 eval:  31%|███▏      | 55/175 [00:50<01:43,  1.16it/s, ms_per_img=1.775, samples=1,760]
Resolution 224 eval:  31%|███▏      | 55/175 [00:51<01:43,  1.16it/s, ms_per_img=1.773, samples=1,792]
Resolution 224 eval:  32%|███▏      | 56/175 [00:51<01:42,  1.16it/s, ms_per_img=1.773, samples=1,792]
Resolution 224 eval:  32%|███▏      | 56/175 [00:52<01:42,  1.16it/s, ms_per_img=1.775, samples=1,824]
Resolution 224 eval:  33%|███▎      | 57/175 [00:52<01:38,  1.20it/s, ms_per_img=1.775, samples=1,824]
Resolution 224 eval:  33%|███▎      | 57/175 [00:52<01:38,  1.20it/s, ms_per_img=1.776, samples=1,856]
Resolution 224 eval:  33%|███▎      | 58/175 [00:52<01:32,  1.26it/s, ms_per_img=1.776, samples=1,856]
Resolution 224 eval:  33%|███▎      | 58/175 [00:53<01:32,  1.26it/s, ms_per_img=1.773, samples=1,888]
Resolution 224 eval:  34%|███▎      | 59/175 [00:53<01:34,  1.22it/s, ms_per_img=1.773, samples=1,888]
Resolution 224 eval:  34%|███▎      | 59/175 [00:54<01:34,  1.22it/s, ms_per_img=1.775, samples=1,920]
Resolution 224 eval:  34%|███▍      | 60/175 [00:54<01:26,  1.34it/s, ms_per_img=1.775, samples=1,920]
Resolution 224 eval:  34%|███▍      | 60/175 [00:55<01:26,  1.34it/s, ms_per_img=1.775, samples=1,952]
Resolution 224 eval:  35%|███▍      | 61/175 [00:55<01:26,  1.31it/s, ms_per_img=1.775, samples=1,952]
Resolution 224 eval:  35%|███▍      | 61/175 [00:55<01:26,  1.31it/s, ms_per_img=1.775, samples=1,984]
Resolution 224 eval:  35%|███▌      | 62/175 [00:55<01:23,  1.35it/s, ms_per_img=1.775, samples=1,984]
Resolution 224 eval:  35%|███▌      | 62/175 [00:56<01:23,  1.35it/s, ms_per_img=1.776, samples=2,016]
Resolution 224 eval:  36%|███▌      | 63/175 [00:56<01:17,  1.44it/s, ms_per_img=1.776, samples=2,016]
Resolution 224 eval:  36%|███▌      | 63/175 [00:57<01:17,  1.44it/s, ms_per_img=1.775, samples=2,048]
Resolution 224 eval:  37%|███▋      | 64/175 [00:57<01:19,  1.40it/s, ms_per_img=1.775, samples=2,048]
Resolution 224 eval:  37%|███▋      | 64/175 [00:58<01:19,  1.40it/s, ms_per_img=1.774, samples=2,080]
Resolution 224 eval:  37%|███▋      | 65/175 [00:58<01:28,  1.24it/s, ms_per_img=1.774, samples=2,080]
Resolution 224 eval:  37%|███▋      | 65/175 [00:58<01:28,  1.24it/s, ms_per_img=1.777, samples=2,112]
Resolution 224 eval:  38%|███▊      | 66/175 [00:58<01:27,  1.24it/s, ms_per_img=1.777, samples=2,112]
Resolution 224 eval:  38%|███▊      | 66/175 [01:00<01:27,  1.24it/s, ms_per_img=1.775, samples=2,144]
Resolution 224 eval:  38%|███▊      | 67/175 [01:00<01:38,  1.09it/s, ms_per_img=1.775, samples=2,144]
Resolution 224 eval:  38%|███▊      | 67/175 [01:00<01:38,  1.09it/s, ms_per_img=1.774, samples=2,176]
Resolution 224 eval:  39%|███▉      | 68/175 [01:00<01:31,  1.16it/s, ms_per_img=1.774, samples=2,176]
Resolution 224 eval:  39%|███▉      | 68/175 [01:01<01:31,  1.16it/s, ms_per_img=1.774, samples=2,208]
Resolution 224 eval:  39%|███▉      | 69/175 [01:01<01:29,  1.19it/s, ms_per_img=1.774, samples=2,208]
Resolution 224 eval:  39%|███▉      | 69/175 [01:02<01:29,  1.19it/s, ms_per_img=1.772, samples=2,240]
Resolution 224 eval:  40%|████      | 70/175 [01:02<01:27,  1.20it/s, ms_per_img=1.772, samples=2,240]
Resolution 224 eval:  40%|████      | 70/175 [01:03<01:27,  1.20it/s, ms_per_img=1.773, samples=2,272]
Resolution 224 eval:  41%|████      | 71/175 [01:03<01:33,  1.12it/s, ms_per_img=1.773, samples=2,272]
Resolution 224 eval:  41%|████      | 71/175 [01:04<01:33,  1.12it/s, ms_per_img=1.777, samples=2,304]
Resolution 224 eval:  41%|████      | 72/175 [01:04<01:41,  1.02it/s, ms_per_img=1.777, samples=2,304]
Resolution 224 eval:  41%|████      | 72/175 [01:05<01:41,  1.02it/s, ms_per_img=1.773, samples=2,336]
Resolution 224 eval:  42%|████▏     | 73/175 [01:05<01:27,  1.17it/s, ms_per_img=1.773, samples=2,336]
Resolution 224 eval:  42%|████▏     | 73/175 [01:06<01:27,  1.17it/s, ms_per_img=1.774, samples=2,368]
Resolution 224 eval:  42%|████▏     | 74/175 [01:06<01:33,  1.08it/s, ms_per_img=1.774, samples=2,368]
Resolution 224 eval:  42%|████▏     | 74/175 [01:07<01:33,  1.08it/s, ms_per_img=1.779, samples=2,400]
Resolution 224 eval:  43%|████▎     | 75/175 [01:07<01:25,  1.17it/s, ms_per_img=1.779, samples=2,400]
Resolution 224 eval:  43%|████▎     | 75/175 [01:07<01:25,  1.17it/s, ms_per_img=1.774, samples=2,432]
Resolution 224 eval:  43%|████▎     | 76/175 [01:07<01:23,  1.19it/s, ms_per_img=1.774, samples=2,432]
Resolution 224 eval:  43%|████▎     | 76/175 [01:09<01:23,  1.19it/s, ms_per_img=1.774, samples=2,464]
Resolution 224 eval:  44%|████▍     | 77/175 [01:09<01:31,  1.07it/s, ms_per_img=1.774, samples=2,464]
Resolution 224 eval:  44%|████▍     | 77/175 [01:10<01:31,  1.07it/s, ms_per_img=1.773, samples=2,496]
Resolution 224 eval:  45%|████▍     | 78/175 [01:10<01:57,  1.22s/it, ms_per_img=1.773, samples=2,496]
Resolution 224 eval:  45%|████▍     | 78/175 [01:11<01:57,  1.22s/it, ms_per_img=1.773, samples=2,528]
Resolution 224 eval:  45%|████▌     | 79/175 [01:11<01:44,  1.08s/it, ms_per_img=1.773, samples=2,528]
Resolution 224 eval:  45%|████▌     | 79/175 [01:12<01:44,  1.08s/it, ms_per_img=1.776, samples=2,560]
Resolution 224 eval:  46%|████▌     | 80/175 [01:12<01:40,  1.06s/it, ms_per_img=1.776, samples=2,560]
Resolution 224 eval:  46%|████▌     | 80/175 [01:13<01:40,  1.06s/it, ms_per_img=1.776, samples=2,592]
Resolution 224 eval:  46%|████▋     | 81/175 [01:13<01:43,  1.10s/it, ms_per_img=1.776, samples=2,592]
Resolution 224 eval:  46%|████▋     | 81/175 [01:14<01:43,  1.10s/it, ms_per_img=1.776, samples=2,624]
Resolution 224 eval:  47%|████▋     | 82/175 [01:14<01:37,  1.05s/it, ms_per_img=1.776, samples=2,624]
Resolution 224 eval:  47%|████▋     | 82/175 [01:15<01:37,  1.05s/it, ms_per_img=1.777, samples=2,656]
Resolution 224 eval:  47%|████▋     | 83/175 [01:15<01:32,  1.00s/it, ms_per_img=1.777, samples=2,656]
Resolution 224 eval:  47%|████▋     | 83/175 [01:16<01:32,  1.00s/it, ms_per_img=1.774, samples=2,688]
Resolution 224 eval:  48%|████▊     | 84/175 [01:16<01:32,  1.01s/it, ms_per_img=1.774, samples=2,688]
Resolution 224 eval:  48%|████▊     | 84/175 [01:18<01:32,  1.01s/it, ms_per_img=1.774, samples=2,720]
Resolution 224 eval:  49%|████▊     | 85/175 [01:18<01:42,  1.14s/it, ms_per_img=1.774, samples=2,720]
Resolution 224 eval:  49%|████▊     | 85/175 [01:19<01:42,  1.14s/it, ms_per_img=1.776, samples=2,752]
Resolution 224 eval:  49%|████▉     | 86/175 [01:19<01:41,  1.15s/it, ms_per_img=1.776, samples=2,752]
Resolution 224 eval:  49%|████▉     | 86/175 [01:20<01:41,  1.15s/it, ms_per_img=1.773, samples=2,784]
Resolution 224 eval:  50%|████▉     | 87/175 [01:20<01:42,  1.17s/it, ms_per_img=1.773, samples=2,784]
Resolution 224 eval:  50%|████▉     | 87/175 [01:21<01:42,  1.17s/it, ms_per_img=1.774, samples=2,816]
Resolution 224 eval:  50%|█████     | 88/175 [01:21<01:25,  1.02it/s, ms_per_img=1.774, samples=2,816]
Resolution 224 eval:  50%|█████     | 88/175 [01:22<01:25,  1.02it/s, ms_per_img=1.773, samples=2,848]
Resolution 224 eval:  51%|█████     | 89/175 [01:22<01:34,  1.10s/it, ms_per_img=1.773, samples=2,848]
Resolution 224 eval:  51%|█████     | 89/175 [01:23<01:34,  1.10s/it, ms_per_img=1.774, samples=2,880]
Resolution 224 eval:  51%|█████▏    | 90/175 [01:23<01:19,  1.07it/s, ms_per_img=1.774, samples=2,880]
Resolution 224 eval:  51%|█████▏    | 90/175 [01:23<01:19,  1.07it/s, ms_per_img=1.776, samples=2,912]
Resolution 224 eval:  52%|█████▏    | 91/175 [01:23<01:14,  1.13it/s, ms_per_img=1.776, samples=2,912]
Resolution 224 eval:  52%|█████▏    | 91/175 [01:25<01:14,  1.13it/s, ms_per_img=1.774, samples=2,944]
Resolution 224 eval:  53%|█████▎    | 92/175 [01:25<01:26,  1.04s/it, ms_per_img=1.774, samples=2,944]
Resolution 224 eval:  53%|█████▎    | 92/175 [01:25<01:26,  1.04s/it, ms_per_img=1.774, samples=2,976]
Resolution 224 eval:  53%|█████▎    | 93/175 [01:25<01:13,  1.12it/s, ms_per_img=1.774, samples=2,976]
Resolution 224 eval:  53%|█████▎    | 93/175 [01:26<01:13,  1.12it/s, ms_per_img=1.774, samples=3,008]
Resolution 224 eval:  54%|█████▎    | 94/175 [01:26<01:08,  1.18it/s, ms_per_img=1.774, samples=3,008]
Resolution 224 eval:  54%|█████▎    | 94/175 [01:27<01:08,  1.18it/s, ms_per_img=1.777, samples=3,040]
Resolution 224 eval:  54%|█████▍    | 95/175 [01:27<01:08,  1.17it/s, ms_per_img=1.777, samples=3,040]
Resolution 224 eval:  54%|█████▍    | 95/175 [01:27<01:08,  1.17it/s, ms_per_img=1.773, samples=3,072]
Resolution 224 eval:  55%|█████▍    | 96/175 [01:27<01:02,  1.27it/s, ms_per_img=1.773, samples=3,072]
Resolution 224 eval:  55%|█████▍    | 96/175 [01:28<01:02,  1.27it/s, ms_per_img=1.773, samples=3,104]
Resolution 224 eval:  55%|█████▌    | 97/175 [01:28<00:57,  1.36it/s, ms_per_img=1.773, samples=3,104]
Resolution 224 eval:  55%|█████▌    | 97/175 [01:29<00:57,  1.36it/s, ms_per_img=1.776, samples=3,136]
Resolution 224 eval:  56%|█████▌    | 98/175 [01:29<01:03,  1.21it/s, ms_per_img=1.776, samples=3,136]
Resolution 224 eval:  56%|█████▌    | 98/175 [01:30<01:03,  1.21it/s, ms_per_img=1.776, samples=3,168]

Acc=0.3575 AUC=0.5414 Fast=100.00% Medium=0.00% Full=0.00%

Resolution sweep:  50%|█████     | 2/4 [04:46<04:40, 140.45s/it]

Source Res=224 Single: 5.869 ms/img | 170.4 FPS
Source Res=224 Batch=32: 1.782 ms/img | 561.0 FPS

Resolution 256

Resolution 256 eval:   0%|          | 0/175 [00:00<?, ?it/s]
Resolution 256 eval:   0%|          | 0/175 [00:00<?, ?it/s, ms_per_img=1.781, samples=32]
Resolution 256 eval:   0%|          | 0/175 [00:00<?, ?it/s, ms_per_img=1.773, samples=64]
Resolution 256 eval:   1%|          | 2/175 [00:00<00:52,  3.27it/s, ms_per_img=1.773, samples=64]
Resolution 256 eval:   1%|          | 2/175 [00:01<00:52,  3.27it/s, ms_per_img=1.778, samples=96]
Resolution 256 eval:   1%|          | 2/175 [00:01<00:52,  3.27it/s, ms_per_img=1.774, samples=128]
Resolution 256 eval:   2%|▏         | 4/175 [00:01<01:10,  2.41it/s, ms_per_img=1.774, samples=128]
Resolution 256 eval:   2%|▏         | 4/175 [00:01<01:10,  2.41it/s, ms_per_img=1.776, samples=160]
Resolution 256 eval:   2%|▏         | 4/175 [00:02<01:10,  2.41it/s, ms_per_img=1.774, samples=192]
Resolution 256 eval:   3%|▎         | 6/175 [00:02<01:05,  2.60it/s, ms_per_img=1.774, samples=192]
Resolution 256 eval:   3%|▎         | 6/175 [00:02<01:05,  2.60it/s, ms_per_img=1.776, samples=224]
Resolution 256 eval:   3%|▎         | 6/175 [00:02<01:05,  2.60it/s, ms_per_img=1.779, samples=256]
Resolution 256 eval:   5%|▍         | 8/175 [00:02<00:55,  3.00it/s, ms_per_img=1.779, samples=256]
Resolution 256 eval:   5%|▍         | 8/175 [00:03<00:55,  3.00it/s, ms_per_img=1.775, samples=288]
Resolution 256 eval:   5%|▍         | 8/175 [00:03<00:55,  3.00it/s, ms_per_img=1.775, samples=320]
Resolution 256 eval:   6%|▌         | 10/175 [00:03<00:59,  2.78it/s, ms_per_img=1.775, samples=320]
Resolution 256 eval:   6%|▌         | 10/175 [00:04<00:59,  2.78it/s, ms_per_img=1.775, samples=352]
Resolution 256 eval:   6%|▌         | 10/175 [00:04<00:59,  2.78it/s, ms_per_img=1.776, samples=384]
Resolution 256 eval:   7%|▋         | 12/175 [00:04<01:00,  2.70it/s, ms_per_img=1.776, samples=384]
Resolution 256 eval:   7%|▋         | 12/175 [00:04<01:00,  2.70it/s, ms_per_img=1.777, samples=416]
Resolution 256 eval:   7%|▋         | 12/175 [00:04<01:00,  2.70it/s, ms_per_img=1.777, samples=448]
Resolution 256 eval:   8%|▊         | 14/175 [00:04<00:55,  2.88it/s, ms_per_img=1.777, samples=448]
Resolution 256 eval:   8%|▊         | 14/175 [00:05<00:55,  2.88it/s, ms_per_img=1.774, samples=480]
Resolution 256 eval:   8%|▊         | 14/175 [00:05<00:55,  2.88it/s, ms_per_img=1.776, samples=512]
Resolution 256 eval:   8%|▊         | 14/175 [00:05<00:55,  2.88it/s, ms_per_img=1.776, samples=544]
Resolution 256 eval:  10%|▉         | 17/175 [00:05<00:51,  3.05it/s, ms_per_img=1.776, samples=544]
Resolution 256 eval:  10%|▉         | 17/175 [00:06<00:51,  3.05it/s, ms_per_img=1.778, samples=576]
Resolution 256 eval:  10%|▉         | 17/175 [00:06<00:51,  3.05it/s, ms_per_img=1.773, samples=608]
Resolution 256 eval:  11%|█         | 19/175 [00:06<00:48,  3.25it/s, ms_per_img=1.773, samples=608]
Resolution 256 eval:  11%|█         | 19/175 [00:06<00:48,  3.25it/s, ms_per_img=1.775, samples=640]
Resolution 256 eval:  11%|█         | 19/175 [00:07<00:48,  3.25it/s, ms_per_img=1.776, samples=672]
Resolution 256 eval:  12%|█▏        | 21/175 [00:07<00:47,  3.21it/s, ms_per_img=1.776, samples=672]
Resolution 256 eval:  12%|█▏        | 21/175 [00:07<00:47,  3.21it/s, ms_per_img=1.776, samples=704]
Resolution 256 eval:  12%|█▏        | 21/175 [00:07<00:47,  3.21it/s, ms_per_img=1.777, samples=736]
Resolution 256 eval:  13%|█▎        | 23/175 [00:07<00:49,  3.05it/s, ms_per_img=1.777, samples=736]
Resolution 256 eval:  13%|█▎        | 23/175 [00:08<00:49,  3.05it/s, ms_per_img=1.777, samples=768]
Resolution 256 eval:  13%|█▎        | 23/175 [00:08<00:49,  3.05it/s, ms_per_img=1.778, samples=800]
Resolution 256 eval:  14%|█▍        | 25/175 [00:08<00:48,  3.07it/s, ms_per_img=1.778, samples=800]
Resolution 256 eval:  14%|█▍        | 25/175 [00:08<00:48,  3.07it/s, ms_per_img=1.777, samples=832]
Resolution 256 eval:  14%|█▍        | 25/175 [00:09<00:48,  3.07it/s, ms_per_img=1.774, samples=864]
Resolution 256 eval:  15%|█▌        | 27/175 [00:09<00:51,  2.90it/s, ms_per_img=1.774, samples=864]
Resolution 256 eval:  15%|█▌        | 27/175 [00:09<00:51,  2.90it/s, ms_per_img=1.776, samples=896]
Resolution 256 eval:  15%|█▌        | 27/175 [00:09<00:51,  2.90it/s, ms_per_img=1.775, samples=928]
Resolution 256 eval:  17%|█▋        | 29/175 [00:09<00:49,  2.96it/s, ms_per_img=1.775, samples=928]
Resolution 256 eval:  17%|█▋        | 29/175 [00:10<00:49,  2.96it/s, ms_per_img=1.776, samples=960]
Resolution 256 eval:  17%|█▋        | 29/175 [00:10<00:49,  2.96it/s, ms_per_img=1.778, samples=992]
Resolution 256 eval:  18%|█▊        | 31/175 [00:10<00:48,  2.94it/s, ms_per_img=1.778, samples=992]
Resolution 256 eval:  18%|█▊        | 31/175 [00:10<00:48,  2.94it/s, ms_per_img=1.776, samples=1,024]
Resolution 256 eval:  18%|█▊        | 31/175 [00:11<00:48,  2.94it/s, ms_per_img=1.776, samples=1,056]
Resolution 256 eval:  19%|█▉        | 33/175 [00:11<00:47,  2.97it/s, ms_per_img=1.776, samples=1,056]
Resolution 256 eval:  19%|█▉        | 33/175 [00:11<00:47,  2.97it/s, ms_per_img=1.774, samples=1,088]
Resolution 256 eval:  19%|█▉        | 33/175 [00:12<00:47,  2.97it/s, ms_per_img=1.780, samples=1,120]
Resolution 256 eval:  20%|██        | 35/175 [00:12<00:56,  2.48it/s, ms_per_img=1.780, samples=1,120]
Resolution 256 eval:  20%|██        | 35/175 [00:12<00:56,  2.48it/s, ms_per_img=1.778, samples=1,152]
Resolution 256 eval:  20%|██        | 35/175 [00:13<00:56,  2.48it/s, ms_per_img=1.775, samples=1,184]
Resolution 256 eval:  21%|██        | 37/175 [00:13<00:54,  2.53it/s, ms_per_img=1.775, samples=1,184]
Resolution 256 eval:  21%|██        | 37/175 [00:13<00:54,  2.53it/s, ms_per_img=1.777, samples=1,216]
Resolution 256 eval:  21%|██        | 37/175 [00:13<00:54,  2.53it/s, ms_per_img=1.777, samples=1,248]
Resolution 256 eval:  22%|██▏       | 39/175 [00:13<00:49,  2.77it/s, ms_per_img=1.777, samples=1,248]
Resolution 256 eval:  22%|██▏       | 39/175 [00:13<00:49,  2.77it/s, ms_per_img=1.775, samples=1,280]
Resolution 256 eval:  22%|██▏       | 39/175 [00:14<00:49,  2.77it/s, ms_per_img=1.777, samples=1,312]
Resolution 256 eval:  23%|██▎       | 41/175 [00:14<00:46,  2.86it/s, ms_per_img=1.777, samples=1,312]
Resolution 256 eval:  23%|██▎       | 41/175 [00:14<00:46,  2.86it/s, ms_per_img=1.775, samples=1,344]
Resolution 256 eval:  23%|██▎       | 41/175 [00:15<00:46,  2.86it/s, ms_per_img=1.774, samples=1,376]
Resolution 256 eval:  25%|██▍       | 43/175 [00:15<00:49,  2.69it/s, ms_per_img=1.774, samples=1,376]
Resolution 256 eval:  25%|██▍       | 43/175 [00:15<00:49,  2.69it/s, ms_per_img=1.777, samples=1,408]
Resolution 256 eval:  25%|██▍       | 43/175 [00:15<00:49,  2.69it/s, ms_per_img=1.776, samples=1,440]
Resolution 256 eval:  26%|██▌       | 45/175 [00:15<00:46,  2.80it/s, ms_per_img=1.776, samples=1,440]
Resolution 256 eval:  26%|██▌       | 45/175 [00:15<00:46,  2.80it/s, ms_per_img=1.779, samples=1,472]
Resolution 256 eval:  26%|██▌       | 45/175 [00:16<00:46,  2.80it/s, ms_per_img=1.775, samples=1,504]
Resolution 256 eval:  27%|██▋       | 47/175 [00:16<00:44,  2.90it/s, ms_per_img=1.775, samples=1,504]
Resolution 256 eval:  27%|██▋       | 47/175 [00:16<00:44,  2.90it/s, ms_per_img=1.778, samples=1,536]
Resolution 256 eval:  27%|██▋       | 47/175 [00:16<00:44,  2.90it/s, ms_per_img=1.776, samples=1,568]
Resolution 256 eval:  28%|██▊       | 49/175 [00:16<00:41,  3.03it/s, ms_per_img=1.776, samples=1,568]
Resolution 256 eval:  28%|██▊       | 49/175 [00:17<00:41,  3.03it/s, ms_per_img=1.776, samples=1,600]
Resolution 256 eval:  28%|██▊       | 49/175 [00:17<00:41,  3.03it/s, ms_per_img=1.777, samples=1,632]
Resolution 256 eval:  29%|██▉       | 51/175 [00:17<00:39,  3.10it/s, ms_per_img=1.777, samples=1,632]
Resolution 256 eval:  29%|██▉       | 51/175 [00:18<00:39,  3.10it/s, ms_per_img=1.775, samples=1,664]
Resolution 256 eval:  29%|██▉       | 51/175 [00:18<00:39,  3.10it/s, ms_per_img=1.775, samples=1,696]
Resolution 256 eval:  30%|███       | 53/175 [00:18<00:41,  2.92it/s, ms_per_img=1.775, samples=1,696]
Resolution 256 eval:  30%|███       | 53/175 [00:18<00:41,  2.92it/s, ms_per_img=1.777, samples=1,728]
Resolution 256 eval:  30%|███       | 53/175 [00:19<00:41,  2.92it/s, ms_per_img=1.778, samples=1,760]
Resolution 256 eval:  31%|███▏      | 55/175 [00:19<00:40,  2.93it/s, ms_per_img=1.778, samples=1,760]
Resolution 256 eval:  31%|███▏      | 55/175 [00:19<00:40,  2.93it/s, ms_per_img=1.775, samples=1,792]
Resolution 256 eval:  31%|███▏      | 55/175 [00:19<00:40,  2.93it/s, ms_per_img=1.778, samples=1,824]
Resolution 256 eval:  33%|███▎      | 57/175 [00:19<00:39,  3.02it/s, ms_per_img=1.778, samples=1,824]
Resolution 256 eval:  33%|███▎      | 57/175 [00:19<00:39,  3.02it/s, ms_per_img=1.778, samples=1,856]
Resolution 256 eval:  33%|███▎      | 57/175 [00:20<00:39,  3.02it/s, ms_per_img=1.775, samples=1,888]
Resolution 256 eval:  34%|███▎      | 59/175 [00:20<00:38,  3.02it/s, ms_per_img=1.775, samples=1,888]
Resolution 256 eval:  34%|███▎      | 59/175 [00:20<00:38,  3.02it/s, ms_per_img=1.777, samples=1,920]
Resolution 256 eval:  34%|███▎      | 59/175 [00:20<00:38,  3.02it/s, ms_per_img=1.773, samples=1,952]
Resolution 256 eval:  35%|███▍      | 61/175 [00:20<00:37,  3.06it/s, ms_per_img=1.773, samples=1,952]
Resolution 256 eval:  35%|███▍      | 61/175 [00:21<00:37,  3.06it/s, ms_per_img=1.777, samples=1,984]
Resolution 256 eval:  35%|███▍      | 61/175 [00:21<00:37,  3.06it/s, ms_per_img=1.775, samples=2,016]
Resolution 256 eval:  36%|███▌      | 63/175 [00:21<00:35,  3.11it/s, ms_per_img=1.775, samples=2,016]
Resolution 256 eval:  36%|███▌      | 63/175 [00:22<00:35,  3.11it/s, ms_per_img=1.776, samples=2,048]
Resolution 256 eval:  36%|███▌      | 63/175 [00:22<00:35,  3.11it/s, ms_per_img=1.777, samples=2,080]
Resolution 256 eval:  37%|███▋      | 65/175 [00:22<00:37,  2.94it/s, ms_per_img=1.777, samples=2,080]
Resolution 256 eval:  37%|███▋      | 65/175 [00:22<00:37,  2.94it/s, ms_per_img=1.774, samples=2,112]
Resolution 256 eval:  37%|███▋      | 65/175 [00:23<00:37,  2.94it/s, ms_per_img=1.774, samples=2,144]
Resolution 256 eval:  38%|███▊      | 67/175 [00:23<00:38,  2.78it/s, ms_per_img=1.774, samples=2,144]
Resolution 256 eval:  38%|███▊      | 67/175 [00:23<00:38,  2.78it/s, ms_per_img=1.776, samples=2,176]
Resolution 256 eval:  38%|███▊      | 67/175 [00:23<00:38,  2.78it/s, ms_per_img=1.775, samples=2,208]
Resolution 256 eval:  39%|███▉      | 69/175 [00:23<00:36,  2.90it/s, ms_per_img=1.775, samples=2,208]
Resolution 256 eval:  39%|███▉      | 69/175 [00:24<00:36,  2.90it/s, ms_per_img=1.776, samples=2,240]
Resolution 256 eval:  39%|███▉      | 69/175 [00:24<00:36,  2.90it/s, ms_per_img=1.776, samples=2,272]
Resolution 256 eval:  41%|████      | 71/175 [00:24<00:38,  2.69it/s, ms_per_img=1.776, samples=2,272]
Resolution 256 eval:  41%|████      | 71/175 [00:24<00:38,  2.69it/s, ms_per_img=1.776, samples=2,304]
Resolution 256 eval:  41%|████      | 71/175 [00:25<00:38,  2.69it/s, ms_per_img=1.775, samples=2,336]
Resolution 256 eval:  42%|████▏     | 73/175 [00:25<00:36,  2.81it/s, ms_per_img=1.775, samples=2,336]
Resolution 256 eval:  42%|████▏     | 73/175 [00:25<00:36,  2.81it/s, ms_per_img=1.774, samples=2,368]
Resolution 256 eval:  42%|████▏     | 73/175 [00:25<00:36,  2.81it/s, ms_per_img=1.775, samples=2,400]
Resolution 256 eval:  43%|████▎     | 75/175 [00:25<00:34,  2.91it/s, ms_per_img=1.775, samples=2,400]
Resolution 256 eval:  43%|████▎     | 75/175 [00:26<00:34,  2.91it/s, ms_per_img=1.778, samples=2,432]
Resolution 256 eval:  43%|████▎     | 75/175 [00:26<00:34,  2.91it/s, ms_per_img=1.777, samples=2,464]
Resolution 256 eval:  44%|████▍     | 77/175 [00:26<00:33,  2.92it/s, ms_per_img=1.777, samples=2,464]
Resolution 256 eval:  44%|████▍     | 77/175 [00:27<00:33,  2.92it/s, ms_per_img=1.778, samples=2,496]
Resolution 256 eval:  44%|████▍     | 77/175 [00:27<00:33,  2.92it/s, ms_per_img=1.774, samples=2,528]
Resolution 256 eval:  45%|████▌     | 79/175 [00:27<00:36,  2.66it/s, ms_per_img=1.774, samples=2,528]
Resolution 256 eval:  45%|████▌     | 79/175 [00:27<00:36,  2.66it/s, ms_per_img=1.778, samples=2,560]
Resolution 256 eval:  45%|████▌     | 79/175 [00:28<00:36,  2.66it/s, ms_per_img=1.775, samples=2,592]
Resolution 256 eval:  46%|████▋     | 81/175 [00:28<00:34,  2.72it/s, ms_per_img=1.775, samples=2,592]
Resolution 256 eval:  46%|████▋     | 81/175 [00:28<00:34,  2.72it/s, ms_per_img=1.774, samples=2,624]
Resolution 256 eval:  46%|████▋     | 81/175 [00:28<00:34,  2.72it/s, ms_per_img=1.773, samples=2,656]
Resolution 256 eval:  47%|████▋     | 83/175 [00:28<00:34,  2.67it/s, ms_per_img=1.773, samples=2,656]
Resolution 256 eval:  47%|████▋     | 83/175 [00:29<00:34,  2.67it/s, ms_per_img=1.774, samples=2,688]
Resolution 256 eval:  47%|████▋     | 83/175 [00:29<00:34,  2.67it/s, ms_per_img=1.776, samples=2,720]
Resolution 256 eval:  49%|████▊     | 85/175 [00:29<00:33,  2.66it/s, ms_per_img=1.776, samples=2,720]
Resolution 256 eval:  49%|████▊     | 85/175 [00:30<00:33,  2.66it/s, ms_per_img=1.776, samples=2,752]
Resolution 256 eval:  49%|████▊     | 85/175 [00:30<00:33,  2.66it/s, ms_per_img=1.775, samples=2,784]
Resolution 256 eval:  50%|████▉     | 87/175 [00:30<00:34,  2.58it/s, ms_per_img=1.775, samples=2,784]
Resolution 256 eval:  50%|████▉     | 87/175 [00:30<00:34,  2.58it/s, ms_per_img=1.778, samples=2,816]
Resolution 256 eval:  50%|████▉     | 87/175 [00:31<00:34,  2.58it/s, ms_per_img=1.775, samples=2,848]
Resolution 256 eval:  51%|█████     | 89/175 [00:31<00:33,  2.53it/s, ms_per_img=1.775, samples=2,848]
Resolution 256 eval:  51%|█████     | 89/175 [00:31<00:33,  2.53it/s, ms_per_img=1.775, samples=2,880]
Resolution 256 eval:  51%|█████     | 89/175 [00:32<00:33,  2.53it/s, ms_per_img=1.775, samples=2,912]
Resolution 256 eval:  52%|█████▏    | 91/175 [00:32<00:31,  2.67it/s, ms_per_img=1.775, samples=2,912]
Resolution 256 eval:  52%|█████▏    | 91/175 [00:32<00:31,  2.67it/s, ms_per_img=1.774, samples=2,944]
Resolution 256 eval:  52%|█████▏    | 91/175 [00:32<00:31,  2.67it/s, ms_per_img=1.777, samples=2,976]
Resolution 256 eval:  53%|█████▎    | 93/175 [00:32<00:29,  2.81it/s, ms_per_img=1.777, samples=2,976]
Resolution 256 eval:  53%|█████▎    | 93/175 [00:32<00:29,  2.81it/s, ms_per_img=1.777, samples=3,008]
Resolution 256 eval:  53%|█████▎    | 93/175 [00:33<00:29,  2.81it/s, ms_per_img=1.777, samples=3,040]
Resolution 256 eval:  54%|█████▍    | 95/175 [00:33<00:26,  3.04it/s, ms_per_img=1.777, samples=3,040]
Resolution 256 eval:  54%|█████▍    | 95/175 [00:33<00:26,  3.04it/s, ms_per_img=1.777, samples=3,072]
Resolution 256 eval:  54%|█████▍    | 95/175 [00:33<00:26,  3.04it/s, ms_per_img=1.775, samples=3,104]
Resolution 256 eval:  55%|█████▌    | 97/175 [00:33<00:24,  3.13it/s, ms_per_img=1.775, samples=3,104]
Resolution 256 eval:  55%|█████▌    | 97/175 [00:34<00:24,  3.13it/s, ms_per_img=1.776, samples=3,136]
Resolution 256 eval:  55%|█████▌    | 97/175 [00:34<00:24,  3.13it/s, ms_per_img=1.773, samples=3,168]
Resolution 256 eval:  57%|█████▋    | 99/175 [00:34<00:25,  2.99it/s, ms_per_img=1.773, samples=3,168]
Resolution 256 eval:  57%|█████▋    | 99/175 [00:34<00:25,  2.99it/s, ms_per_img=1.779, samples=3,200]
Resolution 256 eval:  57%|█████▋    | 99/175 [00:35<00:25,  2.99it/s, ms_per_img=1.775, samples=3,232]
Resolution 256 eval:  58%|█████▊    | 101/175 [00:35<00:25,  2.88it/s, ms_per_img=1.775, samples=3,232]
Resolution 256 eval:  58%|█████▊    | 101/175 [00:35<00:25,  2.88it/s, ms_per_img=1.775, samples=3,264]
Resolution 256 eval:  58%|█████▊    | 101/175 [00:35<00:25,  2.88it/s, ms_per_img=1.776, samples=3,296]
Resolution 256 eval:  59%|█████▉    | 103/175 [00:35<00:24,  2.91it/s, ms_per_img=1.776, samples=3,296]
Resolution 256 eval:  59%|█████▉    | 103/175 [00:36<00:24,  2.91it/s, ms_per_img=1.810, samples=3,328]
Resolution 256 eval:  59%|█████▉    | 103/175 [00:36<00:24,  2.91it/s, ms_per_img=1.775, samples=3,360]
Resolution 256 eval:  60%|██████    | 105/175 [00:36<00:23,  2.92it/s, ms_per_img=1.775, samples=3,360]
Resolution 256 eval:  60%|██████    | 105/175 [00:36<00:23,  2.92it/s, ms_per_img=1.774, samples=3,392]
Resolution 256 eval:  60%|██████    | 105/175 [00:37<00:23,  2.92it/s, ms_per_img=1.774, samples=3,424]
Resolution 256 eval:  61%|██████    | 107/175 [00:37<00:21,  3.13it/s, ms_per_img=1.774, samples=3,424]
Resolution 256 eval:  61%|██████    | 107/175 [00:37<00:21,  3.13it/s, ms_per_img=1.777, samples=3,456]
Resolution 256 eval:  61%|██████    | 107/175 [00:37<00:21,  3.13it/s, ms_per_img=1.775, samples=3,488]
Resolution 256 eval:  62%|██████▏   | 109/175 [00:37<00:19,  3.31it/s, ms_per_img=1.775, samples=3,488]
Resolution 256 eval:  62%|██████▏   | 109/175 [00:38<00:19,  3.31it/s, ms_per_img=1.776, samples=3,520]
Resolution 256 eval:  62%|██████▏   | 109/175 [00:38<00:19,  3.31it/s, ms_per_img=1.777, samples=3,552]
Resolution 256 eval:  63%|██████▎   | 111/175 [00:38<00:18,  3.40it/s, ms_per_img=1.777, samples=3,552]
Resolution 256 eval:  63%|██████▎   | 111/175 [00:38<00:18,  3.40it/s, ms_per_img=1.776, samples=3,584]
Resolution 256 eval:  63%|██████▎   | 111/175 [00:38<00:18,  3.40it/s, ms_per_img=1.775, samples=3,616]
Resolution 256 eval:  65%|██████▍   | 113/175 [00:38<00:17,  3.51it/s, ms_per_img=1.775, samples=3,616]
Resolution 256 eval:  65%|██████▍   | 113/175 [00:39<00:17,  3.51it/s, ms_per_img=1.774, samples=3,648]
Resolution 256 eval:  65%|██████▍   | 113/175 [00:39<00:17,  3.51it/s, ms_per_img=1.777, samples=3,680]
Resolution 256 eval:  66%|██████▌   | 115/175 [00:39<00:19,  3.03it/s, ms_per_img=1.777, samples=3,680]
Resolution 256 eval:  66%|██████▌   | 115/175 [00:39<00:19,  3.03it/s, ms_per_img=1.775, samples=3,712]
Resolution 256 eval:  66%|██████▌   | 115/175 [00:40<00:19,  3.03it/s, ms_per_img=1.774, samples=3,744]
Resolution 256 eval:  67%|██████▋   | 117/175 [00:40<00:19,  2.97it/s, ms_per_img=1.774, samples=3,744]
Resolution 256 eval:  67%|██████▋   | 117/175 [00:40<00:19,  2.97it/s, ms_per_img=1.775, samples=3,776]
Resolution 256 eval:  67%|██████▋   | 117/175 [00:40<00:19,  2.97it/s, ms_per_img=1.778, samples=3,808]
Resolution 256 eval:  68%|██████▊   | 119/175 [00:40<00:18,  3.07it/s, ms_per_img=1.778, samples=3,808]
Resolution 256 eval:  68%|██████▊   | 119/175 [00:41<00:18,  3.07it/s, ms_per_img=1.777, samples=3,840]
Resolution 256 eval:  68%|██████▊   | 119/175 [00:41<00:18,  3.07it/s, ms_per_img=1.776, samples=3,872]
Resolution 256 eval:  69%|██████▉   | 121/175 [00:41<00:17,  3.15it/s, ms_per_img=1.776, samples=3,872]
Resolution 256 eval:  69%|██████▉   | 121/175 [00:42<00:17,  3.15it/s, ms_per_img=1.774, samples=3,904]
Resolution 256 eval:  69%|██████▉   | 121/175 [00:42<00:17,  3.15it/s, ms_per_img=1.777, samples=3,936]
Resolution 256 eval:  70%|███████   | 123/175 [00:42<00:18,  2.83it/s, ms_per_img=1.777, samples=3,936]
Resolution 256 eval:  70%|███████   | 123/175 [00:42<00:18,  2.83it/s, ms_per_img=1.777, samples=3,968]
Resolution 256 eval:  70%|███████   | 123/175 [00:43<00:18,  2.83it/s, ms_per_img=1.775, samples=4,000]
Resolution 256 eval:  71%|███████▏  | 125/175 [00:43<00:17,  2.82it/s, ms_per_img=1.775, samples=4,000]
Resolution 256 eval:  71%|███████▏  | 125/175 [00:43<00:17,  2.82it/s, ms_per_img=1.775, samples=4,032]
Resolution 256 eval:  71%|███████▏  | 125/175 [00:43<00:17,  2.82it/s, ms_per_img=1.774, samples=4,064]
Resolution 256 eval:  73%|███████▎  | 127/175 [00:43<00:17,  2.72it/s, ms_per_img=1.774, samples=4,064]
Resolution 256 eval:  73%|███████▎  | 127/175 [00:44<00:17,  2.72it/s, ms_per_img=1.775, samples=4,096]
Resolution 256 eval:  73%|███████▎  | 127/175 [00:44<00:17,  2.72it/s, ms_per_img=1.776, samples=4,128]
Resolution 256 eval:  74%|███████▎  | 129/175 [00:44<00:16,  2.81it/s, ms_per_img=1.776, samples=4,128]
Resolution 256 eval:  74%|███████▎  | 129/175 [00:44<00:16,  2.81it/s, ms_per_img=1.777, samples=4,160]

Acc=0.3523 AUC=0.5418 Fast=100.00% Medium=0.00% Full=0.00%

Resolution sweep:  75%|███████▌  | 3/4 [06:00<01:50, 110.32s/it]

Source Res=256 Single: 5.876 ms/img | 170.2 FPS
Source Res=256 Batch=32: 1.784 ms/img | 560.6 FPS

Resolution 384

Resolution 384 eval:   0%|          | 0/175 [00:00<?, ?it/s]
Resolution 384 eval:   0%|          | 0/175 [00:00<?, ?it/s, ms_per_img=1.778, samples=32]
Resolution 384 eval:   0%|          | 0/175 [00:00<?, ?it/s, ms_per_img=1.779, samples=64]
Resolution 384 eval:   1%|          | 2/175 [00:00<00:58,  2.96it/s, ms_per_img=1.779, samples=64]
Resolution 384 eval:   1%|          | 2/175 [00:01<00:58,  2.96it/s, ms_per_img=1.776, samples=96]
Resolution 384 eval:   1%|          | 2/175 [00:01<00:58,  2.96it/s, ms_per_img=1.776, samples=128]
Resolution 384 eval:   2%|▏         | 4/175 [00:01<01:16,  2.23it/s, ms_per_img=1.776, samples=128]
Resolution 384 eval:   2%|▏         | 4/175 [00:02<01:16,  2.23it/s, ms_per_img=1.778, samples=160]
Resolution 384 eval:   2%|▏         | 4/175 [00:02<01:16,  2.23it/s, ms_per_img=1.779, samples=192]
Resolution 384 eval:   3%|▎         | 6/175 [00:02<01:10,  2.39it/s, ms_per_img=1.779, samples=192]
Resolution 384 eval:   3%|▎         | 6/175 [00:02<01:10,  2.39it/s, ms_per_img=1.776, samples=224]
Resolution 384 eval:   3%|▎         | 6/175 [00:03<01:10,  2.39it/s, ms_per_img=1.777, samples=256]
Resolution 384 eval:   5%|▍         | 8/175 [00:03<01:01,  2.72it/s, ms_per_img=1.777, samples=256]
Resolution 384 eval:   5%|▍         | 8/175 [00:03<01:01,  2.72it/s, ms_per_img=1.777, samples=288]
Resolution 384 eval:   5%|▍         | 8/175 [00:03<01:01,  2.72it/s, ms_per_img=1.775, samples=320]
Resolution 384 eval:   6%|▌         | 10/175 [00:03<01:04,  2.54it/s, ms_per_img=1.775, samples=320]
Resolution 384 eval:   6%|▌         | 10/175 [00:04<01:04,  2.54it/s, ms_per_img=1.778, samples=352]
Resolution 384 eval:   6%|▌         | 10/175 [00:04<01:04,  2.54it/s, ms_per_img=1.777, samples=384]
Resolution 384 eval:   7%|▋         | 12/175 [00:04<01:05,  2.47it/s, ms_per_img=1.777, samples=384]
Resolution 384 eval:   7%|▋         | 12/175 [00:05<01:05,  2.47it/s, ms_per_img=1.776, samples=416]
Resolution 384 eval:   7%|▋         | 12/175 [00:05<01:05,  2.47it/s, ms_per_img=1.774, samples=448]
Resolution 384 eval:   8%|▊         | 14/175 [00:05<01:01,  2.64it/s, ms_per_img=1.774, samples=448]
Resolution 384 eval:   8%|▊         | 14/175 [00:05<01:01,  2.64it/s, ms_per_img=1.777, samples=480]
Resolution 384 eval:   8%|▊         | 14/175 [00:06<01:01,  2.64it/s, ms_per_img=1.775, samples=512]
Resolution 384 eval:   9%|▉         | 16/175 [00:06<00:55,  2.88it/s, ms_per_img=1.775, samples=512]
Resolution 384 eval:   9%|▉         | 16/175 [00:06<00:55,  2.88it/s, ms_per_img=1.775, samples=544]
Resolution 384 eval:   9%|▉         | 16/175 [00:06<00:55,  2.88it/s, ms_per_img=1.777, samples=576]
Resolution 384 eval:  10%|█         | 18/175 [00:06<00:54,  2.88it/s, ms_per_img=1.777, samples=576]
Resolution 384 eval:  10%|█         | 18/175 [00:07<00:54,  2.88it/s, ms_per_img=1.776, samples=608]
Resolution 384 eval:  10%|█         | 18/175 [00:07<00:54,  2.88it/s, ms_per_img=1.775, samples=640]
Resolution 384 eval:  11%|█▏        | 20/175 [00:07<00:54,  2.87it/s, ms_per_img=1.775, samples=640]
Resolution 384 eval:  11%|█▏        | 20/175 [00:07<00:54,  2.87it/s, ms_per_img=1.776, samples=672]
Resolution 384 eval:  11%|█▏        | 20/175 [00:08<00:54,  2.87it/s, ms_per_img=1.777, samples=704]
Resolution 384 eval:  13%|█▎        | 22/175 [00:08<00:55,  2.78it/s, ms_per_img=1.777, samples=704]
Resolution 384 eval:  13%|█▎        | 22/175 [00:08<00:55,  2.78it/s, ms_per_img=1.776, samples=736]
Resolution 384 eval:  13%|█▎        | 22/175 [00:08<00:55,  2.78it/s, ms_per_img=1.776, samples=768]
Resolution 384 eval:  14%|█▎        | 24/175 [00:08<00:55,  2.74it/s, ms_per_img=1.776, samples=768]
Resolution 384 eval:  14%|█▎        | 24/175 [00:09<00:55,  2.74it/s, ms_per_img=1.777, samples=800]
Resolution 384 eval:  14%|█▎        | 24/175 [00:09<00:55,  2.74it/s, ms_per_img=1.777, samples=832]
Resolution 384 eval:  15%|█▍        | 26/175 [00:09<00:53,  2.81it/s, ms_per_img=1.777, samples=832]
Resolution 384 eval:  15%|█▍        | 26/175 [00:10<00:53,  2.81it/s, ms_per_img=1.779, samples=864]
Resolution 384 eval:  15%|█▍        | 26/175 [00:10<00:53,  2.81it/s, ms_per_img=1.778, samples=896]
Resolution 384 eval:  16%|█▌        | 28/175 [00:10<00:54,  2.71it/s, ms_per_img=1.778, samples=896]
Resolution 384 eval:  16%|█▌        | 28/175 [00:10<00:54,  2.71it/s, ms_per_img=1.774, samples=928]
Resolution 384 eval:  16%|█▌        | 28/175 [00:11<00:54,  2.71it/s, ms_per_img=1.774, samples=960]
Resolution 384 eval:  17%|█▋        | 30/175 [00:11<00:55,  2.63it/s, ms_per_img=1.774, samples=960]
Resolution 384 eval:  17%|█▋        | 30/175 [00:11<00:55,  2.63it/s, ms_per_img=1.775, samples=992]
Resolution 384 eval:  17%|█▋        | 30/175 [00:11<00:55,  2.63it/s, ms_per_img=1.777, samples=1,024]
Resolution 384 eval:  18%|█▊        | 32/175 [00:11<00:54,  2.63it/s, ms_per_img=1.777, samples=1,024]
Resolution 384 eval:  18%|█▊        | 32/175 [00:12<00:54,  2.63it/s, ms_per_img=1.778, samples=1,056]
Resolution 384 eval:  18%|█▊        | 32/175 [00:12<00:54,  2.63it/s, ms_per_img=1.775, samples=1,088]
Resolution 384 eval:  19%|█▉        | 34/175 [00:12<00:56,  2.51it/s, ms_per_img=1.775, samples=1,088]
Resolution 384 eval:  19%|█▉        | 34/175 [00:13<00:56,  2.51it/s, ms_per_img=1.774, samples=1,120]
Resolution 384 eval:  19%|█▉        | 34/175 [00:14<00:56,  2.51it/s, ms_per_img=1.775, samples=1,152]
Resolution 384 eval:  21%|██        | 36/175 [00:14<01:02,  2.21it/s, ms_per_img=1.775, samples=1,152]
Resolution 384 eval:  21%|██        | 36/175 [00:14<01:02,  2.21it/s, ms_per_img=1.777, samples=1,184]
Resolution 384 eval:  21%|██        | 36/175 [00:14<01:02,  2.21it/s, ms_per_img=1.777, samples=1,216]
Resolution 384 eval:  22%|██▏       | 38/175 [00:14<00:54,  2.51it/s, ms_per_img=1.777, samples=1,216]
Resolution 384 eval:  22%|██▏       | 38/175 [00:14<00:54,  2.51it/s, ms_per_img=1.777, samples=1,248]
Resolution 384 eval:  22%|██▏       | 38/175 [00:15<00:54,  2.51it/s, ms_per_img=1.776, samples=1,280]
Resolution 384 eval:  23%|██▎       | 40/175 [00:15<00:51,  2.63it/s, ms_per_img=1.776, samples=1,280]
Resolution 384 eval:  23%|██▎       | 40/175 [00:15<00:51,  2.63it/s, ms_per_img=1.778, samples=1,312]
Resolution 384 eval:  23%|██▎       | 40/175 [00:16<00:51,  2.63it/s, ms_per_img=1.775, samples=1,344]
Resolution 384 eval:  24%|██▍       | 42/175 [00:16<00:53,  2.51it/s, ms_per_img=1.775, samples=1,344]
Resolution 384 eval:  24%|██▍       | 42/175 [00:16<00:53,  2.51it/s, ms_per_img=1.777, samples=1,376]
Resolution 384 eval:  24%|██▍       | 42/175 [00:16<00:53,  2.51it/s, ms_per_img=1.773, samples=1,408]
Resolution 384 eval:  25%|██▌       | 44/175 [00:16<00:52,  2.51it/s, ms_per_img=1.773, samples=1,408]
Resolution 384 eval:  25%|██▌       | 44/175 [00:17<00:52,  2.51it/s, ms_per_img=1.776, samples=1,440]
Resolution 384 eval:  25%|██▌       | 44/175 [00:17<00:52,  2.51it/s, ms_per_img=1.775, samples=1,472]
Resolution 384 eval:  26%|██▋       | 46/175 [00:17<00:46,  2.75it/s, ms_per_img=1.775, samples=1,472]
Resolution 384 eval:  26%|██▋       | 46/175 [00:17<00:46,  2.75it/s, ms_per_img=1.778, samples=1,504]
Resolution 384 eval:  26%|██▋       | 46/175 [00:18<00:46,  2.75it/s, ms_per_img=1.777, samples=1,536]
Resolution 384 eval:  27%|██▋       | 48/175 [00:18<00:47,  2.70it/s, ms_per_img=1.777, samples=1,536]
Resolution 384 eval:  27%|██▋       | 48/175 [00:18<00:47,  2.70it/s, ms_per_img=1.778, samples=1,568]
Resolution 384 eval:  27%|██▋       | 48/175 [00:18<00:47,  2.70it/s, ms_per_img=1.774, samples=1,600]
Resolution 384 eval:  29%|██▊       | 50/175 [00:18<00:45,  2.73it/s, ms_per_img=1.774, samples=1,600]
Resolution 384 eval:  29%|██▊       | 50/175 [00:19<00:45,  2.73it/s, ms_per_img=1.778, samples=1,632]
Resolution 384 eval:  29%|██▊       | 50/175 [00:19<00:45,  2.73it/s, ms_per_img=1.774, samples=1,664]
Resolution 384 eval:  30%|██▉       | 52/175 [00:19<00:46,  2.65it/s, ms_per_img=1.774, samples=1,664]
Resolution 384 eval:  30%|██▉       | 52/175 [00:20<00:46,  2.65it/s, ms_per_img=1.780, samples=1,696]
Resolution 384 eval:  30%|██▉       | 52/175 [00:20<00:46,  2.65it/s, ms_per_img=1.773, samples=1,728]
Resolution 384 eval:  31%|███       | 54/175 [00:20<00:45,  2.66it/s, ms_per_img=1.773, samples=1,728]
Resolution 384 eval:  31%|███       | 54/175 [00:20<00:45,  2.66it/s, ms_per_img=1.774, samples=1,760]
Resolution 384 eval:  31%|███       | 54/175 [00:21<00:45,  2.66it/s, ms_per_img=1.776, samples=1,792]
Resolution 384 eval:  32%|███▏      | 56/175 [00:21<00:42,  2.80it/s, ms_per_img=1.776, samples=1,792]
Resolution 384 eval:  32%|███▏      | 56/175 [00:21<00:42,  2.80it/s, ms_per_img=1.776, samples=1,824]
Resolution 384 eval:  32%|███▏      | 56/175 [00:21<00:42,  2.80it/s, ms_per_img=1.776, samples=1,856]
Resolution 384 eval:  33%|███▎      | 58/175 [00:21<00:41,  2.85it/s, ms_per_img=1.776, samples=1,856]
Resolution 384 eval:  33%|███▎      | 58/175 [00:22<00:41,  2.85it/s, ms_per_img=1.777, samples=1,888]
Resolution 384 eval:  33%|███▎      | 58/175 [00:22<00:41,  2.85it/s, ms_per_img=1.774, samples=1,920]
Resolution 384 eval:  34%|███▍      | 60/175 [00:22<00:40,  2.85it/s, ms_per_img=1.774, samples=1,920]
Resolution 384 eval:  34%|███▍      | 60/175 [00:22<00:40,  2.85it/s, ms_per_img=1.778, samples=1,952]
Resolution 384 eval:  34%|███▍      | 60/175 [00:23<00:40,  2.85it/s, ms_per_img=1.775, samples=1,984]
Resolution 384 eval:  35%|███▌      | 62/175 [00:23<00:40,  2.76it/s, ms_per_img=1.775, samples=1,984]
Resolution 384 eval:  35%|███▌      | 62/175 [00:23<00:40,  2.76it/s, ms_per_img=1.776, samples=2,016]
Resolution 384 eval:  35%|███▌      | 62/175 [00:24<00:40,  2.76it/s, ms_per_img=1.775, samples=2,048]
Resolution 384 eval:  37%|███▋      | 64/175 [00:24<00:41,  2.69it/s, ms_per_img=1.775, samples=2,048]
Resolution 384 eval:  37%|███▋      | 64/175 [00:24<00:41,  2.69it/s, ms_per_img=1.776, samples=2,080]
Resolution 384 eval:  37%|███▋      | 64/175 [00:24<00:41,  2.69it/s, ms_per_img=1.775, samples=2,112]
Resolution 384 eval:  38%|███▊      | 66/175 [00:24<00:41,  2.65it/s, ms_per_img=1.775, samples=2,112]
Resolution 384 eval:  38%|███▊      | 66/175 [00:25<00:41,  2.65it/s, ms_per_img=1.775, samples=2,144]
Resolution 384 eval:  38%|███▊      | 66/175 [00:25<00:41,  2.65it/s, ms_per_img=1.774, samples=2,176]
Resolution 384 eval:  39%|███▉      | 68/175 [00:25<00:41,  2.57it/s, ms_per_img=1.774, samples=2,176]
Resolution 384 eval:  39%|███▉      | 68/175 [00:26<00:41,  2.57it/s, ms_per_img=1.777, samples=2,208]
Resolution 384 eval:  39%|███▉      | 68/175 [00:26<00:41,  2.57it/s, ms_per_img=1.775, samples=2,240]
Resolution 384 eval:  40%|████      | 70/175 [00:26<00:42,  2.46it/s, ms_per_img=1.775, samples=2,240]
Resolution 384 eval:  40%|████      | 70/175 [00:26<00:42,  2.46it/s, ms_per_img=1.774, samples=2,272]
Resolution 384 eval:  40%|████      | 70/175 [00:27<00:42,  2.46it/s, ms_per_img=1.775, samples=2,304]
Resolution 384 eval:  41%|████      | 72/175 [00:27<00:39,  2.58it/s, ms_per_img=1.775, samples=2,304]
Resolution 384 eval:  41%|████      | 72/175 [00:27<00:39,  2.58it/s, ms_per_img=1.773, samples=2,336]
Resolution 384 eval:  41%|████      | 72/175 [00:28<00:39,  2.58it/s, ms_per_img=1.775, samples=2,368]
Resolution 384 eval:  42%|████▏     | 74/175 [00:28<00:38,  2.59it/s, ms_per_img=1.775, samples=2,368]
Resolution 384 eval:  42%|████▏     | 74/175 [00:28<00:38,  2.59it/s, ms_per_img=1.777, samples=2,400]
Resolution 384 eval:  42%|████▏     | 74/175 [00:28<00:38,  2.59it/s, ms_per_img=1.776, samples=2,432]
Resolution 384 eval:  43%|████▎     | 76/175 [00:28<00:36,  2.69it/s, ms_per_img=1.776, samples=2,432]
Resolution 384 eval:  43%|████▎     | 76/175 [00:29<00:36,  2.69it/s, ms_per_img=1.775, samples=2,464]
Resolution 384 eval:  43%|████▎     | 76/175 [00:29<00:36,  2.69it/s, ms_per_img=1.777, samples=2,496]
Resolution 384 eval:  45%|████▍     | 78/175 [00:29<00:39,  2.46it/s, ms_per_img=1.777, samples=2,496]
Resolution 384 eval:  45%|████▍     | 78/175 [00:30<00:39,  2.46it/s, ms_per_img=1.774, samples=2,528]
Resolution 384 eval:  45%|████▍     | 78/175 [00:30<00:39,  2.46it/s, ms_per_img=1.778, samples=2,560]
Resolution 384 eval:  46%|████▌     | 80/175 [00:30<00:36,  2.58it/s, ms_per_img=1.778, samples=2,560]
Resolution 384 eval:  46%|████▌     | 80/175 [00:30<00:36,  2.58it/s, ms_per_img=1.776, samples=2,592]
Resolution 384 eval:  46%|████▌     | 80/175 [00:31<00:36,  2.58it/s, ms_per_img=1.776, samples=2,624]
Resolution 384 eval:  47%|████▋     | 82/175 [00:31<00:36,  2.54it/s, ms_per_img=1.776, samples=2,624]
Resolution 384 eval:  47%|████▋     | 82/175 [00:31<00:36,  2.54it/s, ms_per_img=1.777, samples=2,656]
Resolution 384 eval:  47%|████▋     | 82/175 [00:32<00:36,  2.54it/s, ms_per_img=1.775, samples=2,688]
Resolution 384 eval:  48%|████▊     | 84/175 [00:32<00:38,  2.38it/s, ms_per_img=1.775, samples=2,688]
Resolution 384 eval:  48%|████▊     | 84/175 [00:32<00:38,  2.38it/s, ms_per_img=1.776, samples=2,720]
Resolution 384 eval:  48%|████▊     | 84/175 [00:32<00:38,  2.38it/s, ms_per_img=1.775, samples=2,752]
Resolution 384 eval:  49%|████▉     | 86/175 [00:32<00:35,  2.48it/s, ms_per_img=1.775, samples=2,752]
Resolution 384 eval:  49%|████▉     | 86/175 [00:33<00:35,  2.48it/s, ms_per_img=1.776, samples=2,784]
Resolution 384 eval:  49%|████▉     | 86/175 [00:33<00:35,  2.48it/s, ms_per_img=1.776, samples=2,816]
Resolution 384 eval:  50%|█████     | 88/175 [00:33<00:35,  2.44it/s, ms_per_img=1.776, samples=2,816]
Resolution 384 eval:  50%|█████     | 88/175 [00:34<00:35,  2.44it/s, ms_per_img=1.776, samples=2,848]
Resolution 384 eval:  50%|█████     | 88/175 [00:34<00:35,  2.44it/s, ms_per_img=1.777, samples=2,880]
Resolution 384 eval:  51%|█████▏    | 90/175 [00:34<00:35,  2.39it/s, ms_per_img=1.777, samples=2,880]
Resolution 384 eval:  51%|█████▏    | 90/175 [00:34<00:35,  2.39it/s, ms_per_img=1.772, samples=2,912]
Resolution 384 eval:  51%|█████▏    | 90/175 [00:35<00:35,  2.39it/s, ms_per_img=1.777, samples=2,944]
Resolution 384 eval:  53%|█████▎    | 92/175 [00:35<00:33,  2.49it/s, ms_per_img=1.777, samples=2,944]
Resolution 384 eval:  53%|█████▎    | 92/175 [00:35<00:33,  2.49it/s, ms_per_img=1.775, samples=2,976]
Resolution 384 eval:  53%|█████▎    | 92/175 [00:35<00:33,  2.49it/s, ms_per_img=1.776, samples=3,008]
Resolution 384 eval:  54%|█████▎    | 94/175 [00:35<00:30,  2.67it/s, ms_per_img=1.776, samples=3,008]
Resolution 384 eval:  54%|█████▎    | 94/175 [00:36<00:30,  2.67it/s, ms_per_img=1.777, samples=3,040]
Resolution 384 eval:  54%|█████▎    | 94/175 [00:36<00:30,  2.67it/s, ms_per_img=1.776, samples=3,072]
Resolution 384 eval:  55%|█████▍    | 96/175 [00:36<00:28,  2.78it/s, ms_per_img=1.776, samples=3,072]
Resolution 384 eval:  55%|█████▍    | 96/175 [00:36<00:28,  2.78it/s, ms_per_img=1.779, samples=3,104]
Resolution 384 eval:  55%|█████▍    | 96/175 [00:37<00:28,  2.78it/s, ms_per_img=1.776, samples=3,136]
Resolution 384 eval:  56%|█████▌    | 98/175 [00:37<00:27,  2.84it/s, ms_per_img=1.776, samples=3,136]
Resolution 384 eval:  56%|█████▌    | 98/175 [00:37<00:27,  2.84it/s, ms_per_img=1.776, samples=3,168]
Resolution 384 eval:  56%|█████▌    | 98/175 [00:38<00:27,  2.84it/s, ms_per_img=1.778, samples=3,200]
Resolution 384 eval:  57%|█████▋    | 100/175 [00:38<00:27,  2.73it/s, ms_per_img=1.778, samples=3,200]
Resolution 384 eval:  57%|█████▋    | 100/175 [00:38<00:27,  2.73it/s, ms_per_img=1.777, samples=3,232]
Resolution 384 eval:  57%|█████▋    | 100/175 [00:38<00:27,  2.73it/s, ms_per_img=1.776, samples=3,264]
Resolution 384 eval:  58%|█████▊    | 102/175 [00:38<00:27,  2.63it/s, ms_per_img=1.776, samples=3,264]
Resolution 384 eval:  58%|█████▊    | 102/175 [00:39<00:27,  2.63it/s, ms_per_img=1.775, samples=3,296]
Resolution 384 eval:  58%|█████▊    | 102/175 [00:39<00:27,  2.63it/s, ms_per_img=1.776, samples=3,328]
Resolution 384 eval:  59%|█████▉    | 104/175 [00:39<00:26,  2.64it/s, ms_per_img=1.776, samples=3,328]
Resolution 384 eval:  59%|█████▉    | 104/175 [00:40<00:26,  2.64it/s, ms_per_img=1.778, samples=3,360]
Resolution 384 eval:  59%|█████▉    | 104/175 [00:40<00:26,  2.64it/s, ms_per_img=1.778, samples=3,392]
Resolution 384 eval:  61%|██████    | 106/175 [00:40<00:26,  2.64it/s, ms_per_img=1.778, samples=3,392]
Resolution 384 eval:  61%|██████    | 106/175 [00:40<00:26,  2.64it/s, ms_per_img=1.777, samples=3,424]
Resolution 384 eval:  61%|██████    | 106/175 [00:40<00:26,  2.64it/s, ms_per_img=1.776, samples=3,456]
Resolution 384 eval:  62%|██████▏   | 108/175 [00:40<00:22,  2.92it/s, ms_per_img=1.776, samples=3,456]
Resolution 384 eval:  62%|██████▏   | 108/175 [00:41<00:22,  2.92it/s, ms_per_img=1.778, samples=3,488]
Resolution 384 eval:  62%|██████▏   | 108/175 [00:41<00:22,  2.92it/s, ms_per_img=1.777, samples=3,520]
Resolution 384 eval:  63%|██████▎   | 110/175 [00:41<00:22,  2.94it/s, ms_per_img=1.777, samples=3,520]
Resolution 384 eval:  63%|██████▎   | 110/175 [00:41<00:22,  2.94it/s, ms_per_img=1.778, samples=3,552]
Resolution 384 eval:  63%|██████▎   | 110/175 [00:42<00:22,  2.94it/s, ms_per_img=1.777, samples=3,584]
Resolution 384 eval:  63%|██████▎   | 110/175 [00:42<00:22,  2.94it/s, ms_per_img=1.779, samples=3,616]
Resolution 384 eval:  65%|██████▍   | 113/175 [00:42<00:19,  3.16it/s, ms_per_img=1.779, samples=3,616]
Resolution 384 eval:  65%|██████▍   | 113/175 [00:42<00:19,  3.16it/s, ms_per_img=1.776, samples=3,648]
Resolution 384 eval:  65%|██████▍   | 113/175 [00:43<00:19,  3.16it/s, ms_per_img=1.775, samples=3,680]
Resolution 384 eval:  66%|██████▌   | 115/175 [00:43<00:21,  2.81it/s, ms_per_img=1.775, samples=3,680]
Resolution 384 eval:  66%|██████▌   | 115/175 [00:43<00:21,  2.81it/s, ms_per_img=1.776, samples=3,712]
Resolution 384 eval:  66%|██████▌   | 115/175 [00:44<00:21,  2.81it/s, ms_per_img=1.778, samples=3,744]
Resolution 384 eval:  67%|██████▋   | 117/175 [00:44<00:21,  2.75it/s, ms_per_img=1.778, samples=3,744]
Resolution 384 eval:  67%|██████▋   | 117/175 [00:44<00:21,  2.75it/s, ms_per_img=1.775, samples=3,776]
Resolution 384 eval:  67%|██████▋   | 117/175 [00:44<00:21,  2.75it/s, ms_per_img=1.774, samples=3,808]
Resolution 384 eval:  68%|██████▊   | 119/175 [00:44<00:19,  2.83it/s, ms_per_img=1.774, samples=3,808]
Resolution 384 eval:  68%|██████▊   | 119/175 [00:45<00:19,  2.83it/s, ms_per_img=1.779, samples=3,840]
Resolution 384 eval:  68%|██████▊   | 119/175 [00:45<00:19,  2.83it/s, ms_per_img=1.774, samples=3,872]
Resolution 384 eval:  69%|██████▉   | 121/175 [00:45<00:18,  2.89it/s, ms_per_img=1.774, samples=3,872]
Resolution 384 eval:  69%|██████▉   | 121/175 [00:45<00:18,  2.89it/s, ms_per_img=1.774, samples=3,904]
Resolution 384 eval:  69%|██████▉   | 121/175 [00:46<00:18,  2.89it/s, ms_per_img=1.777, samples=3,936]
Resolution 384 eval:  70%|███████   | 123/175 [00:46<00:19,  2.61it/s, ms_per_img=1.777, samples=3,936]
Resolution 384 eval:  70%|███████   | 123/175 [00:46<00:19,  2.61it/s, ms_per_img=1.778, samples=3,968]
Resolution 384 eval:  70%|███████   | 123/175 [00:47<00:19,  2.61it/s, ms_per_img=1.775, samples=4,000]
Resolution 384 eval:  71%|███████▏  | 125/175 [00:47<00:19,  2.59it/s, ms_per_img=1.775, samples=4,000]
Resolution 384 eval:  71%|███████▏  | 125/175 [00:47<00:19,  2.59it/s, ms_per_img=1.773, samples=4,032]
Resolution 384 eval:  71%|███████▏  | 125/175 [00:48<00:19,  2.59it/s, ms_per_img=1.778, samples=4,064]
Resolution 384 eval:  73%|███████▎  | 127/175 [00:48<00:19,  2.51it/s, ms_per_img=1.778, samples=4,064]
Resolution 384 eval:  73%|███████▎  | 127/175 [00:48<00:19,  2.51it/s, ms_per_img=1.776, samples=4,096]
Resolution 384 eval:  73%|███████▎  | 127/175 [00:48<00:19,  2.51it/s, ms_per_img=1.776, samples=4,128]
Resolution 384 eval:  74%|███████▎  | 129/175 [00:48<00:17,  2.57it/s, ms_per_img=1.776, samples=4,128]
Resolution 384 eval:  74%|███████▎  | 129/175 [00:49<00:17,  2.57it/s, ms_per_img=1.776, samples=4,160]

Acc=0.3539 AUC=0.5420 Fast=100.00% Medium=0.00% Full=0.00%

Resolution sweep: 100%|██████████| 4/4 [07:20<00:00, 110.14s/it]

Source Res=384 Single: 5.892 ms/img | 169.7 FPS
Source Res=384 Batch=32: 1.785 ms/img | 560.4 FPS

====================================================================================================
====================================MaD-CoRN EXPERIMENT RESULTS=====================================
====================================================================================================

[1] TRAINING PERIODS RESULTS
                                               Training Periods Results

+-------+------------+-----------+-----------+---------+---------+-----------+--------+--------+--------------------+
| Epoch | Train Loss | Train Acc | Train AUC | Val Acc | Val AUC | Precision | Recall | F1     | Uncertain Rate (%) |
+-------+------------+-----------+-----------+---------+---------+-----------+--------+--------+--------------------+
| 1     | 0.6956     | 0.4999    | 0.4990    | 0.1429  | 0.5096  | 0.0000    | 0.0000 | 0.0000 | 100.00             |
| 2     | 0.6846     | 0.5376    | 0.5496    | 0.3495  | 0.5958  | 0.9048    | 0.2694 | 0.4152 | 80.20              |
| 3     | 0.6701     | 0.5635    | 0.5746    | 0.3206  | 0.5519  | 0.9024    | 0.2326 | 0.3698 | 82.12              |
| 4     | 0.6656     | 0.5666    | 0.5739    | 0.2745  | 0.5677  | 0.9706    | 0.1583 | 0.2723 | 89.39              |
| 5     | 0.6601     | 0.5726    | 0.5767    | 0.2827  | 0.5626  | 0.9503    | 0.1721 | 0.2915 | 86.79              |
| 6     | 0.6552     | 0.5748    | 0.5766    | 0.3136  | 0.5764  | 0.9326    | 0.2147 | 0.3490 | 84.95              |
| 7     | 0.6525     | 0.5785    | 0.5805    | 0.2825  | 0.5680  | 0.9505    | 0.1719 | 0.2911 | 86.42              |
| 8     | 0.6493     | 0.5804    | 0.5781    | 0.3345  | 0.5585  | 0.9220    | 0.2443 | 0.3862 | 82.45              |
| 9     | 0.6479     | 0.5823    | 0.5819    | 0.3003  | 0.5666  | 0.9421    | 0.1957 | 0.3241 | 85.42              |
| 10    | 0.6454     | 0.5840    | 0.5865    | 0.2727  | 0.5604  | 0.9709    | 0.1561 | 0.2690 | 86.55              |
| 11    | 0.6433     | 0.5862    | 0.5850    | 0.2769  | 0.5612  | 0.9481    | 0.1654 | 0.2817 | 85.72              |
| 12    | 0.6419     | 0.5883    | 0.5892    | 0.2756  | 0.5347  | 0.9036    | 0.1734 | 0.2909 | 85.10              |
| 13    | 0.6402     | 0.5914    | 0.5936    | 0.2699  | 0.5289  | 0.8811    | 0.1713 | 0.2868 | 84.19              |
| 14    | 0.6384     | 0.5939    | 0.5955    | 0.2732  | 0.5145  | 0.8626    | 0.1809 | 0.2991 | 83.61              |
| 15    | 0.6377     | 0.5949    | 0.5962    | 0.2734  | 0.5118  | 0.8601    | 0.1819 | 0.3003 | 83.43              |
+-------+------------+-----------+-----------+---------+---------+-----------+--------+--------+--------------------+

[2] TEST RESULTS
                                           Test Results

+------------------------+----------+--------+-----------+--------+--------+--------------------+
| Model                  | Accuracy | AUC    | Precision | Recall | F1     | Uncertain Rate (%) |
+------------------------+----------+--------+-----------+--------+--------+--------------------+
| MaD-CoRN-FFPP-Balanced | 0.3524   | 0.5430 | 0.8969    | 0.2762 | 0.4223 | 80.39              |
+------------------------+----------+--------+-----------+--------+--------+--------------------+

[3] ACCURACY BASED ON RESOLUTION
                     Accuracy Based on Resolution

+------------+----------+--------+----------+------------+----------+
| Resolution | Accuracy | AUC    | Fast (%) | Medium (%) | Full (%) |
+------------+----------+--------+----------+------------+----------+
| 128        | 0.3459   | 0.5467 | 100.00   | 0.00       | 0.00     |
| 224        | 0.3575   | 0.5414 | 100.00   | 0.00       | 0.00     |
| 256        | 0.3523   | 0.5418 | 100.00   | 0.00       | 0.00     |
| 384        | 0.3539   | 0.5420 | 100.00   | 0.00       | 0.00     |
+------------+----------+--------+----------+------------+----------+

[4] INFERENCE TIME
                      Inference Time

+-------------------------+---------------------+-------+
| Mode                    | Time per Image (ms) | FPS   |
+-------------------------+---------------------+-------+
| Source Res=128 Single   | 5.916               | 169.0 |
| Source Res=128 Batch=32 | 1.782               | 561.1 |
| Source Res=224 Single   | 5.869               | 170.4 |
| Source Res=224 Batch=32 | 1.782               | 561.0 |
| Source Res=256 Single   | 5.876               | 170.2 |
| Source Res=256 Batch=32 | 1.784               | 560.6 |
| Source Res=384 Single   | 5.892               | 169.7 |
| Source Res=384 Batch=32 | 1.785               | 560.4 |
+-------------------------+---------------------+-------+

[5] TRAINING TIME
                              Training Time

+--------------------------------------------------------+-------+-------+
| Model Type                                             | min   | hrs   |
+--------------------------------------------------------+-------+-------+
| MaD-CoRN FF++ balanced train multi-resolution training | 798.6 | 13.31 |
+--------------------------------------------------------+-------+-------+

Experiment Summary

,Experiment Name,Dataset,Train Samples Original,Train Samples Used Balanced,Validation Samples,Test Samples,Train Real Used,Train Fake Used,Validation Real,Validation Fake,Test Real,Test Fake,Balancing Method,Resolutions Used,Input Modalities,RGB Shape,Device,CUDA Available,Framework,Torch Version
0,MaD-CoRN Balanced Train,FaceForensics++ C23,44756,76712,5600,5597,38356,38356,800,4800,800,4797,Train-only oversampling of real class with rep...,"[128, 224, 256, 384]",RGB,"(3, 224, 224)",cuda,True,PyTorch,2.11.0+cu130

Results saved to: ./mad_corn_results_ffpp_balanced

In [1]:
#FF++ with balance configuration
!pip install scikit-learn torch torchvision tqdm pandas pillow

import os, io, json, math, time, random, warnings
import numpy as np
import pandas as pd
from dataclasses import dataclass, asdict
from PIL import Image, ImageFile

warnings.filterwarnings("ignore")
ImageFile.LOAD_TRUNCATED_IMAGES = True

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader, TensorDataset
import torchvision.transforms as T
from torch.cuda.amp import GradScaler, autocast

from tqdm.auto import tqdm
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score, accuracy_score

# ============================================================
# CONFIG
# ============================================================

CONFIG = dict(
    metadata_csv="/home/jovyan/.cache/kagglehub/datasets/xdxd003/ff-c23/versions/1/ffpp_preprocessed/metadata.csv",

    resolutions=[128, 224, 256, 384],
    image_size_for_model=224,

    epochs=15,
    batch_size=32,
    lr=1e-3,
    weight_decay=1e-4,
    label_smoothing=0.05,
    warmup_epochs=3,

    base_ch=32,

    num_workers=0,
    seed=42,
    save_dir="./mad_corn_results_ffpp_balanced",
    device="auto",
    smoke_test=False,
)

# ============================================================
# HELPERS
# ============================================================

def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

def auto_device(requested):
    if requested != "auto":
        return torch.device(requested)
    return torch.device("cuda" if torch.cuda.is_available() else "cpu")

set_seed(CONFIG["seed"])
DEVICE = auto_device(CONFIG["device"])
os.makedirs(CONFIG["save_dir"], exist_ok=True)

print("Torch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
print("Device:", DEVICE)

# ============================================================
# RESULT CLASSES
# ============================================================

@dataclass
class EpochResult:
    epoch: int
    train_loss: float
    train_acc: float
    train_auc: float
    val_acc: float
    val_auc: float
    precision: float
    recall: float
    f1: float
    uncertain_rate: float
    lr: float

@dataclass
class TestResult:
    model_name: str
    accuracy: float
    auc: float
    precision: float
    recall: float
    f1: float
    uncertain_rate: float

@dataclass
class ResolutionResult:
    resolution: int
    accuracy: float
    auc: float
    fast_pct: float
    medium_pct: float
    full_pct: float

@dataclass
class InferenceResult:
    mode: str
    time_per_image_ms: float
    fps: float

@dataclass
class TrainingTimeResult:
    model_type: str
    minutes: float
    hours: float

# ============================================================
# MODEL
# ============================================================

class ConvBNReLU(nn.Module):
    def __init__(self, in_ch, out_ch, kernel=3, stride=1, padding=1, groups=1):
        super().__init__()
        self.block = nn.Sequential(
            nn.Conv2d(in_ch, out_ch, kernel, stride, padding, groups=groups, bias=False),
            nn.BatchNorm2d(out_ch),
            nn.ReLU6(inplace=True),
        )

    def forward(self, x):
        return self.block(x)

class DepthwiseSeparable(nn.Module):
    def __init__(self, in_ch, out_ch, stride=1):
        super().__init__()
        self.dw = ConvBNReLU(in_ch, in_ch, kernel=3, stride=stride, padding=1, groups=in_ch)
        self.pw = ConvBNReLU(in_ch, out_ch, kernel=1, padding=0)

    def forward(self, x):
        return self.pw(self.dw(x))

class ConvReservoir(nn.Module):
    def __init__(self, in_ch, reservoir_ch=64, spectral_radius=0.9):
        super().__init__()
        self.input_proj = nn.Conv2d(in_ch, reservoir_ch, kernel_size=1, bias=False)
        self.input_bn = nn.BatchNorm2d(reservoir_ch)

        W = torch.randn(reservoir_ch, reservoir_ch, 3, 3)
        W = W / (W.abs().max() + 1e-8) * spectral_radius
        self.register_buffer("W_res", W)

        self.readout = nn.Sequential(
            nn.Conv2d(reservoir_ch, reservoir_ch, kernel_size=1, bias=False),
            nn.BatchNorm2d(reservoir_ch),
            nn.ReLU6(inplace=True),
        )

    def forward(self, x):
        h = F.relu(self.input_bn(self.input_proj(x)))
        h_res = torch.tanh(F.conv2d(h, self.W_res, padding=1))
        return self.readout(h + h_res)

class ChannelAttention(nn.Module):
    def __init__(self, channels, reduction=4):
        super().__init__()
        mid = max(channels // reduction, 8)
        self.gate = nn.Sequential(
            nn.AdaptiveAvgPool2d(1),
            nn.Flatten(),
            nn.Linear(channels, mid),
            nn.ReLU(inplace=True),
            nn.Linear(mid, channels),
            nn.Sigmoid(),
        )

    def forward(self, x):
        w = self.gate(x).view(x.size(0), x.size(1), 1, 1)
        return x * w

class SpatialAttention(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = nn.Conv2d(2, 1, kernel_size=7, padding=3, bias=False)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        avg = x.mean(dim=1, keepdim=True)
        mx, _ = x.max(dim=1, keepdim=True)
        return x * self.sigmoid(self.conv(torch.cat([avg, mx], dim=1)))

class MultiScaleAttentionBlock(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()
        b_ch = out_ch // 3

        self.branch1 = DepthwiseSeparable(in_ch, b_ch)
        self.branch2 = nn.Sequential(
            DepthwiseSeparable(in_ch, b_ch),
            DepthwiseSeparable(b_ch, b_ch),
        )
        self.branch3 = nn.Sequential(
            DepthwiseSeparable(in_ch, b_ch),
            DepthwiseSeparable(b_ch, b_ch),
            DepthwiseSeparable(b_ch, b_ch),
        )

        self.fuse = ConvBNReLU(b_ch * 3, out_ch, kernel=1, padding=0)
        self.ca = ChannelAttention(out_ch)
        self.sa = SpatialAttention()

    def forward(self, x):
        f = self.fuse(torch.cat([self.branch1(x), self.branch2(x), self.branch3(x)], dim=1))
        return self.sa(self.ca(f))

class MaDCoRN(nn.Module):
    def __init__(self, in_ch=3, num_classes=2, base_ch=32):
        super().__init__()
        c = base_ch

        self.stem = nn.Sequential(
            ConvBNReLU(in_ch, c, kernel=3, stride=2, padding=1),
            ConvBNReLU(c, c * 2, kernel=3, stride=1, padding=1),
        )

        self.mad1 = MultiScaleAttentionBlock(c * 2, c * 4)
        self.mad2 = MultiScaleAttentionBlock(c * 4, c * 4)
        self.res1 = ConvReservoir(c * 4, c * 4)
        self.down1 = nn.Conv2d(c * 4, c * 4, kernel_size=3, stride=2, padding=1, bias=False)

        self.mad3 = MultiScaleAttentionBlock(c * 4, c * 8)
        self.mad4 = MultiScaleAttentionBlock(c * 8, c * 8)
        self.res2 = ConvReservoir(c * 8, c * 8)
        self.down2 = nn.Conv2d(c * 8, c * 8, kernel_size=3, stride=2, padding=1, bias=False)

        self.mad5 = MultiScaleAttentionBlock(c * 8, c * 16)
        self.mad6 = MultiScaleAttentionBlock(c * 16, c * 16)
        self.res3 = ConvReservoir(c * 16, c * 16)

        self.pool = nn.AdaptiveAvgPool2d(1)
        self.head = nn.Sequential(
            nn.Flatten(),
            nn.Linear(c * 16, 256),
            nn.ReLU(inplace=True),
            nn.Dropout(0.4),
            nn.Linear(256, num_classes),
        )

        self._init_weights()

    def _init_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, mode="fan_out", nonlinearity="relu")
            elif isinstance(m, nn.BatchNorm2d):
                nn.init.ones_(m.weight)
                nn.init.zeros_(m.bias)
            elif isinstance(m, nn.Linear):
                nn.init.trunc_normal_(m.weight, std=0.02)
                if m.bias is not None:
                    nn.init.zeros_(m.bias)

    def forward(self, x):
        x = self.stem(x)
        x = self.down1(self.res1(self.mad2(self.mad1(x))))
        x = self.down2(self.res2(self.mad4(self.mad3(x))))
        x = self.res3(self.mad6(self.mad5(x)))
        return self.head(self.pool(x))

    def count_parameters(self):
        total = sum(p.numel() for p in self.parameters())
        frozen = sum(p.numel() for p in self.parameters() if not p.requires_grad)
        return total, frozen

def freeze_reservoir_weights(model):
    for name, param in model.named_parameters():
        if "W_res" in name:
            param.requires_grad_(False)

# ============================================================
# DATASET
# ============================================================

class AddGaussianNoise:
    def __init__(self, std=0.01):
        self.std = std

    def __call__(self, t):
        return t + torch.randn_like(t) * self.std

class JPEGCompression:
    def __init__(self, quality_range=(60, 95)):
        self.lo, self.hi = quality_range

    def __call__(self, img):
        q = random.randint(self.lo, self.hi)
        buf = io.BytesIO()
        img.save(buf, format="JPEG", quality=q)
        buf.seek(0)
        return Image.open(buf).copy()

_MEAN = [0.485, 0.456, 0.406]
_STD = [0.229, 0.224, 0.225]

def build_transforms(source_resolution, split="train", image_size_for_model=224):
    if split == "train":
        return T.Compose([
            T.Resize((source_resolution, source_resolution)),
            T.Resize((image_size_for_model + 16, image_size_for_model + 16)),
            T.RandomCrop(image_size_for_model),
            T.RandomHorizontalFlip(p=0.5),
            T.RandomVerticalFlip(p=0.1),
            T.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.1, hue=0.05),
            T.RandomGrayscale(p=0.05),
            T.RandomApply([T.GaussianBlur(kernel_size=3)], p=0.15),
            JPEGCompression(quality_range=(60, 95)),
            T.ToTensor(),
            AddGaussianNoise(std=0.01),
            T.Normalize(_MEAN, _STD),
        ])

    return T.Compose([
        T.Resize((source_resolution, source_resolution)),
        T.Resize((image_size_for_model, image_size_for_model)),
        T.ToTensor(),
        T.Normalize(_MEAN, _STD),
    ])

def load_ffpp_dataframes(cfg):
    df = pd.read_csv(cfg["metadata_csv"])

    required = {"frame_path", "split", "label", "label_name", "video_id"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"metadata.csv missing columns: {missing}")

    df = df[df["frame_path"].apply(os.path.exists)].reset_index(drop=True)

    print("\nLoaded FF++ metadata")
    print("Total usable frames:", len(df))

    for split in ["Train", "Val", "Test"]:
        sdf = df[df["split"].str.lower() == split.lower()]
        real = int((sdf["label"] == 0).sum())
        fake = int((sdf["label"] == 1).sum())
        videos = sdf["video_id"].nunique()
        print(f"{split}: real={real}, fake={fake}, total={len(sdf)}, videos={videos}")

    train_full = df[df["split"].str.lower() == "train"].reset_index(drop=True)
    val_df = df[df["split"].str.lower() == "val"].reset_index(drop=True)
    test_df = df[df["split"].str.lower() == "test"].reset_index(drop=True)

    return train_full, val_df, test_df

def make_balanced_train_df(train_df, seed=42):
    real_df = train_df[train_df["label"] == 0]
    fake_df = train_df[train_df["label"] == 1]

    n = min(len(real_df), len(fake_df))

    real_bal = real_df.sample(n=n, random_state=seed)
    fake_bal = fake_df.sample(n=n, random_state=seed)

    balanced_df = (
        pd.concat([real_bal, fake_bal])
        .sample(frac=1, random_state=seed)
        .reset_index(drop=True)
    )

    print("\nBalanced train set by undersampling")
    print(balanced_df["label_name"].value_counts())
    print("Total balanced train samples:", len(balanced_df))

    return balanced_df

def df_to_samples(df):
    return [(row["frame_path"], int(row["label"])) for _, row in df.iterrows()]

class MultiResolutionFFPPDataset(Dataset):
    def __init__(self, base_samples, resolutions, split="train", image_size_for_model=224):
        self.base_samples = list(base_samples)
        self.resolutions = list(resolutions)
        self.split = split
        self.image_size_for_model = image_size_for_model

        self.transforms = {
            res: build_transforms(res, split=split, image_size_for_model=image_size_for_model)
            for res in self.resolutions
        }

        if split == "train":
            self.samples = [(path, label, None) for path, label in self.base_samples]
        else:
            self.samples = [
                (path, label, res)
                for path, label in self.base_samples
                for res in self.resolutions
            ]

        n_real = sum(1 for _, label in self.base_samples if label == 0)
        n_fake = len(self.base_samples) - n_real

        print(
            f"[{split}] base: real={n_real:,}, fake={n_fake:,}, total={len(self.base_samples):,} | "
            f"effective={len(self.samples):,}"
        )

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        path, label, resolution = self.samples[idx]

        if resolution is None:
            resolution = random.choice(self.resolutions)

        try:
            img = Image.open(path).convert("RGB")
        except Exception:
            img = Image.fromarray(np.zeros((resolution, resolution, 3), dtype=np.uint8))

        x = self.transforms[resolution](img)
        y = torch.tensor(label, dtype=torch.long)

        return x, y

    def subset_for_resolution(self, resolution):
        return SingleResolutionView(
            self.base_samples,
            resolution,
            image_size_for_model=self.image_size_for_model,
        )

    @property
    def base_count(self):
        return len(self.base_samples)

    @property
    def expanded_count(self):
        return len(self.samples)

class SingleResolutionView(Dataset):
    def __init__(self, base_samples, resolution, image_size_for_model=224):
        self.base_samples = list(base_samples)
        self.resolution = resolution
        self.transform = build_transforms(
            resolution,
            split="val",
            image_size_for_model=image_size_for_model,
        )

    def __len__(self):
        return len(self.base_samples)

    def __getitem__(self, idx):
        path, label = self.base_samples[idx]

        try:
            img = Image.open(path).convert("RGB")
        except Exception:
            img = Image.fromarray(np.zeros((self.resolution, self.resolution, 3), dtype=np.uint8))

        x = self.transform(img)
        y = torch.tensor(label, dtype=torch.long)

        return x, y

def _make_loader(dataset, batch_size, num_workers, shuffle, drop_last):
    return DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,
        num_workers=num_workers,
        pin_memory=(DEVICE.type == "cuda"),
        persistent_workers=False,
    )

def print_dataset_summary(split_datasets, resolutions):
    print("\nDataset size summary")
    for name in ["train", "val", "test"]:
        ds = split_datasets[name]
        print(
            f"{name.title():<5} | base={ds.base_count:,}, "
            f"effective={ds.expanded_count:,}, resolutions={resolutions}"
        )

    print("\nStrategy:")
    print("  Train: balanced undersampled train set + one random source resolution per image per epoch")
    print("  Val:   original val set + all requested source resolutions per image")
    print("  Test:  original test set + all requested source resolutions per image")
    print(f"  Model input tensor size: (3, {CONFIG['image_size_for_model']}, {CONFIG['image_size_for_model']})")

def make_dataloaders(cfg):
    train_full_df, val_df, test_df = load_ffpp_dataframes(cfg)
    train_balanced_df = make_balanced_train_df(train_full_df, seed=cfg["seed"])

    train_samples = df_to_samples(train_balanced_df)
    val_samples = df_to_samples(val_df)
    test_samples = df_to_samples(test_df)

    resolutions = list(cfg["resolutions"])

    split_datasets = {
        "train": MultiResolutionFFPPDataset(
            train_samples,
            resolutions,
            split="train",
            image_size_for_model=cfg["image_size_for_model"],
        ),
        "val": MultiResolutionFFPPDataset(
            val_samples,
            resolutions,
            split="val",
            image_size_for_model=cfg["image_size_for_model"],
        ),
        "test": MultiResolutionFFPPDataset(
            test_samples,
            resolutions,
            split="test",
            image_size_for_model=cfg["image_size_for_model"],
        ),
    }

    print_dataset_summary(split_datasets, resolutions)

    loaders = {
        "train": _make_loader(
            split_datasets["train"],
            cfg["batch_size"],
            cfg["num_workers"],
            shuffle=True,
            drop_last=True,
        ),
        "val": _make_loader(
            split_datasets["val"],
            cfg["batch_size"],
            cfg["num_workers"],
            shuffle=False,
            drop_last=False,
        ),
        "test": _make_loader(
            split_datasets["test"],
            cfg["batch_size"],
            cfg["num_workers"],
            shuffle=False,
            drop_last=False,
        ),
    }

    meta = {
        "train_full_df": train_full_df,
        "train_balanced_df": train_balanced_df,
        "val_df": val_df,
        "test_df": test_df,
    }

    return {
        "loaders": loaders,
        "datasets": split_datasets,
        "meta": meta,
    }

def make_smoke_loader(resolution, n=200, bs=8):
    imgs = torch.randn(n, 3, CONFIG["image_size_for_model"], CONFIG["image_size_for_model"])
    labels = torch.randint(0, 2, (n,))
    return DataLoader(TensorDataset(imgs, labels), batch_size=bs, shuffle=True)

# ============================================================
# TRAINING
# ============================================================

def compute_uncertain_rate(probs, threshold=0.65):
    conf = probs.max(axis=1)
    return float(np.mean(conf < threshold) * 100)

def run_epoch(model, loader, criterion, optimizer, device, scaler=None, is_train=True, desc=None):
    model.train(is_train)

    total_loss = 0.0
    seen = 0
    all_probs, all_preds, all_labels = [], [], []

    pbar = tqdm(
        loader,
        total=len(loader) if hasattr(loader, "__len__") else None,
        desc=desc or ("Train" if is_train else "Eval"),
        leave=False,
        dynamic_ncols=True,
        mininterval=0.5,
    )

    with torch.set_grad_enabled(is_train):
        for imgs, labels in pbar:
            imgs = imgs.to(device, non_blocking=True)
            labels = labels.to(device, non_blocking=True)

            if is_train:
                optimizer.zero_grad(set_to_none=True)

            if is_train and scaler:
                with autocast():
                    logits = model(imgs)
                    loss = criterion(logits, labels)

                scaler.scale(loss).backward()
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                scaler.step(optimizer)
                scaler.update()

            else:
                logits = model(imgs)
                loss = criterion(logits, labels)

                if is_train:
                    loss.backward()
                    torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                    optimizer.step()

            probs = torch.softmax(logits.float(), dim=1).detach().cpu().numpy()
            preds = probs.argmax(axis=1)

            all_probs.append(probs)
            all_preds.append(preds)
            all_labels.append(labels.detach().cpu().numpy())

            batch_n = len(labels)
            total_loss += loss.item() * batch_n
            seen += batch_n

            pbar.set_postfix(loss=f"{loss.item():.4f}", samples=f"{seen:,}")

    all_probs = np.vstack(all_probs)
    all_preds = np.concatenate(all_preds)
    all_labels = np.concatenate(all_labels)

    acc = accuracy_score(all_labels, all_preds)

    try:
        auc = roc_auc_score(all_labels, all_probs[:, 1])
    except ValueError:
        auc = 0.5

    precision = precision_score(all_labels, all_preds, zero_division=0)
    recall = recall_score(all_labels, all_preds, zero_division=0)
    f1 = f1_score(all_labels, all_preds, zero_division=0)
    uncertain_rate = compute_uncertain_rate(all_probs)

    return {
        "loss": total_loss / max(seen, 1),
        "acc": acc,
        "auc": auc,
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "uncertain_rate": uncertain_rate,
        "probs": all_probs,
        "preds": all_preds,
        "labels": all_labels,
    }

class Trainer:
    def __init__(self, model, train_loader, val_loader, test_loader, device, cfg, ckpt_path):
        self.model = model.to(device)
        self.train_loader = train_loader
        self.val_loader = val_loader
        self.test_loader = test_loader
        self.device = device
        self.epochs = cfg["epochs"]
        self.ckpt_path = ckpt_path
        self.model_name = "MaD-CoRN-FFPP-Balanced"

        self.criterion = nn.CrossEntropyLoss(label_smoothing=cfg["label_smoothing"])

        self.optimizer = optim.AdamW(
            [p for p in model.parameters() if p.requires_grad],
            lr=cfg["lr"],
            weight_decay=cfg["weight_decay"],
        )

        total_steps = self.epochs
        warmup_steps = cfg["warmup_epochs"]

        def lr_lambda(epoch):
            if epoch < warmup_steps:
                return max(1e-8, epoch / max(1, warmup_steps))
            prog = (epoch - warmup_steps) / max(1, total_steps - warmup_steps)
            return 0.5 * (1.0 + math.cos(math.pi * prog))

        self.scheduler = optim.lr_scheduler.LambdaLR(self.optimizer, lr_lambda)
        self.scaler = GradScaler() if device.type == "cuda" else None
        self.epoch_results = []

    def train(self):
        best_auc = -1.0
        t0 = time.time()

        for epoch in range(1, self.epochs + 1):
            tr = run_epoch(
                self.model,
                self.train_loader,
                self.criterion,
                self.optimizer,
                self.device,
                self.scaler,
                is_train=True,
                desc=f"Epoch {epoch}/{self.epochs} [train]",
            )

            with torch.no_grad():
                vl = run_epoch(
                    self.model,
                    self.val_loader,
                    self.criterion,
                    None,
                    self.device,
                    None,
                    is_train=False,
                    desc=f"Epoch {epoch}/{self.epochs} [val]",
                )

            self.scheduler.step()
            lr_now = self.optimizer.param_groups[0]["lr"]

            er = EpochResult(
                epoch=epoch,
                train_loss=tr["loss"],
                train_acc=tr["acc"],
                train_auc=tr["auc"],
                val_acc=vl["acc"],
                val_auc=vl["auc"],
                precision=vl["precision"],
                recall=vl["recall"],
                f1=vl["f1"],
                uncertain_rate=vl["uncertain_rate"],
                lr=lr_now,
            )

            self.epoch_results.append(er)

            print(
                f"Epoch {epoch:3d}/{self.epochs} | "
                f"Loss {er.train_loss:.4f} | "
                f"Tr Acc {er.train_acc:.4f} AUC {er.train_auc:.4f} | "
                f"Val Acc {er.val_acc:.4f} AUC {er.val_auc:.4f} | "
                f"P {er.precision:.4f} R {er.recall:.4f} F1 {er.f1:.4f} | "
                f"Unc {er.uncertain_rate:.1f}% | LR {lr_now:.2e}"
            )

            if vl["auc"] > best_auc:
                best_auc = vl["auc"]
                torch.save(self.model.state_dict(), self.ckpt_path)
                print(f"Checkpoint saved. Val AUC = {best_auc:.4f}")

        return self.epoch_results, (time.time() - t0) / 60

    def evaluate(self, loader=None, load_best=True):
        if load_best and os.path.exists(self.ckpt_path):
            self.model.load_state_dict(torch.load(self.ckpt_path, map_location=self.device))

        loader = loader or self.test_loader

        with torch.no_grad():
            r = run_epoch(
                self.model,
                loader,
                self.criterion,
                None,
                self.device,
                None,
                is_train=False,
                desc="Test evaluation",
            )

        return TestResult(
            model_name=self.model_name,
            accuracy=r["acc"],
            auc=r["auc"],
            precision=r["precision"],
            recall=r["recall"],
            f1=r["f1"],
            uncertain_rate=r["uncertain_rate"],
        )

# ============================================================
# EVAL / TIMING
# ============================================================

@torch.no_grad()
def measure_inference(model, resolution, device, image_size_for_model=224, batch_size=32, n_warmup=20, n_runs=200):
    model.eval()
    results = []

    for bs, label in [(1, "Single"), (batch_size, f"Batch={batch_size}")]:
        dummy = torch.randn(bs, 3, image_size_for_model, image_size_for_model, device=device)

        for _ in range(n_warmup):
            model(dummy)

        if device.type == "cuda":
            torch.cuda.synchronize()

        t0 = time.perf_counter()

        for _ in range(n_runs):
            model(dummy)

        if device.type == "cuda":
            torch.cuda.synchronize()

        elapsed = time.perf_counter() - t0
        total = bs * n_runs

        results.append(
            InferenceResult(
                mode=f"Source Res={resolution} {label}",
                time_per_image_ms=elapsed / total * 1000,
                fps=total / elapsed,
            )
        )

    return results

@torch.no_grad()
def evaluate_by_resolution(model, loader, device, resolution):
    model.eval()

    all_probs, all_labels = [], []
    buckets = {"fast": 0, "medium": 0, "full": 0}
    total = 0

    pbar = tqdm(
        loader,
        total=len(loader) if hasattr(loader, "__len__") else None,
        desc=f"Resolution {resolution} eval",
        leave=False,
        dynamic_ncols=True,
        mininterval=0.5,
    )

    for imgs, labels in pbar:
        imgs = imgs.to(device, non_blocking=True)
        bs = imgs.size(0)

        if device.type == "cuda":
            torch.cuda.synchronize()

        t0 = time.perf_counter()
        logits = model(imgs)

        if device.type == "cuda":
            torch.cuda.synchronize()

        ms = (time.perf_counter() - t0) / bs * 1000

        probs = torch.softmax(logits.float(), dim=1).cpu().numpy()

        all_probs.append(probs)
        all_labels.append(labels.numpy())

        if ms < 5:
            buckets["fast"] += bs
        elif ms < 20:
            buckets["medium"] += bs
        else:
            buckets["full"] += bs

        total += bs
        pbar.set_postfix(samples=f"{total:,}", ms_per_img=f"{ms:.3f}")

    all_probs = np.vstack(all_probs)
    all_labels = np.concatenate(all_labels)
    preds = all_probs.argmax(axis=1)

    acc = accuracy_score(all_labels, preds)

    try:
        auc = roc_auc_score(all_labels, all_probs[:, 1])
    except ValueError:
        auc = 0.5

    return ResolutionResult(
        resolution=resolution,
        accuracy=acc,
        auc=auc,
        fast_pct=buckets["fast"] / max(total, 1) * 100,
        medium_pct=buckets["medium"] / max(total, 1) * 100,
        full_pct=buckets["full"] / max(total, 1) * 100,
    )

# ============================================================
# REPORTING
# ============================================================

def _table(headers, rows, title=""):
    col_w = [
        max(len(str(h)), max((len(str(r[i])) for r in rows), default=0))
        for i, h in enumerate(headers)
    ]

    sep = "+" + "+".join("-" * (w + 2) for w in col_w) + "+"
    hdr = "|" + "|".join(f" {h:<{w}} " for h, w in zip(headers, col_w)) + "|"

    body = [
        "|" + "|".join(f" {str(v):<{w}} " for v, w in zip(r, col_w)) + "|"
        for r in rows
    ]

    out = [sep, hdr, sep] + body + [sep]

    if title:
        out.insert(0, title.center(len(sep)))
        out.insert(1, "")

    return "\n".join(out)

def print_training_table(ers):
    h = [
        "Epoch", "Train Loss", "Train Acc", "Train AUC",
        "Val Acc", "Val AUC", "Precision", "Recall", "F1",
        "Uncertain Rate (%)"
    ]

    rows = [
        [
            e.epoch,
            f"{e.train_loss:.4f}",
            f"{e.train_acc:.4f}",
            f"{e.train_auc:.4f}",
            f"{e.val_acc:.4f}",
            f"{e.val_auc:.4f}",
            f"{e.precision:.4f}",
            f"{e.recall:.4f}",
            f"{e.f1:.4f}",
            f"{e.uncertain_rate:.2f}",
        ]
        for e in ers
    ]

    t = _table(h, rows, "Training Periods Results")
    print(t)
    return t

def print_test_table(trs):
    h = ["Model", "Accuracy", "AUC", "Precision", "Recall", "F1", "Uncertain Rate (%)"]

    rows = [
        [
            r.model_name,
            f"{r.accuracy:.4f}",
            f"{r.auc:.4f}",
            f"{r.precision:.4f}",
            f"{r.recall:.4f}",
            f"{r.f1:.4f}",
            f"{r.uncertain_rate:.2f}",
        ]
        for r in trs
    ]

    t = _table(h, rows, "Test Results")
    print(t)
    return t

def print_resolution_table(rrs):
    h = ["Resolution", "Accuracy", "AUC", "Fast (%)", "Medium (%)", "Full (%)"]

    rows = [
        [
            r.resolution,
            f"{r.accuracy:.4f}",
            f"{r.auc:.4f}",
            f"{r.fast_pct:.2f}",
            f"{r.medium_pct:.2f}",
            f"{r.full_pct:.2f}",
        ]
        for r in rrs
    ]

    t = _table(h, rows, "Accuracy Based on Resolution")
    print(t)
    return t

def print_inference_table(irs):
    h = ["Mode", "Time per Image (ms)", "FPS"]

    rows = [
        [r.mode, f"{r.time_per_image_ms:.3f}", f"{r.fps:.1f}"]
        for r in irs
    ]

    t = _table(h, rows, "Inference Time")
    print(t)
    return t

def print_training_time_table(tts):
    h = ["Model Type", "min", "hrs"]

    rows = [
        [r.model_type, f"{r.minutes:.1f}", f"{r.hours:.2f}"]
        for r in tts
    ]

    t = _table(h, rows, "Training Time")
    print(t)
    return t

def save_all_results(epoch_results, test_results, res_results, inf_results, tt_results, save_dir, meta):
    os.makedirs(save_dir, exist_ok=True)

    data = {
        "epoch_results": [asdict(e) for e in epoch_results],
        "test_results": [asdict(t) for t in test_results],
        "res_results": [asdict(r) for r in res_results],
        "inference": [asdict(i) for i in inf_results],
        "training_time": [asdict(t) for t in tt_results],
    }

    with open(os.path.join(save_dir, "mad_corn_results.json"), "w") as f:
        json.dump(data, f, indent=2)

    for name, rows in data.items():
        if rows:
            pd.DataFrame(rows).to_csv(os.path.join(save_dir, f"mad_corn_{name}.csv"), index=False)

    train_full_df = meta["train_full_df"]
    train_balanced_df = meta["train_balanced_df"]
    val_df = meta["val_df"]
    test_df = meta["test_df"]

    experiment_summary = pd.DataFrame([{
        "Experiment Name": "MaD-CoRN Balanced Train",
        "Dataset": "FaceForensics++ C23",
        "Train Samples Original": len(train_full_df),
        "Train Samples Used Balanced": len(train_balanced_df),
        "Validation Samples": len(val_df),
        "Test Samples": len(test_df),
        "Train Real Used": int((train_balanced_df["label"] == 0).sum()),
        "Train Fake Used": int((train_balanced_df["label"] == 1).sum()),
        "Validation Real": int((val_df["label"] == 0).sum()),
        "Validation Fake": int((val_df["label"] == 1).sum()),
        "Test Real": int((test_df["label"] == 0).sum()),
        "Test Fake": int((test_df["label"] == 1).sum()),
        "Balancing Method": "Train-only undersampling of fake class to match real class",
        "Resolutions Used": str(CONFIG["resolutions"]),
        "Input Modalities": "RGB",
        "RGB Shape": f"(3, {CONFIG['image_size_for_model']}, {CONFIG['image_size_for_model']})",
        "Device": str(DEVICE),
        "CUDA Available": torch.cuda.is_available(),
        "Framework": "PyTorch",
        "Torch Version": torch.__version__,
        "Batching Strategy": "Train: balanced undersampled set with one random source resolution per image per epoch; Val/Test: original distribution with all requested source resolutions",
    }])

    experiment_summary.to_csv(os.path.join(save_dir, "experiment_summary.csv"), index=False)

    print("\nExperiment Summary")
    display(experiment_summary)

    print("\nResults saved to:", save_dir)

def print_full_report(epoch_results, test_results, res_results, inf_results, tt_results, save_dir, meta):
    div = "=" * 100

    print("\n" + div)
    print("MaD-CoRN EXPERIMENT RESULTS".center(100, "="))
    print(div)

    print("\n[1] TRAINING PERIODS RESULTS")
    print_training_table(epoch_results)

    print("\n[2] TEST RESULTS")
    print_test_table(test_results)

    print("\n[3] ACCURACY BASED ON RESOLUTION")
    print_resolution_table(res_results)

    print("\n[4] INFERENCE TIME")
    print_inference_table(inf_results)

    print("\n[5] TRAINING TIME")
    print_training_time_table(tt_results)

    save_all_results(epoch_results, test_results, res_results, inf_results, tt_results, save_dir, meta)

# ============================================================
# PIPELINE
# ============================================================

def run_pipeline(cfg):
    set_seed(cfg["seed"])
    device = auto_device(cfg["device"])
    os.makedirs(cfg["save_dir"], exist_ok=True)

    print("\n" + "=" * 70)
    print("MaD-CoRN Pipeline FF++ Balanced Train")
    print("Device:", device)
    print("Source resolutions:", cfg["resolutions"])
    print("Model input size:", cfg["image_size_for_model"])
    print("Epochs:", cfg["epochs"])
    print("Smoke test:", cfg["smoke_test"])
    print("=" * 70)

    model = MaDCoRN(in_ch=3, num_classes=2, base_ch=cfg["base_ch"])
    freeze_reservoir_weights(model)

    total, frozen = model.count_parameters()
    trainable = total - frozen
    print(f"\nModel params: {total:,} total | {trainable:,} trainable | {frozen:,} frozen")

    split_datasets = None
    meta = None

    if cfg["smoke_test"]:
        print("\nSMOKE TEST")
        bs = cfg["batch_size"]
        train_loader = make_smoke_loader(cfg["image_size_for_model"], n=320, bs=bs)
        val_loader = make_smoke_loader(cfg["image_size_for_model"], n=80, bs=bs)
        test_loader = make_smoke_loader(cfg["image_size_for_model"], n=80, bs=bs)
        cfg = {**cfg, "epochs": min(cfg["epochs"], 3)}
        meta = {
            "train_full_df": pd.DataFrame(),
            "train_balanced_df": pd.DataFrame(),
            "val_df": pd.DataFrame(),
            "test_df": pd.DataFrame(),
        }
    else:
        print("\nLoading FF++ dataset...")
        data_bundle = make_dataloaders(cfg)
        split_datasets = data_bundle["datasets"]
        train_loader = data_bundle["loaders"]["train"]
        val_loader = data_bundle["loaders"]["val"]
        test_loader = data_bundle["loaders"]["test"]
        meta = data_bundle["meta"]

    ckpt_path = os.path.join(cfg["save_dir"], "mad_corn_ffpp_balanced_multires.pt")

    print("\n" + "-" * 60)
    print("TRAINING")
    print("-" * 60)

    trainer = Trainer(
        model,
        train_loader,
        val_loader,
        test_loader,
        device,
        cfg,
        ckpt_path,
    )

    epoch_results, training_min = trainer.train()

    print(f"\nTraining done: {training_min:.1f} min ({training_min / 60:.2f} hrs)")

    print("\n" + "-" * 60)
    print("TEST EVALUATION ON COMBINED MULTI-RES TEST SET")
    print("-" * 60)

    test_result = trainer.evaluate(test_loader, load_best=True)
    test_results = [test_result]

    print("\n" + "-" * 60)
    print("PER-RESOLUTION BREAKDOWN")
    print("-" * 60)

    res_results = []
    inf_results = []

    for res in tqdm(cfg["resolutions"], desc="Resolution sweep", dynamic_ncols=True):
        print(f"\nResolution {res}")

        if cfg["smoke_test"]:
            res_loader = make_smoke_loader(cfg["image_size_for_model"], n=80, bs=cfg["batch_size"])
        else:
            res_ds = split_datasets["test"].subset_for_resolution(res)
            res_loader = DataLoader(
                res_ds,
                batch_size=cfg["batch_size"],
                shuffle=False,
                num_workers=cfg["num_workers"],
                pin_memory=(device.type == "cuda"),
                persistent_workers=False,
            )

        rr = evaluate_by_resolution(model, res_loader, device, res)
        res_results.append(rr)

        print(
            f"Acc={rr.accuracy:.4f} AUC={rr.auc:.4f} "
            f"Fast={rr.fast_pct:.2f}% Medium={rr.medium_pct:.2f}% Full={rr.full_pct:.2f}%"
        )

        infs = measure_inference(
            model,
            res,
            device,
            image_size_for_model=cfg["image_size_for_model"],
            batch_size=cfg["batch_size"],
        )
        inf_results.extend(infs)

        for ir in infs:
            print(f"{ir.mode}: {ir.time_per_image_ms:.3f} ms/img | {ir.fps:.1f} FPS")

    tt_results = [
        TrainingTimeResult(
            model_type="MaD-CoRN FF++ balanced train multi-resolution training",
            minutes=training_min,
            hours=training_min / 60,
        )
    ]

    print_full_report(
        epoch_results,
        test_results,
        res_results,
        inf_results,
        tt_results,
        cfg["save_dir"],
        meta,
    )

    return {
        "epoch_results": epoch_results,
        "test_results": test_results,
        "res_results": res_results,
        "inf_results": inf_results,
        "tt_results": tt_results,
        "model": model,
        "trainer": trainer,
        "split_datasets": split_datasets,
        "meta": meta,
    }

results = run_pipeline(CONFIG)

Requirement already satisfied: scikit-learn in /opt/conda/lib/python3.11/site-packages (1.8.0)
Requirement already satisfied: torch in /opt/conda/lib/python3.11/site-packages (2.11.0)
Requirement already satisfied: torchvision in /opt/conda/lib/python3.11/site-packages (0.26.0)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.11/site-packages (4.66.4)
Requirement already satisfied: pandas in /opt/conda/lib/python3.11/site-packages (3.0.2)
Requirement already satisfied: pillow in /opt/conda/lib/python3.11/site-packages (12.2.0)
Requirement already satisfied: numpy>=1.24.1 in /opt/conda/lib/python3.11/site-packages (from scikit-learn) (2.4.4)
Requirement already satisfied: scipy>=1.10.0 in /opt/conda/lib/python3.11/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in /opt/conda/lib/python3.11/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /opt/conda/lib/python3.11/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: filelock in /opt/conda/lib/python3.11/site-packages (from torch) (3.29.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /opt/conda/lib/python3.11/site-packages (from torch) (4.12.2)
Requirement already satisfied: setuptools<82 in /opt/conda/lib/python3.11/site-packages (from torch) (71.0.4)
Requirement already satisfied: sympy>=1.13.3 in /opt/conda/lib/python3.11/site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /opt/conda/lib/python3.11/site-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.11/site-packages (from torch) (3.1.4)
Requirement already satisfied: fsspec>=0.8.5 in /opt/conda/lib/python3.11/site-packages (from torch) (2026.4.0)
Requirement already satisfied: cuda-toolkit==13.0.2 in /opt/conda/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.0.2)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /opt/conda/lib/python3.11/site-packages (from torch) (13.2.0)
Requirement already satisfied: nvidia-cudnn-cu13==9.19.0.56 in /opt/conda/lib/python3.11/site-packages (from torch) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.0 in /opt/conda/lib/python3.11/site-packages (from torch) (0.8.0)
Requirement already satisfied: nvidia-nccl-cu13==2.28.9 in /opt/conda/lib/python3.11/site-packages (from torch) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /opt/conda/lib/python3.11/site-packages (from torch) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /opt/conda/lib/python3.11/site-packages (from torch) (3.6.0)
Requirement already satisfied: nvidia-cublas==13.1.0.3.* in /opt/conda/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.1.0.3)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /opt/conda/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /opt/conda/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (12.0.0.61)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /opt/conda/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /opt/conda/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /opt/conda/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /opt/conda/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /opt/conda/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (12.6.3.3)
Requirement already satisfied: nvidia-nvjitlink==13.0.88.* in /opt/conda/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.0.88)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /opt/conda/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.0.88)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /opt/conda/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.0.85)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.11/site-packages (from pandas) (2.9.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /opt/conda/lib/python3.11/site-packages (from cuda-bindings<14,>=13.0.3->torch) (1.5.4)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /opt/conda/lib/python3.11/site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.11/site-packages (from jinja2->torch) (2.1.5)
Torch: 2.11.0+cu130
CUDA available: True
Device: cuda

======================================================================
MaD-CoRN Pipeline FF++ Balanced Train
Device: cuda
Source resolutions: [128, 224, 256, 384]
Model input size: 224
Epochs: 15
Smoke test: False
======================================================================

Model params: 3,428,062 total | 3,428,062 trainable | 0 frozen

Loading FF++ dataset...

Loaded FF++ metadata
Total usable frames: 55953
Train: real=6400, fake=38356, total=44756, videos=5600
Val: real=800, fake=4800, total=5600, videos=700
Test: real=800, fake=4797, total=5597, videos=700

Balanced train set by undersampling
label_name
Real    6400
Fake    6400
Name: count, dtype: int64
Total balanced train samples: 12800
[train] base: real=6,400, fake=6,400, total=12,800 | effective=12,800
[val] base: real=800, fake=4,800, total=5,600 | effective=22,400
[test] base: real=800, fake=4,797, total=5,597 | effective=22,388

Dataset size summary
Train | base=12,800, effective=12,800, resolutions=[128, 224, 256, 384]
Val   | base=5,600, effective=22,400, resolutions=[128, 224, 256, 384]
Test  | base=5,597, effective=22,388, resolutions=[128, 224, 256, 384]

Strategy:
  Train: balanced undersampled train set + one random source resolution per image per epoch
  Val:   original val set + all requested source resolutions per image
  Test:  original test set + all requested source resolutions per image
  Model input tensor size: (3, 224, 224)

------------------------------------------------------------
TRAINING
------------------------------------------------------------

Epoch   1/15 | Loss 0.6958 | Tr Acc 0.4998 AUC 0.4960 | Val Acc 0.1429 AUC 0.4994 | P 0.0000 R 0.0000 F1 0.0000 | Unc 100.0% | LR 3.33e-04
Checkpoint saved. Val AUC = 0.4994

Epoch   2/15 | Loss 0.6942 | Tr Acc 0.5063 AUC 0.5043 | Val Acc 0.2946 AUC 0.5095 | P 0.8779 R 0.2057 F1 0.3333 | Unc 97.8% | LR 6.67e-04
Checkpoint saved. Val AUC = 0.5095

Epoch   3/15 | Loss 0.6932 | Tr Acc 0.5187 AUC 0.5230 | Val Acc 0.1838 AUC 0.5000 | P 0.9935 R 0.0481 F1 0.0917 | Unc 100.0% | LR 1.00e-03

Epoch   4/15 | Loss 0.6940 | Tr Acc 0.5048 AUC 0.5091 | Val Acc 0.7200 AUC 0.5691 | P 0.8725 R 0.7885 F1 0.8284 | Unc 100.0% | LR 9.83e-04
Checkpoint saved. Val AUC = 0.5691

Epoch   5/15 | Loss 0.6928 | Tr Acc 0.5125 AUC 0.5208 | Val Acc 0.3951 AUC 0.5093 | P 0.8479 R 0.3586 F1 0.5041 | Unc 100.0% | LR 9.33e-04

Epoch   6/15 | Loss 0.6925 | Tr Acc 0.5145 AUC 0.5185 | Val Acc 0.3276 AUC 0.4796 | P 0.8437 R 0.2646 F1 0.4028 | Unc 100.0% | LR 8.54e-04

Epoch   7/15 | Loss 0.6920 | Tr Acc 0.5252 AUC 0.5344 | Val Acc 0.5956 AUC 0.5183 | P 0.8616 R 0.6293 F1 0.7274 | Unc 99.9% | LR 7.50e-04

Epoch   8/15 | Loss 0.6871 | Tr Acc 0.5405 AUC 0.5533 | Val Acc 0.3789 AUC 0.5279 | P 0.8557 R 0.3312 F1 0.4776 | Unc 90.4% | LR 6.29e-04

Epoch   9/15 | Loss 0.6841 | Tr Acc 0.5397 AUC 0.5529 | Val Acc 0.3377 AUC 0.5772 | P 0.9086 R 0.2528 F1 0.3955 | Unc 92.4% | LR 5.00e-04
Checkpoint saved. Val AUC = 0.5772

Epoch  10/15 | Loss 0.6775 | Tr Acc 0.5581 AUC 0.5696 | Val Acc 0.3261 AUC 0.5773 | P 0.9344 R 0.2299 F1 0.3690 | Unc 91.5% | LR 3.71e-04
Checkpoint saved. Val AUC = 0.5773

Epoch  11/15 | Loss 0.6712 | Tr Acc 0.5644 AUC 0.5726 | Val Acc 0.2980 AUC 0.5870 | P 0.9338 R 0.1948 F1 0.3224 | Unc 87.2% | LR 2.50e-04
Checkpoint saved. Val AUC = 0.5870

Epoch  12/15 | Loss 0.6672 | Tr Acc 0.5716 AUC 0.5827 | Val Acc 0.2859 AUC 0.5818 | P 0.9346 R 0.1795 F1 0.3011 | Unc 87.9% | LR 1.46e-04

Epoch  13/15 | Loss 0.6608 | Tr Acc 0.5709 AUC 0.5810 | Val Acc 0.2879 AUC 0.5607 | P 0.9501 R 0.1786 F1 0.3007 | Unc 86.8% | LR 6.70e-05

Epoch  14/15 | Loss 0.6587 | Tr Acc 0.5772 AUC 0.5796 | Val Acc 0.2943 AUC 0.5705 | P 0.9389 R 0.1890 F1 0.3146 | Unc 85.3% | LR 1.70e-05

Epoch  15/15 | Loss 0.6580 | Tr Acc 0.5807 AUC 0.5936 | Val Acc 0.2864 AUC 0.5720 | P 0.9360 R 0.1798 F1 0.3016 | Unc 86.6% | LR 0.00e+00

Training done: 305.7 min (5.09 hrs)

------------------------------------------------------------
TEST EVALUATION ON COMBINED MULTI-RES TEST SET
------------------------------------------------------------

------------------------------------------------------------
PER-RESOLUTION BREAKDOWN
------------------------------------------------------------

Resolution sweep:   0%|          | 0/4 [00:00<?, ?it/s]

Resolution 128

Resolution 128 eval:   0%|          | 0/175 [00:00<?, ?it/s]
Resolution 128 eval:   0%|          | 0/175 [00:00<?, ?it/s, ms_per_img=1.776, samples=32]
Resolution 128 eval:   1%|          | 1/175 [00:00<02:32,  1.14it/s, ms_per_img=1.776, samples=32]
Resolution 128 eval:   1%|          | 1/175 [00:01<02:32,  1.14it/s, ms_per_img=1.774, samples=64]
Resolution 128 eval:   1%|          | 2/175 [00:01<02:38,  1.09it/s, ms_per_img=1.774, samples=64]
Resolution 128 eval:   1%|          | 2/175 [00:03<02:38,  1.09it/s, ms_per_img=1.773, samples=96]
Resolution 128 eval:   2%|▏         | 3/175 [00:03<04:05,  1.43s/it, ms_per_img=1.773, samples=96]
Resolution 128 eval:   2%|▏         | 3/175 [00:05<04:05,  1.43s/it, ms_per_img=1.773, samples=128]
Resolution 128 eval:   2%|▏         | 4/175 [00:05<04:10,  1.46s/it, ms_per_img=1.773, samples=128]
Resolution 128 eval:   2%|▏         | 4/175 [00:07<04:10,  1.46s/it, ms_per_img=1.773, samples=160]
Resolution 128 eval:   3%|▎         | 5/175 [00:07<04:41,  1.66s/it, ms_per_img=1.773, samples=160]
Resolution 128 eval:   3%|▎         | 5/175 [00:09<04:41,  1.66s/it, ms_per_img=1.773, samples=192]
Resolution 128 eval:   3%|▎         | 6/175 [00:09<04:59,  1.77s/it, ms_per_img=1.773, samples=192]
Resolution 128 eval:   3%|▎         | 6/175 [00:10<04:59,  1.77s/it, ms_per_img=1.772, samples=224]
Resolution 128 eval:   4%|▍         | 7/175 [00:10<04:24,  1.57s/it, ms_per_img=1.772, samples=224]
Resolution 128 eval:   4%|▍         | 7/175 [00:11<04:24,  1.57s/it, ms_per_img=1.771, samples=256]
Resolution 128 eval:   5%|▍         | 8/175 [00:11<04:11,  1.50s/it, ms_per_img=1.771, samples=256]
Resolution 128 eval:   5%|▍         | 8/175 [00:13<04:11,  1.50s/it, ms_per_img=1.774, samples=288]
Resolution 128 eval:   5%|▌         | 9/175 [00:13<04:28,  1.61s/it, ms_per_img=1.774, samples=288]
Resolution 128 eval:   5%|▌         | 9/175 [00:15<04:28,  1.61s/it, ms_per_img=1.774, samples=320]
Resolution 128 eval:   6%|▌         | 10/175 [00:15<04:30,  1.64s/it, ms_per_img=1.774, samples=320]
Resolution 128 eval:   6%|▌         | 10/175 [00:16<04:30,  1.64s/it, ms_per_img=1.770, samples=352]
Resolution 128 eval:   6%|▋         | 11/175 [00:16<04:21,  1.59s/it, ms_per_img=1.770, samples=352]
Resolution 128 eval:   6%|▋         | 11/175 [00:17<04:21,  1.59s/it, ms_per_img=1.772, samples=384]
Resolution 128 eval:   7%|▋         | 12/175 [00:17<03:29,  1.28s/it, ms_per_img=1.772, samples=384]
Resolution 128 eval:   7%|▋         | 12/175 [00:18<03:29,  1.28s/it, ms_per_img=1.773, samples=416]
Resolution 128 eval:   7%|▋         | 13/175 [00:18<03:11,  1.18s/it, ms_per_img=1.773, samples=416]
Resolution 128 eval:   7%|▋         | 13/175 [00:19<03:11,  1.18s/it, ms_per_img=1.773, samples=448]
Resolution 128 eval:   8%|▊         | 14/175 [00:19<03:01,  1.13s/it, ms_per_img=1.773, samples=448]
Resolution 128 eval:   8%|▊         | 14/175 [00:19<03:01,  1.13s/it, ms_per_img=1.773, samples=480]
Resolution 128 eval:   9%|▊         | 15/175 [00:19<02:30,  1.06it/s, ms_per_img=1.773, samples=480]
Resolution 128 eval:   9%|▊         | 15/175 [00:20<02:30,  1.06it/s, ms_per_img=1.773, samples=512]
Resolution 128 eval:   9%|▉         | 16/175 [00:20<02:19,  1.14it/s, ms_per_img=1.773, samples=512]
Resolution 128 eval:   9%|▉         | 16/175 [00:22<02:19,  1.14it/s, ms_per_img=1.773, samples=544]
Resolution 128 eval:  10%|▉         | 17/175 [00:22<02:48,  1.07s/it, ms_per_img=1.773, samples=544]
Resolution 128 eval:  10%|▉         | 17/175 [00:22<02:48,  1.07s/it, ms_per_img=1.772, samples=576]
Resolution 128 eval:  10%|█         | 18/175 [00:22<02:30,  1.04it/s, ms_per_img=1.772, samples=576]
Resolution 128 eval:  10%|█         | 18/175 [00:23<02:30,  1.04it/s, ms_per_img=1.774, samples=608]
Resolution 128 eval:  11%|█         | 19/175 [00:23<02:24,  1.08it/s, ms_per_img=1.774, samples=608]
Resolution 128 eval:  11%|█         | 19/175 [00:24<02:24,  1.08it/s, ms_per_img=1.773, samples=640]
Resolution 128 eval:  11%|█▏        | 20/175 [00:24<02:25,  1.07it/s, ms_per_img=1.773, samples=640]
Resolution 128 eval:  11%|█▏        | 20/175 [00:25<02:25,  1.07it/s, ms_per_img=1.773, samples=672]
Resolution 128 eval:  11%|█▏        | 20/175 [00:26<02:25,  1.07it/s, ms_per_img=1.774, samples=704]
Resolution 128 eval:  13%|█▎        | 22/175 [00:26<02:11,  1.17it/s, ms_per_img=1.774, samples=704]
Resolution 128 eval:  13%|█▎        | 22/175 [00:27<02:11,  1.17it/s, ms_per_img=1.771, samples=736]
Resolution 128 eval:  13%|█▎        | 23/175 [00:27<02:37,  1.04s/it, ms_per_img=1.771, samples=736]
Resolution 128 eval:  13%|█▎        | 23/175 [00:29<02:37,  1.04s/it, ms_per_img=1.772, samples=768]
Resolution 128 eval:  14%|█▎        | 24/175 [00:29<02:46,  1.10s/it, ms_per_img=1.772, samples=768]
Resolution 128 eval:  14%|█▎        | 24/175 [00:31<02:46,  1.10s/it, ms_per_img=1.776, samples=800]
Resolution 128 eval:  14%|█▍        | 25/175 [00:31<03:26,  1.38s/it, ms_per_img=1.776, samples=800]
Resolution 128 eval:  14%|█▍        | 25/175 [00:32<03:26,  1.38s/it, ms_per_img=1.771, samples=832]
Resolution 128 eval:  15%|█▍        | 26/175 [00:32<03:01,  1.22s/it, ms_per_img=1.771, samples=832]
Resolution 128 eval:  15%|█▍        | 26/175 [00:32<03:01,  1.22s/it, ms_per_img=1.772, samples=864]
Resolution 128 eval:  15%|█▌        | 27/175 [00:32<02:48,  1.14s/it, ms_per_img=1.772, samples=864]
Resolution 128 eval:  15%|█▌        | 27/175 [00:33<02:48,  1.14s/it, ms_per_img=1.773, samples=896]
Resolution 128 eval:  16%|█▌        | 28/175 [00:33<02:26,  1.00it/s, ms_per_img=1.773, samples=896]
Resolution 128 eval:  16%|█▌        | 28/175 [00:34<02:26,  1.00it/s, ms_per_img=1.773, samples=928]
Resolution 128 eval:  17%|█▋        | 29/175 [00:34<02:12,  1.10it/s, ms_per_img=1.773, samples=928]
Resolution 128 eval:  17%|█▋        | 29/175 [00:35<02:12,  1.10it/s, ms_per_img=1.773, samples=960]
Resolution 128 eval:  17%|█▋        | 30/175 [00:35<02:16,  1.06it/s, ms_per_img=1.773, samples=960]
Resolution 128 eval:  17%|█▋        | 30/175 [00:36<02:16,  1.06it/s, ms_per_img=1.771, samples=992]
Resolution 128 eval:  18%|█▊        | 31/175 [00:36<02:12,  1.08it/s, ms_per_img=1.771, samples=992]
Resolution 128 eval:  18%|█▊        | 31/175 [00:37<02:12,  1.08it/s, ms_per_img=1.772, samples=1,024]
Resolution 128 eval:  18%|█▊        | 32/175 [00:37<02:37,  1.10s/it, ms_per_img=1.772, samples=1,024]
Resolution 128 eval:  18%|█▊        | 32/175 [00:38<02:37,  1.10s/it, ms_per_img=1.771, samples=1,056]
Resolution 128 eval:  19%|█▉        | 33/175 [00:38<02:27,  1.04s/it, ms_per_img=1.771, samples=1,056]
Resolution 128 eval:  19%|█▉        | 33/175 [00:39<02:27,  1.04s/it, ms_per_img=1.773, samples=1,088]
Resolution 128 eval:  19%|█▉        | 34/175 [00:39<02:18,  1.02it/s, ms_per_img=1.773, samples=1,088]
Resolution 128 eval:  19%|█▉        | 34/175 [00:41<02:18,  1.02it/s, ms_per_img=1.774, samples=1,120]
Resolution 128 eval:  20%|██        | 35/175 [00:41<02:51,  1.23s/it, ms_per_img=1.774, samples=1,120]
Resolution 128 eval:  20%|██        | 35/175 [00:42<02:51,  1.23s/it, ms_per_img=1.771, samples=1,152]
Resolution 128 eval:  21%|██        | 36/175 [00:42<02:47,  1.20s/it, ms_per_img=1.771, samples=1,152]
Resolution 128 eval:  21%|██        | 36/175 [00:43<02:47,  1.20s/it, ms_per_img=1.773, samples=1,184]
Resolution 128 eval:  21%|██        | 37/175 [00:43<02:25,  1.06s/it, ms_per_img=1.773, samples=1,184]
Resolution 128 eval:  21%|██        | 37/175 [00:43<02:25,  1.06s/it, ms_per_img=1.774, samples=1,216]
Resolution 128 eval:  22%|██▏       | 38/175 [00:43<02:02,  1.12it/s, ms_per_img=1.774, samples=1,216]
Resolution 128 eval:  22%|██▏       | 38/175 [00:44<02:02,  1.12it/s, ms_per_img=1.773, samples=1,248]
Resolution 128 eval:  22%|██▏       | 39/175 [00:44<02:04,  1.10it/s, ms_per_img=1.773, samples=1,248]
Resolution 128 eval:  22%|██▏       | 39/175 [00:45<02:04,  1.10it/s, ms_per_img=1.773, samples=1,280]
Resolution 128 eval:  23%|██▎       | 40/175 [00:45<01:48,  1.24it/s, ms_per_img=1.773, samples=1,280]
Resolution 128 eval:  23%|██▎       | 40/175 [00:46<01:48,  1.24it/s, ms_per_img=1.773, samples=1,312]
Resolution 128 eval:  23%|██▎       | 41/175 [00:46<01:55,  1.16it/s, ms_per_img=1.773, samples=1,312]
Resolution 128 eval:  23%|██▎       | 41/175 [00:47<01:55,  1.16it/s, ms_per_img=1.772, samples=1,344]
Resolution 128 eval:  24%|██▍       | 42/175 [00:47<02:20,  1.06s/it, ms_per_img=1.772, samples=1,344]
Resolution 128 eval:  24%|██▍       | 42/175 [00:48<02:20,  1.06s/it, ms_per_img=1.772, samples=1,376]
Resolution 128 eval:  25%|██▍       | 43/175 [00:48<02:15,  1.03s/it, ms_per_img=1.772, samples=1,376]
Resolution 128 eval:  25%|██▍       | 43/175 [00:49<02:15,  1.03s/it, ms_per_img=1.774, samples=1,408]
Resolution 128 eval:  25%|██▌       | 44/175 [00:49<02:19,  1.07s/it, ms_per_img=1.774, samples=1,408]
Resolution 128 eval:  25%|██▌       | 44/175 [00:50<02:19,  1.07s/it, ms_per_img=1.773, samples=1,440]
Resolution 128 eval:  26%|██▌       | 45/175 [00:50<01:59,  1.08it/s, ms_per_img=1.773, samples=1,440]
Resolution 128 eval:  26%|██▌       | 45/175 [00:50<01:59,  1.08it/s, ms_per_img=1.773, samples=1,472]
Resolution 128 eval:  26%|██▋       | 46/175 [00:50<01:43,  1.24it/s, ms_per_img=1.773, samples=1,472]
Resolution 128 eval:  26%|██▋       | 46/175 [00:51<01:43,  1.24it/s, ms_per_img=1.772, samples=1,504]
Resolution 128 eval:  27%|██▋       | 47/175 [00:51<01:40,  1.28it/s, ms_per_img=1.772, samples=1,504]
Resolution 128 eval:  27%|██▋       | 47/175 [00:52<01:40,  1.28it/s, ms_per_img=1.774, samples=1,536]
Resolution 128 eval:  27%|██▋       | 47/175 [00:53<01:40,  1.28it/s, ms_per_img=1.771, samples=1,568]
Resolution 128 eval:  28%|██▊       | 49/175 [00:53<01:36,  1.30it/s, ms_per_img=1.771, samples=1,568]
Resolution 128 eval:  28%|██▊       | 49/175 [00:54<01:36,  1.30it/s, ms_per_img=1.774, samples=1,600]
Resolution 128 eval:  29%|██▊       | 50/175 [00:54<01:44,  1.20it/s, ms_per_img=1.774, samples=1,600]
Resolution 128 eval:  29%|██▊       | 50/175 [00:55<01:44,  1.20it/s, ms_per_img=1.773, samples=1,632]
Resolution 128 eval:  29%|██▉       | 51/175 [00:55<01:58,  1.04it/s, ms_per_img=1.773, samples=1,632]
Resolution 128 eval:  29%|██▉       | 51/175 [00:57<01:58,  1.04it/s, ms_per_img=1.772, samples=1,664]
Resolution 128 eval:  30%|██▉       | 52/175 [00:57<02:33,  1.25s/it, ms_per_img=1.772, samples=1,664]
Resolution 128 eval:  30%|██▉       | 52/175 [00:58<02:33,  1.25s/it, ms_per_img=1.771, samples=1,696]
Resolution 128 eval:  30%|███       | 53/175 [00:58<02:11,  1.08s/it, ms_per_img=1.771, samples=1,696]
Resolution 128 eval:  30%|███       | 53/175 [00:59<02:11,  1.08s/it, ms_per_img=1.773, samples=1,728]
Resolution 128 eval:  31%|███       | 54/175 [00:59<02:20,  1.16s/it, ms_per_img=1.773, samples=1,728]
Resolution 128 eval:  31%|███       | 54/175 [01:01<02:20,  1.16s/it, ms_per_img=1.771, samples=1,760]
Resolution 128 eval:  31%|███▏      | 55/175 [01:01<02:31,  1.26s/it, ms_per_img=1.771, samples=1,760]
Resolution 128 eval:  31%|███▏      | 55/175 [01:01<02:31,  1.26s/it, ms_per_img=1.774, samples=1,792]
Resolution 128 eval:  32%|███▏      | 56/175 [01:01<02:08,  1.08s/it, ms_per_img=1.774, samples=1,792]
Resolution 128 eval:  32%|███▏      | 56/175 [01:02<02:08,  1.08s/it, ms_per_img=1.773, samples=1,824]
Resolution 128 eval:  33%|███▎      | 57/175 [01:02<01:54,  1.03it/s, ms_per_img=1.773, samples=1,824]
Resolution 128 eval:  33%|███▎      | 57/175 [01:02<01:54,  1.03it/s, ms_per_img=1.773, samples=1,856]
Resolution 128 eval:  33%|███▎      | 57/175 [01:03<01:54,  1.03it/s, ms_per_img=1.773, samples=1,888]
Resolution 128 eval:  34%|███▎      | 59/175 [01:03<01:34,  1.23it/s, ms_per_img=1.773, samples=1,888]
Resolution 128 eval:  34%|███▎      | 59/175 [01:04<01:34,  1.23it/s, ms_per_img=1.772, samples=1,920]
Resolution 128 eval:  34%|███▍      | 60/175 [01:04<01:47,  1.07it/s, ms_per_img=1.772, samples=1,920]
Resolution 128 eval:  34%|███▍      | 60/175 [01:05<01:47,  1.07it/s, ms_per_img=1.774, samples=1,952]
Resolution 128 eval:  35%|███▍      | 61/175 [01:05<01:44,  1.09it/s, ms_per_img=1.774, samples=1,952]
Resolution 128 eval:  35%|███▍      | 61/175 [01:06<01:44,  1.09it/s, ms_per_img=1.773, samples=1,984]
Resolution 128 eval:  35%|███▌      | 62/175 [01:06<01:30,  1.24it/s, ms_per_img=1.773, samples=1,984]
Resolution 128 eval:  35%|███▌      | 62/175 [01:07<01:30,  1.24it/s, ms_per_img=1.771, samples=2,016]
Resolution 128 eval:  36%|███▌      | 63/175 [01:07<01:33,  1.19it/s, ms_per_img=1.771, samples=2,016]
Resolution 128 eval:  36%|███▌      | 63/175 [01:09<01:33,  1.19it/s, ms_per_img=1.772, samples=2,048]
Resolution 128 eval:  37%|███▋      | 64/175 [01:09<02:08,  1.16s/it, ms_per_img=1.772, samples=2,048]
Resolution 128 eval:  37%|███▋      | 64/175 [01:10<02:08,  1.16s/it, ms_per_img=1.774, samples=2,080]
Resolution 128 eval:  37%|███▋      | 65/175 [01:10<02:15,  1.23s/it, ms_per_img=1.774, samples=2,080]
Resolution 128 eval:  37%|███▋      | 65/175 [01:12<02:15,  1.23s/it, ms_per_img=1.773, samples=2,112]
Resolution 128 eval:  38%|███▊      | 66/175 [01:12<02:22,  1.31s/it, ms_per_img=1.773, samples=2,112]
Resolution 128 eval:  38%|███▊      | 66/175 [01:13<02:22,  1.31s/it, ms_per_img=1.771, samples=2,144]
Resolution 128 eval:  38%|███▊      | 67/175 [01:13<02:13,  1.23s/it, ms_per_img=1.771, samples=2,144]
Resolution 128 eval:  38%|███▊      | 67/175 [01:14<02:13,  1.23s/it, ms_per_img=1.774, samples=2,176]
Resolution 128 eval:  39%|███▉      | 68/175 [01:14<02:12,  1.24s/it, ms_per_img=1.774, samples=2,176]
Resolution 128 eval:  39%|███▉      | 68/175 [01:15<02:12,  1.24s/it, ms_per_img=1.774, samples=2,208]
Resolution 128 eval:  39%|███▉      | 69/175 [01:15<02:16,  1.29s/it, ms_per_img=1.774, samples=2,208]
Resolution 128 eval:  39%|███▉      | 69/175 [01:17<02:16,  1.29s/it, ms_per_img=1.774, samples=2,240]
Resolution 128 eval:  40%|████      | 70/175 [01:17<02:13,  1.27s/it, ms_per_img=1.774, samples=2,240]
Resolution 128 eval:  40%|████      | 70/175 [01:17<02:13,  1.27s/it, ms_per_img=1.774, samples=2,272]
Resolution 128 eval:  41%|████      | 71/175 [01:17<01:56,  1.12s/it, ms_per_img=1.774, samples=2,272]
Resolution 128 eval:  41%|████      | 71/175 [01:18<01:56,  1.12s/it, ms_per_img=1.771, samples=2,304]
Resolution 128 eval:  41%|████      | 72/175 [01:18<01:44,  1.01s/it, ms_per_img=1.771, samples=2,304]
Resolution 128 eval:  41%|████      | 72/175 [01:19<01:44,  1.01s/it, ms_per_img=1.771, samples=2,336]
Resolution 128 eval:  42%|████▏     | 73/175 [01:19<01:38,  1.03it/s, ms_per_img=1.771, samples=2,336]
Resolution 128 eval:  42%|████▏     | 73/175 [01:20<01:38,  1.03it/s, ms_per_img=1.774, samples=2,368]
Resolution 128 eval:  42%|████▏     | 74/175 [01:20<01:37,  1.03it/s, ms_per_img=1.774, samples=2,368]
Resolution 128 eval:  42%|████▏     | 74/175 [01:21<01:37,  1.03it/s, ms_per_img=1.773, samples=2,400]
Resolution 128 eval:  43%|████▎     | 75/175 [01:21<01:41,  1.01s/it, ms_per_img=1.773, samples=2,400]
Resolution 128 eval:  43%|████▎     | 75/175 [01:22<01:41,  1.01s/it, ms_per_img=1.771, samples=2,432]
Resolution 128 eval:  43%|████▎     | 76/175 [01:22<01:48,  1.09s/it, ms_per_img=1.771, samples=2,432]
Resolution 128 eval:  43%|████▎     | 76/175 [01:23<01:48,  1.09s/it, ms_per_img=1.772, samples=2,464]
Resolution 128 eval:  44%|████▍     | 77/175 [01:23<01:47,  1.10s/it, ms_per_img=1.772, samples=2,464]
Resolution 128 eval:  44%|████▍     | 77/175 [01:25<01:47,  1.10s/it, ms_per_img=1.773, samples=2,496]
Resolution 128 eval:  45%|████▍     | 78/175 [01:25<01:50,  1.14s/it, ms_per_img=1.773, samples=2,496]
Resolution 128 eval:  45%|████▍     | 78/175 [01:26<01:50,  1.14s/it, ms_per_img=1.774, samples=2,528]
Resolution 128 eval:  45%|████▌     | 79/175 [01:26<01:47,  1.12s/it, ms_per_img=1.774, samples=2,528]
Resolution 128 eval:  45%|████▌     | 79/175 [01:27<01:47,  1.12s/it, ms_per_img=1.774, samples=2,560]
Resolution 128 eval:  46%|████▌     | 80/175 [01:27<01:57,  1.23s/it, ms_per_img=1.774, samples=2,560]
Resolution 128 eval:  46%|████▌     | 80/175 [01:28<01:57,  1.23s/it, ms_per_img=1.772, samples=2,592]
Resolution 128 eval:  46%|████▋     | 81/175 [01:28<01:45,  1.12s/it, ms_per_img=1.772, samples=2,592]
Resolution 128 eval:  46%|████▋     | 81/175 [01:29<01:45,  1.12s/it, ms_per_img=1.773, samples=2,624]
Resolution 128 eval:  47%|████▋     | 82/175 [01:29<01:40,  1.08s/it, ms_per_img=1.773, samples=2,624]
Resolution 128 eval:  47%|████▋     | 82/175 [01:30<01:40,  1.08s/it, ms_per_img=1.775, samples=2,656]
Resolution 128 eval:  47%|████▋     | 83/175 [01:30<01:48,  1.18s/it, ms_per_img=1.775, samples=2,656]
Resolution 128 eval:  47%|████▋     | 83/175 [01:32<01:48,  1.18s/it, ms_per_img=1.771, samples=2,688]
Resolution 128 eval:  48%|████▊     | 84/175 [01:32<01:59,  1.31s/it, ms_per_img=1.771, samples=2,688]
Resolution 128 eval:  48%|████▊     | 84/175 [01:33<01:59,  1.31s/it, ms_per_img=1.772, samples=2,720]
Resolution 128 eval:  49%|████▊     | 85/175 [01:33<01:57,  1.31s/it, ms_per_img=1.772, samples=2,720]
Resolution 128 eval:  49%|████▊     | 85/175 [01:34<01:57,  1.31s/it, ms_per_img=1.773, samples=2,752]
Resolution 128 eval:  49%|████▉     | 86/175 [01:34<01:48,  1.21s/it, ms_per_img=1.773, samples=2,752]
Resolution 128 eval:  49%|████▉     | 86/175 [01:35<01:48,  1.21s/it, ms_per_img=1.771, samples=2,784]
Resolution 128 eval:  50%|████▉     | 87/175 [01:35<01:38,  1.12s/it, ms_per_img=1.771, samples=2,784]
Resolution 128 eval:  50%|████▉     | 87/175 [01:36<01:38,  1.12s/it, ms_per_img=1.775, samples=2,816]
Resolution 128 eval:  50%|█████     | 88/175 [01:36<01:24,  1.03it/s, ms_per_img=1.775, samples=2,816]
Resolution 128 eval:  50%|█████     | 88/175 [01:37<01:24,  1.03it/s, ms_per_img=1.772, samples=2,848]
Resolution 128 eval:  51%|█████     | 89/175 [01:37<01:24,  1.02it/s, ms_per_img=1.772, samples=2,848]
Resolution 128 eval:  51%|█████     | 89/175 [01:37<01:24,  1.02it/s, ms_per_img=1.773, samples=2,880]
Resolution 128 eval:  51%|█████▏    | 90/175 [01:37<01:11,  1.20it/s, ms_per_img=1.773, samples=2,880]
Resolution 128 eval:  51%|█████▏    | 90/175 [01:38<01:11,  1.20it/s, ms_per_img=1.774, samples=2,912]
Resolution 128 eval:  52%|█████▏    | 91/175 [01:38<01:06,  1.26it/s, ms_per_img=1.774, samples=2,912]
Resolution 128 eval:  52%|█████▏    | 91/175 [01:39<01:06,  1.26it/s, ms_per_img=1.772, samples=2,944]
Resolution 128 eval:  53%|█████▎    | 92/175 [01:39<01:04,  1.28it/s, ms_per_img=1.772, samples=2,944]
Resolution 128 eval:  53%|█████▎    | 92/175 [01:39<01:04,  1.28it/s, ms_per_img=1.773, samples=2,976]
Resolution 128 eval:  53%|█████▎    | 93/175 [01:39<00:57,  1.42it/s, ms_per_img=1.773, samples=2,976]
Resolution 128 eval:  53%|█████▎    | 93/175 [01:40<00:57,  1.42it/s, ms_per_img=1.772, samples=3,008]
Resolution 128 eval:  54%|█████▎    | 94/175 [01:40<00:57,  1.42it/s, ms_per_img=1.772, samples=3,008]
Resolution 128 eval:  54%|█████▎    | 94/175 [01:41<00:57,  1.42it/s, ms_per_img=1.772, samples=3,040]
Resolution 128 eval:  54%|█████▍    | 95/175 [01:41<00:58,  1.37it/s, ms_per_img=1.772, samples=3,040]
Resolution 128 eval:  54%|█████▍    | 95/175 [01:42<00:58,  1.37it/s, ms_per_img=1.772, samples=3,072]
Resolution 128 eval:  55%|█████▍    | 96/175 [01:42<01:07,  1.17it/s, ms_per_img=1.772, samples=3,072]
Resolution 128 eval:  55%|█████▍    | 96/175 [01:43<01:07,  1.17it/s, ms_per_img=1.772, samples=3,104]
Resolution 128 eval:  55%|█████▌    | 97/175 [01:43<01:16,  1.02it/s, ms_per_img=1.772, samples=3,104]
Resolution 128 eval:  55%|█████▌    | 97/175 [01:44<01:16,  1.02it/s, ms_per_img=1.773, samples=3,136]
Resolution 128 eval:  56%|█████▌    | 98/175 [01:44<01:08,  1.12it/s, ms_per_img=1.773, samples=3,136]
Resolution 128 eval:  56%|█████▌    | 98/175 [01:45<01:08,  1.12it/s, ms_per_img=1.771, samples=3,168]
Resolution 128 eval:  57%|█████▋    | 99/175 [01:45<01:10,  1.08it/s, ms_per_img=1.771, samples=3,168]

Acc=0.3005 AUC=0.5473 Fast=100.00% Medium=0.00% Full=0.00%

Resolution sweep:  25%|██▌       | 1/4 [02:35<07:46, 155.34s/it]

Source Res=128 Single: 5.912 ms/img | 169.2 FPS
Source Res=128 Batch=32: 1.769 ms/img | 565.4 FPS

Resolution 224

Resolution 224 eval:   0%|          | 0/175 [00:00<?, ?it/s]
Resolution 224 eval:   0%|          | 0/175 [00:00<?, ?it/s, ms_per_img=1.777, samples=32]
Resolution 224 eval:   0%|          | 0/175 [00:00<?, ?it/s, ms_per_img=1.776, samples=64]
Resolution 224 eval:   1%|          | 2/175 [00:00<00:48,  3.56it/s, ms_per_img=1.776, samples=64]
Resolution 224 eval:   1%|          | 2/175 [00:01<00:48,  3.56it/s, ms_per_img=1.776, samples=96]
Resolution 224 eval:   1%|          | 2/175 [00:01<00:48,  3.56it/s, ms_per_img=1.776, samples=128]
Resolution 224 eval:   2%|▏         | 4/175 [00:01<01:06,  2.56it/s, ms_per_img=1.776, samples=128]
Resolution 224 eval:   2%|▏         | 4/175 [00:01<01:06,  2.56it/s, ms_per_img=1.775, samples=160]
Resolution 224 eval:   2%|▏         | 4/175 [00:02<01:06,  2.56it/s, ms_per_img=1.774, samples=192]
Resolution 224 eval:   3%|▎         | 6/175 [00:02<01:01,  2.77it/s, ms_per_img=1.774, samples=192]
Resolution 224 eval:   3%|▎         | 6/175 [00:02<01:01,  2.77it/s, ms_per_img=1.774, samples=224]
Resolution 224 eval:   3%|▎         | 6/175 [00:02<01:01,  2.77it/s, ms_per_img=1.775, samples=256]
Resolution 224 eval:   3%|▎         | 6/175 [00:02<01:01,  2.77it/s, ms_per_img=1.774, samples=288]
Resolution 224 eval:   5%|▌         | 9/175 [00:02<00:50,  3.27it/s, ms_per_img=1.774, samples=288]
Resolution 224 eval:   5%|▌         | 9/175 [00:03<00:50,  3.27it/s, ms_per_img=1.775, samples=320]
Resolution 224 eval:   5%|▌         | 9/175 [00:03<00:50,  3.27it/s, ms_per_img=1.774, samples=352]
Resolution 224 eval:   6%|▋         | 11/175 [00:03<00:59,  2.76it/s, ms_per_img=1.774, samples=352]
Resolution 224 eval:   6%|▋         | 11/175 [00:04<00:59,  2.76it/s, ms_per_img=1.777, samples=384]
Resolution 224 eval:   6%|▋         | 11/175 [00:04<00:59,  2.76it/s, ms_per_img=1.773, samples=416]
Resolution 224 eval:   7%|▋         | 13/175 [00:04<00:53,  3.04it/s, ms_per_img=1.773, samples=416]
Resolution 224 eval:   7%|▋         | 13/175 [00:04<00:53,  3.04it/s, ms_per_img=1.778, samples=448]
Resolution 224 eval:   7%|▋         | 13/175 [00:04<00:53,  3.04it/s, ms_per_img=1.775, samples=480]
Resolution 224 eval:   7%|▋         | 13/175 [00:05<00:53,  3.04it/s, ms_per_img=1.777, samples=512]
Resolution 224 eval:   9%|▉         | 16/175 [00:05<00:46,  3.41it/s, ms_per_img=1.777, samples=512]
Resolution 224 eval:   9%|▉         | 16/175 [00:05<00:46,  3.41it/s, ms_per_img=1.775, samples=544]
Resolution 224 eval:   9%|▉         | 16/175 [00:05<00:46,  3.41it/s, ms_per_img=1.774, samples=576]
Resolution 224 eval:  10%|█         | 18/175 [00:05<00:46,  3.41it/s, ms_per_img=1.774, samples=576]
Resolution 224 eval:  10%|█         | 18/175 [00:05<00:46,  3.41it/s, ms_per_img=1.774, samples=608]
Resolution 224 eval:  10%|█         | 18/175 [00:06<00:46,  3.41it/s, ms_per_img=1.775, samples=640]
Resolution 224 eval:  11%|█▏        | 20/175 [00:06<00:45,  3.40it/s, ms_per_img=1.775, samples=640]
Resolution 224 eval:  11%|█▏        | 20/175 [00:06<00:45,  3.40it/s, ms_per_img=1.773, samples=672]
Resolution 224 eval:  11%|█▏        | 20/175 [00:06<00:45,  3.40it/s, ms_per_img=1.776, samples=704]
Resolution 224 eval:  13%|█▎        | 22/175 [00:06<00:46,  3.31it/s, ms_per_img=1.776, samples=704]
Resolution 224 eval:  13%|█▎        | 22/175 [00:07<00:46,  3.31it/s, ms_per_img=1.776, samples=736]
Resolution 224 eval:  13%|█▎        | 22/175 [00:07<00:46,  3.31it/s, ms_per_img=1.773, samples=768]
Resolution 224 eval:  14%|█▎        | 24/175 [00:07<00:46,  3.25it/s, ms_per_img=1.773, samples=768]
Resolution 224 eval:  14%|█▎        | 24/175 [00:07<00:46,  3.25it/s, ms_per_img=1.776, samples=800]
Resolution 224 eval:  14%|█▎        | 24/175 [00:08<00:46,  3.25it/s, ms_per_img=1.775, samples=832]
Resolution 224 eval:  15%|█▍        | 26/175 [00:08<00:44,  3.34it/s, ms_per_img=1.775, samples=832]
Resolution 224 eval:  15%|█▍        | 26/175 [00:08<00:44,  3.34it/s, ms_per_img=1.773, samples=864]
Resolution 224 eval:  15%|█▍        | 26/175 [00:08<00:44,  3.34it/s, ms_per_img=1.774, samples=896]
Resolution 224 eval:  16%|█▌        | 28/175 [00:08<00:45,  3.21it/s, ms_per_img=1.774, samples=896]
Resolution 224 eval:  16%|█▌        | 28/175 [00:09<00:45,  3.21it/s, ms_per_img=1.773, samples=928]
Resolution 224 eval:  16%|█▌        | 28/175 [00:09<00:45,  3.21it/s, ms_per_img=1.775, samples=960]
Resolution 224 eval:  17%|█▋        | 30/175 [00:09<00:46,  3.10it/s, ms_per_img=1.775, samples=960]
Resolution 224 eval:  17%|█▋        | 30/175 [00:09<00:46,  3.10it/s, ms_per_img=1.776, samples=992]
Resolution 224 eval:  17%|█▋        | 30/175 [00:10<00:46,  3.10it/s, ms_per_img=1.773, samples=1,024]
Resolution 224 eval:  18%|█▊        | 32/175 [00:10<00:46,  3.09it/s, ms_per_img=1.773, samples=1,024]
Resolution 224 eval:  18%|█▊        | 32/175 [00:10<00:46,  3.09it/s, ms_per_img=1.776, samples=1,056]
Resolution 224 eval:  18%|█▊        | 32/175 [00:10<00:46,  3.09it/s, ms_per_img=1.776, samples=1,088]
Resolution 224 eval:  19%|█▉        | 34/175 [00:10<00:48,  2.93it/s, ms_per_img=1.776, samples=1,088]
Resolution 224 eval:  19%|█▉        | 34/175 [00:11<00:48,  2.93it/s, ms_per_img=1.773, samples=1,120]
Resolution 224 eval:  19%|█▉        | 34/175 [00:11<00:48,  2.93it/s, ms_per_img=1.775, samples=1,152]
Resolution 224 eval:  21%|██        | 36/175 [00:11<00:55,  2.52it/s, ms_per_img=1.775, samples=1,152]
Resolution 224 eval:  21%|██        | 36/175 [00:12<00:55,  2.52it/s, ms_per_img=1.774, samples=1,184]
Resolution 224 eval:  21%|██        | 36/175 [00:12<00:55,  2.52it/s, ms_per_img=1.775, samples=1,216]
Resolution 224 eval:  21%|██        | 36/175 [00:12<00:55,  2.52it/s, ms_per_img=1.775, samples=1,248]
Resolution 224 eval:  22%|██▏       | 39/175 [00:12<00:45,  2.97it/s, ms_per_img=1.775, samples=1,248]
Resolution 224 eval:  22%|██▏       | 39/175 [00:12<00:45,  2.97it/s, ms_per_img=1.776, samples=1,280]
Resolution 224 eval:  22%|██▏       | 39/175 [00:13<00:45,  2.97it/s, ms_per_img=1.774, samples=1,312]
Resolution 224 eval:  23%|██▎       | 41/175 [00:13<00:43,  3.06it/s, ms_per_img=1.774, samples=1,312]
Resolution 224 eval:  23%|██▎       | 41/175 [00:13<00:43,  3.06it/s, ms_per_img=1.774, samples=1,344]
Resolution 224 eval:  23%|██▎       | 41/175 [00:14<00:43,  3.06it/s, ms_per_img=1.773, samples=1,376]
Resolution 224 eval:  25%|██▍       | 43/175 [00:14<00:45,  2.88it/s, ms_per_img=1.773, samples=1,376]
Resolution 224 eval:  25%|██▍       | 43/175 [00:14<00:45,  2.88it/s, ms_per_img=1.777, samples=1,408]
Resolution 224 eval:  25%|██▍       | 43/175 [00:14<00:45,  2.88it/s, ms_per_img=1.776, samples=1,440]
Resolution 224 eval:  26%|██▌       | 45/175 [00:14<00:43,  2.99it/s, ms_per_img=1.776, samples=1,440]
Resolution 224 eval:  26%|██▌       | 45/175 [00:14<00:43,  2.99it/s, ms_per_img=1.775, samples=1,472]
Resolution 224 eval:  26%|██▌       | 45/175 [00:15<00:43,  2.99it/s, ms_per_img=1.775, samples=1,504]
Resolution 224 eval:  27%|██▋       | 47/175 [00:15<00:41,  3.09it/s, ms_per_img=1.775, samples=1,504]
Resolution 224 eval:  27%|██▋       | 47/175 [00:15<00:41,  3.09it/s, ms_per_img=1.777, samples=1,536]
Resolution 224 eval:  27%|██▋       | 47/175 [00:15<00:41,  3.09it/s, ms_per_img=1.776, samples=1,568]
Resolution 224 eval:  28%|██▊       | 49/175 [00:15<00:39,  3.22it/s, ms_per_img=1.776, samples=1,568]
Resolution 224 eval:  28%|██▊       | 49/175 [00:16<00:39,  3.22it/s, ms_per_img=1.775, samples=1,600]
Resolution 224 eval:  28%|██▊       | 49/175 [00:16<00:39,  3.22it/s, ms_per_img=1.774, samples=1,632]
Resolution 224 eval:  29%|██▉       | 51/175 [00:16<00:37,  3.32it/s, ms_per_img=1.774, samples=1,632]
Resolution 224 eval:  29%|██▉       | 51/175 [00:16<00:37,  3.32it/s, ms_per_img=1.775, samples=1,664]
Resolution 224 eval:  29%|██▉       | 51/175 [00:17<00:37,  3.32it/s, ms_per_img=1.776, samples=1,696]
Resolution 224 eval:  30%|███       | 53/175 [00:17<00:38,  3.14it/s, ms_per_img=1.776, samples=1,696]
Resolution 224 eval:  30%|███       | 53/175 [00:17<00:38,  3.14it/s, ms_per_img=1.774, samples=1,728]
Resolution 224 eval:  30%|███       | 53/175 [00:17<00:38,  3.14it/s, ms_per_img=1.774, samples=1,760]
Resolution 224 eval:  31%|███▏      | 55/175 [00:17<00:38,  3.14it/s, ms_per_img=1.774, samples=1,760]
Resolution 224 eval:  31%|███▏      | 55/175 [00:18<00:38,  3.14it/s, ms_per_img=1.774, samples=1,792]
Resolution 224 eval:  31%|███▏      | 55/175 [00:18<00:38,  3.14it/s, ms_per_img=1.775, samples=1,824]
Resolution 224 eval:  33%|███▎      | 57/175 [00:18<00:36,  3.24it/s, ms_per_img=1.775, samples=1,824]
Resolution 224 eval:  33%|███▎      | 57/175 [00:18<00:36,  3.24it/s, ms_per_img=1.774, samples=1,856]
Resolution 224 eval:  33%|███▎      | 57/175 [00:18<00:36,  3.24it/s, ms_per_img=1.773, samples=1,888]
Resolution 224 eval:  34%|███▎      | 59/175 [00:18<00:35,  3.25it/s, ms_per_img=1.773, samples=1,888]
Resolution 224 eval:  34%|███▎      | 59/175 [00:19<00:35,  3.25it/s, ms_per_img=1.775, samples=1,920]
Resolution 224 eval:  34%|███▎      | 59/175 [00:19<00:35,  3.25it/s, ms_per_img=1.776, samples=1,952]
Resolution 224 eval:  35%|███▍      | 61/175 [00:19<00:34,  3.30it/s, ms_per_img=1.776, samples=1,952]
Resolution 224 eval:  35%|███▍      | 61/175 [00:19<00:34,  3.30it/s, ms_per_img=1.776, samples=1,984]
Resolution 224 eval:  35%|███▍      | 61/175 [00:20<00:34,  3.30it/s, ms_per_img=1.773, samples=2,016]
Resolution 224 eval:  36%|███▌      | 63/175 [00:20<00:33,  3.37it/s, ms_per_img=1.773, samples=2,016]
Resolution 224 eval:  36%|███▌      | 63/175 [00:20<00:33,  3.37it/s, ms_per_img=1.774, samples=2,048]
Resolution 224 eval:  36%|███▌      | 63/175 [00:20<00:33,  3.37it/s, ms_per_img=1.773, samples=2,080]
Resolution 224 eval:  37%|███▋      | 65/175 [00:20<00:34,  3.18it/s, ms_per_img=1.773, samples=2,080]
Resolution 224 eval:  37%|███▋      | 65/175 [00:21<00:34,  3.18it/s, ms_per_img=1.776, samples=2,112]
Resolution 224 eval:  37%|███▋      | 65/175 [00:21<00:34,  3.18it/s, ms_per_img=1.775, samples=2,144]
Resolution 224 eval:  38%|███▊      | 67/175 [00:21<00:35,  3.01it/s, ms_per_img=1.775, samples=2,144]
Resolution 224 eval:  38%|███▊      | 67/175 [00:21<00:35,  3.01it/s, ms_per_img=1.775, samples=2,176]
Resolution 224 eval:  38%|███▊      | 67/175 [00:22<00:35,  3.01it/s, ms_per_img=1.776, samples=2,208]
Resolution 224 eval:  39%|███▉      | 69/175 [00:22<00:33,  3.14it/s, ms_per_img=1.776, samples=2,208]
Resolution 224 eval:  39%|███▉      | 69/175 [00:22<00:33,  3.14it/s, ms_per_img=1.773, samples=2,240]
Resolution 224 eval:  39%|███▉      | 69/175 [00:22<00:33,  3.14it/s, ms_per_img=1.776, samples=2,272]
Resolution 224 eval:  41%|████      | 71/175 [00:22<00:35,  2.89it/s, ms_per_img=1.776, samples=2,272]
Resolution 224 eval:  41%|████      | 71/175 [00:23<00:35,  2.89it/s, ms_per_img=1.774, samples=2,304]
Resolution 224 eval:  41%|████      | 71/175 [00:23<00:35,  2.89it/s, ms_per_img=1.774, samples=2,336]
Resolution 224 eval:  42%|████▏     | 73/175 [00:23<00:33,  3.01it/s, ms_per_img=1.774, samples=2,336]
Resolution 224 eval:  42%|████▏     | 73/175 [00:23<00:33,  3.01it/s, ms_per_img=1.774, samples=2,368]
Resolution 224 eval:  42%|████▏     | 73/175 [00:24<00:33,  3.01it/s, ms_per_img=1.775, samples=2,400]
Resolution 224 eval:  43%|████▎     | 75/175 [00:24<00:31,  3.13it/s, ms_per_img=1.775, samples=2,400]
Resolution 224 eval:  43%|████▎     | 75/175 [00:24<00:31,  3.13it/s, ms_per_img=1.774, samples=2,432]
Resolution 224 eval:  43%|████▎     | 75/175 [00:24<00:31,  3.13it/s, ms_per_img=1.773, samples=2,464]
Resolution 224 eval:  44%|████▍     | 77/175 [00:24<00:31,  3.14it/s, ms_per_img=1.773, samples=2,464]
Resolution 224 eval:  44%|████▍     | 77/175 [00:25<00:31,  3.14it/s, ms_per_img=1.773, samples=2,496]
Resolution 224 eval:  44%|████▍     | 77/175 [00:25<00:31,  3.14it/s, ms_per_img=1.775, samples=2,528]
Resolution 224 eval:  45%|████▌     | 79/175 [00:25<00:33,  2.84it/s, ms_per_img=1.775, samples=2,528]
Resolution 224 eval:  45%|████▌     | 79/175 [00:25<00:33,  2.84it/s, ms_per_img=1.773, samples=2,560]
Resolution 224 eval:  45%|████▌     | 79/175 [00:26<00:33,  2.84it/s, ms_per_img=1.776, samples=2,592]
Resolution 224 eval:  46%|████▋     | 81/175 [00:26<00:32,  2.90it/s, ms_per_img=1.776, samples=2,592]
Resolution 224 eval:  46%|████▋     | 81/175 [00:26<00:32,  2.90it/s, ms_per_img=1.775, samples=2,624]
Resolution 224 eval:  46%|████▋     | 81/175 [00:27<00:32,  2.90it/s, ms_per_img=1.774, samples=2,656]
Resolution 224 eval:  47%|████▋     | 83/175 [00:27<00:32,  2.85it/s, ms_per_img=1.774, samples=2,656]
Resolution 224 eval:  47%|████▋     | 83/175 [00:27<00:32,  2.85it/s, ms_per_img=1.772, samples=2,688]
Resolution 224 eval:  47%|████▋     | 83/175 [00:27<00:32,  2.85it/s, ms_per_img=1.774, samples=2,720]
Resolution 224 eval:  49%|████▊     | 85/175 [00:27<00:31,  2.85it/s, ms_per_img=1.774, samples=2,720]
Resolution 224 eval:  49%|████▊     | 85/175 [00:28<00:31,  2.85it/s, ms_per_img=1.772, samples=2,752]
Resolution 224 eval:  49%|████▊     | 85/175 [00:28<00:31,  2.85it/s, ms_per_img=1.774, samples=2,784]
Resolution 224 eval:  50%|████▉     | 87/175 [00:28<00:32,  2.75it/s, ms_per_img=1.774, samples=2,784]
Resolution 224 eval:  50%|████▉     | 87/175 [00:28<00:32,  2.75it/s, ms_per_img=1.777, samples=2,816]
Resolution 224 eval:  50%|████▉     | 87/175 [00:29<00:32,  2.75it/s, ms_per_img=1.775, samples=2,848]
Resolution 224 eval:  51%|█████     | 89/175 [00:29<00:31,  2.71it/s, ms_per_img=1.775, samples=2,848]
Resolution 224 eval:  51%|█████     | 89/175 [00:29<00:31,  2.71it/s, ms_per_img=1.774, samples=2,880]
Resolution 224 eval:  51%|█████     | 89/175 [00:29<00:31,  2.71it/s, ms_per_img=1.775, samples=2,912]
Resolution 224 eval:  52%|█████▏    | 91/175 [00:29<00:29,  2.86it/s, ms_per_img=1.775, samples=2,912]
Resolution 224 eval:  52%|█████▏    | 91/175 [00:30<00:29,  2.86it/s, ms_per_img=1.774, samples=2,944]
Resolution 224 eval:  52%|█████▏    | 91/175 [00:30<00:29,  2.86it/s, ms_per_img=1.775, samples=2,976]
Resolution 224 eval:  53%|█████▎    | 93/175 [00:30<00:27,  3.03it/s, ms_per_img=1.775, samples=2,976]
Resolution 224 eval:  53%|█████▎    | 93/175 [00:30<00:27,  3.03it/s, ms_per_img=1.775, samples=3,008]
Resolution 224 eval:  53%|█████▎    | 93/175 [00:30<00:27,  3.03it/s, ms_per_img=1.776, samples=3,040]
Resolution 224 eval:  53%|█████▎    | 93/175 [00:31<00:27,  3.03it/s, ms_per_img=1.773, samples=3,072]
Resolution 224 eval:  55%|█████▍    | 96/175 [00:31<00:23,  3.32it/s, ms_per_img=1.773, samples=3,072]
Resolution 224 eval:  55%|█████▍    | 96/175 [00:31<00:23,  3.32it/s, ms_per_img=1.772, samples=3,104]
Resolution 224 eval:  55%|█████▍    | 96/175 [00:31<00:23,  3.32it/s, ms_per_img=1.776, samples=3,136]
Resolution 224 eval:  56%|█████▌    | 98/175 [00:31<00:22,  3.39it/s, ms_per_img=1.776, samples=3,136]
Resolution 224 eval:  56%|█████▌    | 98/175 [00:32<00:22,  3.39it/s, ms_per_img=1.773, samples=3,168]
Resolution 224 eval:  56%|█████▌    | 98/175 [00:32<00:22,  3.39it/s, ms_per_img=1.774, samples=3,200]
Resolution 224 eval:  57%|█████▋    | 100/175 [00:32<00:23,  3.26it/s, ms_per_img=1.774, samples=3,200]
Resolution 224 eval:  57%|█████▋    | 100/175 [00:32<00:23,  3.26it/s, ms_per_img=1.776, samples=3,232]
Resolution 224 eval:  57%|█████▋    | 100/175 [00:33<00:23,  3.26it/s, ms_per_img=1.773, samples=3,264]
Resolution 224 eval:  58%|█████▊    | 102/175 [00:33<00:23,  3.11it/s, ms_per_img=1.773, samples=3,264]
Resolution 224 eval:  58%|█████▊    | 102/175 [00:33<00:23,  3.11it/s, ms_per_img=1.775, samples=3,296]
Resolution 224 eval:  58%|█████▊    | 102/175 [00:33<00:23,  3.11it/s, ms_per_img=1.775, samples=3,328]
Resolution 224 eval:  59%|█████▉    | 104/175 [00:33<00:22,  3.12it/s, ms_per_img=1.775, samples=3,328]
Resolution 224 eval:  59%|█████▉    | 104/175 [00:34<00:22,  3.12it/s, ms_per_img=1.774, samples=3,360]
Resolution 224 eval:  59%|█████▉    | 104/175 [00:34<00:22,  3.12it/s, ms_per_img=1.774, samples=3,392]
Resolution 224 eval:  61%|██████    | 106/175 [00:34<00:21,  3.14it/s, ms_per_img=1.774, samples=3,392]
Resolution 224 eval:  61%|██████    | 106/175 [00:34<00:21,  3.14it/s, ms_per_img=1.772, samples=3,424]
Resolution 224 eval:  61%|██████    | 106/175 [00:34<00:21,  3.14it/s, ms_per_img=1.774, samples=3,456]
Resolution 224 eval:  61%|██████    | 106/175 [00:35<00:21,  3.14it/s, ms_per_img=1.774, samples=3,488]
Resolution 224 eval:  62%|██████▏   | 109/175 [00:35<00:18,  3.55it/s, ms_per_img=1.774, samples=3,488]
Resolution 224 eval:  62%|██████▏   | 109/175 [00:35<00:18,  3.55it/s, ms_per_img=1.776, samples=3,520]
Resolution 224 eval:  62%|██████▏   | 109/175 [00:35<00:18,  3.55it/s, ms_per_img=1.773, samples=3,552]
Resolution 224 eval:  63%|██████▎   | 111/175 [00:35<00:17,  3.66it/s, ms_per_img=1.773, samples=3,552]
Resolution 224 eval:  63%|██████▎   | 111/175 [00:35<00:17,  3.66it/s, ms_per_img=1.775, samples=3,584]
Resolution 224 eval:  63%|██████▎   | 111/175 [00:36<00:17,  3.66it/s, ms_per_img=1.776, samples=3,616]
Resolution 224 eval:  63%|██████▎   | 111/175 [00:36<00:17,  3.66it/s, ms_per_img=1.772, samples=3,648]
Resolution 224 eval:  65%|██████▌   | 114/175 [00:36<00:17,  3.54it/s, ms_per_img=1.772, samples=3,648]
Resolution 224 eval:  65%|██████▌   | 114/175 [00:36<00:17,  3.54it/s, ms_per_img=1.773, samples=3,680]
Resolution 224 eval:  65%|██████▌   | 114/175 [00:37<00:17,  3.54it/s, ms_per_img=1.774, samples=3,712]
Resolution 224 eval:  66%|██████▋   | 116/175 [00:37<00:17,  3.29it/s, ms_per_img=1.774, samples=3,712]
Resolution 224 eval:  66%|██████▋   | 116/175 [00:37<00:17,  3.29it/s, ms_per_img=1.773, samples=3,744]
Resolution 224 eval:  66%|██████▋   | 116/175 [00:37<00:17,  3.29it/s, ms_per_img=1.777, samples=3,776]
Resolution 224 eval:  67%|██████▋   | 118/175 [00:37<00:18,  3.16it/s, ms_per_img=1.777, samples=3,776]
Resolution 224 eval:  67%|██████▋   | 118/175 [00:38<00:18,  3.16it/s, ms_per_img=1.773, samples=3,808]
Resolution 224 eval:  67%|██████▋   | 118/175 [00:38<00:18,  3.16it/s, ms_per_img=1.778, samples=3,840]
Resolution 224 eval:  67%|██████▋   | 118/175 [00:38<00:18,  3.16it/s, ms_per_img=1.775, samples=3,872]
Resolution 224 eval:  69%|██████▉   | 121/175 [00:38<00:15,  3.43it/s, ms_per_img=1.775, samples=3,872]
Resolution 224 eval:  69%|██████▉   | 121/175 [00:39<00:15,  3.43it/s, ms_per_img=1.775, samples=3,904]
Resolution 224 eval:  69%|██████▉   | 121/175 [00:39<00:15,  3.43it/s, ms_per_img=1.775, samples=3,936]
Resolution 224 eval:  70%|███████   | 123/175 [00:39<00:16,  3.10it/s, ms_per_img=1.775, samples=3,936]
Resolution 224 eval:  70%|███████   | 123/175 [00:39<00:16,  3.10it/s, ms_per_img=1.774, samples=3,968]
Resolution 224 eval:  70%|███████   | 123/175 [00:40<00:16,  3.10it/s, ms_per_img=1.774, samples=4,000]
Resolution 224 eval:  71%|███████▏  | 125/175 [00:40<00:16,  3.08it/s, ms_per_img=1.774, samples=4,000]
Resolution 224 eval:  71%|███████▏  | 125/175 [00:40<00:16,  3.08it/s, ms_per_img=1.775, samples=4,032]
Resolution 224 eval:  71%|███████▏  | 125/175 [00:40<00:16,  3.08it/s, ms_per_img=1.773, samples=4,064]
Resolution 224 eval:  73%|███████▎  | 127/175 [00:40<00:16,  2.96it/s, ms_per_img=1.773, samples=4,064]
Resolution 224 eval:  73%|███████▎  | 127/175 [00:41<00:16,  2.96it/s, ms_per_img=1.776, samples=4,096]
Resolution 224 eval:  73%|███████▎  | 127/175 [00:41<00:16,  2.96it/s, ms_per_img=1.773, samples=4,128]
Resolution 224 eval:  74%|███████▎  | 129/175 [00:41<00:15,  3.03it/s, ms_per_img=1.773, samples=4,128]
Resolution 224 eval:  74%|███████▎  | 129/175 [00:41<00:15,  3.03it/s, ms_per_img=1.776, samples=4,160]
Resolution 224 eval:  74%|███████▎  | 129/175 [00:42<00:15,  3.03it/s, ms_per_img=1.774, samples=4,192]
Resolution 224 eval:  75%|███████▍  | 131/175 [00:42<00:14,  3.06it/s, ms_per_img=1.774, samples=4,192]
Resolution 224 eval:  75%|███████▍  | 131/175 [00:42<00:14,  3.06it/s, ms_per_img=1.774, samples=4,224]

Acc=0.3036 AUC=0.5449 Fast=100.00% Medium=0.00% Full=0.00%

Resolution sweep:  50%|█████     | 2/4 [03:45<03:30, 105.27s/it]

Source Res=224 Single: 5.970 ms/img | 167.5 FPS
Source Res=224 Batch=32: 1.769 ms/img | 565.2 FPS

Resolution 256

Resolution 256 eval:   0%|          | 0/175 [00:00<?, ?it/s]
Resolution 256 eval:   0%|          | 0/175 [00:00<?, ?it/s, ms_per_img=1.776, samples=32]
Resolution 256 eval:   0%|          | 0/175 [00:00<?, ?it/s, ms_per_img=1.773, samples=64]
Resolution 256 eval:   1%|          | 2/175 [00:00<00:53,  3.26it/s, ms_per_img=1.773, samples=64]
Resolution 256 eval:   1%|          | 2/175 [00:01<00:53,  3.26it/s, ms_per_img=1.775, samples=96]
Resolution 256 eval:   1%|          | 2/175 [00:01<00:53,  3.26it/s, ms_per_img=1.776, samples=128]
Resolution 256 eval:   2%|▏         | 4/175 [00:01<01:11,  2.40it/s, ms_per_img=1.776, samples=128]
Resolution 256 eval:   2%|▏         | 4/175 [00:01<01:11,  2.40it/s, ms_per_img=1.779, samples=160]
Resolution 256 eval:   2%|▏         | 4/175 [00:02<01:11,  2.40it/s, ms_per_img=1.776, samples=192]
Resolution 256 eval:   3%|▎         | 6/175 [00:02<01:05,  2.58it/s, ms_per_img=1.776, samples=192]
Resolution 256 eval:   3%|▎         | 6/175 [00:02<01:05,  2.58it/s, ms_per_img=1.777, samples=224]
Resolution 256 eval:   3%|▎         | 6/175 [00:02<01:05,  2.58it/s, ms_per_img=1.774, samples=256]
Resolution 256 eval:   5%|▍         | 8/175 [00:02<00:56,  2.96it/s, ms_per_img=1.774, samples=256]
Resolution 256 eval:   5%|▍         | 8/175 [00:03<00:56,  2.96it/s, ms_per_img=1.777, samples=288]
Resolution 256 eval:   5%|▍         | 8/175 [00:03<00:56,  2.96it/s, ms_per_img=1.774, samples=320]
Resolution 256 eval:   6%|▌         | 10/175 [00:03<00:59,  2.76it/s, ms_per_img=1.774, samples=320]
Resolution 256 eval:   6%|▌         | 10/175 [00:04<00:59,  2.76it/s, ms_per_img=1.774, samples=352]
Resolution 256 eval:   6%|▌         | 10/175 [00:04<00:59,  2.76it/s, ms_per_img=1.777, samples=384]
Resolution 256 eval:   7%|▋         | 12/175 [00:04<01:00,  2.69it/s, ms_per_img=1.777, samples=384]
Resolution 256 eval:   7%|▋         | 12/175 [00:04<01:00,  2.69it/s, ms_per_img=1.773, samples=416]
Resolution 256 eval:   7%|▋         | 12/175 [00:05<01:00,  2.69it/s, ms_per_img=1.775, samples=448]
Resolution 256 eval:   8%|▊         | 14/175 [00:05<00:56,  2.87it/s, ms_per_img=1.775, samples=448]
Resolution 256 eval:   8%|▊         | 14/175 [00:05<00:56,  2.87it/s, ms_per_img=1.777, samples=480]
Resolution 256 eval:   8%|▊         | 14/175 [00:05<00:56,  2.87it/s, ms_per_img=1.777, samples=512]
Resolution 256 eval:   9%|▉         | 16/175 [00:05<00:50,  3.15it/s, ms_per_img=1.777, samples=512]
Resolution 256 eval:   9%|▉         | 16/175 [00:05<00:50,  3.15it/s, ms_per_img=1.774, samples=544]
Resolution 256 eval:   9%|▉         | 16/175 [00:06<00:50,  3.15it/s, ms_per_img=1.773, samples=576]
Resolution 256 eval:  10%|█         | 18/175 [00:06<00:49,  3.15it/s, ms_per_img=1.773, samples=576]
Resolution 256 eval:  10%|█         | 18/175 [00:06<00:49,  3.15it/s, ms_per_img=1.776, samples=608]
Resolution 256 eval:  10%|█         | 18/175 [00:06<00:49,  3.15it/s, ms_per_img=1.776, samples=640]
Resolution 256 eval:  11%|█▏        | 20/175 [00:06<00:49,  3.13it/s, ms_per_img=1.776, samples=640]
Resolution 256 eval:  11%|█▏        | 20/175 [00:07<00:49,  3.13it/s, ms_per_img=1.775, samples=672]
Resolution 256 eval:  11%|█▏        | 20/175 [00:07<00:49,  3.13it/s, ms_per_img=1.775, samples=704]
Resolution 256 eval:  13%|█▎        | 22/175 [00:07<00:50,  3.03it/s, ms_per_img=1.775, samples=704]
Resolution 256 eval:  13%|█▎        | 22/175 [00:07<00:50,  3.03it/s, ms_per_img=1.775, samples=736]
Resolution 256 eval:  13%|█▎        | 22/175 [00:08<00:50,  3.03it/s, ms_per_img=1.773, samples=768]
Resolution 256 eval:  14%|█▎        | 24/175 [00:08<00:50,  2.98it/s, ms_per_img=1.773, samples=768]
Resolution 256 eval:  14%|█▎        | 24/175 [00:08<00:50,  2.98it/s, ms_per_img=1.775, samples=800]
Resolution 256 eval:  14%|█▎        | 24/175 [00:08<00:50,  2.98it/s, ms_per_img=1.775, samples=832]
Resolution 256 eval:  15%|█▍        | 26/175 [00:08<00:48,  3.05it/s, ms_per_img=1.775, samples=832]
Resolution 256 eval:  15%|█▍        | 26/175 [00:09<00:48,  3.05it/s, ms_per_img=1.776, samples=864]
Resolution 256 eval:  15%|█▍        | 26/175 [00:09<00:48,  3.05it/s, ms_per_img=1.774, samples=896]
Resolution 256 eval:  16%|█▌        | 28/175 [00:09<00:50,  2.94it/s, ms_per_img=1.774, samples=896]
Resolution 256 eval:  16%|█▌        | 28/175 [00:09<00:50,  2.94it/s, ms_per_img=1.777, samples=928]
Resolution 256 eval:  16%|█▌        | 28/175 [00:10<00:50,  2.94it/s, ms_per_img=1.775, samples=960]
Resolution 256 eval:  17%|█▋        | 30/175 [00:10<00:51,  2.84it/s, ms_per_img=1.775, samples=960]
Resolution 256 eval:  17%|█▋        | 30/175 [00:10<00:51,  2.84it/s, ms_per_img=1.774, samples=992]
Resolution 256 eval:  17%|█▋        | 30/175 [00:11<00:51,  2.84it/s, ms_per_img=1.774, samples=1,024]
Resolution 256 eval:  18%|█▊        | 32/175 [00:11<00:50,  2.85it/s, ms_per_img=1.774, samples=1,024]
Resolution 256 eval:  18%|█▊        | 32/175 [00:11<00:50,  2.85it/s, ms_per_img=1.775, samples=1,056]
Resolution 256 eval:  18%|█▊        | 32/175 [00:11<00:50,  2.85it/s, ms_per_img=1.776, samples=1,088]
Resolution 256 eval:  19%|█▉        | 34/175 [00:11<00:51,  2.72it/s, ms_per_img=1.776, samples=1,088]
Resolution 256 eval:  19%|█▉        | 34/175 [00:12<00:51,  2.72it/s, ms_per_img=1.777, samples=1,120]
Resolution 256 eval:  19%|█▉        | 34/175 [00:12<00:51,  2.72it/s, ms_per_img=1.774, samples=1,152]
Resolution 256 eval:  21%|██        | 36/175 [00:12<00:58,  2.38it/s, ms_per_img=1.774, samples=1,152]
Resolution 256 eval:  21%|██        | 36/175 [00:13<00:58,  2.38it/s, ms_per_img=1.774, samples=1,184]
Resolution 256 eval:  21%|██        | 36/175 [00:13<00:58,  2.38it/s, ms_per_img=1.774, samples=1,216]
Resolution 256 eval:  21%|██        | 36/175 [00:13<00:58,  2.38it/s, ms_per_img=1.774, samples=1,248]
Resolution 256 eval:  22%|██▏       | 39/175 [00:13<00:48,  2.78it/s, ms_per_img=1.774, samples=1,248]
Resolution 256 eval:  22%|██▏       | 39/175 [00:14<00:48,  2.78it/s, ms_per_img=1.775, samples=1,280]
Resolution 256 eval:  22%|██▏       | 39/175 [00:14<00:48,  2.78it/s, ms_per_img=1.775, samples=1,312]
Resolution 256 eval:  23%|██▎       | 41/175 [00:14<00:46,  2.85it/s, ms_per_img=1.775, samples=1,312]
Resolution 256 eval:  23%|██▎       | 41/175 [00:14<00:46,  2.85it/s, ms_per_img=1.774, samples=1,344]
Resolution 256 eval:  23%|██▎       | 41/175 [00:15<00:46,  2.85it/s, ms_per_img=1.775, samples=1,376]
Resolution 256 eval:  25%|██▍       | 43/175 [00:15<00:48,  2.69it/s, ms_per_img=1.775, samples=1,376]
Resolution 256 eval:  25%|██▍       | 43/175 [00:15<00:48,  2.69it/s, ms_per_img=1.775, samples=1,408]
Resolution 256 eval:  25%|██▍       | 43/175 [00:15<00:48,  2.69it/s, ms_per_img=1.776, samples=1,440]
Resolution 256 eval:  26%|██▌       | 45/175 [00:15<00:46,  2.79it/s, ms_per_img=1.776, samples=1,440]
Resolution 256 eval:  26%|██▌       | 45/175 [00:16<00:46,  2.79it/s, ms_per_img=1.777, samples=1,472]
Resolution 256 eval:  26%|██▌       | 45/175 [00:16<00:46,  2.79it/s, ms_per_img=1.774, samples=1,504]
Resolution 256 eval:  27%|██▋       | 47/175 [00:16<00:44,  2.87it/s, ms_per_img=1.774, samples=1,504]
Resolution 256 eval:  27%|██▋       | 47/175 [00:16<00:44,  2.87it/s, ms_per_img=1.774, samples=1,536]
Resolution 256 eval:  27%|██▋       | 47/175 [00:17<00:44,  2.87it/s, ms_per_img=1.774, samples=1,568]
Resolution 256 eval:  28%|██▊       | 49/175 [00:17<00:42,  2.99it/s, ms_per_img=1.774, samples=1,568]
Resolution 256 eval:  28%|██▊       | 49/175 [00:17<00:42,  2.99it/s, ms_per_img=1.774, samples=1,600]
Resolution 256 eval:  28%|██▊       | 49/175 [00:17<00:42,  2.99it/s, ms_per_img=1.772, samples=1,632]
Resolution 256 eval:  29%|██▉       | 51/175 [00:17<00:40,  3.06it/s, ms_per_img=1.772, samples=1,632]
Resolution 256 eval:  29%|██▉       | 51/175 [00:18<00:40,  3.06it/s, ms_per_img=1.776, samples=1,664]
Resolution 256 eval:  29%|██▉       | 51/175 [00:18<00:40,  3.06it/s, ms_per_img=1.779, samples=1,696]
Resolution 256 eval:  30%|███       | 53/175 [00:18<00:42,  2.89it/s, ms_per_img=1.779, samples=1,696]
Resolution 256 eval:  30%|███       | 53/175 [00:18<00:42,  2.89it/s, ms_per_img=1.776, samples=1,728]
Resolution 256 eval:  30%|███       | 53/175 [00:19<00:42,  2.89it/s, ms_per_img=1.775, samples=1,760]
Resolution 256 eval:  31%|███▏      | 55/175 [00:19<00:41,  2.90it/s, ms_per_img=1.775, samples=1,760]
Resolution 256 eval:  31%|███▏      | 55/175 [00:19<00:41,  2.90it/s, ms_per_img=1.776, samples=1,792]
Resolution 256 eval:  31%|███▏      | 55/175 [00:19<00:41,  2.90it/s, ms_per_img=1.775, samples=1,824]
Resolution 256 eval:  33%|███▎      | 57/175 [00:19<00:39,  2.98it/s, ms_per_img=1.775, samples=1,824]
Resolution 256 eval:  33%|███▎      | 57/175 [00:20<00:39,  2.98it/s, ms_per_img=1.776, samples=1,856]
Resolution 256 eval:  33%|███▎      | 57/175 [00:20<00:39,  2.98it/s, ms_per_img=1.774, samples=1,888]
Resolution 256 eval:  34%|███▎      | 59/175 [00:20<00:38,  2.98it/s, ms_per_img=1.774, samples=1,888]
Resolution 256 eval:  34%|███▎      | 59/175 [00:20<00:38,  2.98it/s, ms_per_img=1.775, samples=1,920]
Resolution 256 eval:  34%|███▎      | 59/175 [00:21<00:38,  2.98it/s, ms_per_img=1.775, samples=1,952]
Resolution 256 eval:  35%|███▍      | 61/175 [00:21<00:37,  3.03it/s, ms_per_img=1.775, samples=1,952]
Resolution 256 eval:  35%|███▍      | 61/175 [00:21<00:37,  3.03it/s, ms_per_img=1.775, samples=1,984]
Resolution 256 eval:  35%|███▍      | 61/175 [00:21<00:37,  3.03it/s, ms_per_img=1.773, samples=2,016]
Resolution 256 eval:  36%|███▌      | 63/175 [00:21<00:36,  3.08it/s, ms_per_img=1.773, samples=2,016]
Resolution 256 eval:  36%|███▌      | 63/175 [00:22<00:36,  3.08it/s, ms_per_img=1.777, samples=2,048]
Resolution 256 eval:  36%|███▌      | 63/175 [00:22<00:36,  3.08it/s, ms_per_img=1.775, samples=2,080]
Resolution 256 eval:  37%|███▋      | 65/175 [00:22<00:37,  2.91it/s, ms_per_img=1.775, samples=2,080]
Resolution 256 eval:  37%|███▋      | 65/175 [00:22<00:37,  2.91it/s, ms_per_img=1.773, samples=2,112]
Resolution 256 eval:  37%|███▋      | 65/175 [00:23<00:37,  2.91it/s, ms_per_img=1.774, samples=2,144]
Resolution 256 eval:  38%|███▊      | 67/175 [00:23<00:39,  2.76it/s, ms_per_img=1.774, samples=2,144]
Resolution 256 eval:  38%|███▊      | 67/175 [00:23<00:39,  2.76it/s, ms_per_img=1.776, samples=2,176]
Resolution 256 eval:  38%|███▊      | 67/175 [00:23<00:39,  2.76it/s, ms_per_img=1.774, samples=2,208]
Resolution 256 eval:  39%|███▉      | 69/175 [00:23<00:36,  2.87it/s, ms_per_img=1.774, samples=2,208]
Resolution 256 eval:  39%|███▉      | 69/175 [00:24<00:36,  2.87it/s, ms_per_img=1.776, samples=2,240]
Resolution 256 eval:  39%|███▉      | 69/175 [00:24<00:36,  2.87it/s, ms_per_img=1.774, samples=2,272]
Resolution 256 eval:  41%|████      | 71/175 [00:24<00:39,  2.66it/s, ms_per_img=1.774, samples=2,272]
Resolution 256 eval:  41%|████      | 71/175 [00:25<00:39,  2.66it/s, ms_per_img=1.775, samples=2,304]
Resolution 256 eval:  41%|████      | 71/175 [00:25<00:39,  2.66it/s, ms_per_img=1.773, samples=2,336]
Resolution 256 eval:  42%|████▏     | 73/175 [00:25<00:36,  2.78it/s, ms_per_img=1.773, samples=2,336]
Resolution 256 eval:  42%|████▏     | 73/175 [00:25<00:36,  2.78it/s, ms_per_img=1.774, samples=2,368]
Resolution 256 eval:  42%|████▏     | 73/175 [00:26<00:36,  2.78it/s, ms_per_img=1.775, samples=2,400]
Resolution 256 eval:  43%|████▎     | 75/175 [00:26<00:34,  2.87it/s, ms_per_img=1.775, samples=2,400]
Resolution 256 eval:  43%|████▎     | 75/175 [00:26<00:34,  2.87it/s, ms_per_img=1.774, samples=2,432]
Resolution 256 eval:  43%|████▎     | 75/175 [00:26<00:34,  2.87it/s, ms_per_img=1.775, samples=2,464]
Resolution 256 eval:  44%|████▍     | 77/175 [00:26<00:33,  2.89it/s, ms_per_img=1.775, samples=2,464]
Resolution 256 eval:  44%|████▍     | 77/175 [00:27<00:33,  2.89it/s, ms_per_img=1.774, samples=2,496]
Resolution 256 eval:  44%|████▍     | 77/175 [00:27<00:33,  2.89it/s, ms_per_img=1.775, samples=2,528]
Resolution 256 eval:  45%|████▌     | 79/175 [00:27<00:36,  2.63it/s, ms_per_img=1.775, samples=2,528]
Resolution 256 eval:  45%|████▌     | 79/175 [00:28<00:36,  2.63it/s, ms_per_img=1.777, samples=2,560]
Resolution 256 eval:  45%|████▌     | 79/175 [00:28<00:36,  2.63it/s, ms_per_img=1.774, samples=2,592]
Resolution 256 eval:  46%|████▋     | 81/175 [00:28<00:34,  2.69it/s, ms_per_img=1.774, samples=2,592]
Resolution 256 eval:  46%|████▋     | 81/175 [00:28<00:34,  2.69it/s, ms_per_img=1.775, samples=2,624]
Resolution 256 eval:  46%|████▋     | 81/175 [00:29<00:34,  2.69it/s, ms_per_img=1.773, samples=2,656]
Resolution 256 eval:  47%|████▋     | 83/175 [00:29<00:34,  2.65it/s, ms_per_img=1.773, samples=2,656]
Resolution 256 eval:  47%|████▋     | 83/175 [00:29<00:34,  2.65it/s, ms_per_img=1.774, samples=2,688]
Resolution 256 eval:  47%|████▋     | 83/175 [00:30<00:34,  2.65it/s, ms_per_img=1.777, samples=2,720]
Resolution 256 eval:  49%|████▊     | 85/175 [00:30<00:34,  2.64it/s, ms_per_img=1.777, samples=2,720]
Resolution 256 eval:  49%|████▊     | 85/175 [00:30<00:34,  2.64it/s, ms_per_img=1.775, samples=2,752]
Resolution 256 eval:  49%|████▊     | 85/175 [00:30<00:34,  2.64it/s, ms_per_img=1.775, samples=2,784]
Resolution 256 eval:  50%|████▉     | 87/175 [00:30<00:34,  2.56it/s, ms_per_img=1.775, samples=2,784]
Resolution 256 eval:  50%|████▉     | 87/175 [00:31<00:34,  2.56it/s, ms_per_img=1.775, samples=2,816]
Resolution 256 eval:  50%|████▉     | 87/175 [00:31<00:34,  2.56it/s, ms_per_img=1.776, samples=2,848]
Resolution 256 eval:  51%|█████     | 89/175 [00:31<00:34,  2.52it/s, ms_per_img=1.776, samples=2,848]
Resolution 256 eval:  51%|█████     | 89/175 [00:31<00:34,  2.52it/s, ms_per_img=1.774, samples=2,880]
Resolution 256 eval:  51%|█████     | 89/175 [00:32<00:34,  2.52it/s, ms_per_img=1.776, samples=2,912]
Resolution 256 eval:  52%|█████▏    | 91/175 [00:32<00:31,  2.65it/s, ms_per_img=1.776, samples=2,912]
Resolution 256 eval:  52%|█████▏    | 91/175 [00:32<00:31,  2.65it/s, ms_per_img=1.773, samples=2,944]
Resolution 256 eval:  52%|█████▏    | 91/175 [00:32<00:31,  2.65it/s, ms_per_img=1.773, samples=2,976]
Resolution 256 eval:  53%|█████▎    | 93/175 [00:32<00:29,  2.80it/s, ms_per_img=1.773, samples=2,976]
Resolution 256 eval:  53%|█████▎    | 93/175 [00:33<00:29,  2.80it/s, ms_per_img=1.776, samples=3,008]
Resolution 256 eval:  53%|█████▎    | 93/175 [00:33<00:29,  2.80it/s, ms_per_img=1.776, samples=3,040]
Resolution 256 eval:  54%|█████▍    | 95/175 [00:33<00:26,  3.04it/s, ms_per_img=1.776, samples=3,040]
Resolution 256 eval:  54%|█████▍    | 95/175 [00:33<00:26,  3.04it/s, ms_per_img=1.775, samples=3,072]
Resolution 256 eval:  54%|█████▍    | 95/175 [00:34<00:26,  3.04it/s, ms_per_img=1.775, samples=3,104]
Resolution 256 eval:  55%|█████▌    | 97/175 [00:34<00:24,  3.12it/s, ms_per_img=1.775, samples=3,104]
Resolution 256 eval:  55%|█████▌    | 97/175 [00:34<00:24,  3.12it/s, ms_per_img=1.775, samples=3,136]
Resolution 256 eval:  55%|█████▌    | 97/175 [00:34<00:24,  3.12it/s, ms_per_img=1.775, samples=3,168]
Resolution 256 eval:  57%|█████▋    | 99/175 [00:34<00:25,  2.97it/s, ms_per_img=1.775, samples=3,168]
Resolution 256 eval:  57%|█████▋    | 99/175 [00:35<00:25,  2.97it/s, ms_per_img=1.772, samples=3,200]
Resolution 256 eval:  57%|█████▋    | 99/175 [00:35<00:25,  2.97it/s, ms_per_img=1.774, samples=3,232]
Resolution 256 eval:  58%|█████▊    | 101/175 [00:35<00:25,  2.87it/s, ms_per_img=1.774, samples=3,232]
Resolution 256 eval:  58%|█████▊    | 101/175 [00:35<00:25,  2.87it/s, ms_per_img=1.774, samples=3,264]
Resolution 256 eval:  58%|█████▊    | 101/175 [00:36<00:25,  2.87it/s, ms_per_img=1.774, samples=3,296]
Resolution 256 eval:  59%|█████▉    | 103/175 [00:36<00:24,  2.89it/s, ms_per_img=1.774, samples=3,296]
Resolution 256 eval:  59%|█████▉    | 103/175 [00:36<00:24,  2.89it/s, ms_per_img=1.776, samples=3,328]
Resolution 256 eval:  59%|█████▉    | 103/175 [00:36<00:24,  2.89it/s, ms_per_img=1.777, samples=3,360]
Resolution 256 eval:  60%|██████    | 105/175 [00:36<00:24,  2.91it/s, ms_per_img=1.777, samples=3,360]
Resolution 256 eval:  60%|██████    | 105/175 [00:37<00:24,  2.91it/s, ms_per_img=1.774, samples=3,392]
Resolution 256 eval:  60%|██████    | 105/175 [00:37<00:24,  2.91it/s, ms_per_img=1.777, samples=3,424]
Resolution 256 eval:  61%|██████    | 107/175 [00:37<00:21,  3.11it/s, ms_per_img=1.777, samples=3,424]
Resolution 256 eval:  61%|██████    | 107/175 [00:37<00:21,  3.11it/s, ms_per_img=1.773, samples=3,456]
Resolution 256 eval:  61%|██████    | 107/175 [00:38<00:21,  3.11it/s, ms_per_img=1.772, samples=3,488]
Resolution 256 eval:  62%|██████▏   | 109/175 [00:38<00:20,  3.28it/s, ms_per_img=1.772, samples=3,488]
Resolution 256 eval:  62%|██████▏   | 109/175 [00:38<00:20,  3.28it/s, ms_per_img=1.774, samples=3,520]
Resolution 256 eval:  62%|██████▏   | 109/175 [00:38<00:20,  3.28it/s, ms_per_img=1.775, samples=3,552]
Resolution 256 eval:  63%|██████▎   | 111/175 [00:38<00:19,  3.36it/s, ms_per_img=1.775, samples=3,552]
Resolution 256 eval:  63%|██████▎   | 111/175 [00:38<00:19,  3.36it/s, ms_per_img=1.777, samples=3,584]
Resolution 256 eval:  63%|██████▎   | 111/175 [00:39<00:19,  3.36it/s, ms_per_img=1.776, samples=3,616]
Resolution 256 eval:  65%|██████▍   | 113/175 [00:39<00:17,  3.48it/s, ms_per_img=1.776, samples=3,616]
Resolution 256 eval:  65%|██████▍   | 113/175 [00:39<00:17,  3.48it/s, ms_per_img=1.773, samples=3,648]
Resolution 256 eval:  65%|██████▍   | 113/175 [00:39<00:17,  3.48it/s, ms_per_img=1.775, samples=3,680]
Resolution 256 eval:  66%|██████▌   | 115/175 [00:39<00:19,  3.01it/s, ms_per_img=1.775, samples=3,680]
Resolution 256 eval:  66%|██████▌   | 115/175 [00:40<00:19,  3.01it/s, ms_per_img=1.775, samples=3,712]
Resolution 256 eval:  66%|██████▌   | 115/175 [00:40<00:19,  3.01it/s, ms_per_img=1.774, samples=3,744]
Resolution 256 eval:  67%|██████▋   | 117/175 [00:40<00:19,  2.94it/s, ms_per_img=1.774, samples=3,744]
Resolution 256 eval:  67%|██████▋   | 117/175 [00:41<00:19,  2.94it/s, ms_per_img=1.773, samples=3,776]
Resolution 256 eval:  67%|██████▋   | 117/175 [00:41<00:19,  2.94it/s, ms_per_img=1.776, samples=3,808]
Resolution 256 eval:  68%|██████▊   | 119/175 [00:41<00:18,  3.04it/s, ms_per_img=1.776, samples=3,808]
Resolution 256 eval:  68%|██████▊   | 119/175 [00:41<00:18,  3.04it/s, ms_per_img=1.777, samples=3,840]
Resolution 256 eval:  68%|██████▊   | 119/175 [00:41<00:18,  3.04it/s, ms_per_img=1.774, samples=3,872]
Resolution 256 eval:  69%|██████▉   | 121/175 [00:41<00:17,  3.13it/s, ms_per_img=1.774, samples=3,872]
Resolution 256 eval:  69%|██████▉   | 121/175 [00:42<00:17,  3.13it/s, ms_per_img=1.775, samples=3,904]
Resolution 256 eval:  69%|██████▉   | 121/175 [00:42<00:17,  3.13it/s, ms_per_img=1.772, samples=3,936]
Resolution 256 eval:  70%|███████   | 123/175 [00:42<00:18,  2.81it/s, ms_per_img=1.772, samples=3,936]
Resolution 256 eval:  70%|███████   | 123/175 [00:43<00:18,  2.81it/s, ms_per_img=1.775, samples=3,968]
Resolution 256 eval:  70%|███████   | 123/175 [00:43<00:18,  2.81it/s, ms_per_img=1.778, samples=4,000]
Resolution 256 eval:  71%|███████▏  | 125/175 [00:43<00:17,  2.79it/s, ms_per_img=1.778, samples=4,000]
Resolution 256 eval:  71%|███████▏  | 125/175 [00:43<00:17,  2.79it/s, ms_per_img=1.775, samples=4,032]
Resolution 256 eval:  71%|███████▏  | 125/175 [00:44<00:17,  2.79it/s, ms_per_img=1.775, samples=4,064]
Resolution 256 eval:  73%|███████▎  | 127/175 [00:44<00:17,  2.70it/s, ms_per_img=1.775, samples=4,064]
Resolution 256 eval:  73%|███████▎  | 127/175 [00:44<00:17,  2.70it/s, ms_per_img=1.774, samples=4,096]
Resolution 256 eval:  73%|███████▎  | 127/175 [00:44<00:17,  2.70it/s, ms_per_img=1.774, samples=4,128]
Resolution 256 eval:  74%|███████▎  | 129/175 [00:44<00:16,  2.79it/s, ms_per_img=1.774, samples=4,128]
Resolution 256 eval:  74%|███████▎  | 129/175 [00:45<00:16,  2.79it/s, ms_per_img=1.774, samples=4,160]

Acc=0.3043 AUC=0.5464 Fast=100.00% Medium=0.00% Full=0.00%

Resolution sweep:  75%|███████▌  | 3/4 [05:00<01:31, 91.41s/it]

Source Res=256 Single: 5.950 ms/img | 168.1 FPS
Source Res=256 Batch=32: 1.769 ms/img | 565.2 FPS

Resolution 384

Resolution 384 eval:   0%|          | 0/175 [00:00<?, ?it/s]
Resolution 384 eval:   0%|          | 0/175 [00:00<?, ?it/s, ms_per_img=1.779, samples=32]
Resolution 384 eval:   0%|          | 0/175 [00:00<?, ?it/s, ms_per_img=1.777, samples=64]
Resolution 384 eval:   1%|          | 2/175 [00:00<00:58,  2.96it/s, ms_per_img=1.777, samples=64]
Resolution 384 eval:   1%|          | 2/175 [00:01<00:58,  2.96it/s, ms_per_img=1.776, samples=96]
Resolution 384 eval:   1%|          | 2/175 [00:01<00:58,  2.96it/s, ms_per_img=1.775, samples=128]
Resolution 384 eval:   2%|▏         | 4/175 [00:01<01:16,  2.23it/s, ms_per_img=1.775, samples=128]
Resolution 384 eval:   2%|▏         | 4/175 [00:02<01:16,  2.23it/s, ms_per_img=1.776, samples=160]
Resolution 384 eval:   2%|▏         | 4/175 [00:02<01:16,  2.23it/s, ms_per_img=1.775, samples=192]
Resolution 384 eval:   3%|▎         | 6/175 [00:02<01:10,  2.38it/s, ms_per_img=1.775, samples=192]
Resolution 384 eval:   3%|▎         | 6/175 [00:02<01:10,  2.38it/s, ms_per_img=1.774, samples=224]
Resolution 384 eval:   3%|▎         | 6/175 [00:03<01:10,  2.38it/s, ms_per_img=1.774, samples=256]
Resolution 384 eval:   5%|▍         | 8/175 [00:03<01:01,  2.71it/s, ms_per_img=1.774, samples=256]
Resolution 384 eval:   5%|▍         | 8/175 [00:03<01:01,  2.71it/s, ms_per_img=1.773, samples=288]
Resolution 384 eval:   5%|▍         | 8/175 [00:03<01:01,  2.71it/s, ms_per_img=1.773, samples=320]
Resolution 384 eval:   6%|▌         | 10/175 [00:03<01:05,  2.53it/s, ms_per_img=1.773, samples=320]
Resolution 384 eval:   6%|▌         | 10/175 [00:04<01:05,  2.53it/s, ms_per_img=1.774, samples=352]
Resolution 384 eval:   6%|▌         | 10/175 [00:04<01:05,  2.53it/s, ms_per_img=1.775, samples=384]
Resolution 384 eval:   7%|▋         | 12/175 [00:04<01:06,  2.45it/s, ms_per_img=1.775, samples=384]
Resolution 384 eval:   7%|▋         | 12/175 [00:05<01:06,  2.45it/s, ms_per_img=1.772, samples=416]
Resolution 384 eval:   7%|▋         | 12/175 [00:05<01:06,  2.45it/s, ms_per_img=1.776, samples=448]
Resolution 384 eval:   8%|▊         | 14/175 [00:05<01:01,  2.61it/s, ms_per_img=1.776, samples=448]
Resolution 384 eval:   8%|▊         | 14/175 [00:05<01:01,  2.61it/s, ms_per_img=1.775, samples=480]
Resolution 384 eval:   8%|▊         | 14/175 [00:06<01:01,  2.61it/s, ms_per_img=1.775, samples=512]
Resolution 384 eval:   9%|▉         | 16/175 [00:06<00:55,  2.84it/s, ms_per_img=1.775, samples=512]
Resolution 384 eval:   9%|▉         | 16/175 [00:06<00:55,  2.84it/s, ms_per_img=1.774, samples=544]
Resolution 384 eval:   9%|▉         | 16/175 [00:06<00:55,  2.84it/s, ms_per_img=1.777, samples=576]
Resolution 384 eval:  10%|█         | 18/175 [00:06<00:55,  2.84it/s, ms_per_img=1.777, samples=576]
Resolution 384 eval:  10%|█         | 18/175 [00:07<00:55,  2.84it/s, ms_per_img=1.775, samples=608]
Resolution 384 eval:  10%|█         | 18/175 [00:07<00:55,  2.84it/s, ms_per_img=1.776, samples=640]
Resolution 384 eval:  11%|█▏        | 20/175 [00:07<00:54,  2.84it/s, ms_per_img=1.776, samples=640]
Resolution 384 eval:  11%|█▏        | 20/175 [00:07<00:54,  2.84it/s, ms_per_img=1.775, samples=672]
Resolution 384 eval:  11%|█▏        | 20/175 [00:08<00:54,  2.84it/s, ms_per_img=1.776, samples=704]
Resolution 384 eval:  13%|█▎        | 22/175 [00:08<00:55,  2.76it/s, ms_per_img=1.776, samples=704]
Resolution 384 eval:  13%|█▎        | 22/175 [00:08<00:55,  2.76it/s, ms_per_img=1.776, samples=736]
Resolution 384 eval:  13%|█▎        | 22/175 [00:09<00:55,  2.76it/s, ms_per_img=1.775, samples=768]
Resolution 384 eval:  14%|█▎        | 24/175 [00:09<00:55,  2.72it/s, ms_per_img=1.775, samples=768]
Resolution 384 eval:  14%|█▎        | 24/175 [00:09<00:55,  2.72it/s, ms_per_img=1.773, samples=800]
Resolution 384 eval:  14%|█▎        | 24/175 [00:09<00:55,  2.72it/s, ms_per_img=1.777, samples=832]
Resolution 384 eval:  15%|█▍        | 26/175 [00:09<00:53,  2.79it/s, ms_per_img=1.777, samples=832]
Resolution 384 eval:  15%|█▍        | 26/175 [00:10<00:53,  2.79it/s, ms_per_img=1.775, samples=864]
Resolution 384 eval:  15%|█▍        | 26/175 [00:10<00:53,  2.79it/s, ms_per_img=1.775, samples=896]
Resolution 384 eval:  16%|█▌        | 28/175 [00:10<00:54,  2.69it/s, ms_per_img=1.775, samples=896]
Resolution 384 eval:  16%|█▌        | 28/175 [00:10<00:54,  2.69it/s, ms_per_img=1.775, samples=928]
Resolution 384 eval:  16%|█▌        | 28/175 [00:11<00:54,  2.69it/s, ms_per_img=1.775, samples=960]
Resolution 384 eval:  17%|█▋        | 30/175 [00:11<00:55,  2.60it/s, ms_per_img=1.775, samples=960]
Resolution 384 eval:  17%|█▋        | 30/175 [00:11<00:55,  2.60it/s, ms_per_img=1.774, samples=992]
Resolution 384 eval:  17%|█▋        | 30/175 [00:12<00:55,  2.60it/s, ms_per_img=1.775, samples=1,024]
Resolution 384 eval:  18%|█▊        | 32/175 [00:12<00:55,  2.60it/s, ms_per_img=1.775, samples=1,024]
Resolution 384 eval:  18%|█▊        | 32/175 [00:12<00:55,  2.60it/s, ms_per_img=1.775, samples=1,056]
Resolution 384 eval:  18%|█▊        | 32/175 [00:12<00:55,  2.60it/s, ms_per_img=1.776, samples=1,088]
Resolution 384 eval:  19%|█▉        | 34/175 [00:12<00:56,  2.49it/s, ms_per_img=1.776, samples=1,088]
Resolution 384 eval:  19%|█▉        | 34/175 [00:13<00:56,  2.49it/s, ms_per_img=1.776, samples=1,120]
Resolution 384 eval:  19%|█▉        | 34/175 [00:14<00:56,  2.49it/s, ms_per_img=1.774, samples=1,152]
Resolution 384 eval:  21%|██        | 36/175 [00:14<01:03,  2.19it/s, ms_per_img=1.774, samples=1,152]
Resolution 384 eval:  21%|██        | 36/175 [00:14<01:03,  2.19it/s, ms_per_img=1.776, samples=1,184]
Resolution 384 eval:  21%|██        | 36/175 [00:14<01:03,  2.19it/s, ms_per_img=1.775, samples=1,216]
Resolution 384 eval:  22%|██▏       | 38/175 [00:14<00:55,  2.49it/s, ms_per_img=1.775, samples=1,216]
Resolution 384 eval:  22%|██▏       | 38/175 [00:15<00:55,  2.49it/s, ms_per_img=1.774, samples=1,248]
Resolution 384 eval:  22%|██▏       | 38/175 [00:15<00:55,  2.49it/s, ms_per_img=1.774, samples=1,280]
Resolution 384 eval:  23%|██▎       | 40/175 [00:15<00:51,  2.60it/s, ms_per_img=1.774, samples=1,280]
Resolution 384 eval:  23%|██▎       | 40/175 [00:15<00:51,  2.60it/s, ms_per_img=1.774, samples=1,312]
Resolution 384 eval:  23%|██▎       | 40/175 [00:16<00:51,  2.60it/s, ms_per_img=1.775, samples=1,344]
Resolution 384 eval:  24%|██▍       | 42/175 [00:16<00:53,  2.48it/s, ms_per_img=1.775, samples=1,344]
Resolution 384 eval:  24%|██▍       | 42/175 [00:16<00:53,  2.48it/s, ms_per_img=1.774, samples=1,376]
Resolution 384 eval:  24%|██▍       | 42/175 [00:17<00:53,  2.48it/s, ms_per_img=1.777, samples=1,408]
Resolution 384 eval:  25%|██▌       | 44/175 [00:17<00:52,  2.49it/s, ms_per_img=1.777, samples=1,408]
Resolution 384 eval:  25%|██▌       | 44/175 [00:17<00:52,  2.49it/s, ms_per_img=1.774, samples=1,440]
Resolution 384 eval:  25%|██▌       | 44/175 [00:17<00:52,  2.49it/s, ms_per_img=1.773, samples=1,472]
Resolution 384 eval:  26%|██▋       | 46/175 [00:17<00:47,  2.71it/s, ms_per_img=1.773, samples=1,472]
Resolution 384 eval:  26%|██▋       | 46/175 [00:18<00:47,  2.71it/s, ms_per_img=1.774, samples=1,504]
Resolution 384 eval:  26%|██▋       | 46/175 [00:18<00:47,  2.71it/s, ms_per_img=1.775, samples=1,536]
Resolution 384 eval:  27%|██▋       | 48/175 [00:18<00:47,  2.67it/s, ms_per_img=1.775, samples=1,536]
Resolution 384 eval:  27%|██▋       | 48/175 [00:18<00:47,  2.67it/s, ms_per_img=1.774, samples=1,568]
Resolution 384 eval:  27%|██▋       | 48/175 [00:19<00:47,  2.67it/s, ms_per_img=1.774, samples=1,600]
Resolution 384 eval:  29%|██▊       | 50/175 [00:19<00:46,  2.70it/s, ms_per_img=1.774, samples=1,600]
Resolution 384 eval:  29%|██▊       | 50/175 [00:19<00:46,  2.70it/s, ms_per_img=1.776, samples=1,632]
Resolution 384 eval:  29%|██▊       | 50/175 [00:19<00:46,  2.70it/s, ms_per_img=1.773, samples=1,664]
Resolution 384 eval:  30%|██▉       | 52/175 [00:19<00:46,  2.62it/s, ms_per_img=1.773, samples=1,664]
Resolution 384 eval:  30%|██▉       | 52/175 [00:20<00:46,  2.62it/s, ms_per_img=1.776, samples=1,696]
Resolution 384 eval:  30%|██▉       | 52/175 [00:20<00:46,  2.62it/s, ms_per_img=1.774, samples=1,728]
Resolution 384 eval:  31%|███       | 54/175 [00:20<00:45,  2.64it/s, ms_per_img=1.774, samples=1,728]
Resolution 384 eval:  31%|███       | 54/175 [00:21<00:45,  2.64it/s, ms_per_img=1.775, samples=1,760]
Resolution 384 eval:  31%|███       | 54/175 [00:21<00:45,  2.64it/s, ms_per_img=1.774, samples=1,792]
Resolution 384 eval:  32%|███▏      | 56/175 [00:21<00:43,  2.76it/s, ms_per_img=1.774, samples=1,792]
Resolution 384 eval:  32%|███▏      | 56/175 [00:21<00:43,  2.76it/s, ms_per_img=1.772, samples=1,824]
Resolution 384 eval:  32%|███▏      | 56/175 [00:22<00:43,  2.76it/s, ms_per_img=1.773, samples=1,856]
Resolution 384 eval:  33%|███▎      | 58/175 [00:22<00:41,  2.80it/s, ms_per_img=1.773, samples=1,856]
Resolution 384 eval:  33%|███▎      | 58/175 [00:22<00:41,  2.80it/s, ms_per_img=1.773, samples=1,888]
Resolution 384 eval:  33%|███▎      | 58/175 [00:22<00:41,  2.80it/s, ms_per_img=1.775, samples=1,920]
Resolution 384 eval:  34%|███▍      | 60/175 [00:22<00:41,  2.80it/s, ms_per_img=1.775, samples=1,920]
Resolution 384 eval:  34%|███▍      | 60/175 [00:23<00:41,  2.80it/s, ms_per_img=1.776, samples=1,952]
Resolution 384 eval:  34%|███▍      | 60/175 [00:23<00:41,  2.80it/s, ms_per_img=1.774, samples=1,984]
Resolution 384 eval:  35%|███▌      | 62/175 [00:23<00:41,  2.73it/s, ms_per_img=1.774, samples=1,984]
Resolution 384 eval:  35%|███▌      | 62/175 [00:23<00:41,  2.73it/s, ms_per_img=1.776, samples=2,016]
Resolution 384 eval:  35%|███▌      | 62/175 [00:24<00:41,  2.73it/s, ms_per_img=1.774, samples=2,048]
Resolution 384 eval:  37%|███▋      | 64/175 [00:24<00:41,  2.67it/s, ms_per_img=1.774, samples=2,048]
Resolution 384 eval:  37%|███▋      | 64/175 [00:24<00:41,  2.67it/s, ms_per_img=1.771, samples=2,080]
Resolution 384 eval:  37%|███▋      | 64/175 [00:25<00:41,  2.67it/s, ms_per_img=1.775, samples=2,112]
Resolution 384 eval:  38%|███▊      | 66/175 [00:25<00:41,  2.63it/s, ms_per_img=1.775, samples=2,112]
Resolution 384 eval:  38%|███▊      | 66/175 [00:25<00:41,  2.63it/s, ms_per_img=1.774, samples=2,144]
Resolution 384 eval:  38%|███▊      | 66/175 [00:25<00:41,  2.63it/s, ms_per_img=1.774, samples=2,176]
Resolution 384 eval:  39%|███▉      | 68/175 [00:25<00:41,  2.56it/s, ms_per_img=1.774, samples=2,176]
Resolution 384 eval:  39%|███▉      | 68/175 [00:26<00:41,  2.56it/s, ms_per_img=1.775, samples=2,208]
Resolution 384 eval:  39%|███▉      | 68/175 [00:26<00:41,  2.56it/s, ms_per_img=1.774, samples=2,240]
Resolution 384 eval:  40%|████      | 70/175 [00:26<00:43,  2.44it/s, ms_per_img=1.774, samples=2,240]
Resolution 384 eval:  40%|████      | 70/175 [00:27<00:43,  2.44it/s, ms_per_img=1.774, samples=2,272]
Resolution 384 eval:  40%|████      | 70/175 [00:27<00:43,  2.44it/s, ms_per_img=1.773, samples=2,304]
Resolution 384 eval:  41%|████      | 72/175 [00:27<00:40,  2.56it/s, ms_per_img=1.773, samples=2,304]
Resolution 384 eval:  41%|████      | 72/175 [00:27<00:40,  2.56it/s, ms_per_img=1.775, samples=2,336]
Resolution 384 eval:  41%|████      | 72/175 [00:28<00:40,  2.56it/s, ms_per_img=1.775, samples=2,368]
Resolution 384 eval:  42%|████▏     | 74/175 [00:28<00:39,  2.57it/s, ms_per_img=1.775, samples=2,368]
Resolution 384 eval:  42%|████▏     | 74/175 [00:28<00:39,  2.57it/s, ms_per_img=1.774, samples=2,400]
Resolution 384 eval:  42%|████▏     | 74/175 [00:29<00:39,  2.57it/s, ms_per_img=1.774, samples=2,432]
Resolution 384 eval:  43%|████▎     | 76/175 [00:29<00:37,  2.65it/s, ms_per_img=1.774, samples=2,432]
Resolution 384 eval:  43%|████▎     | 76/175 [00:29<00:37,  2.65it/s, ms_per_img=1.776, samples=2,464]
Resolution 384 eval:  43%|████▎     | 76/175 [00:29<00:37,  2.65it/s, ms_per_img=1.775, samples=2,496]
Resolution 384 eval:  45%|████▍     | 78/175 [00:29<00:39,  2.43it/s, ms_per_img=1.775, samples=2,496]
Resolution 384 eval:  45%|████▍     | 78/175 [00:30<00:39,  2.43it/s, ms_per_img=1.775, samples=2,528]
Resolution 384 eval:  45%|████▍     | 78/175 [00:30<00:39,  2.43it/s, ms_per_img=1.778, samples=2,560]
Resolution 384 eval:  46%|████▌     | 80/175 [00:30<00:37,  2.54it/s, ms_per_img=1.778, samples=2,560]
Resolution 384 eval:  46%|████▌     | 80/175 [00:31<00:37,  2.54it/s, ms_per_img=1.773, samples=2,592]
Resolution 384 eval:  46%|████▌     | 80/175 [00:31<00:37,  2.54it/s, ms_per_img=1.776, samples=2,624]
Resolution 384 eval:  47%|████▋     | 82/175 [00:31<00:36,  2.52it/s, ms_per_img=1.776, samples=2,624]
Resolution 384 eval:  47%|████▋     | 82/175 [00:31<00:36,  2.52it/s, ms_per_img=1.776, samples=2,656]
Resolution 384 eval:  47%|████▋     | 82/175 [00:32<00:36,  2.52it/s, ms_per_img=1.773, samples=2,688]
Resolution 384 eval:  48%|████▊     | 84/175 [00:32<00:38,  2.37it/s, ms_per_img=1.773, samples=2,688]
Resolution 384 eval:  48%|████▊     | 84/175 [00:32<00:38,  2.37it/s, ms_per_img=1.775, samples=2,720]
Resolution 384 eval:  48%|████▊     | 84/175 [00:33<00:38,  2.37it/s, ms_per_img=1.775, samples=2,752]
Resolution 384 eval:  49%|████▉     | 86/175 [00:33<00:36,  2.46it/s, ms_per_img=1.775, samples=2,752]
Resolution 384 eval:  49%|████▉     | 86/175 [00:33<00:36,  2.46it/s, ms_per_img=1.775, samples=2,784]
Resolution 384 eval:  49%|████▉     | 86/175 [00:34<00:36,  2.46it/s, ms_per_img=1.774, samples=2,816]
Resolution 384 eval:  50%|█████     | 88/175 [00:34<00:35,  2.42it/s, ms_per_img=1.774, samples=2,816]
Resolution 384 eval:  50%|█████     | 88/175 [00:34<00:35,  2.42it/s, ms_per_img=1.775, samples=2,848]
Resolution 384 eval:  50%|█████     | 88/175 [00:34<00:35,  2.42it/s, ms_per_img=1.778, samples=2,880]
Resolution 384 eval:  51%|█████▏    | 90/175 [00:34<00:35,  2.37it/s, ms_per_img=1.778, samples=2,880]
Resolution 384 eval:  51%|█████▏    | 90/175 [00:35<00:35,  2.37it/s, ms_per_img=1.776, samples=2,912]
Resolution 384 eval:  51%|█████▏    | 90/175 [00:35<00:35,  2.37it/s, ms_per_img=1.775, samples=2,944]
Resolution 384 eval:  53%|█████▎    | 92/175 [00:35<00:33,  2.48it/s, ms_per_img=1.775, samples=2,944]
Resolution 384 eval:  53%|█████▎    | 92/175 [00:36<00:33,  2.48it/s, ms_per_img=1.775, samples=2,976]
Resolution 384 eval:  53%|█████▎    | 92/175 [00:36<00:33,  2.48it/s, ms_per_img=1.774, samples=3,008]
Resolution 384 eval:  54%|█████▎    | 94/175 [00:36<00:30,  2.65it/s, ms_per_img=1.774, samples=3,008]
Resolution 384 eval:  54%|█████▎    | 94/175 [00:36<00:30,  2.65it/s, ms_per_img=1.778, samples=3,040]
Resolution 384 eval:  54%|█████▎    | 94/175 [00:36<00:30,  2.65it/s, ms_per_img=1.774, samples=3,072]
Resolution 384 eval:  55%|█████▍    | 96/175 [00:36<00:28,  2.77it/s, ms_per_img=1.774, samples=3,072]
Resolution 384 eval:  55%|█████▍    | 96/175 [00:37<00:28,  2.77it/s, ms_per_img=1.774, samples=3,104]
Resolution 384 eval:  55%|█████▍    | 96/175 [00:37<00:28,  2.77it/s, ms_per_img=1.777, samples=3,136]
Resolution 384 eval:  56%|█████▌    | 98/175 [00:37<00:27,  2.82it/s, ms_per_img=1.777, samples=3,136]
Resolution 384 eval:  56%|█████▌    | 98/175 [00:38<00:27,  2.82it/s, ms_per_img=1.775, samples=3,168]
Resolution 384 eval:  56%|█████▌    | 98/175 [00:38<00:27,  2.82it/s, ms_per_img=1.773, samples=3,200]
Resolution 384 eval:  57%|█████▋    | 100/175 [00:38<00:27,  2.71it/s, ms_per_img=1.773, samples=3,200]
Resolution 384 eval:  57%|█████▋    | 100/175 [00:38<00:27,  2.71it/s, ms_per_img=1.773, samples=3,232]
Resolution 384 eval:  57%|█████▋    | 100/175 [00:39<00:27,  2.71it/s, ms_per_img=1.774, samples=3,264]
Resolution 384 eval:  58%|█████▊    | 102/175 [00:39<00:27,  2.62it/s, ms_per_img=1.774, samples=3,264]
Resolution 384 eval:  58%|█████▊    | 102/175 [00:39<00:27,  2.62it/s, ms_per_img=1.776, samples=3,296]
Resolution 384 eval:  58%|█████▊    | 102/175 [00:40<00:27,  2.62it/s, ms_per_img=1.774, samples=3,328]
Resolution 384 eval:  59%|█████▉    | 104/175 [00:40<00:26,  2.63it/s, ms_per_img=1.774, samples=3,328]
Resolution 384 eval:  59%|█████▉    | 104/175 [00:40<00:26,  2.63it/s, ms_per_img=1.776, samples=3,360]
Resolution 384 eval:  59%|█████▉    | 104/175 [00:40<00:26,  2.63it/s, ms_per_img=1.776, samples=3,392]
Resolution 384 eval:  61%|██████    | 106/175 [00:40<00:26,  2.64it/s, ms_per_img=1.776, samples=3,392]
Resolution 384 eval:  61%|██████    | 106/175 [00:41<00:26,  2.64it/s, ms_per_img=1.776, samples=3,424]
Resolution 384 eval:  61%|██████    | 106/175 [00:41<00:26,  2.64it/s, ms_per_img=1.776, samples=3,456]
Resolution 384 eval:  62%|██████▏   | 108/175 [00:41<00:23,  2.90it/s, ms_per_img=1.776, samples=3,456]
Resolution 384 eval:  62%|██████▏   | 108/175 [00:41<00:23,  2.90it/s, ms_per_img=1.773, samples=3,488]
Resolution 384 eval:  62%|██████▏   | 108/175 [00:41<00:23,  2.90it/s, ms_per_img=1.773, samples=3,520]
Resolution 384 eval:  63%|██████▎   | 110/175 [00:41<00:22,  2.93it/s, ms_per_img=1.773, samples=3,520]
Resolution 384 eval:  63%|██████▎   | 110/175 [00:42<00:22,  2.93it/s, ms_per_img=1.779, samples=3,552]
Resolution 384 eval:  63%|██████▎   | 110/175 [00:42<00:22,  2.93it/s, ms_per_img=1.777, samples=3,584]
Resolution 384 eval:  63%|██████▎   | 110/175 [00:42<00:22,  2.93it/s, ms_per_img=1.778, samples=3,616]
Resolution 384 eval:  65%|██████▍   | 113/175 [00:42<00:19,  3.14it/s, ms_per_img=1.778, samples=3,616]
Resolution 384 eval:  65%|██████▍   | 113/175 [00:43<00:19,  3.14it/s, ms_per_img=1.777, samples=3,648]
Resolution 384 eval:  65%|██████▍   | 113/175 [00:43<00:19,  3.14it/s, ms_per_img=1.774, samples=3,680]
Resolution 384 eval:  66%|██████▌   | 115/175 [00:43<00:21,  2.79it/s, ms_per_img=1.774, samples=3,680]
Resolution 384 eval:  66%|██████▌   | 115/175 [00:44<00:21,  2.79it/s, ms_per_img=1.776, samples=3,712]
Resolution 384 eval:  66%|██████▌   | 115/175 [00:44<00:21,  2.79it/s, ms_per_img=1.773, samples=3,744]
Resolution 384 eval:  67%|██████▋   | 117/175 [00:44<00:21,  2.72it/s, ms_per_img=1.773, samples=3,744]
Resolution 384 eval:  67%|██████▋   | 117/175 [00:44<00:21,  2.72it/s, ms_per_img=1.774, samples=3,776]
Resolution 384 eval:  67%|██████▋   | 117/175 [00:45<00:21,  2.72it/s, ms_per_img=1.774, samples=3,808]
Resolution 384 eval:  68%|██████▊   | 119/175 [00:45<00:19,  2.81it/s, ms_per_img=1.774, samples=3,808]
Resolution 384 eval:  68%|██████▊   | 119/175 [00:45<00:19,  2.81it/s, ms_per_img=1.775, samples=3,840]
Resolution 384 eval:  68%|██████▊   | 119/175 [00:45<00:19,  2.81it/s, ms_per_img=1.774, samples=3,872]
Resolution 384 eval:  69%|██████▉   | 121/175 [00:45<00:18,  2.87it/s, ms_per_img=1.774, samples=3,872]
Resolution 384 eval:  69%|██████▉   | 121/175 [00:46<00:18,  2.87it/s, ms_per_img=1.774, samples=3,904]
Resolution 384 eval:  69%|██████▉   | 121/175 [00:46<00:18,  2.87it/s, ms_per_img=1.775, samples=3,936]
Resolution 384 eval:  70%|███████   | 123/175 [00:46<00:19,  2.60it/s, ms_per_img=1.775, samples=3,936]
Resolution 384 eval:  70%|███████   | 123/175 [00:47<00:19,  2.60it/s, ms_per_img=1.777, samples=3,968]
Resolution 384 eval:  70%|███████   | 123/175 [00:47<00:19,  2.60it/s, ms_per_img=1.774, samples=4,000]
Resolution 384 eval:  71%|███████▏  | 125/175 [00:47<00:19,  2.58it/s, ms_per_img=1.774, samples=4,000]
Resolution 384 eval:  71%|███████▏  | 125/175 [00:47<00:19,  2.58it/s, ms_per_img=1.775, samples=4,032]
Resolution 384 eval:  71%|███████▏  | 125/175 [00:48<00:19,  2.58it/s, ms_per_img=1.775, samples=4,064]
Resolution 384 eval:  73%|███████▎  | 127/175 [00:48<00:19,  2.50it/s, ms_per_img=1.775, samples=4,064]
Resolution 384 eval:  73%|███████▎  | 127/175 [00:48<00:19,  2.50it/s, ms_per_img=1.774, samples=4,096]
Resolution 384 eval:  73%|███████▎  | 127/175 [00:49<00:19,  2.50it/s, ms_per_img=1.775, samples=4,128]
Resolution 384 eval:  74%|███████▎  | 129/175 [00:49<00:17,  2.57it/s, ms_per_img=1.775, samples=4,128]
Resolution 384 eval:  74%|███████▎  | 129/175 [00:49<00:17,  2.57it/s, ms_per_img=1.774, samples=4,160]

Acc=0.3039 AUC=0.5456 Fast=100.00% Medium=0.00% Full=0.00%

Resolution sweep: 100%|██████████| 4/4 [06:20<00:00, 95.23s/it]

Source Res=384 Single: 5.917 ms/img | 169.0 FPS
Source Res=384 Batch=32: 1.769 ms/img | 565.2 FPS

====================================================================================================
====================================MaD-CoRN EXPERIMENT RESULTS=====================================
====================================================================================================

[1] TRAINING PERIODS RESULTS
                                               Training Periods Results

+-------+------------+-----------+-----------+---------+---------+-----------+--------+--------+--------------------+
| Epoch | Train Loss | Train Acc | Train AUC | Val Acc | Val AUC | Precision | Recall | F1     | Uncertain Rate (%) |
+-------+------------+-----------+-----------+---------+---------+-----------+--------+--------+--------------------+
| 1     | 0.6958     | 0.4998    | 0.4960    | 0.1429  | 0.4994  | 0.0000    | 0.0000 | 0.0000 | 100.00             |
| 2     | 0.6942     | 0.5063    | 0.5043    | 0.2946  | 0.5095  | 0.8779    | 0.2057 | 0.3333 | 97.81              |
| 3     | 0.6932     | 0.5187    | 0.5230    | 0.1838  | 0.5000  | 0.9935    | 0.0481 | 0.0917 | 100.00             |
| 4     | 0.6940     | 0.5048    | 0.5091    | 0.7200  | 0.5691  | 0.8725    | 0.7885 | 0.8284 | 100.00             |
| 5     | 0.6928     | 0.5125    | 0.5208    | 0.3951  | 0.5093  | 0.8479    | 0.3586 | 0.5041 | 100.00             |
| 6     | 0.6925     | 0.5145    | 0.5185    | 0.3276  | 0.4796  | 0.8437    | 0.2646 | 0.4028 | 100.00             |
| 7     | 0.6920     | 0.5252    | 0.5344    | 0.5956  | 0.5183  | 0.8616    | 0.6293 | 0.7274 | 99.85              |
| 8     | 0.6871     | 0.5405    | 0.5533    | 0.3789  | 0.5279  | 0.8557    | 0.3312 | 0.4776 | 90.45              |
| 9     | 0.6841     | 0.5397    | 0.5529    | 0.3377  | 0.5772  | 0.9086    | 0.2528 | 0.3955 | 92.42              |
| 10    | 0.6775     | 0.5581    | 0.5696    | 0.3261  | 0.5773  | 0.9344    | 0.2299 | 0.3690 | 91.47              |
| 11    | 0.6712     | 0.5644    | 0.5726    | 0.2980  | 0.5870  | 0.9338    | 0.1948 | 0.3224 | 87.21              |
| 12    | 0.6672     | 0.5716    | 0.5827    | 0.2859  | 0.5818  | 0.9346    | 0.1795 | 0.3011 | 87.88              |
| 13    | 0.6608     | 0.5709    | 0.5810    | 0.2879  | 0.5607  | 0.9501    | 0.1786 | 0.3007 | 86.81              |
| 14    | 0.6587     | 0.5772    | 0.5796    | 0.2943  | 0.5705  | 0.9389    | 0.1890 | 0.3146 | 85.34              |
| 15    | 0.6580     | 0.5807    | 0.5936    | 0.2864  | 0.5720  | 0.9360    | 0.1798 | 0.3016 | 86.60              |
+-------+------------+-----------+-----------+---------+---------+-----------+--------+--------+--------------------+

[2] TEST RESULTS
                                           Test Results

+------------------------+----------+--------+-----------+--------+--------+--------------------+
| Model                  | Accuracy | AUC    | Precision | Recall | F1     | Uncertain Rate (%) |
+------------------------+----------+--------+-----------+--------+--------+--------------------+
| MaD-CoRN-FFPP-Balanced | 0.3031   | 0.5461 | 0.9283    | 0.2025 | 0.3324 | 86.49              |
+------------------------+----------+--------+-----------+--------+--------+--------------------+

[3] ACCURACY BASED ON RESOLUTION
                     Accuracy Based on Resolution

+------------+----------+--------+----------+------------+----------+
| Resolution | Accuracy | AUC    | Fast (%) | Medium (%) | Full (%) |
+------------+----------+--------+----------+------------+----------+
| 128        | 0.3005   | 0.5473 | 100.00   | 0.00       | 0.00     |
| 224        | 0.3036   | 0.5449 | 100.00   | 0.00       | 0.00     |
| 256        | 0.3043   | 0.5464 | 100.00   | 0.00       | 0.00     |
| 384        | 0.3039   | 0.5456 | 100.00   | 0.00       | 0.00     |
+------------+----------+--------+----------+------------+----------+

[4] INFERENCE TIME
                      Inference Time

+-------------------------+---------------------+-------+
| Mode                    | Time per Image (ms) | FPS   |
+-------------------------+---------------------+-------+
| Source Res=128 Single   | 5.912               | 169.2 |
| Source Res=128 Batch=32 | 1.769               | 565.4 |
| Source Res=224 Single   | 5.970               | 167.5 |
| Source Res=224 Batch=32 | 1.769               | 565.2 |
| Source Res=256 Single   | 5.950               | 168.1 |
| Source Res=256 Batch=32 | 1.769               | 565.2 |
| Source Res=384 Single   | 5.917               | 169.0 |
| Source Res=384 Batch=32 | 1.769               | 565.2 |
+-------------------------+---------------------+-------+

[5] TRAINING TIME
                              Training Time

+--------------------------------------------------------+-------+------+
| Model Type                                             | min   | hrs  |
+--------------------------------------------------------+-------+------+
| MaD-CoRN FF++ balanced train multi-resolution training | 305.7 | 5.09 |
+--------------------------------------------------------+-------+------+

Experiment Summary

,Experiment Name,Dataset,Train Samples Original,Train Samples Used Balanced,Validation Samples,Test Samples,Train Real Used,Train Fake Used,Validation Real,Validation Fake,...,Test Fake,Balancing Method,Resolutions Used,Input Modalities,RGB Shape,Device,CUDA Available,Framework,Torch Version,Batching Strategy
0,MaD-CoRN Balanced Train,FaceForensics++ C23,44756,12800,5600,5597,6400,6400,800,4800,...,4797,Train-only undersampling of fake class to matc...,"[128, 224, 256, 384]",RGB,"(3, 224, 224)",cuda,True,PyTorch,2.11.0+cu130,Train: balanced undersampled set with one rand...

Results saved to: ./mad_corn_results_ffpp_balanced

In [3]:
# !pip install scikit-learn torch torchvision tqdm pandas pillow

import os, io, json, math, time, random, warnings
import numpy as np
import pandas as pd
from dataclasses import dataclass, asdict
from PIL import Image, ImageFile

warnings.filterwarnings("ignore")
ImageFile.LOAD_TRUNCATED_IMAGES = True

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader, TensorDataset
import torchvision.transforms as T
from torch.cuda.amp import GradScaler, autocast

from tqdm.auto import tqdm
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score, accuracy_score

# ============================================================
# CONFIG
# ============================================================

CONFIG = dict(
    metadata_csv="/home/jovyan/.cache/kagglehub/datasets/xdxd003/ff-c23/versions/1/ffpp_preprocessed/metadata.csv",
    frames_dir="/home/jovyan/.cache/kagglehub/datasets/xdxd003/ff-c23/versions/1/ffpp_preprocessed/all_frames",

    resolutions=[128, 224, 256, 384],
    image_size_for_model=224,

    epochs=15,
    batch_size=32,
    lr=1e-3,
    weight_decay=1e-4,
    label_smoothing=0.05,
    warmup_epochs=3,

    base_ch=32,

    num_workers=0,
    seed=42,
    save_dir="./mad_corn_results_ffpp",
    device="auto",
    smoke_test=False,
)

# ============================================================
# HELPERS
# ============================================================

def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

def auto_device(requested):
    if requested != "auto":
        return torch.device(requested)
    return torch.device("cuda" if torch.cuda.is_available() else "cpu")

set_seed(CONFIG["seed"])
DEVICE = auto_device(CONFIG["device"])
os.makedirs(CONFIG["save_dir"], exist_ok=True)

print("Torch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
print("Device:", DEVICE)

# ============================================================
# RESULT CLASSES
# ============================================================

@dataclass
class EpochResult:
    epoch: int
    train_loss: float
    train_acc: float
    train_auc: float
    val_acc: float
    val_auc: float
    precision: float
    recall: float
    f1: float
    uncertain_rate: float
    lr: float

@dataclass
class TestResult:
    model_name: str
    accuracy: float
    auc: float
    precision: float
    recall: float
    f1: float
    uncertain_rate: float

@dataclass
class ResolutionResult:
    resolution: int
    accuracy: float
    auc: float
    fast_pct: float
    medium_pct: float
    full_pct: float

@dataclass
class InferenceResult:
    mode: str
    time_per_image_ms: float
    fps: float

@dataclass
class TrainingTimeResult:
    model_type: str
    minutes: float
    hours: float

# ============================================================
# MODEL
# ============================================================

class ConvBNReLU(nn.Module):
    def __init__(self, in_ch, out_ch, kernel=3, stride=1, padding=1, groups=1):
        super().__init__()
        self.block = nn.Sequential(
            nn.Conv2d(in_ch, out_ch, kernel, stride, padding, groups=groups, bias=False),
            nn.BatchNorm2d(out_ch),
            nn.ReLU6(inplace=True),
        )

    def forward(self, x):
        return self.block(x)

class DepthwiseSeparable(nn.Module):
    def __init__(self, in_ch, out_ch, stride=1):
        super().__init__()
        self.dw = ConvBNReLU(in_ch, in_ch, kernel=3, stride=stride, padding=1, groups=in_ch)
        self.pw = ConvBNReLU(in_ch, out_ch, kernel=1, padding=0)

    def forward(self, x):
        return self.pw(self.dw(x))

class ConvReservoir(nn.Module):
    def __init__(self, in_ch, reservoir_ch=64, spectral_radius=0.9):
        super().__init__()
        self.input_proj = nn.Conv2d(in_ch, reservoir_ch, kernel_size=1, bias=False)
        self.input_bn = nn.BatchNorm2d(reservoir_ch)

        W = torch.randn(reservoir_ch, reservoir_ch, 3, 3)
        W = W / (W.abs().max() + 1e-8) * spectral_radius
        self.register_buffer("W_res", W)

        self.readout = nn.Sequential(
            nn.Conv2d(reservoir_ch, reservoir_ch, kernel_size=1, bias=False),
            nn.BatchNorm2d(reservoir_ch),
            nn.ReLU6(inplace=True),
        )

    def forward(self, x):
        h = F.relu(self.input_bn(self.input_proj(x)))
        h_res = torch.tanh(F.conv2d(h, self.W_res, padding=1))
        return self.readout(h + h_res)

class ChannelAttention(nn.Module):
    def __init__(self, channels, reduction=4):
        super().__init__()
        mid = max(channels // reduction, 8)
        self.gate = nn.Sequential(
            nn.AdaptiveAvgPool2d(1),
            nn.Flatten(),
            nn.Linear(channels, mid),
            nn.ReLU(inplace=True),
            nn.Linear(mid, channels),
            nn.Sigmoid(),
        )

    def forward(self, x):
        w = self.gate(x).view(x.size(0), x.size(1), 1, 1)
        return x * w

class SpatialAttention(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = nn.Conv2d(2, 1, kernel_size=7, padding=3, bias=False)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        avg = x.mean(dim=1, keepdim=True)
        mx, _ = x.max(dim=1, keepdim=True)
        return x * self.sigmoid(self.conv(torch.cat([avg, mx], dim=1)))

class MultiScaleAttentionBlock(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()
        b_ch = out_ch // 3

        self.branch1 = DepthwiseSeparable(in_ch, b_ch)
        self.branch2 = nn.Sequential(
            DepthwiseSeparable(in_ch, b_ch),
            DepthwiseSeparable(b_ch, b_ch),
        )
        self.branch3 = nn.Sequential(
            DepthwiseSeparable(in_ch, b_ch),
            DepthwiseSeparable(b_ch, b_ch),
            DepthwiseSeparable(b_ch, b_ch),
        )

        self.fuse = ConvBNReLU(b_ch * 3, out_ch, kernel=1, padding=0)
        self.ca = ChannelAttention(out_ch)
        self.sa = SpatialAttention()

    def forward(self, x):
        f = self.fuse(torch.cat([self.branch1(x), self.branch2(x), self.branch3(x)], dim=1))
        return self.sa(self.ca(f))

class MaDCoRN(nn.Module):
    def __init__(self, in_ch=3, num_classes=2, base_ch=32):
        super().__init__()
        c = base_ch

        self.stem = nn.Sequential(
            ConvBNReLU(in_ch, c, kernel=3, stride=2, padding=1),
            ConvBNReLU(c, c * 2, kernel=3, stride=1, padding=1),
        )

        self.mad1 = MultiScaleAttentionBlock(c * 2, c * 4)
        self.mad2 = MultiScaleAttentionBlock(c * 4, c * 4)
        self.res1 = ConvReservoir(c * 4, c * 4)
        self.down1 = nn.Conv2d(c * 4, c * 4, kernel_size=3, stride=2, padding=1, bias=False)

        self.mad3 = MultiScaleAttentionBlock(c * 4, c * 8)
        self.mad4 = MultiScaleAttentionBlock(c * 8, c * 8)
        self.res2 = ConvReservoir(c * 8, c * 8)
        self.down2 = nn.Conv2d(c * 8, c * 8, kernel_size=3, stride=2, padding=1, bias=False)

        self.mad5 = MultiScaleAttentionBlock(c * 8, c * 16)
        self.mad6 = MultiScaleAttentionBlock(c * 16, c * 16)
        self.res3 = ConvReservoir(c * 16, c * 16)

        self.pool = nn.AdaptiveAvgPool2d(1)
        self.head = nn.Sequential(
            nn.Flatten(),
            nn.Linear(c * 16, 256),
            nn.ReLU(inplace=True),
            nn.Dropout(0.4),
            nn.Linear(256, num_classes),
        )

        self._init_weights()

    def _init_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, mode="fan_out", nonlinearity="relu")
            elif isinstance(m, nn.BatchNorm2d):
                nn.init.ones_(m.weight)
                nn.init.zeros_(m.bias)
            elif isinstance(m, nn.Linear):
                nn.init.trunc_normal_(m.weight, std=0.02)
                if m.bias is not None:
                    nn.init.zeros_(m.bias)

    def forward(self, x):
        x = self.stem(x)
        x = self.down1(self.res1(self.mad2(self.mad1(x))))
        x = self.down2(self.res2(self.mad4(self.mad3(x))))
        x = self.res3(self.mad6(self.mad5(x)))
        return self.head(self.pool(x))

    def count_parameters(self):
        total = sum(p.numel() for p in self.parameters())
        frozen = sum(p.numel() for p in self.parameters() if not p.requires_grad)
        return total, frozen

def freeze_reservoir_weights(model):
    for name, param in model.named_parameters():
        if "W_res" in name:
            param.requires_grad_(False)

# ============================================================
# DATASET
# ============================================================

class AddGaussianNoise:
    def __init__(self, std=0.01):
        self.std = std

    def __call__(self, t):
        return t + torch.randn_like(t) * self.std

class JPEGCompression:
    def __init__(self, quality_range=(60, 95)):
        self.lo, self.hi = quality_range

    def __call__(self, img):
        q = random.randint(self.lo, self.hi)
        buf = io.BytesIO()
        img.save(buf, format="JPEG", quality=q)
        buf.seek(0)
        return Image.open(buf).copy()

_MEAN = [0.485, 0.456, 0.406]
_STD = [0.229, 0.224, 0.225]

def build_transforms(source_resolution, split="train", image_size_for_model=224):
    """
    Source resolution simulates compression/downsampling.
    Final tensor size is always image_size_for_model.
    This prevents DataLoader stack errors.
    """
    if split == "train":
        return T.Compose([
            T.Resize((source_resolution, source_resolution)),
            T.Resize((image_size_for_model + 16, image_size_for_model + 16)),
            T.RandomCrop(image_size_for_model),
            T.RandomHorizontalFlip(p=0.5),
            T.RandomVerticalFlip(p=0.1),
            T.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.1, hue=0.05),
            T.RandomGrayscale(p=0.05),
            T.RandomApply([T.GaussianBlur(kernel_size=3)], p=0.15),
            JPEGCompression(quality_range=(60, 95)),
            T.ToTensor(),
            AddGaussianNoise(std=0.01),
            T.Normalize(_MEAN, _STD),
        ])

    return T.Compose([
        T.Resize((source_resolution, source_resolution)),
        T.Resize((image_size_for_model, image_size_for_model)),
        T.ToTensor(),
        T.Normalize(_MEAN, _STD),
    ])

def load_ffpp_splits(cfg):
    df = pd.read_csv(cfg["metadata_csv"])

    required = {"frame_path", "split", "label", "label_name", "video_id"}
    missing = required - set(df.columns)

    if missing:
        raise ValueError(f"metadata.csv missing columns: {missing}")

    df = df[df["frame_path"].apply(os.path.exists)].reset_index(drop=True)

    print("\nLoaded FF++ metadata")
    print("Total usable frames:", len(df))

    split_map = {}

    for split_name, key in [("Train", "train"), ("Val", "val"), ("Test", "test")]:
        sdf = df[df["split"].str.lower() == split_name.lower()].reset_index(drop=True)
        samples = [(row["frame_path"], int(row["label"])) for _, row in sdf.iterrows()]
        split_map[key] = samples

        real = int((sdf["label"] == 0).sum())
        fake = int((sdf["label"] == 1).sum())
        videos = sdf["video_id"].nunique()

        print(f"{split_name}: real={real}, fake={fake}, total={len(sdf)}, videos={videos}")

    return split_map

class MultiResolutionFFPPDataset(Dataset):
    def __init__(self, base_samples, resolutions, split="train", image_size_for_model=224):
        self.base_samples = list(base_samples)
        self.resolutions = list(resolutions)
        self.split = split
        self.image_size_for_model = image_size_for_model

        self.transforms = {
            res: build_transforms(res, split=split, image_size_for_model=image_size_for_model)
            for res in self.resolutions
        }

        if split == "train":
            self.samples = [(path, label, None) for path, label in self.base_samples]
        else:
            self.samples = [
                (path, label, res)
                for path, label in self.base_samples
                for res in self.resolutions
            ]

        n_real = sum(1 for _, label in self.base_samples if label == 0)
        n_fake = len(self.base_samples) - n_real

        print(
            f"[{split}] base: real={n_real:,}, fake={n_fake:,}, total={len(self.base_samples):,} | "
            f"effective={len(self.samples):,}"
        )

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        path, label, resolution = self.samples[idx]

        if resolution is None:
            resolution = random.choice(self.resolutions)

        try:
            img = Image.open(path).convert("RGB")
        except Exception:
            img = Image.fromarray(np.zeros((resolution, resolution, 3), dtype=np.uint8))

        x = self.transforms[resolution](img)
        y = torch.tensor(label, dtype=torch.long)

        return x, y

    def subset_for_resolution(self, resolution):
        return SingleResolutionView(
            self.base_samples,
            resolution,
            image_size_for_model=self.image_size_for_model,
        )

    @property
    def base_count(self):
        return len(self.base_samples)

    @property
    def expanded_count(self):
        return len(self.samples)

class SingleResolutionView(Dataset):
    def __init__(self, base_samples, resolution, image_size_for_model=224):
        self.base_samples = list(base_samples)
        self.resolution = resolution
        self.transform = build_transforms(
            resolution,
            split="val",
            image_size_for_model=image_size_for_model,
        )

    def __len__(self):
        return len(self.base_samples)

    def __getitem__(self, idx):
        path, label = self.base_samples[idx]

        try:
            img = Image.open(path).convert("RGB")
        except Exception:
            img = Image.fromarray(np.zeros((self.resolution, self.resolution, 3), dtype=np.uint8))

        x = self.transform(img)
        y = torch.tensor(label, dtype=torch.long)

        return x, y

def _make_loader(dataset, batch_size, num_workers, shuffle, drop_last):
    return DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,
        num_workers=num_workers,
        pin_memory=(DEVICE.type == "cuda"),
        persistent_workers=False,
    )

def print_dataset_summary(split_datasets, resolutions):
    print("\nDataset size summary")
    for name in ["train", "val", "test"]:
        ds = split_datasets[name]
        print(
            f"{name.title():<5} | base={ds.base_count:,}, "
            f"effective={ds.expanded_count:,}, resolutions={resolutions}"
        )

    print("\nStrategy:")
    print("  Train: one random source resolution per image per epoch")
    print("  Val:   all requested source resolutions per image")
    print("  Test:  all requested source resolutions per image")
    print(f"  Model input tensor size: (3, {CONFIG['image_size_for_model']}, {CONFIG['image_size_for_model']})")

def make_dataloaders(cfg):
    split_map = load_ffpp_splits(cfg)
    resolutions = list(cfg["resolutions"])

    split_datasets = {
        "train": MultiResolutionFFPPDataset(
            split_map["train"],
            resolutions,
            split="train",
            image_size_for_model=cfg["image_size_for_model"],
        ),
        "val": MultiResolutionFFPPDataset(
            split_map["val"],
            resolutions,
            split="val",
            image_size_for_model=cfg["image_size_for_model"],
        ),
        "test": MultiResolutionFFPPDataset(
            split_map["test"],
            resolutions,
            split="test",
            image_size_for_model=cfg["image_size_for_model"],
        ),
    }

    print_dataset_summary(split_datasets, resolutions)

    loaders = {
        "train": _make_loader(
            split_datasets["train"],
            cfg["batch_size"],
            cfg["num_workers"],
            shuffle=True,
            drop_last=True,
        ),
        "val": _make_loader(
            split_datasets["val"],
            cfg["batch_size"],
            cfg["num_workers"],
            shuffle=False,
            drop_last=False,
        ),
        "test": _make_loader(
            split_datasets["test"],
            cfg["batch_size"],
            cfg["num_workers"],
            shuffle=False,
            drop_last=False,
        ),
    }

    return {
        "loaders": loaders,
        "datasets": split_datasets,
        "base_splits": split_map,
    }

def make_smoke_loader(resolution, n=200, bs=8):
    imgs = torch.randn(n, 3, CONFIG["image_size_for_model"], CONFIG["image_size_for_model"])
    labels = torch.randint(0, 2, (n,))
    return DataLoader(TensorDataset(imgs, labels), batch_size=bs, shuffle=True)

# ============================================================
# TRAINING
# ============================================================

def compute_uncertain_rate(probs, threshold=0.65):
    conf = probs.max(axis=1)
    return float(np.mean(conf < threshold) * 100)

def run_epoch(model, loader, criterion, optimizer, device, scaler=None, is_train=True, desc=None):
    model.train(is_train)

    total_loss = 0.0
    seen = 0
    all_probs, all_preds, all_labels = [], [], []

    pbar = tqdm(
        loader,
        total=len(loader) if hasattr(loader, "__len__") else None,
        desc=desc or ("Train" if is_train else "Eval"),
        leave=False,
        dynamic_ncols=True,
        mininterval=0.5,
    )

    with torch.set_grad_enabled(is_train):
        for imgs, labels in pbar:
            imgs = imgs.to(device, non_blocking=True)
            labels = labels.to(device, non_blocking=True)

            if is_train:
                optimizer.zero_grad(set_to_none=True)

            if is_train and scaler:
                with autocast():
                    logits = model(imgs)
                    loss = criterion(logits, labels)

                scaler.scale(loss).backward()
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                scaler.step(optimizer)
                scaler.update()

            else:
                logits = model(imgs)
                loss = criterion(logits, labels)

                if is_train:
                    loss.backward()
                    torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                    optimizer.step()

            probs = torch.softmax(logits.float(), dim=1).detach().cpu().numpy()
            preds = probs.argmax(axis=1)

            all_probs.append(probs)
            all_preds.append(preds)
            all_labels.append(labels.detach().cpu().numpy())

            batch_n = len(labels)
            total_loss += loss.item() * batch_n
            seen += batch_n

            pbar.set_postfix(loss=f"{loss.item():.4f}", samples=f"{seen:,}")

    all_probs = np.vstack(all_probs)
    all_preds = np.concatenate(all_preds)
    all_labels = np.concatenate(all_labels)

    acc = accuracy_score(all_labels, all_preds)

    try:
        auc = roc_auc_score(all_labels, all_probs[:, 1])
    except ValueError:
        auc = 0.5

    precision = precision_score(all_labels, all_preds, zero_division=0)
    recall = recall_score(all_labels, all_preds, zero_division=0)
    f1 = f1_score(all_labels, all_preds, zero_division=0)
    uncertain_rate = compute_uncertain_rate(all_probs)

    return {
        "loss": total_loss / max(seen, 1),
        "acc": acc,
        "auc": auc,
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "uncertain_rate": uncertain_rate,
        "probs": all_probs,
        "preds": all_preds,
        "labels": all_labels,
    }

class Trainer:
    def __init__(self, model, train_loader, val_loader, test_loader, device, cfg, ckpt_path):
        self.model = model.to(device)
        self.train_loader = train_loader
        self.val_loader = val_loader
        self.test_loader = test_loader
        self.device = device
        self.epochs = cfg["epochs"]
        self.ckpt_path = ckpt_path
        self.model_name = "MaD-CoRN-FFPP"

        self.criterion = nn.CrossEntropyLoss(label_smoothing=cfg["label_smoothing"])

        self.optimizer = optim.AdamW(
            [p for p in model.parameters() if p.requires_grad],
            lr=cfg["lr"],
            weight_decay=cfg["weight_decay"],
        )

        total_steps = self.epochs
        warmup_steps = cfg["warmup_epochs"]

        def lr_lambda(epoch):
            if epoch < warmup_steps:
                return max(1e-8, epoch / max(1, warmup_steps))
            prog = (epoch - warmup_steps) / max(1, total_steps - warmup_steps)
            return 0.5 * (1.0 + math.cos(math.pi * prog))

        self.scheduler = optim.lr_scheduler.LambdaLR(self.optimizer, lr_lambda)
        self.scaler = GradScaler() if device.type == "cuda" else None
        self.epoch_results = []

    def train(self):
        best_auc = -1.0
        t0 = time.time()

        for epoch in range(1, self.epochs + 1):
            tr = run_epoch(
                self.model,
                self.train_loader,
                self.criterion,
                self.optimizer,
                self.device,
                self.scaler,
                is_train=True,
                desc=f"Epoch {epoch}/{self.epochs} [train]",
            )

            with torch.no_grad():
                vl = run_epoch(
                    self.model,
                    self.val_loader,
                    self.criterion,
                    None,
                    self.device,
                    None,
                    is_train=False,
                    desc=f"Epoch {epoch}/{self.epochs} [val]",
                )

            self.scheduler.step()
            lr_now = self.optimizer.param_groups[0]["lr"]

            er = EpochResult(
                epoch=epoch,
                train_loss=tr["loss"],
                train_acc=tr["acc"],
                train_auc=tr["auc"],
                val_acc=vl["acc"],
                val_auc=vl["auc"],
                precision=vl["precision"],
                recall=vl["recall"],
                f1=vl["f1"],
                uncertain_rate=vl["uncertain_rate"],
                lr=lr_now,
            )

            self.epoch_results.append(er)

            print(
                f"Epoch {epoch:3d}/{self.epochs} | "
                f"Loss {er.train_loss:.4f} | "
                f"Tr Acc {er.train_acc:.4f} AUC {er.train_auc:.4f} | "
                f"Val Acc {er.val_acc:.4f} AUC {er.val_auc:.4f} | "
                f"P {er.precision:.4f} R {er.recall:.4f} F1 {er.f1:.4f} | "
                f"Unc {er.uncertain_rate:.1f}% | LR {lr_now:.2e}"
            )

            if vl["auc"] > best_auc:
                best_auc = vl["auc"]
                torch.save(self.model.state_dict(), self.ckpt_path)
                print(f"Checkpoint saved. Val AUC = {best_auc:.4f}")

        return self.epoch_results, (time.time() - t0) / 60

    def evaluate(self, loader=None, load_best=True):
        if load_best and os.path.exists(self.ckpt_path):
            self.model.load_state_dict(torch.load(self.ckpt_path, map_location=self.device))

        loader = loader or self.test_loader

        with torch.no_grad():
            r = run_epoch(
                self.model,
                loader,
                self.criterion,
                None,
                self.device,
                None,
                is_train=False,
                desc="Test evaluation",
            )

        return TestResult(
            model_name=self.model_name,
            accuracy=r["acc"],
            auc=r["auc"],
            precision=r["precision"],
            recall=r["recall"],
            f1=r["f1"],
            uncertain_rate=r["uncertain_rate"],
        )

# ============================================================
# EVAL / TIMING
# ============================================================

@torch.no_grad()
def measure_inference(model, resolution, device, image_size_for_model=224, batch_size=32, n_warmup=20, n_runs=200):
    model.eval()
    results = []

    for bs, label in [(1, "Single"), (batch_size, f"Batch={batch_size}")]:
        dummy = torch.randn(bs, 3, image_size_for_model, image_size_for_model, device=device)

        for _ in range(n_warmup):
            model(dummy)

        if device.type == "cuda":
            torch.cuda.synchronize()

        t0 = time.perf_counter()

        for _ in range(n_runs):
            model(dummy)

        if device.type == "cuda":
            torch.cuda.synchronize()

        elapsed = time.perf_counter() - t0
        total = bs * n_runs

        results.append(
            InferenceResult(
                mode=f"Source Res={resolution} {label}",
                time_per_image_ms=elapsed / total * 1000,
                fps=total / elapsed,
            )
        )

    return results

@torch.no_grad()
def evaluate_by_resolution(model, loader, device, resolution):
    model.eval()

    all_probs, all_labels = [], []
    buckets = {"fast": 0, "medium": 0, "full": 0}
    total = 0

    pbar = tqdm(
        loader,
        total=len(loader) if hasattr(loader, "__len__") else None,
        desc=f"Resolution {resolution} eval",
        leave=False,
        dynamic_ncols=True,
        mininterval=0.5,
    )

    for imgs, labels in pbar:
        imgs = imgs.to(device, non_blocking=True)
        bs = imgs.size(0)

        if device.type == "cuda":
            torch.cuda.synchronize()

        t0 = time.perf_counter()
        logits = model(imgs)

        if device.type == "cuda":
            torch.cuda.synchronize()

        ms = (time.perf_counter() - t0) / bs * 1000

        probs = torch.softmax(logits.float(), dim=1).cpu().numpy()

        all_probs.append(probs)
        all_labels.append(labels.numpy())

        if ms < 5:
            buckets["fast"] += bs
        elif ms < 20:
            buckets["medium"] += bs
        else:
            buckets["full"] += bs

        total += bs
        pbar.set_postfix(samples=f"{total:,}", ms_per_img=f"{ms:.3f}")

    all_probs = np.vstack(all_probs)
    all_labels = np.concatenate(all_labels)
    preds = all_probs.argmax(axis=1)

    acc = accuracy_score(all_labels, preds)

    try:
        auc = roc_auc_score(all_labels, all_probs[:, 1])
    except ValueError:
        auc = 0.5

    return ResolutionResult(
        resolution=resolution,
        accuracy=acc,
        auc=auc,
        fast_pct=buckets["fast"] / max(total, 1) * 100,
        medium_pct=buckets["medium"] / max(total, 1) * 100,
        full_pct=buckets["full"] / max(total, 1) * 100,
    )

# ============================================================
# REPORTING
# ============================================================

def _table(headers, rows, title=""):
    col_w = [
        max(len(str(h)), max((len(str(r[i])) for r in rows), default=0))
        for i, h in enumerate(headers)
    ]

    sep = "+" + "+".join("-" * (w + 2) for w in col_w) + "+"
    hdr = "|" + "|".join(f" {h:<{w}} " for h, w in zip(headers, col_w)) + "|"

    body = [
        "|" + "|".join(f" {str(v):<{w}} " for v, w in zip(r, col_w)) + "|"
        for r in rows
    ]

    out = [sep, hdr, sep] + body + [sep]

    if title:
        out.insert(0, title.center(len(sep)))
        out.insert(1, "")

    return "\n".join(out)

def print_training_table(ers):
    h = [
        "Epoch", "Train Loss", "Train Acc", "Train AUC",
        "Val Acc", "Val AUC", "Precision", "Recall", "F1",
        "Uncertain Rate (%)"
    ]

    rows = [
        [
            e.epoch,
            f"{e.train_loss:.4f}",
            f"{e.train_acc:.4f}",
            f"{e.train_auc:.4f}",
            f"{e.val_acc:.4f}",
            f"{e.val_auc:.4f}",
            f"{e.precision:.4f}",
            f"{e.recall:.4f}",
            f"{e.f1:.4f}",
            f"{e.uncertain_rate:.2f}",
        ]
        for e in ers
    ]

    t = _table(h, rows, "Training Periods Results")
    print(t)
    return t

def print_test_table(trs):
    h = ["Model", "Accuracy", "AUC", "Precision", "Recall", "F1", "Uncertain Rate (%)"]

    rows = [
        [
            r.model_name,
            f"{r.accuracy:.4f}",
            f"{r.auc:.4f}",
            f"{r.precision:.4f}",
            f"{r.recall:.4f}",
            f"{r.f1:.4f}",
            f"{r.uncertain_rate:.2f}",
        ]
        for r in trs
    ]

    t = _table(h, rows, "Test Results")
    print(t)
    return t

def print_resolution_table(rrs):
    h = ["Resolution", "Accuracy", "AUC", "Fast (%)", "Medium (%)", "Full (%)"]

    rows = [
        [
            r.resolution,
            f"{r.accuracy:.4f}",
            f"{r.auc:.4f}",
            f"{r.fast_pct:.2f}",
            f"{r.medium_pct:.2f}",
            f"{r.full_pct:.2f}",
        ]
        for r in rrs
    ]

    t = _table(h, rows, "Accuracy Based on Resolution")
    print(t)
    return t

def print_inference_table(irs):
    h = ["Mode", "Time per Image (ms)", "FPS"]

    rows = [
        [r.mode, f"{r.time_per_image_ms:.3f}", f"{r.fps:.1f}"]
        for r in irs
    ]

    t = _table(h, rows, "Inference Time")
    print(t)
    return t

def print_training_time_table(tts):
    h = ["Model Type", "min", "hrs"]

    rows = [
        [r.model_type, f"{r.minutes:.1f}", f"{r.hours:.2f}"]
        for r in tts
    ]

    t = _table(h, rows, "Training Time")
    print(t)
    return t

def save_all_results(epoch_results, test_results, res_results, inf_results, tt_results, save_dir):
    os.makedirs(save_dir, exist_ok=True)

    data = {
        "epoch_results": [asdict(e) for e in epoch_results],
        "test_results": [asdict(t) for t in test_results],
        "res_results": [asdict(r) for r in res_results],
        "inference": [asdict(i) for i in inf_results],
        "training_time": [asdict(t) for t in tt_results],
    }

    with open(os.path.join(save_dir, "mad_corn_results.json"), "w") as f:
        json.dump(data, f, indent=2)

    for name, rows in data.items():
        if rows:
            pd.DataFrame(rows).to_csv(os.path.join(save_dir, f"mad_corn_{name}.csv"), index=False)

    print("\nResults saved to:", save_dir)

def print_full_report(epoch_results, test_results, res_results, inf_results, tt_results, save_dir):
    div = "=" * 100

    print("\n" + div)
    print("MaD-CoRN EXPERIMENT RESULTS".center(100, "="))
    print(div)

    print("\n[1] TRAINING PERIODS RESULTS")
    print_training_table(epoch_results)

    print("\n[2] TEST RESULTS")
    print_test_table(test_results)

    print("\n[3] ACCURACY BASED ON RESOLUTION")
    print_resolution_table(res_results)

    print("\n[4] INFERENCE TIME")
    print_inference_table(inf_results)

    print("\n[5] TRAINING TIME")
    print_training_time_table(tt_results)

    save_all_results(epoch_results, test_results, res_results, inf_results, tt_results, save_dir)

# ============================================================
# PIPELINE
# ============================================================

def run_pipeline(cfg):
    set_seed(cfg["seed"])
    device = auto_device(cfg["device"])
    os.makedirs(cfg["save_dir"], exist_ok=True)

    print("\n" + "=" * 70)
    print("MaD-CoRN Pipeline FF++")
    print("Device:", device)
    print("Source resolutions:", cfg["resolutions"])
    print("Model input size:", cfg["image_size_for_model"])
    print("Epochs:", cfg["epochs"])
    print("Smoke test:", cfg["smoke_test"])
    print("=" * 70)

    model = MaDCoRN(in_ch=3, num_classes=2, base_ch=cfg["base_ch"])
    freeze_reservoir_weights(model)

    total, frozen = model.count_parameters()
    print(f"\nModel params: {total:,} total | {frozen:,} frozen")

    split_datasets = None

    if cfg["smoke_test"]:
        print("\nSMOKE TEST")
        bs = cfg["batch_size"]
        train_loader = make_smoke_loader(cfg["image_size_for_model"], n=320, bs=bs)
        val_loader = make_smoke_loader(cfg["image_size_for_model"], n=80, bs=bs)
        test_loader = make_smoke_loader(cfg["image_size_for_model"], n=80, bs=bs)
        cfg = {**cfg, "epochs": min(cfg["epochs"], 3)}
    else:
        print("\nLoading FF++ dataset...")
        data_bundle = make_dataloaders(cfg)
        split_datasets = data_bundle["datasets"]
        train_loader = data_bundle["loaders"]["train"]
        val_loader = data_bundle["loaders"]["val"]
        test_loader = data_bundle["loaders"]["test"]

    ckpt_path = os.path.join(cfg["save_dir"], "mad_corn_ffpp_multires.pt")

    print("\n" + "-" * 60)
    print("TRAINING")
    print("-" * 60)

    trainer = Trainer(
        model,
        train_loader,
        val_loader,
        test_loader,
        device,
        cfg,
        ckpt_path,
    )

    epoch_results, training_min = trainer.train()

    print(f"\nTraining done: {training_min:.1f} min ({training_min / 60:.2f} hrs)")

    print("\n" + "-" * 60)
    print("TEST EVALUATION ON COMBINED MULTI-RES TEST SET")
    print("-" * 60)

    test_result = trainer.evaluate(test_loader, load_best=True)
    test_results = [test_result]

    print("\n" + "-" * 60)
    print("PER-RESOLUTION BREAKDOWN")
    print("-" * 60)

    res_results = []
    inf_results = []

    for res in tqdm(cfg["resolutions"], desc="Resolution sweep", dynamic_ncols=True):
        print(f"\nResolution {res}")

        if cfg["smoke_test"]:
            res_loader = make_smoke_loader(cfg["image_size_for_model"], n=80, bs=cfg["batch_size"])
        else:
            res_ds = split_datasets["test"].subset_for_resolution(res)
            res_loader = DataLoader(
                res_ds,
                batch_size=cfg["batch_size"],
                shuffle=False,
                num_workers=cfg["num_workers"],
                pin_memory=(device.type == "cuda"),
                persistent_workers=False,
            )

        rr = evaluate_by_resolution(model, res_loader, device, res)
        res_results.append(rr)

        print(
            f"Acc={rr.accuracy:.4f} AUC={rr.auc:.4f} "
            f"Fast={rr.fast_pct:.2f}% Medium={rr.medium_pct:.2f}% Full={rr.full_pct:.2f}%"
        )

        infs = measure_inference(
            model,
            res,
            device,
            image_size_for_model=cfg["image_size_for_model"],
            batch_size=cfg["batch_size"],
        )
        inf_results.extend(infs)

        for ir in infs:
            print(f"{ir.mode}: {ir.time_per_image_ms:.3f} ms/img | {ir.fps:.1f} FPS")

    tt_results = [
        TrainingTimeResult(
            model_type="MaD-CoRN FF++ multi-resolution training",
            minutes=training_min,
            hours=training_min / 60,
        )
    ]

    print_full_report(
        epoch_results,
        test_results,
        res_results,
        inf_results,
        tt_results,
        cfg["save_dir"],
    )

    return {
        "epoch_results": epoch_results,
        "test_results": test_results,
        "res_results": res_results,
        "inf_results": inf_results,
        "tt_results": tt_results,
        "model": model,
        "trainer": trainer,
        "split_datasets": split_datasets,
    }

results = run_pipeline(CONFIG)

Torch: 2.11.0+cu130
CUDA available: True
Device: cuda

======================================================================
MaD-CoRN Pipeline FF++
Device: cuda
Source resolutions: [128, 224, 256, 384]
Model input size: 224
Epochs: 15
Smoke test: False
======================================================================

Model params: 3,428,062 total | 0 frozen

Loading FF++ dataset...

Loaded FF++ metadata
Total usable frames: 55953
Train: real=6400, fake=38356, total=44756, videos=5600
Val: real=800, fake=4800, total=5600, videos=700
Test: real=800, fake=4797, total=5597, videos=700
[train] base: real=6,400, fake=38,356, total=44,756 | effective=44,756
[val] base: real=800, fake=4,800, total=5,600 | effective=22,400
[test] base: real=800, fake=4,797, total=5,597 | effective=22,388

Dataset size summary
Train | base=44,756, effective=44,756, resolutions=[128, 224, 256, 384]
Val   | base=5,600, effective=22,400, resolutions=[128, 224, 256, 384]
Test  | base=5,597, effective=22,388, resolutions=[128, 224, 256, 384]

Strategy:
  Train: one random source resolution per image per epoch
  Val:   all requested source resolutions per image
  Test:  all requested source resolutions per image
  Model input tensor size: (3, 224, 224)

------------------------------------------------------------
TRAINING
------------------------------------------------------------

Epoch   1/15 | Loss 0.7403 | Tr Acc 0.1444 AUC 0.4939 | Val Acc 0.1429 AUC 0.4981 | P 0.0000 R 0.0000 F1 0.0000 | Unc 100.0% | LR 3.33e-04
Checkpoint saved. Val AUC = 0.4981

Epoch   2/15 | Loss 0.4496 | Tr Acc 0.8565 AUC 0.5112 | Val Acc 0.8571 AUC 0.5343 | P 0.8571 R 1.0000 F1 0.9231 | Unc 0.0% | LR 6.67e-04
Checkpoint saved. Val AUC = 0.5343

Epoch   3/15 | Loss 0.4514 | Tr Acc 0.8570 AUC 0.5214 | Val Acc 0.8571 AUC 0.5348 | P 0.8571 R 1.0000 F1 0.9231 | Unc 0.0% | LR 1.00e-03
Checkpoint saved. Val AUC = 0.5348

Epoch   5/15 | Loss 0.4404 | Tr Acc 0.8570 AUC 0.5411 | Val Acc 0.8571 AUC 0.5376 | P 0.8571 R 1.0000 F1 0.9231 | Unc 0.0% | LR 9.33e-04
Checkpoint saved. Val AUC = 0.5376

Epoch 6/15 [train]:  70%|███████   | 984/1398 [32:47<13:12,  1.91s/it, loss=0.5847, samples=31,488]IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)

Epoch   6/15 | Loss 0.4390 | Tr Acc 0.8571 AUC 0.5526 | Val Acc 0.8571 AUC 0.5680 | P 0.8571 R 1.0000 F1 0.9231 | Unc 0.0% | LR 8.54e-04
Checkpoint saved. Val AUC = 0.5680

Epoch 7/15 [train]:  67%|██████▋   | 934/1398 [24:42<14:12,  1.84s/it, loss=0.4041, samples=29,888]IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)

Epoch   8/15 | Loss 0.4367 | Tr Acc 0.8570 AUC 0.5643 | Val Acc 0.8571 AUC 0.5536 | P 0.8571 R 1.0000 F1 0.9231 | Unc 0.0% | LR 6.29e-04

Epoch 9/15 [train]:  40%|███▉      | 554/1398 [14:19<22:53,  1.63s/it, loss=0.5562, samples=17,728]IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)

Epoch   9/15 | Loss 0.4345 | Tr Acc 0.8570 AUC 0.5699 | Val Acc 0.8571 AUC 0.5723 | P 0.8571 R 1.0000 F1 0.9231 | Unc 0.0% | LR 5.00e-04

Epoch  10/15 | Loss 0.4330 | Tr Acc 0.8570 AUC 0.5731 | Val Acc 0.8571 AUC 0.5754 | P 0.8571 R 1.0000 F1 0.9231 | Unc 0.0% | LR 3.71e-04

Epoch 11/15 [train]:  10%|█         | 140/1398 [03:08<28:22,  1.35s/it, loss=0.3089, samples=4,480]IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)

Epoch  11/15 | Loss 0.4314 | Tr Acc 0.8570 AUC 0.5715 | Val Acc 0.8571 AUC 0.5447 | P 0.8571 R 1.0000 F1 0.9231 | Unc 0.0% | LR 2.50e-04

Epoch 12/15 [train]:  66%|██████▌   | 918/1398 [21:42<10:00,  1.25s/it, loss=0.2548, samples=29,376]IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)

Epoch  13/15 | Loss 0.4291 | Tr Acc 0.8570 AUC 0.5866 | Val Acc 0.8571 AUC 0.5316 | P 0.8571 R 1.0000 F1 0.9231 | Unc 0.0% | LR 6.70e-05

Epoch  14/15 | Loss 0.4284 | Tr Acc 0.8570 AUC 0.5853 | Val Acc 0.8571 AUC 0.5237 | P 0.8571 R 1.0000 F1 0.9231 | Unc 0.0% | LR 1.70e-05

Epoch  15/15 | Loss 0.4279 | Tr Acc 0.8571 AUC 0.5825 | Val Acc 0.8571 AUC 0.5330 | P 0.8571 R 1.0000 F1 0.9231 | Unc 0.0% | LR 0.00e+00

Training done: 646.9 min (10.78 hrs)

------------------------------------------------------------
TEST EVALUATION ON COMBINED MULTI-RES TEST SET
------------------------------------------------------------

------------------------------------------------------------
PER-RESOLUTION BREAKDOWN
------------------------------------------------------------

Resolution sweep:   0%|          | 0/4 [00:00<?, ?it/s]

Resolution 128

Resolution 128 eval:   0%|          | 0/175 [00:00<?, ?it/s]
Resolution 128 eval:   0%|          | 0/175 [00:02<?, ?it/s, ms_per_img=1.789, samples=32]
Resolution 128 eval:   1%|          | 1/175 [00:02<05:49,  2.01s/it, ms_per_img=1.789, samples=32]
Resolution 128 eval:   1%|          | 1/175 [00:03<05:49,  2.01s/it, ms_per_img=1.775, samples=64]
Resolution 128 eval:   1%|          | 2/175 [00:03<04:42,  1.63s/it, ms_per_img=1.775, samples=64]
Resolution 128 eval:   1%|          | 2/175 [00:07<04:42,  1.63s/it, ms_per_img=1.773, samples=96]
Resolution 128 eval:   2%|▏         | 3/175 [00:07<07:17,  2.55s/it, ms_per_img=1.773, samples=96]
Resolution 128 eval:   2%|▏         | 3/175 [00:09<07:17,  2.55s/it, ms_per_img=1.775, samples=128]
Resolution 128 eval:   2%|▏         | 4/175 [00:09<07:26,  2.61s/it, ms_per_img=1.775, samples=128]
Resolution 128 eval:   2%|▏         | 4/175 [00:12<07:26,  2.61s/it, ms_per_img=1.773, samples=160]
Resolution 128 eval:   3%|▎         | 5/175 [00:12<07:13,  2.55s/it, ms_per_img=1.773, samples=160]
Resolution 128 eval:   3%|▎         | 5/175 [00:15<07:13,  2.55s/it, ms_per_img=1.777, samples=192]
Resolution 128 eval:   3%|▎         | 6/175 [00:15<07:33,  2.68s/it, ms_per_img=1.777, samples=192]
Resolution 128 eval:   3%|▎         | 6/175 [00:16<07:33,  2.68s/it, ms_per_img=1.774, samples=224]
Resolution 128 eval:   4%|▍         | 7/175 [00:16<06:29,  2.32s/it, ms_per_img=1.774, samples=224]
Resolution 128 eval:   4%|▍         | 7/175 [00:17<06:29,  2.32s/it, ms_per_img=1.774, samples=256]
Resolution 128 eval:   5%|▍         | 8/175 [00:17<05:13,  1.88s/it, ms_per_img=1.774, samples=256]
Resolution 128 eval:   5%|▍         | 8/175 [00:18<05:13,  1.88s/it, ms_per_img=1.777, samples=288]
Resolution 128 eval:   5%|▌         | 9/175 [00:18<04:24,  1.59s/it, ms_per_img=1.777, samples=288]
Resolution 128 eval:   5%|▌         | 9/175 [00:20<04:24,  1.59s/it, ms_per_img=1.775, samples=320]
Resolution 128 eval:   6%|▌         | 10/175 [00:20<04:31,  1.64s/it, ms_per_img=1.775, samples=320]
Resolution 128 eval:   6%|▌         | 10/175 [00:22<04:31,  1.64s/it, ms_per_img=1.776, samples=352]
Resolution 128 eval:   6%|▋         | 11/175 [00:22<04:41,  1.71s/it, ms_per_img=1.776, samples=352]
Resolution 128 eval:   6%|▋         | 11/175 [00:22<04:41,  1.71s/it, ms_per_img=1.773, samples=384]
Resolution 128 eval:   7%|▋         | 12/175 [00:22<03:53,  1.43s/it, ms_per_img=1.773, samples=384]
Resolution 128 eval:   7%|▋         | 12/175 [00:23<03:53,  1.43s/it, ms_per_img=1.773, samples=416]
Resolution 128 eval:   7%|▋         | 13/175 [00:23<03:27,  1.28s/it, ms_per_img=1.773, samples=416]
Resolution 128 eval:   7%|▋         | 13/175 [00:24<03:27,  1.28s/it, ms_per_img=1.775, samples=448]
Resolution 128 eval:   8%|▊         | 14/175 [00:24<03:06,  1.16s/it, ms_per_img=1.775, samples=448]
Resolution 128 eval:   8%|▊         | 14/175 [00:25<03:06,  1.16s/it, ms_per_img=1.775, samples=480]
Resolution 128 eval:   9%|▊         | 15/175 [00:25<02:54,  1.09s/it, ms_per_img=1.775, samples=480]
Resolution 128 eval:   9%|▊         | 15/175 [00:27<02:54,  1.09s/it, ms_per_img=1.775, samples=512]
Resolution 128 eval:   9%|▉         | 16/175 [00:27<03:19,  1.25s/it, ms_per_img=1.775, samples=512]
Resolution 128 eval:   9%|▉         | 16/175 [00:29<03:19,  1.25s/it, ms_per_img=1.774, samples=544]
Resolution 128 eval:  10%|▉         | 17/175 [00:29<04:00,  1.52s/it, ms_per_img=1.774, samples=544]
Resolution 128 eval:  10%|▉         | 17/175 [00:30<04:00,  1.52s/it, ms_per_img=1.773, samples=576]
Resolution 128 eval:  10%|█         | 18/175 [00:30<03:21,  1.28s/it, ms_per_img=1.773, samples=576]
Resolution 128 eval:  10%|█         | 18/175 [00:31<03:21,  1.28s/it, ms_per_img=1.774, samples=608]
Resolution 128 eval:  11%|█         | 19/175 [00:31<03:00,  1.15s/it, ms_per_img=1.774, samples=608]
Resolution 128 eval:  11%|█         | 19/175 [00:31<03:00,  1.15s/it, ms_per_img=1.774, samples=640]
Resolution 128 eval:  11%|█▏        | 20/175 [00:31<02:45,  1.07s/it, ms_per_img=1.774, samples=640]
Resolution 128 eval:  11%|█▏        | 20/175 [00:32<02:45,  1.07s/it, ms_per_img=1.777, samples=672]
Resolution 128 eval:  12%|█▏        | 21/175 [00:32<02:21,  1.08it/s, ms_per_img=1.777, samples=672]
Resolution 128 eval:  12%|█▏        | 21/175 [00:33<02:21,  1.08it/s, ms_per_img=1.773, samples=704]
Resolution 128 eval:  13%|█▎        | 22/175 [00:33<02:22,  1.08it/s, ms_per_img=1.773, samples=704]
Resolution 128 eval:  13%|█▎        | 22/175 [00:34<02:22,  1.08it/s, ms_per_img=1.774, samples=736]
Resolution 128 eval:  13%|█▎        | 23/175 [00:34<02:14,  1.13it/s, ms_per_img=1.774, samples=736]
Resolution 128 eval:  13%|█▎        | 23/175 [00:35<02:14,  1.13it/s, ms_per_img=1.773, samples=768]
Resolution 128 eval:  14%|█▎        | 24/175 [00:35<02:15,  1.12it/s, ms_per_img=1.773, samples=768]
Resolution 128 eval:  14%|█▎        | 24/175 [00:35<02:15,  1.12it/s, ms_per_img=1.775, samples=800]
Resolution 128 eval:  14%|█▍        | 25/175 [00:35<02:08,  1.16it/s, ms_per_img=1.775, samples=800]
Resolution 128 eval:  14%|█▍        | 25/175 [00:36<02:08,  1.16it/s, ms_per_img=1.774, samples=832]
Resolution 128 eval:  15%|█▍        | 26/175 [00:36<02:02,  1.21it/s, ms_per_img=1.774, samples=832]
Resolution 128 eval:  15%|█▍        | 26/175 [00:37<02:02,  1.21it/s, ms_per_img=1.774, samples=864]
Resolution 128 eval:  15%|█▌        | 27/175 [00:37<02:00,  1.22it/s, ms_per_img=1.774, samples=864]
Resolution 128 eval:  15%|█▌        | 27/175 [00:38<02:00,  1.22it/s, ms_per_img=1.774, samples=896]
Resolution 128 eval:  16%|█▌        | 28/175 [00:38<02:08,  1.15it/s, ms_per_img=1.774, samples=896]
Resolution 128 eval:  16%|█▌        | 28/175 [00:39<02:08,  1.15it/s, ms_per_img=1.774, samples=928]
Resolution 128 eval:  17%|█▋        | 29/175 [00:39<02:01,  1.20it/s, ms_per_img=1.774, samples=928]
Resolution 128 eval:  17%|█▋        | 29/175 [00:39<02:01,  1.20it/s, ms_per_img=1.774, samples=960]
Resolution 128 eval:  17%|█▋        | 30/175 [00:39<01:55,  1.26it/s, ms_per_img=1.774, samples=960]
Resolution 128 eval:  17%|█▋        | 30/175 [00:41<01:55,  1.26it/s, ms_per_img=1.773, samples=992]
Resolution 128 eval:  18%|█▊        | 31/175 [00:41<02:18,  1.04it/s, ms_per_img=1.773, samples=992]
Resolution 128 eval:  18%|█▊        | 31/175 [00:42<02:18,  1.04it/s, ms_per_img=1.774, samples=1,024]
Resolution 128 eval:  18%|█▊        | 32/175 [00:42<02:33,  1.07s/it, ms_per_img=1.774, samples=1,024]
Resolution 128 eval:  18%|█▊        | 32/175 [00:43<02:33,  1.07s/it, ms_per_img=1.774, samples=1,056]
Resolution 128 eval:  19%|█▉        | 33/175 [00:43<02:15,  1.05it/s, ms_per_img=1.774, samples=1,056]
Resolution 128 eval:  19%|█▉        | 33/175 [00:44<02:15,  1.05it/s, ms_per_img=1.776, samples=1,088]
Resolution 128 eval:  19%|█▉        | 34/175 [00:44<02:38,  1.12s/it, ms_per_img=1.776, samples=1,088]
Resolution 128 eval:  19%|█▉        | 34/175 [00:46<02:38,  1.12s/it, ms_per_img=1.777, samples=1,120]
Resolution 128 eval:  20%|██        | 35/175 [00:46<02:46,  1.19s/it, ms_per_img=1.777, samples=1,120]
Resolution 128 eval:  20%|██        | 35/175 [00:47<02:46,  1.19s/it, ms_per_img=1.774, samples=1,152]
Resolution 128 eval:  21%|██        | 36/175 [00:47<02:35,  1.12s/it, ms_per_img=1.774, samples=1,152]
Resolution 128 eval:  21%|██        | 36/175 [00:48<02:35,  1.12s/it, ms_per_img=1.774, samples=1,184]
Resolution 128 eval:  21%|██        | 37/175 [00:48<02:26,  1.06s/it, ms_per_img=1.774, samples=1,184]
Resolution 128 eval:  21%|██        | 37/175 [00:48<02:26,  1.06s/it, ms_per_img=1.775, samples=1,216]
Resolution 128 eval:  22%|██▏       | 38/175 [00:48<02:05,  1.09it/s, ms_per_img=1.775, samples=1,216]
Resolution 128 eval:  22%|██▏       | 38/175 [00:49<02:05,  1.09it/s, ms_per_img=1.775, samples=1,248]
Resolution 128 eval:  22%|██▏       | 39/175 [00:49<02:03,  1.10it/s, ms_per_img=1.775, samples=1,248]
Resolution 128 eval:  22%|██▏       | 39/175 [00:50<02:03,  1.10it/s, ms_per_img=1.776, samples=1,280]
Resolution 128 eval:  23%|██▎       | 40/175 [00:50<01:56,  1.16it/s, ms_per_img=1.776, samples=1,280]
Resolution 128 eval:  23%|██▎       | 40/175 [00:50<01:56,  1.16it/s, ms_per_img=1.774, samples=1,312]
Resolution 128 eval:  23%|██▎       | 41/175 [00:50<01:48,  1.24it/s, ms_per_img=1.774, samples=1,312]
Resolution 128 eval:  23%|██▎       | 41/175 [00:52<01:48,  1.24it/s, ms_per_img=1.773, samples=1,344]
Resolution 128 eval:  24%|██▍       | 42/175 [00:52<02:18,  1.04s/it, ms_per_img=1.773, samples=1,344]
Resolution 128 eval:  24%|██▍       | 42/175 [00:53<02:18,  1.04s/it, ms_per_img=1.774, samples=1,376]
Resolution 128 eval:  25%|██▍       | 43/175 [00:53<02:12,  1.01s/it, ms_per_img=1.774, samples=1,376]
Resolution 128 eval:  25%|██▍       | 43/175 [00:54<02:12,  1.01s/it, ms_per_img=1.776, samples=1,408]
Resolution 128 eval:  25%|██▌       | 44/175 [00:54<02:08,  1.02it/s, ms_per_img=1.776, samples=1,408]
Resolution 128 eval:  25%|██▌       | 44/175 [00:55<02:08,  1.02it/s, ms_per_img=1.775, samples=1,440]
Resolution 128 eval:  26%|██▌       | 45/175 [00:55<01:58,  1.10it/s, ms_per_img=1.775, samples=1,440]
Resolution 128 eval:  26%|██▌       | 45/175 [00:55<01:58,  1.10it/s, ms_per_img=1.777, samples=1,472]
Resolution 128 eval:  26%|██▋       | 46/175 [00:55<01:51,  1.16it/s, ms_per_img=1.777, samples=1,472]
Resolution 128 eval:  26%|██▋       | 46/175 [00:57<01:51,  1.16it/s, ms_per_img=1.773, samples=1,504]
Resolution 128 eval:  27%|██▋       | 47/175 [00:57<02:08,  1.00s/it, ms_per_img=1.773, samples=1,504]
Resolution 128 eval:  27%|██▋       | 47/175 [00:58<02:08,  1.00s/it, ms_per_img=1.774, samples=1,536]
Resolution 128 eval:  27%|██▋       | 48/175 [00:58<02:04,  1.02it/s, ms_per_img=1.774, samples=1,536]
Resolution 128 eval:  27%|██▋       | 48/175 [00:58<02:04,  1.02it/s, ms_per_img=1.776, samples=1,568]
Resolution 128 eval:  28%|██▊       | 49/175 [00:58<01:55,  1.09it/s, ms_per_img=1.776, samples=1,568]
Resolution 128 eval:  28%|██▊       | 49/175 [01:00<01:55,  1.09it/s, ms_per_img=1.773, samples=1,600]
Resolution 128 eval:  29%|██▊       | 50/175 [01:00<02:14,  1.08s/it, ms_per_img=1.773, samples=1,600]
Resolution 128 eval:  29%|██▊       | 50/175 [01:01<02:14,  1.08s/it, ms_per_img=1.775, samples=1,632]
Resolution 128 eval:  29%|██▉       | 51/175 [01:01<02:08,  1.03s/it, ms_per_img=1.775, samples=1,632]
Resolution 128 eval:  29%|██▉       | 51/175 [01:02<02:08,  1.03s/it, ms_per_img=1.774, samples=1,664]
Resolution 128 eval:  30%|██▉       | 52/175 [01:02<02:09,  1.05s/it, ms_per_img=1.774, samples=1,664]
Resolution 128 eval:  30%|██▉       | 52/175 [01:03<02:09,  1.05s/it, ms_per_img=1.772, samples=1,696]
Resolution 128 eval:  30%|███       | 53/175 [01:03<02:02,  1.01s/it, ms_per_img=1.772, samples=1,696]
Resolution 128 eval:  30%|███       | 53/175 [01:04<02:02,  1.01s/it, ms_per_img=1.773, samples=1,728]
Resolution 128 eval:  31%|███       | 54/175 [01:04<01:58,  1.02it/s, ms_per_img=1.773, samples=1,728]
Resolution 128 eval:  31%|███       | 54/175 [01:05<01:58,  1.02it/s, ms_per_img=1.774, samples=1,760]
Resolution 128 eval:  31%|███▏      | 55/175 [01:05<01:58,  1.01it/s, ms_per_img=1.774, samples=1,760]
Resolution 128 eval:  31%|███▏      | 55/175 [01:05<01:58,  1.01it/s, ms_per_img=1.775, samples=1,792]
Resolution 128 eval:  32%|███▏      | 56/175 [01:05<01:41,  1.18it/s, ms_per_img=1.775, samples=1,792]
Resolution 128 eval:  32%|███▏      | 56/175 [01:06<01:41,  1.18it/s, ms_per_img=1.774, samples=1,824]
Resolution 128 eval:  33%|███▎      | 57/175 [01:06<01:39,  1.19it/s, ms_per_img=1.774, samples=1,824]
Resolution 128 eval:  33%|███▎      | 57/175 [01:07<01:39,  1.19it/s, ms_per_img=1.775, samples=1,856]
Resolution 128 eval:  33%|███▎      | 58/175 [01:07<01:30,  1.29it/s, ms_per_img=1.775, samples=1,856]
Resolution 128 eval:  33%|███▎      | 58/175 [01:08<01:30,  1.29it/s, ms_per_img=1.775, samples=1,888]
Resolution 128 eval:  34%|███▎      | 59/175 [01:08<01:52,  1.03it/s, ms_per_img=1.775, samples=1,888]
Resolution 128 eval:  34%|███▎      | 59/175 [01:09<01:52,  1.03it/s, ms_per_img=1.774, samples=1,920]
Resolution 128 eval:  34%|███▍      | 60/175 [01:09<01:42,  1.12it/s, ms_per_img=1.774, samples=1,920]
Resolution 128 eval:  34%|███▍      | 60/175 [01:10<01:42,  1.12it/s, ms_per_img=1.773, samples=1,952]
Resolution 128 eval:  35%|███▍      | 61/175 [01:10<01:40,  1.14it/s, ms_per_img=1.773, samples=1,952]
Resolution 128 eval:  35%|███▍      | 61/175 [01:11<01:40,  1.14it/s, ms_per_img=1.773, samples=1,984]
Resolution 128 eval:  35%|███▌      | 62/175 [01:11<01:47,  1.05it/s, ms_per_img=1.773, samples=1,984]
Resolution 128 eval:  35%|███▌      | 62/175 [01:12<01:47,  1.05it/s, ms_per_img=1.774, samples=2,016]
Resolution 128 eval:  36%|███▌      | 63/175 [01:12<01:44,  1.07it/s, ms_per_img=1.774, samples=2,016]
Resolution 128 eval:  36%|███▌      | 63/175 [01:13<01:44,  1.07it/s, ms_per_img=1.774, samples=2,048]
Resolution 128 eval:  37%|███▋      | 64/175 [01:13<01:47,  1.03it/s, ms_per_img=1.774, samples=2,048]
Resolution 128 eval:  37%|███▋      | 64/175 [01:14<01:47,  1.03it/s, ms_per_img=1.773, samples=2,080]
Resolution 128 eval:  37%|███▋      | 65/175 [01:14<01:43,  1.06it/s, ms_per_img=1.773, samples=2,080]
Resolution 128 eval:  37%|███▋      | 65/175 [01:15<01:43,  1.06it/s, ms_per_img=1.775, samples=2,112]
Resolution 128 eval:  38%|███▊      | 66/175 [01:15<01:45,  1.04it/s, ms_per_img=1.775, samples=2,112]
Resolution 128 eval:  38%|███▊      | 66/175 [01:16<01:45,  1.04it/s, ms_per_img=1.777, samples=2,144]
Resolution 128 eval:  38%|███▊      | 67/175 [01:16<01:51,  1.03s/it, ms_per_img=1.777, samples=2,144]
Resolution 128 eval:  38%|███▊      | 67/175 [01:17<01:51,  1.03s/it, ms_per_img=1.773, samples=2,176]
Resolution 128 eval:  39%|███▉      | 68/175 [01:17<02:04,  1.16s/it, ms_per_img=1.773, samples=2,176]
Resolution 128 eval:  39%|███▉      | 68/175 [01:18<02:04,  1.16s/it, ms_per_img=1.774, samples=2,208]
Resolution 128 eval:  39%|███▉      | 69/175 [01:18<01:52,  1.06s/it, ms_per_img=1.774, samples=2,208]
Resolution 128 eval:  39%|███▉      | 69/175 [01:20<01:52,  1.06s/it, ms_per_img=1.774, samples=2,240]
Resolution 128 eval:  40%|████      | 70/175 [01:20<02:09,  1.24s/it, ms_per_img=1.774, samples=2,240]
Resolution 128 eval:  40%|████      | 70/175 [01:21<02:09,  1.24s/it, ms_per_img=1.776, samples=2,272]
Resolution 128 eval:  41%|████      | 71/175 [01:21<02:10,  1.26s/it, ms_per_img=1.776, samples=2,272]
Resolution 128 eval:  41%|████      | 71/175 [01:22<02:10,  1.26s/it, ms_per_img=1.773, samples=2,304]
Resolution 128 eval:  41%|████      | 72/175 [01:22<02:05,  1.22s/it, ms_per_img=1.773, samples=2,304]
Resolution 128 eval:  41%|████      | 72/175 [01:23<02:05,  1.22s/it, ms_per_img=1.774, samples=2,336]
Resolution 128 eval:  42%|████▏     | 73/175 [01:23<02:06,  1.25s/it, ms_per_img=1.774, samples=2,336]
Resolution 128 eval:  42%|████▏     | 73/175 [01:24<02:06,  1.25s/it, ms_per_img=1.775, samples=2,368]
Resolution 128 eval:  42%|████▏     | 74/175 [01:24<01:47,  1.07s/it, ms_per_img=1.775, samples=2,368]
Resolution 128 eval:  42%|████▏     | 74/175 [01:25<01:47,  1.07s/it, ms_per_img=1.774, samples=2,400]
Resolution 128 eval:  43%|████▎     | 75/175 [01:25<01:35,  1.05it/s, ms_per_img=1.774, samples=2,400]
Resolution 128 eval:  43%|████▎     | 75/175 [01:25<01:35,  1.05it/s, ms_per_img=1.776, samples=2,432]
Resolution 128 eval:  43%|████▎     | 75/175 [01:25<01:35,  1.05it/s, ms_per_img=1.775, samples=2,464]
Resolution 128 eval:  44%|████▍     | 77/175 [01:25<01:04,  1.52it/s, ms_per_img=1.775, samples=2,464]
Resolution 128 eval:  44%|████▍     | 77/175 [01:26<01:04,  1.52it/s, ms_per_img=1.772, samples=2,496]
Resolution 128 eval:  45%|████▍     | 78/175 [01:26<01:00,  1.60it/s, ms_per_img=1.772, samples=2,496]
Resolution 128 eval:  45%|████▍     | 78/175 [01:26<01:00,  1.60it/s, ms_per_img=1.774, samples=2,528]
Resolution 128 eval:  45%|████▍     | 78/175 [01:27<01:00,  1.60it/s, ms_per_img=1.773, samples=2,560]
Resolution 128 eval:  46%|████▌     | 80/175 [01:27<00:45,  2.07it/s, ms_per_img=1.773, samples=2,560]
Resolution 128 eval:  46%|████▌     | 80/175 [01:27<00:45,  2.07it/s, ms_per_img=1.774, samples=2,592]
Resolution 128 eval:  46%|████▌     | 80/175 [01:27<00:45,  2.07it/s, ms_per_img=1.775, samples=2,624]
Resolution 128 eval:  47%|████▋     | 82/175 [01:27<00:39,  2.34it/s, ms_per_img=1.775, samples=2,624]
Resolution 128 eval:  47%|████▋     | 82/175 [01:28<00:39,  2.34it/s, ms_per_img=1.775, samples=2,656]
Resolution 128 eval:  47%|████▋     | 82/175 [01:28<00:39,  2.34it/s, ms_per_img=1.773, samples=2,688]
Resolution 128 eval:  48%|████▊     | 84/175 [01:28<00:38,  2.38it/s, ms_per_img=1.773, samples=2,688]
Resolution 128 eval:  48%|████▊     | 84/175 [01:28<00:38,  2.38it/s, ms_per_img=1.772, samples=2,720]
Resolution 128 eval:  48%|████▊     | 84/175 [01:29<00:38,  2.38it/s, ms_per_img=1.774, samples=2,752]
Resolution 128 eval:  49%|████▉     | 86/175 [01:29<00:33,  2.62it/s, ms_per_img=1.774, samples=2,752]
Resolution 128 eval:  49%|████▉     | 86/175 [01:29<00:33,  2.62it/s, ms_per_img=1.774, samples=2,784]
Resolution 128 eval:  49%|████▉     | 86/175 [01:29<00:33,  2.62it/s, ms_per_img=1.775, samples=2,816]
Resolution 128 eval:  50%|█████     | 88/175 [01:29<00:32,  2.68it/s, ms_per_img=1.775, samples=2,816]
Resolution 128 eval:  50%|█████     | 88/175 [01:30<00:32,  2.68it/s, ms_per_img=1.774, samples=2,848]
Resolution 128 eval:  50%|█████     | 88/175 [01:31<00:32,  2.68it/s, ms_per_img=1.774, samples=2,880]
Resolution 128 eval:  51%|█████▏    | 90/175 [01:31<00:49,  1.72it/s, ms_per_img=1.774, samples=2,880]
Resolution 128 eval:  51%|█████▏    | 90/175 [01:32<00:49,  1.72it/s, ms_per_img=1.775, samples=2,912]
Resolution 128 eval:  51%|█████▏    | 90/175 [01:33<00:49,  1.72it/s, ms_per_img=1.774, samples=2,944]
Resolution 128 eval:  53%|█████▎    | 92/175 [01:33<00:58,  1.43it/s, ms_per_img=1.774, samples=2,944]
Resolution 128 eval:  53%|█████▎    | 92/175 [01:34<00:58,  1.43it/s, ms_per_img=1.776, samples=2,976]
Resolution 128 eval:  53%|█████▎    | 93/175 [01:34<01:00,  1.36it/s, ms_per_img=1.776, samples=2,976]
Resolution 128 eval:  53%|█████▎    | 93/175 [01:35<01:00,  1.36it/s, ms_per_img=1.776, samples=3,008]
Resolution 128 eval:  54%|█████▎    | 94/175 [01:35<01:06,  1.22it/s, ms_per_img=1.776, samples=3,008]
Resolution 128 eval:  54%|█████▎    | 94/175 [01:37<01:06,  1.22it/s, ms_per_img=1.773, samples=3,040]
Resolution 128 eval:  54%|█████▍    | 95/175 [01:37<01:16,  1.04it/s, ms_per_img=1.773, samples=3,040]
Resolution 128 eval:  54%|█████▍    | 95/175 [01:37<01:16,  1.04it/s, ms_per_img=1.775, samples=3,072]
Resolution 128 eval:  55%|█████▍    | 96/175 [01:37<01:08,  1.16it/s, ms_per_img=1.775, samples=3,072]
Resolution 128 eval:  55%|█████▍    | 96/175 [01:38<01:08,  1.16it/s, ms_per_img=1.773, samples=3,104]
Resolution 128 eval:  55%|█████▌    | 97/175 [01:38<01:02,  1.25it/s, ms_per_img=1.773, samples=3,104]
Resolution 128 eval:  55%|█████▌    | 97/175 [01:39<01:02,  1.25it/s, ms_per_img=1.775, samples=3,136]
Resolution 128 eval:  56%|█████▌    | 98/175 [01:39<01:04,  1.19it/s, ms_per_img=1.775, samples=3,136]
Resolution 128 eval:  56%|█████▌    | 98/175 [01:40<01:04,  1.19it/s, ms_per_img=1.774, samples=3,168]
Resolution 128 eval:  57%|█████▋    | 99/175 [01:40<01:11,  1.06it/s, ms_per_img=1.774, samples=3,168]
Resolution 128 eval:  57%|█████▋    | 99/175 [01:41<01:11,  1.06it/s, ms_per_img=1.775, samples=3,200]
Resolution 128 eval:  57%|█████▋    | 100/175 [01:41<01:09,  1.07it/s, ms_per_img=1.775, samples=3,200]
Resolution 128 eval:  57%|█████▋    | 100/175 [01:43<01:09,  1.07it/s, ms_per_img=1.775, samples=3,232]
Resolution 128 eval:  58%|█████▊    | 101/175 [01:43<01:19,  1.08s/it, ms_per_img=1.775, samples=3,232]
Resolution 128 eval:  58%|█████▊    | 101/175 [01:44<01:19,  1.08s/it, ms_per_img=1.774, samples=3,264]

Acc=0.8571 AUC=0.5639 Fast=100.00% Medium=0.00% Full=0.00%

Resolution sweep:  25%|██▌       | 1/4 [03:09<09:27, 189.08s/it]

Source Res=128 Single: 5.864 ms/img | 170.5 FPS
Source Res=128 Batch=32: 1.778 ms/img | 562.3 FPS

Resolution 224

Resolution 224 eval:   0%|          | 0/175 [00:00<?, ?it/s]
Resolution 224 eval:   0%|          | 0/175 [00:01<?, ?it/s, ms_per_img=1.777, samples=32]
Resolution 224 eval:   1%|          | 1/175 [00:01<04:29,  1.55s/it, ms_per_img=1.777, samples=32]
Resolution 224 eval:   1%|          | 1/175 [00:01<04:29,  1.55s/it, ms_per_img=1.777, samples=64]
Resolution 224 eval:   1%|          | 1/175 [00:02<04:29,  1.55s/it, ms_per_img=1.776, samples=96]
Resolution 224 eval:   2%|▏         | 3/175 [00:02<01:58,  1.45it/s, ms_per_img=1.776, samples=96]
Resolution 224 eval:   2%|▏         | 3/175 [00:02<01:58,  1.45it/s, ms_per_img=1.777, samples=128]
Resolution 224 eval:   2%|▏         | 3/175 [00:03<01:58,  1.45it/s, ms_per_img=1.777, samples=160]
Resolution 224 eval:   3%|▎         | 5/175 [00:03<01:28,  1.92it/s, ms_per_img=1.777, samples=160]
Resolution 224 eval:   3%|▎         | 5/175 [00:03<01:28,  1.92it/s, ms_per_img=1.778, samples=192]
Resolution 224 eval:   3%|▎         | 5/175 [00:03<01:28,  1.92it/s, ms_per_img=1.778, samples=224]
Resolution 224 eval:   4%|▍         | 7/175 [00:03<01:12,  2.32it/s, ms_per_img=1.778, samples=224]
Resolution 224 eval:   4%|▍         | 7/175 [00:03<01:12,  2.32it/s, ms_per_img=1.778, samples=256]
Resolution 224 eval:   4%|▍         | 7/175 [00:04<01:12,  2.32it/s, ms_per_img=1.778, samples=288]
Resolution 224 eval:   5%|▌         | 9/175 [00:04<01:01,  2.68it/s, ms_per_img=1.778, samples=288]
Resolution 224 eval:   5%|▌         | 9/175 [00:04<01:01,  2.68it/s, ms_per_img=1.776, samples=320]
Resolution 224 eval:   5%|▌         | 9/175 [00:05<01:01,  2.68it/s, ms_per_img=1.777, samples=352]
Resolution 224 eval:   6%|▋         | 11/175 [00:05<01:07,  2.42it/s, ms_per_img=1.777, samples=352]
Resolution 224 eval:   6%|▋         | 11/175 [00:05<01:07,  2.42it/s, ms_per_img=1.778, samples=384]
Resolution 224 eval:   6%|▋         | 11/175 [00:05<01:07,  2.42it/s, ms_per_img=1.778, samples=416]
Resolution 224 eval:   7%|▋         | 13/175 [00:05<00:58,  2.77it/s, ms_per_img=1.778, samples=416]
Resolution 224 eval:   7%|▋         | 13/175 [00:05<00:58,  2.77it/s, ms_per_img=1.778, samples=448]
Resolution 224 eval:   7%|▋         | 13/175 [00:06<00:58,  2.77it/s, ms_per_img=1.779, samples=480]
Resolution 224 eval:   7%|▋         | 13/175 [00:06<00:58,  2.77it/s, ms_per_img=1.779, samples=512]
Resolution 224 eval:   9%|▉         | 16/175 [00:06<00:49,  3.22it/s, ms_per_img=1.779, samples=512]
Resolution 224 eval:   9%|▉         | 16/175 [00:06<00:49,  3.22it/s, ms_per_img=1.776, samples=544]
Resolution 224 eval:   9%|▉         | 16/175 [00:07<00:49,  3.22it/s, ms_per_img=1.779, samples=576]
Resolution 224 eval:  10%|█         | 18/175 [00:07<00:47,  3.28it/s, ms_per_img=1.779, samples=576]
Resolution 224 eval:  10%|█         | 18/175 [00:07<00:47,  3.28it/s, ms_per_img=1.778, samples=608]
Resolution 224 eval:  10%|█         | 18/175 [00:07<00:47,  3.28it/s, ms_per_img=1.778, samples=640]
Resolution 224 eval:  11%|█▏        | 20/175 [00:07<00:46,  3.31it/s, ms_per_img=1.778, samples=640]
Resolution 224 eval:  11%|█▏        | 20/175 [00:07<00:46,  3.31it/s, ms_per_img=1.776, samples=672]
Resolution 224 eval:  11%|█▏        | 20/175 [00:08<00:46,  3.31it/s, ms_per_img=1.776, samples=704]
Resolution 224 eval:  13%|█▎        | 22/175 [00:08<00:47,  3.23it/s, ms_per_img=1.776, samples=704]
Resolution 224 eval:  13%|█▎        | 22/175 [00:08<00:47,  3.23it/s, ms_per_img=1.777, samples=736]
Resolution 224 eval:  13%|█▎        | 22/175 [00:08<00:47,  3.23it/s, ms_per_img=1.778, samples=768]
Resolution 224 eval:  14%|█▎        | 24/175 [00:08<00:47,  3.19it/s, ms_per_img=1.778, samples=768]
Resolution 224 eval:  14%|█▎        | 24/175 [00:09<00:47,  3.19it/s, ms_per_img=1.777, samples=800]
Resolution 224 eval:  14%|█▎        | 24/175 [00:09<00:47,  3.19it/s, ms_per_img=1.778, samples=832]
Resolution 224 eval:  15%|█▍        | 26/175 [00:09<00:45,  3.30it/s, ms_per_img=1.778, samples=832]
Resolution 224 eval:  15%|█▍        | 26/175 [00:09<00:45,  3.30it/s, ms_per_img=1.776, samples=864]
Resolution 224 eval:  15%|█▍        | 26/175 [00:10<00:45,  3.30it/s, ms_per_img=1.780, samples=896]
Resolution 224 eval:  16%|█▌        | 28/175 [00:10<00:46,  3.18it/s, ms_per_img=1.780, samples=896]
Resolution 224 eval:  16%|█▌        | 28/175 [00:10<00:46,  3.18it/s, ms_per_img=1.775, samples=928]
Resolution 224 eval:  16%|█▌        | 28/175 [00:10<00:46,  3.18it/s, ms_per_img=1.775, samples=960]
Resolution 224 eval:  17%|█▋        | 30/175 [00:10<00:47,  3.07it/s, ms_per_img=1.775, samples=960]
Resolution 224 eval:  17%|█▋        | 30/175 [00:11<00:47,  3.07it/s, ms_per_img=1.776, samples=992]
Resolution 224 eval:  17%|█▋        | 30/175 [00:11<00:47,  3.07it/s, ms_per_img=1.776, samples=1,024]
Resolution 224 eval:  18%|█▊        | 32/175 [00:11<00:46,  3.08it/s, ms_per_img=1.776, samples=1,024]
Resolution 224 eval:  18%|█▊        | 32/175 [00:11<00:46,  3.08it/s, ms_per_img=1.778, samples=1,056]
Resolution 224 eval:  18%|█▊        | 32/175 [00:12<00:46,  3.08it/s, ms_per_img=1.775, samples=1,088]
Resolution 224 eval:  19%|█▉        | 34/175 [00:12<00:48,  2.93it/s, ms_per_img=1.775, samples=1,088]
Resolution 224 eval:  19%|█▉        | 34/175 [00:12<00:48,  2.93it/s, ms_per_img=1.776, samples=1,120]
Resolution 224 eval:  19%|█▉        | 34/175 [00:13<00:48,  2.93it/s, ms_per_img=1.777, samples=1,152]
Resolution 224 eval:  21%|██        | 36/175 [00:13<00:54,  2.54it/s, ms_per_img=1.777, samples=1,152]
Resolution 224 eval:  21%|██        | 36/175 [00:13<00:54,  2.54it/s, ms_per_img=1.777, samples=1,184]
Resolution 224 eval:  21%|██        | 36/175 [00:13<00:54,  2.54it/s, ms_per_img=1.778, samples=1,216]
Resolution 224 eval:  21%|██        | 36/175 [00:14<00:54,  2.54it/s, ms_per_img=1.778, samples=1,248]
Resolution 224 eval:  22%|██▏       | 39/175 [00:14<00:45,  3.00it/s, ms_per_img=1.778, samples=1,248]
Resolution 224 eval:  22%|██▏       | 39/175 [00:14<00:45,  3.00it/s, ms_per_img=1.777, samples=1,280]
Resolution 224 eval:  22%|██▏       | 39/175 [00:14<00:45,  3.00it/s, ms_per_img=1.775, samples=1,312]
Resolution 224 eval:  23%|██▎       | 41/175 [00:14<00:43,  3.09it/s, ms_per_img=1.775, samples=1,312]
Resolution 224 eval:  23%|██▎       | 41/175 [00:15<00:43,  3.09it/s, ms_per_img=1.777, samples=1,344]
Resolution 224 eval:  23%|██▎       | 41/175 [00:15<00:43,  3.09it/s, ms_per_img=1.776, samples=1,376]
Resolution 224 eval:  25%|██▍       | 43/175 [00:15<00:45,  2.90it/s, ms_per_img=1.776, samples=1,376]
Resolution 224 eval:  25%|██▍       | 43/175 [00:15<00:45,  2.90it/s, ms_per_img=1.775, samples=1,408]
Resolution 224 eval:  25%|██▍       | 43/175 [00:15<00:45,  2.90it/s, ms_per_img=1.776, samples=1,440]
Resolution 224 eval:  26%|██▌       | 45/175 [00:15<00:42,  3.02it/s, ms_per_img=1.776, samples=1,440]
Resolution 224 eval:  26%|██▌       | 45/175 [00:16<00:42,  3.02it/s, ms_per_img=1.776, samples=1,472]
Resolution 224 eval:  26%|██▌       | 45/175 [00:16<00:42,  3.02it/s, ms_per_img=1.777, samples=1,504]
Resolution 224 eval:  27%|██▋       | 47/175 [00:16<00:40,  3.13it/s, ms_per_img=1.777, samples=1,504]
Resolution 224 eval:  27%|██▋       | 47/175 [00:16<00:40,  3.13it/s, ms_per_img=1.779, samples=1,536]
Resolution 224 eval:  27%|██▋       | 47/175 [00:17<00:40,  3.13it/s, ms_per_img=1.778, samples=1,568]
Resolution 224 eval:  28%|██▊       | 49/175 [00:17<00:38,  3.28it/s, ms_per_img=1.778, samples=1,568]
Resolution 224 eval:  28%|██▊       | 49/175 [00:17<00:38,  3.28it/s, ms_per_img=1.777, samples=1,600]
Resolution 224 eval:  28%|██▊       | 49/175 [00:17<00:38,  3.28it/s, ms_per_img=1.778, samples=1,632]
Resolution 224 eval:  29%|██▉       | 51/175 [00:17<00:36,  3.36it/s, ms_per_img=1.778, samples=1,632]
Resolution 224 eval:  29%|██▉       | 51/175 [00:18<00:36,  3.36it/s, ms_per_img=1.775, samples=1,664]
Resolution 224 eval:  29%|██▉       | 51/175 [00:18<00:36,  3.36it/s, ms_per_img=1.776, samples=1,696]
Resolution 224 eval:  30%|███       | 53/175 [00:18<00:38,  3.16it/s, ms_per_img=1.776, samples=1,696]
Resolution 224 eval:  30%|███       | 53/175 [00:18<00:38,  3.16it/s, ms_per_img=1.777, samples=1,728]
Resolution 224 eval:  30%|███       | 53/175 [00:19<00:38,  3.16it/s, ms_per_img=1.777, samples=1,760]
Resolution 224 eval:  31%|███▏      | 55/175 [00:19<00:37,  3.16it/s, ms_per_img=1.777, samples=1,760]
Resolution 224 eval:  31%|███▏      | 55/175 [00:19<00:37,  3.16it/s, ms_per_img=1.777, samples=1,792]
Resolution 224 eval:  31%|███▏      | 55/175 [00:19<00:37,  3.16it/s, ms_per_img=1.778, samples=1,824]
Resolution 224 eval:  33%|███▎      | 57/175 [00:19<00:36,  3.26it/s, ms_per_img=1.778, samples=1,824]
Resolution 224 eval:  33%|███▎      | 57/175 [00:19<00:36,  3.26it/s, ms_per_img=1.778, samples=1,856]
Resolution 224 eval:  33%|███▎      | 57/175 [00:20<00:36,  3.26it/s, ms_per_img=1.775, samples=1,888]
Resolution 224 eval:  34%|███▎      | 59/175 [00:20<00:35,  3.26it/s, ms_per_img=1.775, samples=1,888]
Resolution 224 eval:  34%|███▎      | 59/175 [00:20<00:35,  3.26it/s, ms_per_img=1.778, samples=1,920]
Resolution 224 eval:  34%|███▎      | 59/175 [00:20<00:35,  3.26it/s, ms_per_img=1.775, samples=1,952]
Resolution 224 eval:  35%|███▍      | 61/175 [00:20<00:34,  3.30it/s, ms_per_img=1.775, samples=1,952]
Resolution 224 eval:  35%|███▍      | 61/175 [00:21<00:34,  3.30it/s, ms_per_img=1.775, samples=1,984]
Resolution 224 eval:  35%|███▍      | 61/175 [00:21<00:34,  3.30it/s, ms_per_img=1.778, samples=2,016]
Resolution 224 eval:  36%|███▌      | 63/175 [00:21<00:33,  3.35it/s, ms_per_img=1.778, samples=2,016]
Resolution 224 eval:  36%|███▌      | 63/175 [00:21<00:33,  3.35it/s, ms_per_img=1.774, samples=2,048]
Resolution 224 eval:  36%|███▌      | 63/175 [00:22<00:33,  3.35it/s, ms_per_img=1.776, samples=2,080]
Resolution 224 eval:  37%|███▋      | 65/175 [00:22<00:34,  3.15it/s, ms_per_img=1.776, samples=2,080]
Resolution 224 eval:  37%|███▋      | 65/175 [00:22<00:34,  3.15it/s, ms_per_img=1.776, samples=2,112]
Resolution 224 eval:  37%|███▋      | 65/175 [00:22<00:34,  3.15it/s, ms_per_img=1.775, samples=2,144]
Resolution 224 eval:  38%|███▊      | 67/175 [00:22<00:36,  2.97it/s, ms_per_img=1.775, samples=2,144]
Resolution 224 eval:  38%|███▊      | 67/175 [00:23<00:36,  2.97it/s, ms_per_img=1.774, samples=2,176]
Resolution 224 eval:  38%|███▊      | 67/175 [00:23<00:36,  2.97it/s, ms_per_img=1.778, samples=2,208]
Resolution 224 eval:  39%|███▉      | 69/175 [00:23<00:34,  3.11it/s, ms_per_img=1.778, samples=2,208]
Resolution 224 eval:  39%|███▉      | 69/175 [00:23<00:34,  3.11it/s, ms_per_img=1.777, samples=2,240]
Resolution 224 eval:  39%|███▉      | 69/175 [00:24<00:34,  3.11it/s, ms_per_img=1.777, samples=2,272]
Resolution 224 eval:  41%|████      | 71/175 [00:24<00:36,  2.87it/s, ms_per_img=1.777, samples=2,272]
Resolution 224 eval:  41%|████      | 71/175 [00:24<00:36,  2.87it/s, ms_per_img=1.776, samples=2,304]
Resolution 224 eval:  41%|████      | 71/175 [00:24<00:36,  2.87it/s, ms_per_img=1.776, samples=2,336]
Resolution 224 eval:  42%|████▏     | 73/175 [00:24<00:33,  3.01it/s, ms_per_img=1.776, samples=2,336]
Resolution 224 eval:  42%|████▏     | 73/175 [00:25<00:33,  3.01it/s, ms_per_img=1.776, samples=2,368]
Resolution 224 eval:  42%|████▏     | 73/175 [00:25<00:33,  3.01it/s, ms_per_img=1.777, samples=2,400]
Resolution 224 eval:  43%|████▎     | 75/175 [00:25<00:40,  2.48it/s, ms_per_img=1.777, samples=2,400]
Resolution 224 eval:  43%|████▎     | 75/175 [00:27<00:40,  2.48it/s, ms_per_img=1.778, samples=2,432]
Resolution 224 eval:  43%|████▎     | 75/175 [00:27<00:40,  2.48it/s, ms_per_img=1.777, samples=2,464]
Resolution 224 eval:  44%|████▍     | 77/175 [00:27<00:56,  1.72it/s, ms_per_img=1.777, samples=2,464]
Resolution 224 eval:  44%|████▍     | 77/175 [00:29<00:56,  1.72it/s, ms_per_img=1.777, samples=2,496]
Resolution 224 eval:  44%|████▍     | 77/175 [00:30<00:56,  1.72it/s, ms_per_img=1.777, samples=2,528]
Resolution 224 eval:  45%|████▌     | 79/175 [00:30<01:13,  1.31it/s, ms_per_img=1.777, samples=2,528]
Resolution 224 eval:  45%|████▌     | 79/175 [00:31<01:13,  1.31it/s, ms_per_img=1.775, samples=2,560]
Resolution 224 eval:  46%|████▌     | 80/175 [00:31<01:16,  1.25it/s, ms_per_img=1.775, samples=2,560]
Resolution 224 eval:  46%|████▌     | 80/175 [00:32<01:16,  1.25it/s, ms_per_img=1.775, samples=2,592]
Resolution 224 eval:  46%|████▋     | 81/175 [00:32<01:22,  1.14it/s, ms_per_img=1.775, samples=2,592]
Resolution 224 eval:  46%|████▋     | 81/175 [00:33<01:22,  1.14it/s, ms_per_img=1.775, samples=2,624]
Resolution 224 eval:  47%|████▋     | 82/175 [00:33<01:24,  1.10it/s, ms_per_img=1.775, samples=2,624]
Resolution 224 eval:  47%|████▋     | 82/175 [00:34<01:24,  1.10it/s, ms_per_img=1.777, samples=2,656]
Resolution 224 eval:  47%|████▋     | 83/175 [00:34<01:31,  1.01it/s, ms_per_img=1.777, samples=2,656]
Resolution 224 eval:  47%|████▋     | 83/175 [00:36<01:31,  1.01it/s, ms_per_img=1.776, samples=2,688]
Resolution 224 eval:  48%|████▊     | 84/175 [00:36<01:36,  1.06s/it, ms_per_img=1.776, samples=2,688]
Resolution 224 eval:  48%|████▊     | 84/175 [00:37<01:36,  1.06s/it, ms_per_img=1.777, samples=2,720]
Resolution 224 eval:  49%|████▊     | 85/175 [00:37<01:36,  1.07s/it, ms_per_img=1.777, samples=2,720]
Resolution 224 eval:  49%|████▊     | 85/175 [00:38<01:36,  1.07s/it, ms_per_img=1.775, samples=2,752]
Resolution 224 eval:  49%|████▉     | 86/175 [00:38<01:38,  1.11s/it, ms_per_img=1.775, samples=2,752]
Resolution 224 eval:  49%|████▉     | 86/175 [00:39<01:38,  1.11s/it, ms_per_img=1.775, samples=2,784]
Resolution 224 eval:  50%|████▉     | 87/175 [00:39<01:42,  1.16s/it, ms_per_img=1.775, samples=2,784]
Resolution 224 eval:  50%|████▉     | 87/175 [00:40<01:42,  1.16s/it, ms_per_img=1.777, samples=2,816]
Resolution 224 eval:  50%|█████     | 88/175 [00:40<01:43,  1.19s/it, ms_per_img=1.777, samples=2,816]
Resolution 224 eval:  50%|█████     | 88/175 [00:41<01:43,  1.19s/it, ms_per_img=1.776, samples=2,848]
Resolution 224 eval:  51%|█████     | 89/175 [00:41<01:32,  1.08s/it, ms_per_img=1.776, samples=2,848]
Resolution 224 eval:  51%|█████     | 89/175 [00:41<01:32,  1.08s/it, ms_per_img=1.777, samples=2,880]
Resolution 224 eval:  51%|█████     | 89/175 [00:42<01:32,  1.08s/it, ms_per_img=1.775, samples=2,912]
Resolution 224 eval:  52%|█████▏    | 91/175 [00:42<01:01,  1.37it/s, ms_per_img=1.775, samples=2,912]
Resolution 224 eval:  52%|█████▏    | 91/175 [00:42<01:01,  1.37it/s, ms_per_img=1.776, samples=2,944]
Resolution 224 eval:  52%|█████▏    | 91/175 [00:42<01:01,  1.37it/s, ms_per_img=1.776, samples=2,976]
Resolution 224 eval:  53%|█████▎    | 93/175 [00:42<00:45,  1.80it/s, ms_per_img=1.776, samples=2,976]
Resolution 224 eval:  53%|█████▎    | 93/175 [00:43<00:45,  1.80it/s, ms_per_img=1.776, samples=3,008]
Resolution 224 eval:  53%|█████▎    | 93/175 [00:43<00:45,  1.80it/s, ms_per_img=1.775, samples=3,040]
Resolution 224 eval:  53%|█████▎    | 93/175 [00:43<00:45,  1.80it/s, ms_per_img=1.778, samples=3,072]
Resolution 224 eval:  55%|█████▍    | 96/175 [00:43<00:33,  2.39it/s, ms_per_img=1.778, samples=3,072]
Resolution 224 eval:  55%|█████▍    | 96/175 [00:43<00:33,  2.39it/s, ms_per_img=1.775, samples=3,104]
Resolution 224 eval:  55%|█████▍    | 96/175 [00:44<00:33,  2.39it/s, ms_per_img=1.777, samples=3,136]
Resolution 224 eval:  56%|█████▌    | 98/175 [00:44<00:28,  2.66it/s, ms_per_img=1.777, samples=3,136]
Resolution 224 eval:  56%|█████▌    | 98/175 [00:44<00:28,  2.66it/s, ms_per_img=1.776, samples=3,168]
Resolution 224 eval:  56%|█████▌    | 98/175 [00:44<00:28,  2.66it/s, ms_per_img=1.775, samples=3,200]
Resolution 224 eval:  57%|█████▋    | 100/175 [00:44<00:27,  2.74it/s, ms_per_img=1.775, samples=3,200]
Resolution 224 eval:  57%|█████▋    | 100/175 [00:45<00:27,  2.74it/s, ms_per_img=1.778, samples=3,232]
Resolution 224 eval:  57%|█████▋    | 100/175 [00:45<00:27,  2.74it/s, ms_per_img=1.777, samples=3,264]
Resolution 224 eval:  58%|█████▊    | 102/175 [00:45<00:26,  2.76it/s, ms_per_img=1.777, samples=3,264]
Resolution 224 eval:  58%|█████▊    | 102/175 [00:45<00:26,  2.76it/s, ms_per_img=1.776, samples=3,296]
Resolution 224 eval:  58%|█████▊    | 102/175 [00:46<00:26,  2.76it/s, ms_per_img=1.777, samples=3,328]
Resolution 224 eval:  59%|█████▉    | 104/175 [00:46<00:24,  2.86it/s, ms_per_img=1.777, samples=3,328]
Resolution 224 eval:  59%|█████▉    | 104/175 [00:46<00:24,  2.86it/s, ms_per_img=1.777, samples=3,360]
Resolution 224 eval:  59%|█████▉    | 104/175 [00:46<00:24,  2.86it/s, ms_per_img=1.776, samples=3,392]
Resolution 224 eval:  61%|██████    | 106/175 [00:46<00:23,  2.95it/s, ms_per_img=1.776, samples=3,392]
Resolution 224 eval:  61%|██████    | 106/175 [00:47<00:23,  2.95it/s, ms_per_img=1.777, samples=3,424]
Resolution 224 eval:  61%|██████    | 106/175 [00:47<00:23,  2.95it/s, ms_per_img=1.777, samples=3,456]
Resolution 224 eval:  61%|██████    | 106/175 [00:47<00:23,  2.95it/s, ms_per_img=1.779, samples=3,488]
Resolution 224 eval:  62%|██████▏   | 109/175 [00:47<00:19,  3.43it/s, ms_per_img=1.779, samples=3,488]
Resolution 224 eval:  62%|██████▏   | 109/175 [00:47<00:19,  3.43it/s, ms_per_img=1.775, samples=3,520]
Resolution 224 eval:  62%|██████▏   | 109/175 [00:48<00:19,  3.43it/s, ms_per_img=1.777, samples=3,552]
Resolution 224 eval:  63%|██████▎   | 111/175 [00:48<00:17,  3.56it/s, ms_per_img=1.777, samples=3,552]
Resolution 224 eval:  63%|██████▎   | 111/175 [00:48<00:17,  3.56it/s, ms_per_img=1.776, samples=3,584]
Resolution 224 eval:  63%|██████▎   | 111/175 [00:48<00:17,  3.56it/s, ms_per_img=1.778, samples=3,616]
Resolution 224 eval:  63%|██████▎   | 111/175 [00:48<00:17,  3.56it/s, ms_per_img=1.777, samples=3,648]
Resolution 224 eval:  65%|██████▌   | 114/175 [00:48<00:17,  3.50it/s, ms_per_img=1.777, samples=3,648]
Resolution 224 eval:  65%|██████▌   | 114/175 [00:49<00:17,  3.50it/s, ms_per_img=1.774, samples=3,680]
Resolution 224 eval:  65%|██████▌   | 114/175 [00:49<00:17,  3.50it/s, ms_per_img=1.778, samples=3,712]
Resolution 224 eval:  66%|██████▋   | 116/175 [00:49<00:18,  3.26it/s, ms_per_img=1.778, samples=3,712]
Resolution 224 eval:  66%|██████▋   | 116/175 [00:49<00:18,  3.26it/s, ms_per_img=1.775, samples=3,744]
Resolution 224 eval:  66%|██████▋   | 116/175 [00:50<00:18,  3.26it/s, ms_per_img=1.775, samples=3,776]
Resolution 224 eval:  67%|██████▋   | 118/175 [00:50<00:18,  3.15it/s, ms_per_img=1.775, samples=3,776]
Resolution 224 eval:  67%|██████▋   | 118/175 [00:50<00:18,  3.15it/s, ms_per_img=1.775, samples=3,808]
Resolution 224 eval:  67%|██████▋   | 118/175 [00:50<00:18,  3.15it/s, ms_per_img=1.776, samples=3,840]
Resolution 224 eval:  67%|██████▋   | 118/175 [00:51<00:18,  3.15it/s, ms_per_img=1.780, samples=3,872]
Resolution 224 eval:  69%|██████▉   | 121/175 [00:51<00:15,  3.42it/s, ms_per_img=1.780, samples=3,872]
Resolution 224 eval:  69%|██████▉   | 121/175 [00:51<00:15,  3.42it/s, ms_per_img=1.775, samples=3,904]
Resolution 224 eval:  69%|██████▉   | 121/175 [00:51<00:15,  3.42it/s, ms_per_img=1.775, samples=3,936]
Resolution 224 eval:  70%|███████   | 123/175 [00:51<00:16,  3.09it/s, ms_per_img=1.775, samples=3,936]
Resolution 224 eval:  70%|███████   | 123/175 [00:52<00:16,  3.09it/s, ms_per_img=1.777, samples=3,968]
Resolution 224 eval:  70%|███████   | 123/175 [00:52<00:16,  3.09it/s, ms_per_img=1.779, samples=4,000]
Resolution 224 eval:  71%|███████▏  | 125/175 [00:52<00:16,  3.07it/s, ms_per_img=1.779, samples=4,000]
Resolution 224 eval:  71%|███████▏  | 125/175 [00:52<00:16,  3.07it/s, ms_per_img=1.776, samples=4,032]
Resolution 224 eval:  71%|███████▏  | 125/175 [00:53<00:16,  3.07it/s, ms_per_img=1.776, samples=4,064]
Resolution 224 eval:  73%|███████▎  | 127/175 [00:53<00:16,  2.95it/s, ms_per_img=1.776, samples=4,064]
Resolution 224 eval:  73%|███████▎  | 127/175 [00:53<00:16,  2.95it/s, ms_per_img=1.777, samples=4,096]

Acc=0.8571 AUC=0.5569 Fast=100.00% Medium=0.00% Full=0.00%

Resolution sweep:  50%|█████     | 2/4 [04:31<04:12, 126.49s/it]

Source Res=224 Single: 5.934 ms/img | 168.5 FPS
Source Res=224 Batch=32: 1.781 ms/img | 561.6 FPS

Resolution 256

Resolution 256 eval:   0%|          | 0/175 [00:00<?, ?it/s]
Resolution 256 eval:   0%|          | 0/175 [00:00<?, ?it/s, ms_per_img=1.776, samples=32]
Resolution 256 eval:   0%|          | 0/175 [00:00<?, ?it/s, ms_per_img=1.778, samples=64]
Resolution 256 eval:   1%|          | 2/175 [00:00<00:52,  3.30it/s, ms_per_img=1.778, samples=64]
Resolution 256 eval:   1%|          | 2/175 [00:01<00:52,  3.30it/s, ms_per_img=1.777, samples=96]
Resolution 256 eval:   1%|          | 2/175 [00:01<00:52,  3.30it/s, ms_per_img=1.780, samples=128]
Resolution 256 eval:   2%|▏         | 4/175 [00:01<01:10,  2.42it/s, ms_per_img=1.780, samples=128]
Resolution 256 eval:   2%|▏         | 4/175 [00:01<01:10,  2.42it/s, ms_per_img=1.778, samples=160]
Resolution 256 eval:   2%|▏         | 4/175 [00:02<01:10,  2.42it/s, ms_per_img=1.778, samples=192]
Resolution 256 eval:   3%|▎         | 6/175 [00:02<01:05,  2.60it/s, ms_per_img=1.778, samples=192]
Resolution 256 eval:   3%|▎         | 6/175 [00:02<01:05,  2.60it/s, ms_per_img=1.780, samples=224]
Resolution 256 eval:   3%|▎         | 6/175 [00:02<01:05,  2.60it/s, ms_per_img=1.779, samples=256]
Resolution 256 eval:   5%|▍         | 8/175 [00:02<00:55,  2.99it/s, ms_per_img=1.779, samples=256]
Resolution 256 eval:   5%|▍         | 8/175 [00:03<00:55,  2.99it/s, ms_per_img=1.775, samples=288]
Resolution 256 eval:   5%|▍         | 8/175 [00:03<00:55,  2.99it/s, ms_per_img=1.777, samples=320]
Resolution 256 eval:   6%|▌         | 10/175 [00:03<00:59,  2.78it/s, ms_per_img=1.777, samples=320]
Resolution 256 eval:   6%|▌         | 10/175 [00:04<00:59,  2.78it/s, ms_per_img=1.777, samples=352]
Resolution 256 eval:   6%|▌         | 10/175 [00:04<00:59,  2.78it/s, ms_per_img=1.778, samples=384]
Resolution 256 eval:   7%|▋         | 12/175 [00:04<01:00,  2.70it/s, ms_per_img=1.778, samples=384]
Resolution 256 eval:   7%|▋         | 12/175 [00:04<01:00,  2.70it/s, ms_per_img=1.777, samples=416]
Resolution 256 eval:   7%|▋         | 12/175 [00:04<01:00,  2.70it/s, ms_per_img=1.777, samples=448]
Resolution 256 eval:   8%|▊         | 14/175 [00:04<00:55,  2.89it/s, ms_per_img=1.777, samples=448]
Resolution 256 eval:   8%|▊         | 14/175 [00:05<00:55,  2.89it/s, ms_per_img=1.778, samples=480]
Resolution 256 eval:   8%|▊         | 14/175 [00:05<00:55,  2.89it/s, ms_per_img=1.778, samples=512]
Resolution 256 eval:   8%|▊         | 14/175 [00:05<00:55,  2.89it/s, ms_per_img=1.775, samples=544]
Resolution 256 eval:  10%|▉         | 17/175 [00:05<00:51,  3.04it/s, ms_per_img=1.775, samples=544]
Resolution 256 eval:  10%|▉         | 17/175 [00:06<00:51,  3.04it/s, ms_per_img=1.780, samples=576]
Resolution 256 eval:  10%|▉         | 17/175 [00:06<00:51,  3.04it/s, ms_per_img=1.780, samples=608]
Resolution 256 eval:  11%|█         | 19/175 [00:06<00:47,  3.25it/s, ms_per_img=1.780, samples=608]
Resolution 256 eval:  11%|█         | 19/175 [00:06<00:47,  3.25it/s, ms_per_img=1.779, samples=640]
Resolution 256 eval:  11%|█         | 19/175 [00:07<00:47,  3.25it/s, ms_per_img=1.779, samples=672]
Resolution 256 eval:  12%|█▏        | 21/175 [00:07<00:47,  3.21it/s, ms_per_img=1.779, samples=672]
Resolution 256 eval:  12%|█▏        | 21/175 [00:07<00:47,  3.21it/s, ms_per_img=1.778, samples=704]
Resolution 256 eval:  12%|█▏        | 21/175 [00:07<00:47,  3.21it/s, ms_per_img=1.777, samples=736]
Resolution 256 eval:  13%|█▎        | 23/175 [00:07<00:49,  3.06it/s, ms_per_img=1.777, samples=736]
Resolution 256 eval:  13%|█▎        | 23/175 [00:08<00:49,  3.06it/s, ms_per_img=1.775, samples=768]
Resolution 256 eval:  13%|█▎        | 23/175 [00:08<00:49,  3.06it/s, ms_per_img=1.777, samples=800]
Resolution 256 eval:  14%|█▍        | 25/175 [00:08<00:48,  3.07it/s, ms_per_img=1.777, samples=800]
Resolution 256 eval:  14%|█▍        | 25/175 [00:08<00:48,  3.07it/s, ms_per_img=1.776, samples=832]
Resolution 256 eval:  14%|█▍        | 25/175 [00:09<00:48,  3.07it/s, ms_per_img=1.776, samples=864]
Resolution 256 eval:  15%|█▌        | 27/175 [00:09<00:51,  2.89it/s, ms_per_img=1.776, samples=864]
Resolution 256 eval:  15%|█▌        | 27/175 [00:09<00:51,  2.89it/s, ms_per_img=1.777, samples=896]
Resolution 256 eval:  15%|█▌        | 27/175 [00:09<00:51,  2.89it/s, ms_per_img=1.776, samples=928]
Resolution 256 eval:  17%|█▋        | 29/175 [00:09<00:49,  2.95it/s, ms_per_img=1.776, samples=928]
Resolution 256 eval:  17%|█▋        | 29/175 [00:10<00:49,  2.95it/s, ms_per_img=1.777, samples=960]
Resolution 256 eval:  17%|█▋        | 29/175 [00:10<00:49,  2.95it/s, ms_per_img=1.777, samples=992]
Resolution 256 eval:  18%|█▊        | 31/175 [00:10<00:49,  2.93it/s, ms_per_img=1.777, samples=992]
Resolution 256 eval:  18%|█▊        | 31/175 [00:10<00:49,  2.93it/s, ms_per_img=1.777, samples=1,024]
Resolution 256 eval:  18%|█▊        | 31/175 [00:11<00:49,  2.93it/s, ms_per_img=1.778, samples=1,056]
Resolution 256 eval:  19%|█▉        | 33/175 [00:11<00:47,  2.97it/s, ms_per_img=1.778, samples=1,056]
Resolution 256 eval:  19%|█▉        | 33/175 [00:11<00:47,  2.97it/s, ms_per_img=1.778, samples=1,088]
Resolution 256 eval:  19%|█▉        | 33/175 [00:12<00:47,  2.97it/s, ms_per_img=1.775, samples=1,120]
Resolution 256 eval:  20%|██        | 35/175 [00:12<00:56,  2.48it/s, ms_per_img=1.775, samples=1,120]
Resolution 256 eval:  20%|██        | 35/175 [00:12<00:56,  2.48it/s, ms_per_img=1.777, samples=1,152]
Resolution 256 eval:  20%|██        | 35/175 [00:13<00:56,  2.48it/s, ms_per_img=1.776, samples=1,184]
Resolution 256 eval:  21%|██        | 37/175 [00:13<00:54,  2.53it/s, ms_per_img=1.776, samples=1,184]
Resolution 256 eval:  21%|██        | 37/175 [00:13<00:54,  2.53it/s, ms_per_img=1.779, samples=1,216]
Resolution 256 eval:  21%|██        | 37/175 [00:13<00:54,  2.53it/s, ms_per_img=1.780, samples=1,248]
Resolution 256 eval:  22%|██▏       | 39/175 [00:13<00:48,  2.78it/s, ms_per_img=1.780, samples=1,248]
Resolution 256 eval:  22%|██▏       | 39/175 [00:13<00:48,  2.78it/s, ms_per_img=1.779, samples=1,280]
Resolution 256 eval:  22%|██▏       | 39/175 [00:14<00:48,  2.78it/s, ms_per_img=1.776, samples=1,312]
Resolution 256 eval:  23%|██▎       | 41/175 [00:14<00:46,  2.87it/s, ms_per_img=1.776, samples=1,312]
Resolution 256 eval:  23%|██▎       | 41/175 [00:14<00:46,  2.87it/s, ms_per_img=1.778, samples=1,344]
Resolution 256 eval:  23%|██▎       | 41/175 [00:15<00:46,  2.87it/s, ms_per_img=1.776, samples=1,376]
Resolution 256 eval:  25%|██▍       | 43/175 [00:15<00:48,  2.70it/s, ms_per_img=1.776, samples=1,376]
Resolution 256 eval:  25%|██▍       | 43/175 [00:15<00:48,  2.70it/s, ms_per_img=1.774, samples=1,408]
Resolution 256 eval:  25%|██▍       | 43/175 [00:15<00:48,  2.70it/s, ms_per_img=1.778, samples=1,440]
Resolution 256 eval:  26%|██▌       | 45/175 [00:15<00:46,  2.81it/s, ms_per_img=1.778, samples=1,440]
Resolution 256 eval:  26%|██▌       | 45/175 [00:15<00:46,  2.81it/s, ms_per_img=1.778, samples=1,472]
Resolution 256 eval:  26%|██▌       | 45/175 [00:16<00:46,  2.81it/s, ms_per_img=1.776, samples=1,504]
Resolution 256 eval:  27%|██▋       | 47/175 [00:16<00:43,  2.91it/s, ms_per_img=1.776, samples=1,504]
Resolution 256 eval:  27%|██▋       | 47/175 [00:16<00:43,  2.91it/s, ms_per_img=1.779, samples=1,536]
Resolution 256 eval:  27%|██▋       | 47/175 [00:16<00:43,  2.91it/s, ms_per_img=1.778, samples=1,568]
Resolution 256 eval:  28%|██▊       | 49/175 [00:16<00:41,  3.04it/s, ms_per_img=1.778, samples=1,568]
Resolution 256 eval:  28%|██▊       | 49/175 [00:17<00:41,  3.04it/s, ms_per_img=1.775, samples=1,600]
Resolution 256 eval:  28%|██▊       | 49/175 [00:17<00:41,  3.04it/s, ms_per_img=1.777, samples=1,632]
Resolution 256 eval:  29%|██▉       | 51/175 [00:17<00:39,  3.11it/s, ms_per_img=1.777, samples=1,632]
Resolution 256 eval:  29%|██▉       | 51/175 [00:18<00:39,  3.11it/s, ms_per_img=1.777, samples=1,664]
Resolution 256 eval:  29%|██▉       | 51/175 [00:18<00:39,  3.11it/s, ms_per_img=1.777, samples=1,696]
Resolution 256 eval:  30%|███       | 53/175 [00:18<00:41,  2.93it/s, ms_per_img=1.777, samples=1,696]
Resolution 256 eval:  30%|███       | 53/175 [00:18<00:41,  2.93it/s, ms_per_img=1.774, samples=1,728]
Resolution 256 eval:  30%|███       | 53/175 [00:19<00:41,  2.93it/s, ms_per_img=1.777, samples=1,760]
Resolution 256 eval:  31%|███▏      | 55/175 [00:19<00:40,  2.94it/s, ms_per_img=1.777, samples=1,760]
Resolution 256 eval:  31%|███▏      | 55/175 [00:19<00:40,  2.94it/s, ms_per_img=1.780, samples=1,792]
Resolution 256 eval:  31%|███▏      | 55/175 [00:19<00:40,  2.94it/s, ms_per_img=1.775, samples=1,824]
Resolution 256 eval:  33%|███▎      | 57/175 [00:19<00:39,  3.02it/s, ms_per_img=1.775, samples=1,824]
Resolution 256 eval:  33%|███▎      | 57/175 [00:19<00:39,  3.02it/s, ms_per_img=1.778, samples=1,856]
Resolution 256 eval:  33%|███▎      | 57/175 [00:20<00:39,  3.02it/s, ms_per_img=1.777, samples=1,888]
Resolution 256 eval:  34%|███▎      | 59/175 [00:20<00:38,  3.02it/s, ms_per_img=1.777, samples=1,888]
Resolution 256 eval:  34%|███▎      | 59/175 [00:20<00:38,  3.02it/s, ms_per_img=1.777, samples=1,920]
Resolution 256 eval:  34%|███▎      | 59/175 [00:20<00:38,  3.02it/s, ms_per_img=1.775, samples=1,952]
Resolution 256 eval:  35%|███▍      | 61/175 [00:20<00:37,  3.06it/s, ms_per_img=1.775, samples=1,952]
Resolution 256 eval:  35%|███▍      | 61/175 [00:21<00:37,  3.06it/s, ms_per_img=1.777, samples=1,984]
Resolution 256 eval:  35%|███▍      | 61/175 [00:21<00:37,  3.06it/s, ms_per_img=1.777, samples=2,016]
Resolution 256 eval:  36%|███▌      | 63/175 [00:21<00:36,  3.11it/s, ms_per_img=1.777, samples=2,016]
Resolution 256 eval:  36%|███▌      | 63/175 [00:21<00:36,  3.11it/s, ms_per_img=1.776, samples=2,048]
Resolution 256 eval:  36%|███▌      | 63/175 [00:22<00:36,  3.11it/s, ms_per_img=1.776, samples=2,080]
Resolution 256 eval:  37%|███▋      | 65/175 [00:22<00:37,  2.93it/s, ms_per_img=1.776, samples=2,080]
Resolution 256 eval:  37%|███▋      | 65/175 [00:22<00:37,  2.93it/s, ms_per_img=1.780, samples=2,112]
Resolution 256 eval:  37%|███▋      | 65/175 [00:23<00:37,  2.93it/s, ms_per_img=1.775, samples=2,144]
Resolution 256 eval:  38%|███▊      | 67/175 [00:23<00:38,  2.77it/s, ms_per_img=1.775, samples=2,144]
Resolution 256 eval:  38%|███▊      | 67/175 [00:23<00:38,  2.77it/s, ms_per_img=1.776, samples=2,176]
Resolution 256 eval:  38%|███▊      | 67/175 [00:23<00:38,  2.77it/s, ms_per_img=1.775, samples=2,208]
Resolution 256 eval:  39%|███▉      | 69/175 [00:23<00:36,  2.89it/s, ms_per_img=1.775, samples=2,208]
Resolution 256 eval:  39%|███▉      | 69/175 [00:24<00:36,  2.89it/s, ms_per_img=1.777, samples=2,240]
Resolution 256 eval:  39%|███▉      | 69/175 [00:24<00:36,  2.89it/s, ms_per_img=1.776, samples=2,272]
Resolution 256 eval:  41%|████      | 71/175 [00:24<00:38,  2.69it/s, ms_per_img=1.776, samples=2,272]
Resolution 256 eval:  41%|████      | 71/175 [00:24<00:38,  2.69it/s, ms_per_img=1.778, samples=2,304]
Resolution 256 eval:  41%|████      | 71/175 [00:25<00:38,  2.69it/s, ms_per_img=1.777, samples=2,336]
Resolution 256 eval:  42%|████▏     | 73/175 [00:25<00:36,  2.81it/s, ms_per_img=1.777, samples=2,336]
Resolution 256 eval:  42%|████▏     | 73/175 [00:25<00:36,  2.81it/s, ms_per_img=1.779, samples=2,368]
Resolution 256 eval:  42%|████▏     | 73/175 [00:25<00:36,  2.81it/s, ms_per_img=1.777, samples=2,400]
Resolution 256 eval:  43%|████▎     | 75/175 [00:25<00:34,  2.91it/s, ms_per_img=1.777, samples=2,400]
Resolution 256 eval:  43%|████▎     | 75/175 [00:26<00:34,  2.91it/s, ms_per_img=1.776, samples=2,432]
Resolution 256 eval:  43%|████▎     | 75/175 [00:26<00:34,  2.91it/s, ms_per_img=1.777, samples=2,464]
Resolution 256 eval:  44%|████▍     | 77/175 [00:26<00:33,  2.93it/s, ms_per_img=1.777, samples=2,464]
Resolution 256 eval:  44%|████▍     | 77/175 [00:27<00:33,  2.93it/s, ms_per_img=1.777, samples=2,496]
Resolution 256 eval:  44%|████▍     | 77/175 [00:27<00:33,  2.93it/s, ms_per_img=1.776, samples=2,528]
Resolution 256 eval:  45%|████▌     | 79/175 [00:27<00:35,  2.67it/s, ms_per_img=1.776, samples=2,528]
Resolution 256 eval:  45%|████▌     | 79/175 [00:27<00:35,  2.67it/s, ms_per_img=1.776, samples=2,560]
Resolution 256 eval:  45%|████▌     | 79/175 [00:28<00:35,  2.67it/s, ms_per_img=1.778, samples=2,592]
Resolution 256 eval:  46%|████▋     | 81/175 [00:28<00:34,  2.73it/s, ms_per_img=1.778, samples=2,592]
Resolution 256 eval:  46%|████▋     | 81/175 [00:28<00:34,  2.73it/s, ms_per_img=1.777, samples=2,624]
Resolution 256 eval:  46%|████▋     | 81/175 [00:28<00:34,  2.73it/s, ms_per_img=1.775, samples=2,656]
Resolution 256 eval:  47%|████▋     | 83/175 [00:28<00:34,  2.68it/s, ms_per_img=1.775, samples=2,656]
Resolution 256 eval:  47%|████▋     | 83/175 [00:29<00:34,  2.68it/s, ms_per_img=1.776, samples=2,688]
Resolution 256 eval:  47%|████▋     | 83/175 [00:29<00:34,  2.68it/s, ms_per_img=1.778, samples=2,720]
Resolution 256 eval:  49%|████▊     | 85/175 [00:29<00:33,  2.67it/s, ms_per_img=1.778, samples=2,720]
Resolution 256 eval:  49%|████▊     | 85/175 [00:30<00:33,  2.67it/s, ms_per_img=1.775, samples=2,752]
Resolution 256 eval:  49%|████▊     | 85/175 [00:30<00:33,  2.67it/s, ms_per_img=1.777, samples=2,784]
Resolution 256 eval:  50%|████▉     | 87/175 [00:30<00:34,  2.58it/s, ms_per_img=1.777, samples=2,784]
Resolution 256 eval:  50%|████▉     | 87/175 [00:30<00:34,  2.58it/s, ms_per_img=1.779, samples=2,816]
Resolution 256 eval:  50%|████▉     | 87/175 [00:31<00:34,  2.58it/s, ms_per_img=1.778, samples=2,848]
Resolution 256 eval:  51%|█████     | 89/175 [00:31<00:33,  2.54it/s, ms_per_img=1.778, samples=2,848]
Resolution 256 eval:  51%|█████     | 89/175 [00:31<00:33,  2.54it/s, ms_per_img=1.777, samples=2,880]
Resolution 256 eval:  51%|█████     | 89/175 [00:32<00:33,  2.54it/s, ms_per_img=1.775, samples=2,912]
Resolution 256 eval:  52%|█████▏    | 91/175 [00:32<00:31,  2.67it/s, ms_per_img=1.775, samples=2,912]
Resolution 256 eval:  52%|█████▏    | 91/175 [00:32<00:31,  2.67it/s, ms_per_img=1.777, samples=2,944]
Resolution 256 eval:  52%|█████▏    | 91/175 [00:32<00:31,  2.67it/s, ms_per_img=1.775, samples=2,976]
Resolution 256 eval:  53%|█████▎    | 93/175 [00:32<00:29,  2.81it/s, ms_per_img=1.775, samples=2,976]
Resolution 256 eval:  53%|█████▎    | 93/175 [00:32<00:29,  2.81it/s, ms_per_img=1.776, samples=3,008]
Resolution 256 eval:  53%|█████▎    | 93/175 [00:33<00:29,  2.81it/s, ms_per_img=1.778, samples=3,040]
Resolution 256 eval:  54%|█████▍    | 95/175 [00:33<00:26,  3.04it/s, ms_per_img=1.778, samples=3,040]
Resolution 256 eval:  54%|█████▍    | 95/175 [00:33<00:26,  3.04it/s, ms_per_img=1.778, samples=3,072]
Resolution 256 eval:  54%|█████▍    | 95/175 [00:33<00:26,  3.04it/s, ms_per_img=1.777, samples=3,104]
Resolution 256 eval:  55%|█████▌    | 97/175 [00:33<00:24,  3.14it/s, ms_per_img=1.777, samples=3,104]
Resolution 256 eval:  55%|█████▌    | 97/175 [00:34<00:24,  3.14it/s, ms_per_img=1.775, samples=3,136]
Resolution 256 eval:  55%|█████▌    | 97/175 [00:34<00:24,  3.14it/s, ms_per_img=1.775, samples=3,168]
Resolution 256 eval:  57%|█████▋    | 99/175 [00:34<00:25,  2.98it/s, ms_per_img=1.775, samples=3,168]
Resolution 256 eval:  57%|█████▋    | 99/175 [00:34<00:25,  2.98it/s, ms_per_img=1.777, samples=3,200]
Resolution 256 eval:  57%|█████▋    | 99/175 [00:35<00:25,  2.98it/s, ms_per_img=1.777, samples=3,232]
Resolution 256 eval:  58%|█████▊    | 101/175 [00:35<00:25,  2.88it/s, ms_per_img=1.777, samples=3,232]
Resolution 256 eval:  58%|█████▊    | 101/175 [00:35<00:25,  2.88it/s, ms_per_img=1.777, samples=3,264]
Resolution 256 eval:  58%|█████▊    | 101/175 [00:35<00:25,  2.88it/s, ms_per_img=1.776, samples=3,296]
Resolution 256 eval:  59%|█████▉    | 103/175 [00:35<00:24,  2.90it/s, ms_per_img=1.776, samples=3,296]
Resolution 256 eval:  59%|█████▉    | 103/175 [00:36<00:24,  2.90it/s, ms_per_img=1.775, samples=3,328]
Resolution 256 eval:  59%|█████▉    | 103/175 [00:36<00:24,  2.90it/s, ms_per_img=1.777, samples=3,360]
Resolution 256 eval:  60%|██████    | 105/175 [00:36<00:23,  2.92it/s, ms_per_img=1.777, samples=3,360]
Resolution 256 eval:  60%|██████    | 105/175 [00:36<00:23,  2.92it/s, ms_per_img=1.776, samples=3,392]
Resolution 256 eval:  60%|██████    | 105/175 [00:37<00:23,  2.92it/s, ms_per_img=1.778, samples=3,424]
Resolution 256 eval:  61%|██████    | 107/175 [00:37<00:21,  3.13it/s, ms_per_img=1.778, samples=3,424]
Resolution 256 eval:  61%|██████    | 107/175 [00:37<00:21,  3.13it/s, ms_per_img=1.775, samples=3,456]
Resolution 256 eval:  61%|██████    | 107/175 [00:37<00:21,  3.13it/s, ms_per_img=1.779, samples=3,488]
Resolution 256 eval:  62%|██████▏   | 109/175 [00:37<00:19,  3.31it/s, ms_per_img=1.779, samples=3,488]
Resolution 256 eval:  62%|██████▏   | 109/175 [00:38<00:19,  3.31it/s, ms_per_img=1.777, samples=3,520]
Resolution 256 eval:  62%|██████▏   | 109/175 [00:38<00:19,  3.31it/s, ms_per_img=1.778, samples=3,552]
Resolution 256 eval:  63%|██████▎   | 111/175 [00:38<00:18,  3.39it/s, ms_per_img=1.778, samples=3,552]
Resolution 256 eval:  63%|██████▎   | 111/175 [00:38<00:18,  3.39it/s, ms_per_img=1.776, samples=3,584]
Resolution 256 eval:  63%|██████▎   | 111/175 [00:38<00:18,  3.39it/s, ms_per_img=1.778, samples=3,616]
Resolution 256 eval:  65%|██████▍   | 113/175 [00:38<00:17,  3.50it/s, ms_per_img=1.778, samples=3,616]
Resolution 256 eval:  65%|██████▍   | 113/175 [00:39<00:17,  3.50it/s, ms_per_img=1.777, samples=3,648]
Resolution 256 eval:  65%|██████▍   | 113/175 [00:39<00:17,  3.50it/s, ms_per_img=1.777, samples=3,680]
Resolution 256 eval:  66%|██████▌   | 115/175 [00:39<00:19,  3.03it/s, ms_per_img=1.777, samples=3,680]
Resolution 256 eval:  66%|██████▌   | 115/175 [00:39<00:19,  3.03it/s, ms_per_img=1.777, samples=3,712]
Resolution 256 eval:  66%|██████▌   | 115/175 [00:40<00:19,  3.03it/s, ms_per_img=1.776, samples=3,744]
Resolution 256 eval:  67%|██████▋   | 117/175 [00:40<00:19,  2.97it/s, ms_per_img=1.776, samples=3,744]
Resolution 256 eval:  67%|██████▋   | 117/175 [00:40<00:19,  2.97it/s, ms_per_img=1.777, samples=3,776]
Resolution 256 eval:  67%|██████▋   | 117/175 [00:40<00:19,  2.97it/s, ms_per_img=1.777, samples=3,808]
Resolution 256 eval:  68%|██████▊   | 119/175 [00:40<00:18,  3.07it/s, ms_per_img=1.777, samples=3,808]
Resolution 256 eval:  68%|██████▊   | 119/175 [00:41<00:18,  3.07it/s, ms_per_img=1.778, samples=3,840]
Resolution 256 eval:  68%|██████▊   | 119/175 [00:41<00:18,  3.07it/s, ms_per_img=1.777, samples=3,872]
Resolution 256 eval:  69%|██████▉   | 121/175 [00:41<00:17,  3.15it/s, ms_per_img=1.777, samples=3,872]
Resolution 256 eval:  69%|██████▉   | 121/175 [00:41<00:17,  3.15it/s, ms_per_img=1.777, samples=3,904]
Resolution 256 eval:  69%|██████▉   | 121/175 [00:42<00:17,  3.15it/s, ms_per_img=1.776, samples=3,936]
Resolution 256 eval:  70%|███████   | 123/175 [00:42<00:18,  2.83it/s, ms_per_img=1.776, samples=3,936]
Resolution 256 eval:  70%|███████   | 123/175 [00:42<00:18,  2.83it/s, ms_per_img=1.778, samples=3,968]
Resolution 256 eval:  70%|███████   | 123/175 [00:43<00:18,  2.83it/s, ms_per_img=1.775, samples=4,000]
Resolution 256 eval:  71%|███████▏  | 125/175 [00:43<00:17,  2.82it/s, ms_per_img=1.775, samples=4,000]
Resolution 256 eval:  71%|███████▏  | 125/175 [00:43<00:17,  2.82it/s, ms_per_img=1.776, samples=4,032]
Resolution 256 eval:  71%|███████▏  | 125/175 [00:43<00:17,  2.82it/s, ms_per_img=1.777, samples=4,064]
Resolution 256 eval:  73%|███████▎  | 127/175 [00:43<00:17,  2.72it/s, ms_per_img=1.777, samples=4,064]
Resolution 256 eval:  73%|███████▎  | 127/175 [00:44<00:17,  2.72it/s, ms_per_img=1.781, samples=4,096]
Resolution 256 eval:  73%|███████▎  | 127/175 [00:44<00:17,  2.72it/s, ms_per_img=1.777, samples=4,128]
Resolution 256 eval:  74%|███████▎  | 129/175 [00:44<00:16,  2.81it/s, ms_per_img=1.777, samples=4,128]
Resolution 256 eval:  74%|███████▎  | 129/175 [00:44<00:16,  2.81it/s, ms_per_img=1.777, samples=4,160]

Acc=0.8571 AUC=0.5590 Fast=100.00% Medium=0.00% Full=0.00%

Resolution sweep:  75%|███████▌  | 3/4 [05:46<01:42, 102.74s/it]

Source Res=256 Single: 5.846 ms/img | 171.1 FPS
Source Res=256 Batch=32: 1.781 ms/img | 561.5 FPS

Resolution 384

Resolution 384 eval:   0%|          | 0/175 [00:00<?, ?it/s]
Resolution 384 eval:   0%|          | 0/175 [00:00<?, ?it/s, ms_per_img=1.781, samples=32]
Resolution 384 eval:   0%|          | 0/175 [00:00<?, ?it/s, ms_per_img=1.779, samples=64]
Resolution 384 eval:   1%|          | 2/175 [00:00<00:58,  2.97it/s, ms_per_img=1.779, samples=64]
Resolution 384 eval:   1%|          | 2/175 [00:01<00:58,  2.97it/s, ms_per_img=1.783, samples=96]
Resolution 384 eval:   1%|          | 2/175 [00:01<00:58,  2.97it/s, ms_per_img=1.775, samples=128]
Resolution 384 eval:   2%|▏         | 4/175 [00:01<01:16,  2.23it/s, ms_per_img=1.775, samples=128]
Resolution 384 eval:   2%|▏         | 4/175 [00:02<01:16,  2.23it/s, ms_per_img=1.778, samples=160]
Resolution 384 eval:   2%|▏         | 4/175 [00:02<01:16,  2.23it/s, ms_per_img=1.777, samples=192]
Resolution 384 eval:   3%|▎         | 6/175 [00:02<01:10,  2.39it/s, ms_per_img=1.777, samples=192]
Resolution 384 eval:   3%|▎         | 6/175 [00:02<01:10,  2.39it/s, ms_per_img=1.778, samples=224]
Resolution 384 eval:   3%|▎         | 6/175 [00:03<01:10,  2.39it/s, ms_per_img=1.777, samples=256]
Resolution 384 eval:   5%|▍         | 8/175 [00:03<01:01,  2.72it/s, ms_per_img=1.777, samples=256]
Resolution 384 eval:   5%|▍         | 8/175 [00:03<01:01,  2.72it/s, ms_per_img=1.776, samples=288]
Resolution 384 eval:   5%|▍         | 8/175 [00:03<01:01,  2.72it/s, ms_per_img=1.777, samples=320]
Resolution 384 eval:   6%|▌         | 10/175 [00:03<01:04,  2.54it/s, ms_per_img=1.777, samples=320]
Resolution 384 eval:   6%|▌         | 10/175 [00:04<01:04,  2.54it/s, ms_per_img=1.776, samples=352]
Resolution 384 eval:   6%|▌         | 10/175 [00:04<01:04,  2.54it/s, ms_per_img=1.777, samples=384]
Resolution 384 eval:   7%|▋         | 12/175 [00:04<01:05,  2.48it/s, ms_per_img=1.777, samples=384]
Resolution 384 eval:   7%|▋         | 12/175 [00:05<01:05,  2.48it/s, ms_per_img=1.777, samples=416]
Resolution 384 eval:   7%|▋         | 12/175 [00:05<01:05,  2.48it/s, ms_per_img=1.778, samples=448]
Resolution 384 eval:   8%|▊         | 14/175 [00:05<01:01,  2.64it/s, ms_per_img=1.778, samples=448]
Resolution 384 eval:   8%|▊         | 14/175 [00:05<01:01,  2.64it/s, ms_per_img=1.779, samples=480]
Resolution 384 eval:   8%|▊         | 14/175 [00:06<01:01,  2.64it/s, ms_per_img=1.779, samples=512]
Resolution 384 eval:   9%|▉         | 16/175 [00:06<00:55,  2.87it/s, ms_per_img=1.779, samples=512]
Resolution 384 eval:   9%|▉         | 16/175 [00:06<00:55,  2.87it/s, ms_per_img=1.777, samples=544]
Resolution 384 eval:   9%|▉         | 16/175 [00:06<00:55,  2.87it/s, ms_per_img=1.777, samples=576]
Resolution 384 eval:  10%|█         | 18/175 [00:06<00:54,  2.88it/s, ms_per_img=1.777, samples=576]
Resolution 384 eval:  10%|█         | 18/175 [00:07<00:54,  2.88it/s, ms_per_img=1.779, samples=608]
Resolution 384 eval:  10%|█         | 18/175 [00:07<00:54,  2.88it/s, ms_per_img=1.776, samples=640]
Resolution 384 eval:  11%|█▏        | 20/175 [00:07<00:54,  2.86it/s, ms_per_img=1.776, samples=640]
Resolution 384 eval:  11%|█▏        | 20/175 [00:07<00:54,  2.86it/s, ms_per_img=1.778, samples=672]
Resolution 384 eval:  11%|█▏        | 20/175 [00:08<00:54,  2.86it/s, ms_per_img=1.779, samples=704]
Resolution 384 eval:  13%|█▎        | 22/175 [00:08<00:55,  2.78it/s, ms_per_img=1.779, samples=704]
Resolution 384 eval:  13%|█▎        | 22/175 [00:08<00:55,  2.78it/s, ms_per_img=1.776, samples=736]
Resolution 384 eval:  13%|█▎        | 22/175 [00:08<00:55,  2.78it/s, ms_per_img=1.777, samples=768]
Resolution 384 eval:  14%|█▎        | 24/175 [00:08<00:55,  2.73it/s, ms_per_img=1.777, samples=768]
Resolution 384 eval:  14%|█▎        | 24/175 [00:09<00:55,  2.73it/s, ms_per_img=1.778, samples=800]
Resolution 384 eval:  14%|█▎        | 24/175 [00:09<00:55,  2.73it/s, ms_per_img=1.777, samples=832]
Resolution 384 eval:  15%|█▍        | 26/175 [00:09<00:53,  2.80it/s, ms_per_img=1.777, samples=832]
Resolution 384 eval:  15%|█▍        | 26/175 [00:10<00:53,  2.80it/s, ms_per_img=1.779, samples=864]
Resolution 384 eval:  15%|█▍        | 26/175 [00:10<00:53,  2.80it/s, ms_per_img=1.777, samples=896]
Resolution 384 eval:  16%|█▌        | 28/175 [00:10<00:54,  2.71it/s, ms_per_img=1.777, samples=896]
Resolution 384 eval:  16%|█▌        | 28/175 [00:10<00:54,  2.71it/s, ms_per_img=1.778, samples=928]
Resolution 384 eval:  16%|█▌        | 28/175 [00:11<00:54,  2.71it/s, ms_per_img=1.777, samples=960]
Resolution 384 eval:  17%|█▋        | 30/175 [00:11<00:55,  2.62it/s, ms_per_img=1.777, samples=960]
Resolution 384 eval:  17%|█▋        | 30/175 [00:11<00:55,  2.62it/s, ms_per_img=1.778, samples=992]
Resolution 384 eval:  17%|█▋        | 30/175 [00:11<00:55,  2.62it/s, ms_per_img=1.778, samples=1,024]
Resolution 384 eval:  18%|█▊        | 32/175 [00:11<00:54,  2.63it/s, ms_per_img=1.778, samples=1,024]
Resolution 384 eval:  18%|█▊        | 32/175 [00:12<00:54,  2.63it/s, ms_per_img=1.777, samples=1,056]
Resolution 384 eval:  18%|█▊        | 32/175 [00:12<00:54,  2.63it/s, ms_per_img=1.776, samples=1,088]
Resolution 384 eval:  19%|█▉        | 34/175 [00:12<00:56,  2.51it/s, ms_per_img=1.776, samples=1,088]
Resolution 384 eval:  19%|█▉        | 34/175 [00:13<00:56,  2.51it/s, ms_per_img=1.778, samples=1,120]
Resolution 384 eval:  19%|█▉        | 34/175 [00:14<00:56,  2.51it/s, ms_per_img=1.776, samples=1,152]
Resolution 384 eval:  21%|██        | 36/175 [00:14<01:02,  2.21it/s, ms_per_img=1.776, samples=1,152]
Resolution 384 eval:  21%|██        | 36/175 [00:14<01:02,  2.21it/s, ms_per_img=1.778, samples=1,184]
Resolution 384 eval:  21%|██        | 36/175 [00:14<01:02,  2.21it/s, ms_per_img=1.776, samples=1,216]
Resolution 384 eval:  22%|██▏       | 38/175 [00:14<00:54,  2.52it/s, ms_per_img=1.776, samples=1,216]
Resolution 384 eval:  22%|██▏       | 38/175 [00:14<00:54,  2.52it/s, ms_per_img=1.776, samples=1,248]
Resolution 384 eval:  22%|██▏       | 38/175 [00:15<00:54,  2.52it/s, ms_per_img=1.777, samples=1,280]
Resolution 384 eval:  23%|██▎       | 40/175 [00:15<00:51,  2.63it/s, ms_per_img=1.777, samples=1,280]
Resolution 384 eval:  23%|██▎       | 40/175 [00:15<00:51,  2.63it/s, ms_per_img=1.778, samples=1,312]
Resolution 384 eval:  23%|██▎       | 40/175 [00:16<00:51,  2.63it/s, ms_per_img=1.777, samples=1,344]
Resolution 384 eval:  24%|██▍       | 42/175 [00:16<00:53,  2.51it/s, ms_per_img=1.777, samples=1,344]
Resolution 384 eval:  24%|██▍       | 42/175 [00:16<00:53,  2.51it/s, ms_per_img=1.778, samples=1,376]
Resolution 384 eval:  24%|██▍       | 42/175 [00:16<00:53,  2.51it/s, ms_per_img=1.776, samples=1,408]
Resolution 384 eval:  25%|██▌       | 44/175 [00:16<00:52,  2.52it/s, ms_per_img=1.776, samples=1,408]
Resolution 384 eval:  25%|██▌       | 44/175 [00:17<00:52,  2.52it/s, ms_per_img=1.777, samples=1,440]
Resolution 384 eval:  25%|██▌       | 44/175 [00:17<00:52,  2.52it/s, ms_per_img=1.777, samples=1,472]
Resolution 384 eval:  26%|██▋       | 46/175 [00:17<00:46,  2.75it/s, ms_per_img=1.777, samples=1,472]
Resolution 384 eval:  26%|██▋       | 46/175 [00:17<00:46,  2.75it/s, ms_per_img=1.777, samples=1,504]
Resolution 384 eval:  26%|██▋       | 46/175 [00:18<00:46,  2.75it/s, ms_per_img=1.775, samples=1,536]
Resolution 384 eval:  27%|██▋       | 48/175 [00:18<00:46,  2.71it/s, ms_per_img=1.775, samples=1,536]
Resolution 384 eval:  27%|██▋       | 48/175 [00:18<00:46,  2.71it/s, ms_per_img=1.776, samples=1,568]
Resolution 384 eval:  27%|██▋       | 48/175 [00:18<00:46,  2.71it/s, ms_per_img=1.778, samples=1,600]
Resolution 384 eval:  29%|██▊       | 50/175 [00:18<00:45,  2.74it/s, ms_per_img=1.778, samples=1,600]
Resolution 384 eval:  29%|██▊       | 50/175 [00:19<00:45,  2.74it/s, ms_per_img=1.778, samples=1,632]
Resolution 384 eval:  29%|██▊       | 50/175 [00:19<00:45,  2.74it/s, ms_per_img=1.777, samples=1,664]
Resolution 384 eval:  30%|██▉       | 52/175 [00:19<00:46,  2.66it/s, ms_per_img=1.777, samples=1,664]
Resolution 384 eval:  30%|██▉       | 52/175 [00:20<00:46,  2.66it/s, ms_per_img=1.775, samples=1,696]
Resolution 384 eval:  30%|██▉       | 52/175 [00:20<00:46,  2.66it/s, ms_per_img=1.775, samples=1,728]
Resolution 384 eval:  31%|███       | 54/175 [00:20<00:45,  2.66it/s, ms_per_img=1.775, samples=1,728]
Resolution 384 eval:  31%|███       | 54/175 [00:20<00:45,  2.66it/s, ms_per_img=1.778, samples=1,760]
Resolution 384 eval:  31%|███       | 54/175 [00:21<00:45,  2.66it/s, ms_per_img=1.776, samples=1,792]
Resolution 384 eval:  32%|███▏      | 56/175 [00:21<00:42,  2.80it/s, ms_per_img=1.776, samples=1,792]
Resolution 384 eval:  32%|███▏      | 56/175 [00:21<00:42,  2.80it/s, ms_per_img=1.779, samples=1,824]
Resolution 384 eval:  32%|███▏      | 56/175 [00:21<00:42,  2.80it/s, ms_per_img=1.779, samples=1,856]
Resolution 384 eval:  33%|███▎      | 58/175 [00:21<00:41,  2.84it/s, ms_per_img=1.779, samples=1,856]
Resolution 384 eval:  33%|███▎      | 58/175 [00:22<00:41,  2.84it/s, ms_per_img=1.776, samples=1,888]
Resolution 384 eval:  33%|███▎      | 58/175 [00:22<00:41,  2.84it/s, ms_per_img=1.781, samples=1,920]
Resolution 384 eval:  34%|███▍      | 60/175 [00:22<00:40,  2.84it/s, ms_per_img=1.781, samples=1,920]
Resolution 384 eval:  34%|███▍      | 60/175 [00:22<00:40,  2.84it/s, ms_per_img=1.777, samples=1,952]
Resolution 384 eval:  34%|███▍      | 60/175 [00:23<00:40,  2.84it/s, ms_per_img=1.779, samples=1,984]
Resolution 384 eval:  35%|███▌      | 62/175 [00:23<00:40,  2.76it/s, ms_per_img=1.779, samples=1,984]
Resolution 384 eval:  35%|███▌      | 62/175 [00:23<00:40,  2.76it/s, ms_per_img=1.777, samples=2,016]
Resolution 384 eval:  35%|███▌      | 62/175 [00:24<00:40,  2.76it/s, ms_per_img=1.775, samples=2,048]
Resolution 384 eval:  37%|███▋      | 64/175 [00:24<00:41,  2.69it/s, ms_per_img=1.775, samples=2,048]
Resolution 384 eval:  37%|███▋      | 64/175 [00:24<00:41,  2.69it/s, ms_per_img=1.777, samples=2,080]
Resolution 384 eval:  37%|███▋      | 64/175 [00:24<00:41,  2.69it/s, ms_per_img=1.775, samples=2,112]
Resolution 384 eval:  38%|███▊      | 66/175 [00:24<00:41,  2.64it/s, ms_per_img=1.775, samples=2,112]
Resolution 384 eval:  38%|███▊      | 66/175 [00:25<00:41,  2.64it/s, ms_per_img=1.778, samples=2,144]
Resolution 384 eval:  38%|███▊      | 66/175 [00:25<00:41,  2.64it/s, ms_per_img=1.776, samples=2,176]
Resolution 384 eval:  39%|███▉      | 68/175 [00:25<00:41,  2.56it/s, ms_per_img=1.776, samples=2,176]
Resolution 384 eval:  39%|███▉      | 68/175 [00:26<00:41,  2.56it/s, ms_per_img=1.778, samples=2,208]
Resolution 384 eval:  39%|███▉      | 68/175 [00:26<00:41,  2.56it/s, ms_per_img=1.777, samples=2,240]
Resolution 384 eval:  40%|████      | 70/175 [00:26<00:42,  2.45it/s, ms_per_img=1.777, samples=2,240]
Resolution 384 eval:  40%|████      | 70/175 [00:26<00:42,  2.45it/s, ms_per_img=1.776, samples=2,272]
Resolution 384 eval:  40%|████      | 70/175 [00:27<00:42,  2.45it/s, ms_per_img=1.776, samples=2,304]
Resolution 384 eval:  41%|████      | 72/175 [00:27<00:40,  2.57it/s, ms_per_img=1.776, samples=2,304]
Resolution 384 eval:  41%|████      | 72/175 [00:27<00:40,  2.57it/s, ms_per_img=1.776, samples=2,336]
Resolution 384 eval:  41%|████      | 72/175 [00:28<00:40,  2.57it/s, ms_per_img=1.776, samples=2,368]
Resolution 384 eval:  42%|████▏     | 74/175 [00:28<00:39,  2.58it/s, ms_per_img=1.776, samples=2,368]
Resolution 384 eval:  42%|████▏     | 74/175 [00:28<00:39,  2.58it/s, ms_per_img=1.777, samples=2,400]
Resolution 384 eval:  42%|████▏     | 74/175 [00:28<00:39,  2.58it/s, ms_per_img=1.777, samples=2,432]
Resolution 384 eval:  43%|████▎     | 76/175 [00:28<00:37,  2.67it/s, ms_per_img=1.777, samples=2,432]
Resolution 384 eval:  43%|████▎     | 76/175 [00:29<00:37,  2.67it/s, ms_per_img=1.778, samples=2,464]
Resolution 384 eval:  43%|████▎     | 76/175 [00:29<00:37,  2.67it/s, ms_per_img=1.777, samples=2,496]
Resolution 384 eval:  45%|████▍     | 78/175 [00:29<00:39,  2.45it/s, ms_per_img=1.777, samples=2,496]
Resolution 384 eval:  45%|████▍     | 78/175 [00:30<00:39,  2.45it/s, ms_per_img=1.778, samples=2,528]
Resolution 384 eval:  45%|████▍     | 78/175 [00:30<00:39,  2.45it/s, ms_per_img=1.777, samples=2,560]
Resolution 384 eval:  46%|████▌     | 80/175 [00:30<00:36,  2.57it/s, ms_per_img=1.777, samples=2,560]
Resolution 384 eval:  46%|████▌     | 80/175 [00:30<00:36,  2.57it/s, ms_per_img=1.776, samples=2,592]
Resolution 384 eval:  46%|████▌     | 80/175 [00:31<00:36,  2.57it/s, ms_per_img=1.774, samples=2,624]
Resolution 384 eval:  47%|████▋     | 82/175 [00:31<00:36,  2.54it/s, ms_per_img=1.774, samples=2,624]
Resolution 384 eval:  47%|████▋     | 82/175 [00:31<00:36,  2.54it/s, ms_per_img=1.778, samples=2,656]
Resolution 384 eval:  47%|████▋     | 82/175 [00:32<00:36,  2.54it/s, ms_per_img=1.778, samples=2,688]
Resolution 384 eval:  48%|████▊     | 84/175 [00:32<00:38,  2.39it/s, ms_per_img=1.778, samples=2,688]
Resolution 384 eval:  48%|████▊     | 84/175 [00:32<00:38,  2.39it/s, ms_per_img=1.776, samples=2,720]
Resolution 384 eval:  48%|████▊     | 84/175 [00:32<00:38,  2.39it/s, ms_per_img=1.776, samples=2,752]
Resolution 384 eval:  49%|████▉     | 86/175 [00:32<00:35,  2.48it/s, ms_per_img=1.776, samples=2,752]
Resolution 384 eval:  49%|████▉     | 86/175 [00:33<00:35,  2.48it/s, ms_per_img=1.778, samples=2,784]
Resolution 384 eval:  49%|████▉     | 86/175 [00:33<00:35,  2.48it/s, ms_per_img=1.777, samples=2,816]
Resolution 384 eval:  50%|█████     | 88/175 [00:33<00:35,  2.43it/s, ms_per_img=1.777, samples=2,816]
Resolution 384 eval:  50%|█████     | 88/175 [00:34<00:35,  2.43it/s, ms_per_img=1.773, samples=2,848]
Resolution 384 eval:  50%|█████     | 88/175 [00:34<00:35,  2.43it/s, ms_per_img=1.776, samples=2,880]
Resolution 384 eval:  51%|█████▏    | 90/175 [00:34<00:35,  2.38it/s, ms_per_img=1.776, samples=2,880]
Resolution 384 eval:  51%|█████▏    | 90/175 [00:35<00:35,  2.38it/s, ms_per_img=1.776, samples=2,912]
Resolution 384 eval:  51%|█████▏    | 90/175 [00:35<00:35,  2.38it/s, ms_per_img=1.777, samples=2,944]
Resolution 384 eval:  53%|█████▎    | 92/175 [00:35<00:33,  2.48it/s, ms_per_img=1.777, samples=2,944]
Resolution 384 eval:  53%|█████▎    | 92/175 [00:35<00:33,  2.48it/s, ms_per_img=1.775, samples=2,976]
Resolution 384 eval:  53%|█████▎    | 92/175 [00:36<00:33,  2.48it/s, ms_per_img=1.779, samples=3,008]
Resolution 384 eval:  54%|█████▎    | 94/175 [00:36<00:30,  2.66it/s, ms_per_img=1.779, samples=3,008]
Resolution 384 eval:  54%|█████▎    | 94/175 [00:36<00:30,  2.66it/s, ms_per_img=1.778, samples=3,040]
Resolution 384 eval:  54%|█████▎    | 94/175 [00:36<00:30,  2.66it/s, ms_per_img=1.777, samples=3,072]
Resolution 384 eval:  55%|█████▍    | 96/175 [00:36<00:28,  2.78it/s, ms_per_img=1.777, samples=3,072]
Resolution 384 eval:  55%|█████▍    | 96/175 [00:36<00:28,  2.78it/s, ms_per_img=1.776, samples=3,104]
Resolution 384 eval:  55%|█████▍    | 96/175 [00:37<00:28,  2.78it/s, ms_per_img=1.778, samples=3,136]
Resolution 384 eval:  56%|█████▌    | 98/175 [00:37<00:27,  2.84it/s, ms_per_img=1.778, samples=3,136]
Resolution 384 eval:  56%|█████▌    | 98/175 [00:37<00:27,  2.84it/s, ms_per_img=1.778, samples=3,168]
Resolution 384 eval:  56%|█████▌    | 98/175 [00:38<00:27,  2.84it/s, ms_per_img=1.780, samples=3,200]
Resolution 384 eval:  57%|█████▋    | 100/175 [00:38<00:27,  2.73it/s, ms_per_img=1.780, samples=3,200]
Resolution 384 eval:  57%|█████▋    | 100/175 [00:38<00:27,  2.73it/s, ms_per_img=1.777, samples=3,232]
Resolution 384 eval:  57%|█████▋    | 100/175 [00:38<00:27,  2.73it/s, ms_per_img=1.776, samples=3,264]
Resolution 384 eval:  58%|█████▊    | 102/175 [00:38<00:27,  2.63it/s, ms_per_img=1.776, samples=3,264]
Resolution 384 eval:  58%|█████▊    | 102/175 [00:39<00:27,  2.63it/s, ms_per_img=1.777, samples=3,296]
Resolution 384 eval:  58%|█████▊    | 102/175 [00:39<00:27,  2.63it/s, ms_per_img=1.777, samples=3,328]
Resolution 384 eval:  59%|█████▉    | 104/175 [00:39<00:26,  2.64it/s, ms_per_img=1.777, samples=3,328]
Resolution 384 eval:  59%|█████▉    | 104/175 [00:40<00:26,  2.64it/s, ms_per_img=1.775, samples=3,360]
Resolution 384 eval:  59%|█████▉    | 104/175 [00:40<00:26,  2.64it/s, ms_per_img=1.776, samples=3,392]
Resolution 384 eval:  61%|██████    | 106/175 [00:40<00:25,  2.67it/s, ms_per_img=1.776, samples=3,392]
Resolution 384 eval:  61%|██████    | 106/175 [00:40<00:25,  2.67it/s, ms_per_img=1.779, samples=3,424]
Resolution 384 eval:  61%|██████    | 106/175 [00:40<00:25,  2.67it/s, ms_per_img=1.777, samples=3,456]
Resolution 384 eval:  62%|██████▏   | 108/175 [00:40<00:22,  2.94it/s, ms_per_img=1.777, samples=3,456]
Resolution 384 eval:  62%|██████▏   | 108/175 [00:41<00:22,  2.94it/s, ms_per_img=1.778, samples=3,488]
Resolution 384 eval:  62%|██████▏   | 108/175 [00:41<00:22,  2.94it/s, ms_per_img=1.776, samples=3,520]
Resolution 384 eval:  63%|██████▎   | 110/175 [00:41<00:21,  2.96it/s, ms_per_img=1.776, samples=3,520]
Resolution 384 eval:  63%|██████▎   | 110/175 [00:41<00:21,  2.96it/s, ms_per_img=1.779, samples=3,552]
Resolution 384 eval:  63%|██████▎   | 110/175 [00:42<00:21,  2.96it/s, ms_per_img=1.777, samples=3,584]
Resolution 384 eval:  63%|██████▎   | 110/175 [00:42<00:21,  2.96it/s, ms_per_img=1.779, samples=3,616]
Resolution 384 eval:  65%|██████▍   | 113/175 [00:42<00:19,  3.16it/s, ms_per_img=1.779, samples=3,616]
Resolution 384 eval:  65%|██████▍   | 113/175 [00:42<00:19,  3.16it/s, ms_per_img=1.777, samples=3,648]
Resolution 384 eval:  65%|██████▍   | 113/175 [00:43<00:19,  3.16it/s, ms_per_img=1.776, samples=3,680]
Resolution 384 eval:  66%|██████▌   | 115/175 [00:43<00:21,  2.81it/s, ms_per_img=1.776, samples=3,680]
Resolution 384 eval:  66%|██████▌   | 115/175 [00:43<00:21,  2.81it/s, ms_per_img=1.775, samples=3,712]
Resolution 384 eval:  66%|██████▌   | 115/175 [00:44<00:21,  2.81it/s, ms_per_img=1.774, samples=3,744]
Resolution 384 eval:  67%|██████▋   | 117/175 [00:44<00:21,  2.74it/s, ms_per_img=1.774, samples=3,744]
Resolution 384 eval:  67%|██████▋   | 117/175 [00:44<00:21,  2.74it/s, ms_per_img=1.776, samples=3,776]
Resolution 384 eval:  67%|██████▋   | 117/175 [00:44<00:21,  2.74it/s, ms_per_img=1.777, samples=3,808]
Resolution 384 eval:  68%|██████▊   | 119/175 [00:44<00:19,  2.82it/s, ms_per_img=1.777, samples=3,808]
Resolution 384 eval:  68%|██████▊   | 119/175 [00:45<00:19,  2.82it/s, ms_per_img=1.777, samples=3,840]
Resolution 384 eval:  68%|██████▊   | 119/175 [00:45<00:19,  2.82it/s, ms_per_img=1.777, samples=3,872]
Resolution 384 eval:  69%|██████▉   | 121/175 [00:45<00:18,  2.88it/s, ms_per_img=1.777, samples=3,872]
Resolution 384 eval:  69%|██████▉   | 121/175 [00:45<00:18,  2.88it/s, ms_per_img=1.776, samples=3,904]
Resolution 384 eval:  69%|██████▉   | 121/175 [00:46<00:18,  2.88it/s, ms_per_img=1.777, samples=3,936]
Resolution 384 eval:  70%|███████   | 123/175 [00:46<00:19,  2.61it/s, ms_per_img=1.777, samples=3,936]
Resolution 384 eval:  70%|███████   | 123/175 [00:46<00:19,  2.61it/s, ms_per_img=1.773, samples=3,968]
Resolution 384 eval:  70%|███████   | 123/175 [00:47<00:19,  2.61it/s, ms_per_img=1.778, samples=4,000]
Resolution 384 eval:  71%|███████▏  | 125/175 [00:47<00:19,  2.60it/s, ms_per_img=1.778, samples=4,000]
Resolution 384 eval:  71%|███████▏  | 125/175 [00:47<00:19,  2.60it/s, ms_per_img=1.775, samples=4,032]
Resolution 384 eval:  71%|███████▏  | 125/175 [00:48<00:19,  2.60it/s, ms_per_img=1.776, samples=4,064]
Resolution 384 eval:  73%|███████▎  | 127/175 [00:48<00:19,  2.51it/s, ms_per_img=1.776, samples=4,064]
Resolution 384 eval:  73%|███████▎  | 127/175 [00:48<00:19,  2.51it/s, ms_per_img=1.774, samples=4,096]
Resolution 384 eval:  73%|███████▎  | 127/175 [00:48<00:19,  2.51it/s, ms_per_img=1.775, samples=4,128]
Resolution 384 eval:  74%|███████▎  | 129/175 [00:48<00:17,  2.58it/s, ms_per_img=1.775, samples=4,128]
Resolution 384 eval:  74%|███████▎  | 129/175 [00:49<00:17,  2.58it/s, ms_per_img=1.777, samples=4,160]

Acc=0.8571 AUC=0.5575 Fast=100.00% Medium=0.00% Full=0.00%

Resolution sweep: 100%|██████████| 4/4 [07:06<00:00, 106.58s/it]

Source Res=384 Single: 5.859 ms/img | 170.7 FPS
Source Res=384 Batch=32: 1.781 ms/img | 561.4 FPS

====================================================================================================
====================================MaD-CoRN EXPERIMENT RESULTS=====================================
====================================================================================================

[1] TRAINING PERIODS RESULTS
                                               Training Periods Results

+-------+------------+-----------+-----------+---------+---------+-----------+--------+--------+--------------------+
| Epoch | Train Loss | Train Acc | Train AUC | Val Acc | Val AUC | Precision | Recall | F1     | Uncertain Rate (%) |
+-------+------------+-----------+-----------+---------+---------+-----------+--------+--------+--------------------+
| 1     | 0.7403     | 0.1444    | 0.4939    | 0.1429  | 0.4981  | 0.0000    | 0.0000 | 0.0000 | 100.00             |
| 2     | 0.4496     | 0.8565    | 0.5112    | 0.8571  | 0.5343  | 0.8571    | 1.0000 | 0.9231 | 0.00               |
| 3     | 0.4514     | 0.8570    | 0.5214    | 0.8571  | 0.5348  | 0.8571    | 1.0000 | 0.9231 | 0.00               |
| 4     | 0.4443     | 0.8571    | 0.5245    | 0.8571  | 0.5294  | 0.8571    | 1.0000 | 0.9231 | 0.00               |
| 5     | 0.4404     | 0.8570    | 0.5411    | 0.8571  | 0.5376  | 0.8571    | 1.0000 | 0.9231 | 0.00               |
| 6     | 0.4390     | 0.8571    | 0.5526    | 0.8571  | 0.5680  | 0.8571    | 1.0000 | 0.9231 | 0.00               |
| 7     | 0.4372     | 0.8570    | 0.5613    | 0.8571  | 0.6076  | 0.8571    | 1.0000 | 0.9231 | 0.00               |
| 8     | 0.4367     | 0.8570    | 0.5643    | 0.8571  | 0.5536  | 0.8571    | 1.0000 | 0.9231 | 0.00               |
| 9     | 0.4345     | 0.8570    | 0.5699    | 0.8571  | 0.5723  | 0.8571    | 1.0000 | 0.9231 | 0.00               |
| 10    | 0.4330     | 0.8570    | 0.5731    | 0.8571  | 0.5754  | 0.8571    | 1.0000 | 0.9231 | 0.00               |
| 11    | 0.4314     | 0.8570    | 0.5715    | 0.8571  | 0.5447  | 0.8571    | 1.0000 | 0.9231 | 0.00               |
| 12    | 0.4298     | 0.8570    | 0.5791    | 0.8571  | 0.5615  | 0.8571    | 1.0000 | 0.9231 | 0.00               |
| 13    | 0.4291     | 0.8570    | 0.5866    | 0.8571  | 0.5316  | 0.8571    | 1.0000 | 0.9231 | 0.00               |
| 14    | 0.4284     | 0.8570    | 0.5853    | 0.8571  | 0.5237  | 0.8571    | 1.0000 | 0.9231 | 0.00               |
| 15    | 0.4279     | 0.8571    | 0.5825    | 0.8571  | 0.5330  | 0.8571    | 1.0000 | 0.9231 | 0.00               |
+-------+------------+-----------+-----------+---------+---------+-----------+--------+--------+--------------------+

[2] TEST RESULTS
                                      Test Results

+---------------+----------+--------+-----------+--------+--------+--------------------+
| Model         | Accuracy | AUC    | Precision | Recall | F1     | Uncertain Rate (%) |
+---------------+----------+--------+-----------+--------+--------+--------------------+
| MaD-CoRN-FFPP | 0.8571   | 0.5592 | 0.8571    | 1.0000 | 0.9230 | 0.00               |
+---------------+----------+--------+-----------+--------+--------+--------------------+

[3] ACCURACY BASED ON RESOLUTION
                     Accuracy Based on Resolution

+------------+----------+--------+----------+------------+----------+
| Resolution | Accuracy | AUC    | Fast (%) | Medium (%) | Full (%) |
+------------+----------+--------+----------+------------+----------+
| 128        | 0.8571   | 0.5639 | 100.00   | 0.00       | 0.00     |
| 224        | 0.8571   | 0.5569 | 100.00   | 0.00       | 0.00     |
| 256        | 0.8571   | 0.5590 | 100.00   | 0.00       | 0.00     |
| 384        | 0.8571   | 0.5575 | 100.00   | 0.00       | 0.00     |
+------------+----------+--------+----------+------------+----------+

[4] INFERENCE TIME
                      Inference Time

+-------------------------+---------------------+-------+
| Mode                    | Time per Image (ms) | FPS   |
+-------------------------+---------------------+-------+
| Source Res=128 Single   | 5.864               | 170.5 |
| Source Res=128 Batch=32 | 1.778               | 562.3 |
| Source Res=224 Single   | 5.934               | 168.5 |
| Source Res=224 Batch=32 | 1.781               | 561.6 |
| Source Res=256 Single   | 5.846               | 171.1 |
| Source Res=256 Batch=32 | 1.781               | 561.5 |
| Source Res=384 Single   | 5.859               | 170.7 |
| Source Res=384 Batch=32 | 1.781               | 561.4 |
+-------------------------+---------------------+-------+

[5] TRAINING TIME
                       Training Time

+-----------------------------------------+-------+-------+
| Model Type                              | min   | hrs   |
+-----------------------------------------+-------+-------+
| MaD-CoRN FF++ multi-resolution training | 646.9 | 10.78 |
+-----------------------------------------+-------+-------+

Results saved to: ./mad_corn_results_ffpp

In [1]:
print('test')

test

In [2]:
!pip install scikit-learn torch torchvision

Requirement already satisfied: scikit-learn in /opt/conda/lib/python3.11/site-packages (1.8.0)
Requirement already satisfied: torch in /opt/conda/lib/python3.11/site-packages (2.11.0)
Requirement already satisfied: torchvision in /opt/conda/lib/python3.11/site-packages (0.26.0)
Requirement already satisfied: numpy>=1.24.1 in /opt/conda/lib/python3.11/site-packages (from scikit-learn) (2.4.4)
Requirement already satisfied: scipy>=1.10.0 in /opt/conda/lib/python3.11/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in /opt/conda/lib/python3.11/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /opt/conda/lib/python3.11/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: filelock in /opt/conda/lib/python3.11/site-packages (from torch) (3.25.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /opt/conda/lib/python3.11/site-packages (from torch) (4.12.2)
Requirement already satisfied: setuptools<82 in /opt/conda/lib/python3.11/site-packages (from torch) (71.0.4)
Requirement already satisfied: sympy>=1.13.3 in /opt/conda/lib/python3.11/site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /opt/conda/lib/python3.11/site-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.11/site-packages (from torch) (3.1.4)
Requirement already satisfied: fsspec>=0.8.5 in /opt/conda/lib/python3.11/site-packages (from torch) (2026.3.0)
Requirement already satisfied: cuda-toolkit==13.0.2 in /opt/conda/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.0.2)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /opt/conda/lib/python3.11/site-packages (from torch) (13.2.0)
Requirement already satisfied: nvidia-cudnn-cu13==9.19.0.56 in /opt/conda/lib/python3.11/site-packages (from torch) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.0 in /opt/conda/lib/python3.11/site-packages (from torch) (0.8.0)
Requirement already satisfied: nvidia-nccl-cu13==2.28.9 in /opt/conda/lib/python3.11/site-packages (from torch) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /opt/conda/lib/python3.11/site-packages (from torch) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /opt/conda/lib/python3.11/site-packages (from torch) (3.6.0)
Requirement already satisfied: nvidia-cublas==13.1.0.3.* in /opt/conda/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.1.0.3)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /opt/conda/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /opt/conda/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (12.0.0.61)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /opt/conda/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /opt/conda/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /opt/conda/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /opt/conda/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /opt/conda/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (12.6.3.3)
Requirement already satisfied: nvidia-nvjitlink==13.0.88.* in /opt/conda/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.0.88)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /opt/conda/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.0.88)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /opt/conda/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.0.85)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /opt/conda/lib/python3.11/site-packages (from torchvision) (12.2.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /opt/conda/lib/python3.11/site-packages (from cuda-bindings<14,>=13.0.3->torch) (1.5.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /opt/conda/lib/python3.11/site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.11/site-packages (from jinja2->torch) (2.1.5)

In [3]:
!pip install kagglehub
import kagglehub

# Download latest version
path = kagglehub.dataset_download("pranabr0y/celebdf-v2image-dataset")

print("Path to dataset files:", path)

Requirement already satisfied: kagglehub in /opt/conda/lib/python3.11/site-packages (1.0.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.14 in /opt/conda/lib/python3.11/site-packages (from kagglehub) (0.1.18)
Requirement already satisfied: packaging in /opt/conda/lib/python3.11/site-packages (from kagglehub) (24.1)
Requirement already satisfied: pyyaml in /opt/conda/lib/python3.11/site-packages (from kagglehub) (6.0.1)
Requirement already satisfied: requests in /opt/conda/lib/python3.11/site-packages (from kagglehub) (2.32.3)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.11/site-packages (from kagglehub) (4.66.4)
Requirement already satisfied: protobuf in /opt/conda/lib/python3.11/site-packages (from kagglesdk<1.0,>=0.1.14->kagglehub) (7.34.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.11/site-packages (from requests->kagglehub) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.11/site-packages (from requests->kagglehub) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.11/site-packages (from requests->kagglehub) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.11/site-packages (from requests->kagglehub) (2024.7.4)

/opt/conda/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Path to dataset files: /home/jovyan/.cache/kagglehub/datasets/pranabr0y/celebdf-v2image-dataset/versions/1

In [4]:
# CELL 1 — Imports

import io
import os
import csv
import copy
import json
import math
import time
import random
import warnings
import numpy as np
from pathlib import Path
from dataclasses import dataclass, asdict
from typing import Any, Optional

warnings.filterwarnings('ignore')

from PIL import Image
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import (
    Dataset, DataLoader, WeightedRandomSampler, TensorDataset
)
import torchvision.transforms as T
from torch.cuda.amp import GradScaler, autocast

from sklearn.metrics import (
    roc_auc_score, precision_score, recall_score,
    f1_score, accuracy_score,
)

print("✓ All imports OK")
print(f"  PyTorch  : {torch.__version__}")
print(f"  CUDA     : {torch.cuda.is_available()}")



from tqdm.auto import tqdm

✓ All imports OK
  PyTorch  : 2.11.0+cu130
  CUDA     : True

In [5]:
# CELL 2 — Configuration  ← EDIT THIS

CONFIG = dict(
    # ── Data ──────────────────────────────────────────────────────────────────
    data_dir      = "/home/jovyan/.cache/kagglehub/datasets/pranabr0y/celebdf-v2image-dataset/versions/1/Celeb_V2",   # Celeb-DF root. Prefer Celeb_V2 with Train/ Val/ Test
    csv_path      = None,                  # optional CSV manifest (path,label)
    resolutions   = [128, 224, 256, 384], # every split is expanded across all listed resolutions
    train_res     = 224,                   # kept for smoke tests / naming, not single-res training anymore
    max_per_class = None,                  # int to cap dataset size per class before splitting, None = all
    split_ratios  = (0.80, 0.10, 0.10),   # used only when Train/Val/Test folders are not present

    # ── Training ──────────────────────────────────────────────────────────────
    epochs          = 30,
    batch_size      = 32,
    lr              = 1e-3,
    weight_decay    = 1e-4,
    label_smoothing = 0.05,
    warmup_epochs   = 3,
    patience        = 8,

    # ── Model ─────────────────────────────────────────────────────────────────
    base_ch   = 32,

    # ── System ────────────────────────────────────────────────────────────────
    num_workers = 4,
    seed        = 42,
    save_dir    = "./mad_corn_results",
    device      = "auto",

    # ── Dev mode ──────────────────────────────────────────────────────────────
    smoke_test  = False,
)

In [6]:
# CELL 3 — Utility helpers

def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

def auto_device(requested: str) -> torch.device:
    if requested != "auto":
        return torch.device(requested)
    if torch.cuda.is_available():
        return torch.device("cuda")
    if hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")

set_seed(CONFIG["seed"])
DEVICE = auto_device(CONFIG["device"])
os.makedirs(CONFIG["save_dir"], exist_ok=True)
print(f"✓ Device  : {DEVICE}")
print(f"  Save dir: {CONFIG['save_dir']}")

✓ Device  : cuda
  Save dir: ./mad_corn_results

In [7]:
# CELL 4 — Result dataclasses

@dataclass
class EpochResult:
    epoch:          int
    train_loss:     float
    train_acc:      float
    train_auc:      float
    val_acc:        float
    val_auc:        float
    precision:      float
    recall:         float
    f1:             float
    uncertain_rate: float
    lr:             float

@dataclass
class TestResult:
    model_name:     str
    accuracy:       float
    auc:            float
    precision:      float
    recall:         float
    f1:             float
    uncertain_rate: float

@dataclass
class ResolutionResult:
    resolution:  int
    accuracy:    float
    auc:         float
    fast_pct:    float   # % batches with <5 ms per-image latency
    medium_pct:  float   # 5–20 ms
    full_pct:    float   # >20 ms

@dataclass
class InferenceResult:
    mode:              str
    time_per_image_ms: float
    fps:               float

@dataclass
class TrainingTimeResult:
    model_type: str
    minutes:    float
    hours:      float

print("✓ Dataclasses defined")

✓ Dataclasses defined

In [8]:
# CELL 5 — Model: MaD-CoRN Architecture

# ── Utility Blocks ──────────────────────────────────────────────────────────────

class ConvBNReLU(nn.Module):
    """Standard Conv → BN → ReLU6 block."""
    def __init__(self, in_ch, out_ch, kernel=3, stride=1, padding=1, groups=1):
        super().__init__()
        self.block = nn.Sequential(
            nn.Conv2d(in_ch, out_ch, kernel, stride, padding, groups=groups, bias=False),
            nn.BatchNorm2d(out_ch),
            nn.ReLU6(inplace=True),
        )
    def forward(self, x):
        return self.block(x)


class DepthwiseSeparable(nn.Module):
    """Depthwise Separable Convolution — core efficiency component."""
    def __init__(self, in_ch, out_ch, stride=1):
        super().__init__()
        self.dw = ConvBNReLU(in_ch, in_ch, kernel=3, stride=stride, padding=1, groups=in_ch)
        self.pw = ConvBNReLU(in_ch, out_ch, kernel=1, padding=0)
    def forward(self, x):
        return self.pw(self.dw(x))


# ── Convolutional Reservoir (CoRN) ──────────────────────────────────────────────

class ConvReservoir(nn.Module):
    """
    Echo State Network-inspired convolutional reservoir.
    - Fixed (frozen) random reservoir weights W_res
    - Trainable input projection + output readout
    - Reservoir update: h_res = tanh(W_res * h)
    - Combined via residual: h + h_res
    """
    def __init__(self, in_ch, reservoir_ch=64, spectral_radius=0.9):
        super().__init__()
        self.reservoir_ch = reservoir_ch

        # Trainable input projection
        self.input_proj = nn.Conv2d(in_ch, reservoir_ch, kernel_size=1, bias=False)
        self.input_bn   = nn.BatchNorm2d(reservoir_ch)

        # Fixed reservoir (registered as buffer → not a parameter → not trained)
        W = torch.randn(reservoir_ch, reservoir_ch, 3, 3)
        W = W / (W.abs().max() + 1e-8) * spectral_radius
        self.register_buffer("W_res", W)

        # Trainable readout
        self.readout = nn.Sequential(
            nn.Conv2d(reservoir_ch, reservoir_ch, kernel_size=1, bias=False),
            nn.BatchNorm2d(reservoir_ch),
            nn.ReLU6(inplace=True),
        )

    def forward(self, x):
        h     = F.relu(self.input_bn(self.input_proj(x)))
        h_res = torch.tanh(F.conv2d(h, self.W_res, padding=1))  # reservoir echo
        return self.readout(h + h_res)                            # residual combine


# ── Multi-scale Attention (MaD) ─────────────────────────────────────────────────

class ChannelAttention(nn.Module):
    """Squeeze-and-Excitation channel attention."""
    def __init__(self, channels, reduction=4):
        super().__init__()
        mid = max(channels // reduction, 8)
        self.gate = nn.Sequential(
            nn.AdaptiveAvgPool2d(1),
            nn.Flatten(),
            nn.Linear(channels, mid),
            nn.ReLU(inplace=True),
            nn.Linear(mid, channels),
            nn.Sigmoid(),
        )
    def forward(self, x):
        w = self.gate(x).view(x.size(0), x.size(1), 1, 1)
        return x * w


class SpatialAttention(nn.Module):
    """CBAM-style spatial attention."""
    def __init__(self):
        super().__init__()
        self.conv    = nn.Conv2d(2, 1, kernel_size=7, padding=3, bias=False)
        self.sigmoid = nn.Sigmoid()
    def forward(self, x):
        avg = x.mean(dim=1, keepdim=True)
        mx, _ = x.max(dim=1, keepdim=True)
        return x * self.sigmoid(self.conv(torch.cat([avg, mx], dim=1)))


class MultiScaleAttentionBlock(nn.Module):
    """
    MaD block: 3 parallel branches at different depths → fuse → dual attention.
    Branch depths 1/2/3 give multi-scale receptive fields for artefact capture.
    """
    def __init__(self, in_ch, out_ch):
        super().__init__()
        b_ch = out_ch // 3

        self.branch1 = DepthwiseSeparable(in_ch, b_ch)
        self.branch2 = nn.Sequential(
            DepthwiseSeparable(in_ch, b_ch),
            DepthwiseSeparable(b_ch,  b_ch),
        )
        self.branch3 = nn.Sequential(
            DepthwiseSeparable(in_ch, b_ch),
            DepthwiseSeparable(b_ch,  b_ch),
            DepthwiseSeparable(b_ch,  b_ch),
        )
        self.fuse = ConvBNReLU(b_ch * 3, out_ch, kernel=1, padding=0)
        self.ca   = ChannelAttention(out_ch)
        self.sa   = SpatialAttention()

    def forward(self, x):
        f = self.fuse(torch.cat([self.branch1(x), self.branch2(x), self.branch3(x)], dim=1))
        return self.sa(self.ca(f))


# ── Full MaD-CoRN Model ─────────────────────────────────────────────────────────

class MaDCoRN(nn.Module):
    """
    MaD-CoRN: Multi-scale Attention Detection + Convolutional Reservoir Network.

    Stages: Stem → [MaD×2 + CoRN + Downsample] × 3 → GlobalAvgPool → Classifier
    ~3–5 M parameters (base_ch=32), resolution-agnostic (tested 128–384).
    """
    def __init__(self, in_ch=3, num_classes=2, base_ch=32):
        super().__init__()
        c = base_ch

        # Stem
        self.stem = nn.Sequential(
            ConvBNReLU(in_ch, c,     kernel=3, stride=2, padding=1),
            ConvBNReLU(c,    c * 2,  kernel=3, stride=1, padding=1),
        )
        # Stage 1
        self.mad1  = MultiScaleAttentionBlock(c * 2,  c * 4)
        self.mad2  = MultiScaleAttentionBlock(c * 4,  c * 4)
        self.res1  = ConvReservoir(c * 4, c * 4)
        self.down1 = nn.Conv2d(c * 4, c * 4, kernel_size=3, stride=2, padding=1, bias=False)
        # Stage 2
        self.mad3  = MultiScaleAttentionBlock(c * 4,  c * 8)
        self.mad4  = MultiScaleAttentionBlock(c * 8,  c * 8)
        self.res2  = ConvReservoir(c * 8, c * 8)
        self.down2 = nn.Conv2d(c * 8, c * 8, kernel_size=3, stride=2, padding=1, bias=False)
        # Stage 3
        self.mad5  = MultiScaleAttentionBlock(c * 8,  c * 16)
        self.mad6  = MultiScaleAttentionBlock(c * 16, c * 16)
        self.res3  = ConvReservoir(c * 16, c * 16)
        # Classifier
        self.pool  = nn.AdaptiveAvgPool2d(1)
        self.head  = nn.Sequential(
            nn.Flatten(),
            nn.Linear(c * 16, 256),
            nn.ReLU(inplace=True),
            nn.Dropout(0.4),
            nn.Linear(256, num_classes),
        )
        self._init_weights()

    def _init_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, mode="fan_out", nonlinearity="relu")
            elif isinstance(m, nn.BatchNorm2d):
                nn.init.ones_(m.weight); nn.init.zeros_(m.bias)
            elif isinstance(m, nn.Linear):
                nn.init.trunc_normal_(m.weight, std=0.02)
                if m.bias is not None: nn.init.zeros_(m.bias)

    def forward(self, x):
        x = self.stem(x)
        x = self.down1(self.res1(self.mad2(self.mad1(x))))
        x = self.down2(self.res2(self.mad4(self.mad3(x))))
        x = self.res3(self.mad6(self.mad5(x)))
        return self.head(self.pool(x))

    def count_parameters(self):
        total  = sum(p.numel() for p in self.parameters())
        frozen = sum(p.numel() for p in self.parameters() if not p.requires_grad)
        return total, frozen


def freeze_reservoir_weights(model: MaDCoRN):
    """Buffers are already non-trainable, but also guard any named params."""
    for name, param in model.named_parameters():
        if "W_res" in name:
            param.requires_grad_(False)


# Quick sanity check
_m = MaDCoRN(base_ch=CONFIG["base_ch"])
freeze_reservoir_weights(_m)
_total, _frozen = _m.count_parameters()
print(f"✓ MaD-CoRN instantiated")
print(f"  Total params : {_total:,}")
print(f"  Frozen params: {_frozen:,}")
for _r in CONFIG["resolutions"]:
    _x = torch.randn(1, 3, _r, _r)
    _o = _m(_x)
    print(f"  {_r}×{_r} → {_o.shape}  ✓")
del _m, _x, _o

✓ MaD-CoRN instantiated
  Total params : 3,428,062
  Frozen params: 0
  128×128 → torch.Size([1, 2])  ✓
  224×224 → torch.Size([1, 2])  ✓
  256×256 → torch.Size([1, 2])  ✓
  384×384 → torch.Size([1, 2])  ✓

In [9]:
# CELL 6 — Dataset & DataLoaders

# ── Augmentation helpers ────────────────────────────────────────────────────────

class AddGaussianNoise:
    def __init__(self, std=0.01):
        self.std = std
    def __call__(self, t: torch.Tensor) -> torch.Tensor:
        return t + torch.randn_like(t) * self.std


class JPEGCompression:
    """Simulate JPEG compression artefacts (train-time aug)."""
    def __init__(self, quality_range=(60, 95)):
        self.lo, self.hi = quality_range
    def __call__(self, img: Image.Image) -> Image.Image:
        q   = random.randint(self.lo, self.hi)
        buf = io.BytesIO()
        img.save(buf, format="JPEG", quality=q)
        buf.seek(0)
        return Image.open(buf).copy()


# ── Transform factory ───────────────────────────────────────────────────────────

_MEAN = [0.485, 0.456, 0.406]
_STD  = [0.229, 0.224, 0.225]

def build_transforms(resolution: int, split: str = "train") -> T.Compose:
    if split == "train":
        return T.Compose([
            T.Resize((resolution + 16, resolution + 16)),
            T.RandomCrop(resolution),
            T.RandomHorizontalFlip(p=0.5),
            T.RandomVerticalFlip(p=0.1),
            T.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.1, hue=0.05),
            T.RandomGrayscale(p=0.05),
            T.RandomApply([T.GaussianBlur(kernel_size=3)], p=0.15),
            JPEGCompression(quality_range=(60, 95)),
            T.ToTensor(),
            AddGaussianNoise(std=0.01),
            T.Normalize(_MEAN, _STD),
        ])
    return T.Compose([
        T.Resize((resolution, resolution)),
        T.ToTensor(),
        T.Normalize(_MEAN, _STD),
    ])


# ── Celeb-DF path helpers ──────────────────────────────────────────────────────

IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}
REAL_DIRS  = {"real", "celeb-real", "youtube-real", "original"}
FAKE_DIRS  = {"fake", "celeb-synthesis", "synthesis", "manipulated"}

def _detect_label(dirname: str) -> Optional[int]:
    n = dirname.lower()
    if any(n == d or n.startswith(d) for d in REAL_DIRS):
        return 0
    if any(n == d or n.startswith(d) for d in FAKE_DIRS):
        return 1
    return None

def gather_labeled_paths(root: str) -> list[tuple[str, int]]:
    root = Path(root)
    samples = []
    for sub in root.iterdir():
        if not sub.is_dir():
            continue
        label = _detect_label(sub.name)
        if label is None:
            continue
        for p in sub.rglob("*"):
            if p.suffix.lower() in IMAGE_EXTS:
                samples.append((str(p), label))
    return sorted(samples)

def load_csv_samples(csv_path: str) -> list[tuple[str, int]]:
    samples = []
    with open(csv_path, newline="") as f:
        for row in csv.DictReader(f):
            p = row.get("path") or row.get("file") or list(row.values())[0]
            l = int(row.get("label", row.get("Label", 0)))
            if Path(p).suffix.lower() in IMAGE_EXTS and os.path.exists(p):
                samples.append((p, l))
    return samples

def cap_per_class(samples: list[tuple[str, int]], max_per_class: Optional[int], seed: int) -> list[tuple[str, int]]:
    if not max_per_class:
        return samples
    rng = random.Random(seed)
    real = [(p, l) for p, l in samples if l == 0]
    fake = [(p, l) for p, l in samples if l == 1]
    real = rng.sample(real, min(len(real), max_per_class))
    fake = rng.sample(fake, min(len(fake), max_per_class))
    out = real + fake
    rng.shuffle(out)
    return out

def split_samples(samples: list[tuple[str, int]], ratios=(0.8, 0.1, 0.1), seed: int = 42):
    tr_ratio, val_ratio, te_ratio = ratios
    if not math.isclose(tr_ratio + val_ratio + te_ratio, 1.0, rel_tol=1e-6, abs_tol=1e-6):
        raise ValueError(f"split_ratios must sum to 1.0, got {ratios}")

    rng = random.Random(seed)
    by_label = {0: [], 1: []}
    for item in samples:
        by_label[item[1]].append(item)

    split_map = {"train": [], "val": [], "test": []}
    for label, items in by_label.items():
        rng.shuffle(items)
        n = len(items)
        n_tr = int(n * tr_ratio)
        n_val = int(n * val_ratio)
        n_te = n - n_tr - n_val
        split_map["train"].extend(items[:n_tr])
        split_map["val"].extend(items[n_tr:n_tr+n_val])
        split_map["test"].extend(items[n_tr+n_val:])

    for k in split_map:
        rng.shuffle(split_map[k])
    return split_map

def load_celebdf_splits(cfg: dict) -> dict[str, list[tuple[str, int]]]:
    data_dir = Path(cfg["data_dir"])
    seed = cfg["seed"]
    max_per_class = cfg["max_per_class"]

    if cfg.get("csv_path"):
        base_samples = cap_per_class(load_csv_samples(cfg["csv_path"]), max_per_class, seed)
        return split_samples(base_samples, ratios=cfg["split_ratios"], seed=seed)

    split_dirs = {name: data_dir / name for name in ["Train", "Val", "Test"]}
    has_explicit_splits = all(p.exists() and p.is_dir() for p in split_dirs.values())

    if has_explicit_splits:
        split_map = {
            "train": cap_per_class(gather_labeled_paths(split_dirs["Train"]), max_per_class, seed),
            "val":   cap_per_class(gather_labeled_paths(split_dirs["Val"]),   max_per_class, seed),
            "test":  cap_per_class(gather_labeled_paths(split_dirs["Test"]),  max_per_class, seed),
        }
        total = sum(len(v) for v in split_map.values())
        print("Detected explicit Celeb-DF split folders: Train / Val / Test")
        print(f"Requested split_ratios={cfg['split_ratios']} ignored because folder splits already exist.")
        print(f"Using folder totals: train={len(split_map['train']):,}  val={len(split_map['val']):,}  test={len(split_map['test']):,}  total={total:,}")
        return split_map

    base_samples = cap_per_class(gather_labeled_paths(data_dir), max_per_class, seed)
    split_map = split_samples(base_samples, ratios=cfg["split_ratios"], seed=seed)
    print(f"No Train/Val/Test folders found. Built random split with ratios={cfg['split_ratios']}.")
    return split_map


# ── Datasets ───────────────────────────────────────────────────────────────────

class MultiResolutionCelebDFDataset(Dataset):
    """
    Expands every image across all requested resolutions.

    Each item is:
      (image_tensor_at_requested_resolution, label)

    Metadata for each expanded sample is kept in self.expanded_samples as:
      (path, label, resolution)
    """
    def __init__(
        self,
        base_samples: list[tuple[str, int]],
        resolutions: list[int],
        split: str = "train",
    ):
        self.base_samples = list(base_samples)
        self.resolutions = list(resolutions)
        self.split = split
        self.transforms = {res: build_transforms(res, split) for res in self.resolutions}
        self.expanded_samples = [
            (path, label, res)
            for path, label in self.base_samples
            for res in self.resolutions
        ]

        n_r = sum(1 for _, l in self.base_samples if l == 0)
        n_f = len(self.base_samples) - n_r
        print(
            f"  [{split:>5}] base: real={n_r:,}  fake={n_f:,}  total={len(self.base_samples):,} | "
            f"expanded across {len(self.resolutions)} resolutions → {len(self.expanded_samples):,}"
        )

    def __len__(self):
        return len(self.expanded_samples)

    def __getitem__(self, idx):
        path, label, resolution = self.expanded_samples[idx]
        try:
            img = Image.open(path).convert("RGB")
        except Exception:
            img = Image.fromarray(np.zeros((resolution, resolution, 3), dtype=np.uint8))
        return self.transforms[resolution](img), label

    def subset_for_resolution(self, resolution: int):
        return SingleResolutionView(self, resolution)

    @property
    def base_count(self) -> int:
        return len(self.base_samples)

    @property
    def expanded_count(self) -> int:
        return len(self.expanded_samples)


class SingleResolutionView(Dataset):
    def __init__(self, parent: MultiResolutionCelebDFDataset, resolution: int):
        self.parent = parent
        self.resolution = resolution
        self.indices = [i for i, (_, _, r) in enumerate(parent.expanded_samples) if r == resolution]

    def __len__(self):
        return len(self.indices)

    def __getitem__(self, idx):
        return self.parent[self.indices[idx]]


class ResolutionAwareBatchSampler(torch.utils.data.Sampler[list[int]]):
    """
    Keeps batches homogeneous in spatial size so tensors can stack cleanly.
    """
    def __init__(self, dataset: MultiResolutionCelebDFDataset, batch_size: int, shuffle: bool, drop_last: bool, seed: int = 42):
        self.dataset = dataset
        self.batch_size = batch_size
        self.shuffle = shuffle
        self.drop_last = drop_last
        self.seed = seed
        self.epoch = 0

        self.indices_by_res = {}
        for idx, (_, _, res) in enumerate(dataset.expanded_samples):
            self.indices_by_res.setdefault(res, []).append(idx)

    def __iter__(self):
        rng = random.Random(self.seed + self.epoch)
        batches = []

        for res, indices in self.indices_by_res.items():
            idxs = list(indices)
            if self.shuffle:
                rng.shuffle(idxs)

            limit = len(idxs) if not self.drop_last else (len(idxs) // self.batch_size) * self.batch_size
            idxs = idxs[:limit]

            for start in range(0, len(idxs), self.batch_size):
                batch = idxs[start:start+self.batch_size]
                if len(batch) == self.batch_size or (not self.drop_last and len(batch) > 0):
                    batches.append(batch)

        if self.shuffle:
            rng.shuffle(batches)
        return iter(batches)

    def __len__(self):
        total = 0
        for indices in self.indices_by_res.values():
            if self.drop_last:
                total += len(indices) // self.batch_size
            else:
                total += math.ceil(len(indices) / self.batch_size)
        return total

    def set_epoch(self, epoch: int):
        self.epoch = epoch


# ── DataLoader factory ──────────────────────────────────────────────────────────

def _make_loader(dataset, batch_size: int, num_workers: int, shuffle: bool, drop_last: bool, seed: int):
    batch_sampler = ResolutionAwareBatchSampler(
        dataset=dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,
        seed=seed,
    )
    loader = DataLoader(
        dataset,
        batch_sampler=batch_sampler,
        num_workers=num_workers,
        pin_memory=(DEVICE.type == "cuda"),
        persistent_workers=(num_workers > 0),
    )
    loader.resolution_batch_sampler = batch_sampler
    return loader

def print_dataset_summary(split_datasets: dict[str, MultiResolutionCelebDFDataset], resolutions: list[int]):
    print("\nDataset size summary")
    for name in ["train", "val", "test"]:
        ds = split_datasets[name]
        print(
            f"  {name.title():<5} | base={ds.base_count:,}  "
            f"expanded={ds.expanded_count:,}  "
            f"resolutions={resolutions}"
        )

def make_dataloaders(cfg: dict) -> dict[str, Any]:
    split_map = load_celebdf_splits(cfg)
    resolutions = list(cfg["resolutions"])
    batch_size = cfg["batch_size"]
    num_workers = cfg["num_workers"]
    seed = cfg["seed"]

    split_datasets = {
        name: MultiResolutionCelebDFDataset(samples, resolutions, split=name)
        for name, samples in split_map.items()
    }
    print_dataset_summary(split_datasets, resolutions)

    loaders = {
        "train": _make_loader(split_datasets["train"], batch_size, num_workers, shuffle=True,  drop_last=True,  seed=seed),
        "val":   _make_loader(split_datasets["val"],   batch_size, num_workers, shuffle=False, drop_last=False, seed=seed),
        "test":  _make_loader(split_datasets["test"],  batch_size, num_workers, shuffle=False, drop_last=False, seed=seed),
    }
    return {
        "loaders": loaders,
        "datasets": split_datasets,
        "base_splits": split_map,
    }

def make_smoke_loader(resolution: int, n: int = 200, bs: int = 8) -> DataLoader:
    imgs   = torch.randn(n, 3, resolution, resolution)
    labels = torch.randint(0, 2, (n,))
    return DataLoader(TensorDataset(imgs, labels), batch_size=bs, shuffle=True)


print("✓ Dataset classes defined")

✓ Dataset classes defined

In [ ]:
# CELL 7 — Training engine

def compute_uncertain_rate(probs: np.ndarray, threshold: float = 0.15) -> float:
    """% of samples where |P(fake) - 0.5| < threshold → 'uncertain'."""
    fake_p = probs[:, 1] if probs.ndim == 2 else probs
    return float(np.mean(np.abs(fake_p - 0.5) < threshold) * 100)


def run_epoch(
    model, loader, criterion, optimizer, device,
    scaler=None, is_train: bool = True, desc: Optional[str] = None,
) -> dict[str, Any]:
    model.train(is_train)
    total_loss = 0.0
    seen = 0
    all_probs, all_preds, all_labels = [], [], []

    pbar = tqdm(
        loader,
        total=len(loader) if hasattr(loader, "__len__") else None,
        desc=desc or ("Train" if is_train else "Eval"),
        leave=False,
        dynamic_ncols=True,
        mininterval=0.5,
    )

    with torch.set_grad_enabled(is_train):
        for imgs, labels in pbar:
            imgs   = imgs.to(device, non_blocking=True)
            labels = labels.to(device, non_blocking=True)

            if is_train and scaler:
                with autocast():
                    logits = model(imgs)
                    loss   = criterion(logits, labels)
                scaler.scale(loss).backward()
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                scaler.step(optimizer)
                scaler.update()
                optimizer.zero_grad(set_to_none=True)
            else:
                logits = model(imgs)
                loss   = criterion(logits, labels)
                if is_train:
                    loss.backward()
                    torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                    optimizer.step()
                    optimizer.zero_grad(set_to_none=True)

            probs = torch.softmax(logits.float(), dim=1).detach().cpu().numpy()
            all_probs.append(probs)
            all_preds.append(probs.argmax(axis=1))
            all_labels.append(labels.cpu().numpy())
            batch_n = len(labels)
            total_loss += loss.item() * batch_n
            seen += batch_n
            pbar.set_postfix(loss=f"{loss.item():.4f}", samples=f"{seen:,}")

    all_probs  = np.vstack(all_probs)
    all_preds  = np.concatenate(all_preds)
    all_labels = np.concatenate(all_labels)
    n          = len(all_labels)

    acc  = accuracy_score(all_labels, all_preds)
    try:
        auc = roc_auc_score(all_labels, all_probs[:, 1])
    except ValueError:
        auc = 0.5
    prec = precision_score(all_labels, all_preds, zero_division=0)
    rec  = recall_score(all_labels, all_preds, zero_division=0)
    f1   = f1_score(all_labels, all_preds, zero_division=0)
    unc  = compute_uncertain_rate(all_probs)

    return dict(loss=total_loss/n, acc=acc, auc=auc,
                precision=prec, recall=rec, f1=f1,
                uncertain_rate=unc, probs=all_probs,
                preds=all_preds, labels=all_labels)


class Trainer:
    """
    Full training loop:
      - AdamW optimiser
      - Cosine LR schedule with linear warmup
      - Mixed-precision AMP (CUDA only)
      - Label smoothing
      - Best-model checkpointing (by Val AUC)
      - Early stopping
    """
    def __init__(self, model, train_loader, val_loader, test_loader,
                 device, cfg: dict, ckpt_path: str):
        self.model        = model.to(device)
        self.train_loader = train_loader
        self.val_loader   = val_loader
        self.test_loader  = test_loader
        self.device       = device
        self.epochs       = cfg["epochs"]
        self.patience     = cfg["patience"]
        self.ckpt_path    = ckpt_path
        self.model_name   = f"MaD-CoRN-{cfg['train_res']}"

        self.criterion = nn.CrossEntropyLoss(label_smoothing=cfg["label_smoothing"])
        self.optimizer = optim.AdamW(
            [p for p in model.parameters() if p.requires_grad],
            lr=cfg["lr"], weight_decay=cfg["weight_decay"],
        )
        total_steps  = self.epochs * len(train_loader)
        warmup_steps = cfg["warmup_epochs"] * len(train_loader)

        def lr_lambda(step):
            if step < warmup_steps:
                return step / max(1, warmup_steps)
            prog = (step - warmup_steps) / max(1, total_steps - warmup_steps)
            return 0.5 * (1.0 + math.cos(math.pi * prog))

        self.scheduler = optim.lr_scheduler.LambdaLR(self.optimizer, lr_lambda)
        self.scaler    = GradScaler() if device.type == "cuda" else None
        self.epoch_results: list[EpochResult] = []

    def train(self) -> tuple[list[EpochResult], float]:
        best_auc   = 0.0
        no_improve = 0
        t0         = time.time()

        for epoch in range(1, self.epochs + 1):
            # if hasattr(self.train_loader, "resolution_batch_sampler"):
            #     self.train_loader.resolution_batch_sampler.set_epoch(epoch)
            tr = run_epoch(self.model, self.train_loader, self.criterion,
                           self.optimizer, self.device, self.scaler,
                           is_train=True, desc=f"Epoch {epoch}/{self.epochs} [train]")
            self.scheduler.step()

            with torch.no_grad():
                vl = run_epoch(self.model, self.val_loader, self.criterion,
                               None, self.device, None,
                               is_train=False, desc=f"Epoch {epoch}/{self.epochs} [val]")

            lr_now = self.optimizer.param_groups[0]["lr"]
            er = EpochResult(
                epoch=epoch,
                train_loss=tr["loss"],       train_acc=tr["acc"],  train_auc=tr["auc"],
                val_acc=vl["acc"],           val_auc=vl["auc"],
                precision=vl["precision"],   recall=vl["recall"],  f1=vl["f1"],
                uncertain_rate=vl["uncertain_rate"], lr=lr_now,
            )
            self.epoch_results.append(er)

            print(
                f"Epoch {epoch:3d}/{self.epochs} | "
                f"Loss {er.train_loss:.4f} | "
                f"Tr Acc {er.train_acc:.4f} AUC {er.train_auc:.4f} | "
                f"Val Acc {er.val_acc:.4f} AUC {er.val_auc:.4f} | "
                f"P {er.precision:.4f} R {er.recall:.4f} F1 {er.f1:.4f} | "
                f"Unc {er.uncertain_rate:.1f}% | LR {lr_now:.2e}"
            )

            if vl["auc"] > best_auc:
                best_auc = vl["auc"]
                no_improve = 0
                torch.save(self.model.state_dict(), self.ckpt_path)
                print(f"  ✓ Checkpoint saved (Val AUC = {best_auc:.4f})")
            else:
                no_improve += 1
                if no_improve >= self.patience:
                    print(f"  ⏹ Early stopping at epoch {epoch}")
                    break

        return self.epoch_results, (time.time() - t0) / 60

    def evaluate(self, loader=None, load_best: bool = True) -> TestResult:
        if load_best and os.path.exists(self.ckpt_path):
            self.model.load_state_dict(torch.load(self.ckpt_path, map_location=self.device))
        loader = loader or self.test_loader
        with torch.no_grad():
            r = run_epoch(self.model, loader, self.criterion,
                          None, self.device, None,
                          is_train=False, desc="Test evaluation")
        return TestResult(
            model_name=self.model_name,
            accuracy=r["acc"], auc=r["auc"],
            precision=r["precision"], recall=r["recall"],
            f1=r["f1"], uncertain_rate=r["uncertain_rate"],
        )


print("✓ Trainer defined")

In [11]:
# CELL 8 — Inference timing & resolution evaluation

@torch.no_grad()
def measure_inference(
    model, resolution: int, device,
    batch_size: int = 32, n_warmup: int = 20, n_runs: int = 200,
) -> list[InferenceResult]:
    """Benchmark single-image and batch inference speed."""
    model.eval()
    results = []
    for bs, label in [(1, "Single"), (batch_size, f"Batch={batch_size}")]:
        dummy = torch.randn(bs, 3, resolution, resolution, device=device)
        for _ in range(n_warmup):
            model(dummy)
        if device.type == "cuda": torch.cuda.synchronize()

        t0 = time.perf_counter()
        for _ in range(n_runs):
            model(dummy)
        if device.type == "cuda": torch.cuda.synchronize()
        elapsed = time.perf_counter() - t0

        total = bs * n_runs
        results.append(InferenceResult(
            mode=f"Res={resolution} {label}",
            time_per_image_ms=elapsed / total * 1000,
            fps=total / elapsed,
        ))
    return results


@torch.no_grad()
def evaluate_by_resolution(
    model, loader, device, resolution: int,
) -> ResolutionResult:
    """Evaluate accuracy + latency buckets (Fast <5ms, Medium 5–20ms, Full >20ms)."""
    model.eval()
    all_probs, all_labels = [], []
    buckets = {"fast": 0, "medium": 0, "full": 0}
    total   = 0

    pbar = tqdm(
        loader,
        total=len(loader) if hasattr(loader, "__len__") else None,
        desc=f"Resolution {resolution} eval",
        leave=False,
        dynamic_ncols=True,
        mininterval=0.5,
    )

    for imgs, labels in pbar:
        imgs = imgs.to(device, non_blocking=True)
        bs   = imgs.size(0)

        t0     = time.perf_counter()
        logits = model(imgs)
        if device.type == "cuda": torch.cuda.synchronize()
        ms = (time.perf_counter() - t0) / bs * 1000

        probs = torch.softmax(logits.float(), dim=1).cpu().numpy()
        all_probs.append(probs)
        all_labels.append(labels.numpy())

        if ms < 5:    buckets["fast"]   += bs
        elif ms < 20: buckets["medium"] += bs
        else:         buckets["full"]   += bs
        total += bs
        pbar.set_postfix(samples=f"{total:,}", ms_per_img=f"{ms:.3f}")

    all_probs  = np.vstack(all_probs)
    all_labels = np.concatenate(all_labels)
    preds      = all_probs.argmax(axis=1)

    acc = accuracy_score(all_labels, preds)
    try: auc = roc_auc_score(all_labels, all_probs[:, 1])
    except ValueError: auc = 0.5

    return ResolutionResult(
        resolution=resolution, accuracy=acc, auc=auc,
        fast_pct  =buckets["fast"]   / max(total, 1) * 100,
        medium_pct=buckets["medium"] / max(total, 1) * 100,
        full_pct  =buckets["full"]   / max(total, 1) * 100,
    )


print("✓ Inference / resolution evaluation functions defined")

✓ Inference / resolution evaluation functions defined

In [12]:
# CELL 9 — Results reporting (tables + file saving)

def _table(headers: list, rows: list, title: str = "") -> str:
    col_w = [max(len(str(h)), max((len(str(r[i])) for r in rows), default=0))
             for i, h in enumerate(headers)]
    sep  = "+" + "+".join("-" * (w + 2) for w in col_w) + "+"
    hdr  = "|" + "|".join(f" {h:<{w}} " for h, w in zip(headers, col_w)) + "|"
    body = ["|" + "|".join(f" {str(v):<{w}} " for v, w in zip(r, col_w)) + "|"
            for r in rows]
    out  = [sep, hdr, sep] + body + [sep]
    if title:
        out.insert(0, title.center(len(sep)))
        out.insert(1, "")
    return "\n".join(out)


def print_training_table(ers: list[EpochResult]) -> str:
    h = ["Epoch","Train Loss","Train Acc","Train AUC",
         "Val Acc","Val AUC","Precision","Recall","F1","Uncertain Rate (%)"]
    rows = [[e.epoch, f"{e.train_loss:.4f}", f"{e.train_acc*100:.2f}%",
             f"{e.train_auc:.4f}", f"{e.val_acc*100:.2f}%", f"{e.val_auc:.4f}",
             f"{e.precision:.4f}", f"{e.recall:.4f}", f"{e.f1:.4f}",
             f"{e.uncertain_rate:.2f}"] for e in ers]
    t = _table(h, rows, "Training Periods Results")
    print(t); return t


def print_test_table(trs: list[TestResult]) -> str:
    h = ["Model","Accuracy","AUC","Precision","Recall","F1","Uncertain Rate (%)"]
    rows = [[r.model_name, f"{r.accuracy*100:.2f}%", f"{r.auc:.4f}",
             f"{r.precision:.4f}", f"{r.recall:.4f}", f"{r.f1:.4f}",
             f"{r.uncertain_rate:.2f}"] for r in trs]
    t = _table(h, rows, "Test Results")
    print(t); return t


def print_resolution_table(rrs: list[ResolutionResult]) -> str:
    h = ["Resolution","Accuracy","AUC","Fast (%)","Medium (%)","Full (%)"]
    rows = [[f"{r.resolution}×{r.resolution}", f"{r.accuracy*100:.2f}%",
             f"{r.auc:.4f}", f"{r.fast_pct:.1f}", f"{r.medium_pct:.1f}",
             f"{r.full_pct:.1f}"] for r in rrs]
    t = _table(h, rows, "Accuracy Based on Resolution")
    print(t); return t


def print_inference_table(irs: list[InferenceResult]) -> str:
    h = ["Mode","Time per Image (ms)","FPS"]
    rows = [[r.mode, f"{r.time_per_image_ms:.3f}", f"{r.fps:.1f}"] for r in irs]
    t = _table(h, rows, "Inference Time")
    print(t); return t


def print_training_time_table(tts: list[TrainingTimeResult]) -> str:
    h = ["Model Type","min","hrs"]
    rows = [[r.model_type, f"{r.minutes:.1f}", f"{r.hours:.2f}"] for r in tts]
    t = _table(h, rows, "Training Time")
    print(t); return t


def save_all_results(epoch_results, test_results, res_results, inf_results,
                     tt_results, save_dir: str):
    os.makedirs(save_dir, exist_ok=True)
    data = dict(
        epoch_results=[asdict(e) for e in epoch_results],
        test_results =[asdict(t) for t in test_results],
        res_results  =[asdict(r) for r in res_results],
        inference    =[asdict(i) for i in inf_results],
        training_time=[asdict(t) for t in tt_results],
    )
    # JSON
    with open(f"{save_dir}/mad_corn_results.json", "w") as f:
        json.dump(data, f, indent=2)
    # CSVs
    for name, lst in data.items():
        if not lst: continue
        with open(f"{save_dir}/mad_corn_{name}.csv", "w", newline="") as f:
            w = csv.DictWriter(f, fieldnames=lst[0].keys())
            w.writeheader(); w.writerows(lst)
    print(f"\n✓ Results saved to: {save_dir}/")


def print_full_report(epoch_results, test_results, res_results,
                      inf_results, tt_results, save_dir):
    div = "=" * 100
    print(f"\n{div}")
    print(" MaD-CoRN EXPERIMENT RESULTS ".center(100, "="))
    print(f"{div}\n")
    print("\n[1] TRAINING PERIODS RESULTS")
    print_training_table(epoch_results)
    print("\n[2] TEST RESULTS")
    print_test_table(test_results)
    print("\n[3] ACCURACY BASED ON RESOLUTION")
    print_resolution_table(res_results)
    print("\n[4] INFERENCE TIME")
    print_inference_table(inf_results)
    print("\n[5] TRAINING TIME")
    print_training_time_table(tt_results)
    print(f"\n{div}\n")
    save_all_results(epoch_results, test_results, res_results,
                     inf_results, tt_results, save_dir)


print("✓ Reporting functions defined")

✓ Reporting functions defined

In [13]:
# CELL 10 — RUN THE FULL PIPELINE

def run_pipeline(cfg: dict):
    set_seed(cfg["seed"])
    device = auto_device(cfg["device"])
    os.makedirs(cfg["save_dir"], exist_ok=True)

    print(f'\n{"="*70}')
    print(f'  MaD-CoRN Pipeline')
    print(f'  Device      : {device}')
    print(f'  Resolutions : {cfg["resolutions"]}')
    print(f'  Split ratios: {cfg["split_ratios"]}')
    print(f'  Epochs      : {cfg["epochs"]}')
    print(f'  Smoke test  : {cfg["smoke_test"]}')
    print(f'{"="*70}\n')

    # ── Model ─────────────────────────────────────────────────────────────────
    model = MaDCoRN(in_ch=3, num_classes=2, base_ch=cfg["base_ch"])
    freeze_reservoir_weights(model)
    total, frozen = model.count_parameters()
    print(f"Model params: {total:,} total | {frozen:,} frozen\n")

    # ── Data ──────────────────────────────────────────────────────────────────
    split_datasets = None
    if cfg["smoke_test"]:
        print(">>> SMOKE TEST — synthetic data <<<\n")
        bs = cfg["batch_size"]
        train_loader = make_smoke_loader(cfg["train_res"], n=320, bs=bs)
        val_loader   = make_smoke_loader(cfg["train_res"], n=80,  bs=bs)
        test_loader  = make_smoke_loader(cfg["train_res"], n=80,  bs=bs)
        cfg = {**cfg, "epochs": min(cfg["epochs"], 3)}
    else:
        print("Loading Celeb-DF dataset...")
        data_bundle   = make_dataloaders(cfg)
        split_datasets = data_bundle["datasets"]
        train_loader  = data_bundle["loaders"]["train"]
        val_loader    = data_bundle["loaders"]["val"]
        test_loader   = data_bundle["loaders"]["test"]

    ckpt_path = os.path.join(cfg["save_dir"], f'mad_corn_multires.pt')

    # ── Training ──────────────────────────────────────────────────────────────
    print("\n" + "─"*60)
    print("TRAINING")
    print("─"*60)
    trainer = Trainer(model, train_loader, val_loader, test_loader,
                      device, cfg, ckpt_path)
    epoch_results, training_min = trainer.train()
    print(f"\nTraining done: {training_min:.1f} min  ({training_min/60:.2f} hrs)")

    # ── Primary test ──────────────────────────────────────────────────────────
    print("\n" + "─"*60)
    print("TEST EVALUATION ON COMBINED MULTI-RES TEST SET")
    print("─"*60)
    test_result  = trainer.evaluate(test_loader, load_best=True)
    test_results = [test_result]

    # ── Per-resolution evaluation ─────────────────────────────────────────────
    print("\n" + "─"*60)
    print("PER-RESOLUTION BREAKDOWN")
    print("─"*60)
    res_results = []
    inf_results = []

    for res in tqdm(cfg["resolutions"], desc="Resolution sweep", dynamic_ncols=True):
        print(f"\n  → Resolution {res}×{res}")
        if cfg["smoke_test"]:
            res_loader = make_smoke_loader(res, n=80, bs=cfg["batch_size"])
        else:
            res_ds = split_datasets["test"].subset_for_resolution(res)
            res_loader = DataLoader(
                res_ds,
                batch_size=cfg["batch_size"],
                shuffle=False,
                num_workers=cfg["num_workers"],
                pin_memory=(device.type == "cuda"),
                persistent_workers=(cfg["num_workers"] > 0),
            )

        rr = evaluate_by_resolution(model, res_loader, device, res)
        res_results.append(rr)
        print(f"    Acc={rr.accuracy*100:.2f}%  AUC={rr.auc:.4f}  "
              f"Fast={rr.fast_pct:.1f}%  Med={rr.medium_pct:.1f}%  Full={rr.full_pct:.1f}%")

        infs = measure_inference(model, res, device, batch_size=cfg["batch_size"])
        inf_results.extend(infs)
        for ir in infs:
            print(f"    [{ir.mode}]  {ir.time_per_image_ms:.3f} ms/img  |  {ir.fps:.1f} FPS")

    # ── Training time ─────────────────────────────────────────────────────────
    tt_results = [TrainingTimeResult(
        model_type='MaD-CoRN (multi-resolution training)',
        minutes=training_min,
        hours=training_min / 60,
    )]

    # ── Final report ──────────────────────────────────────────────────────────
    print_full_report(
        epoch_results, test_results, res_results,
        inf_results, tt_results, cfg["save_dir"],
    )

    return dict(
        epoch_results=epoch_results,
        test_results=test_results,
        res_results=res_results,
        inf_results=inf_results,
        tt_results=tt_results,
        model=model,
        trainer=trainer,
        split_datasets=split_datasets,
    )

In [ ]:
# CELL 11 — EXECUTE

# Edit CONFIG at the top of this file, then run this cell.
#
# Quick smoke test (no real data):
#   CONFIG["smoke_test"] = True
#
# Full run:
#   CONFIG["smoke_test"] = False
#   CONFIG["data_dir"]   = "/your/celeb_df/path"

results = run_pipeline(CONFIG)

======================================================================
  MaD-CoRN Pipeline
  Device      : cuda
  Resolutions : [128, 224, 256, 384]
  Split ratios: (0.8, 0.1, 0.1)
  Epochs      : 30
  Smoke test  : False
======================================================================

Model params: 3,428,062 total | 0 frozen

Loading Celeb-DF dataset...
Detected explicit Celeb-DF split folders: Train / Val / Test
Requested split_ratios=(0.8, 0.1, 0.1) ignored because folder splits already exist.
Using folder totals: train=80,824  val=10,104  test=10,103  total=101,031
  [train] base: real=40,288  fake=40,536  total=80,824 | expanded across 4 resolutions → 323,296
  [  val] base: real=5,036  fake=5,068  total=10,104 | expanded across 4 resolutions → 40,416
  [ test] base: real=5,036  fake=5,067  total=10,103 | expanded across 4 resolutions → 40,412

Dataset size summary
  Train | base=80,824  expanded=323,296  resolutions=[128, 224, 256, 384]
  Val   | base=10,104  expanded=40,416  resolutions=[128, 224, 256, 384]
  Test  | base=10,103  expanded=40,412  resolutions=[128, 224, 256, 384]

────────────────────────────────────────────────────────────
TRAINING
────────────────────────────────────────────────────────────

Epoch   1/30 | Loss 0.6957 | Tr Acc 0.4986 AUC 0.5009 | Val Acc 0.4984 AUC 0.5027 | P 0.0000 R 0.0000 F1 0.0000 | Unc 100.0% | LR 3.30e-08
  ✓ Checkpoint saved (Val AUC = 0.5027)

Epoch   2/30 | Loss 0.6949 | Tr Acc 0.4983 AUC 0.5016 | Val Acc 0.4984 AUC 0.5065 | P 0.0000 R 0.0000 F1 0.0000 | Unc 100.0% | LR 6.60e-08
  ✓ Checkpoint saved (Val AUC = 0.5065)

Epoch   3/30 | Loss 0.6938 | Tr Acc 0.4997 AUC 0.5014 | Val Acc 0.4984 AUC 0.5112 | P 0.0000 R 0.0000 F1 0.0000 | Unc 100.0% | LR 9.90e-08
  ✓ Checkpoint saved (Val AUC = 0.5112)

Epoch   4/30 | Loss 0.6934 | Tr Acc 0.5010 AUC 0.5023 | Val Acc 0.5071 AUC 0.5144 | P 0.5191 R 0.2351 F1 0.3236 | Unc 100.0% | LR 1.32e-07
  ✓ Checkpoint saved (Val AUC = 0.5144)

Epoch   5/30 | Loss 0.6933 | Tr Acc 0.5014 AUC 0.5020 | Val Acc 0.5089 AUC 0.5123 | P 0.5063 R 0.8463 F1 0.6336 | Unc 100.0% | LR 1.65e-07

Epoch   6/30 | Loss 0.6933 | Tr Acc 0.5025 AUC 0.5033 | Val Acc 0.5150 AUC 0.5193 | P 0.5113 R 0.7498 F1 0.6080 | Unc 100.0% | LR 1.98e-07
  ✓ Checkpoint saved (Val AUC = 0.5193)

Epoch   7/30 | Loss 0.6932 | Tr Acc 0.5042 AUC 0.5051 | Val Acc 0.5137 AUC 0.5193 | P 0.5163 R 0.4845 F1 0.4999 | Unc 100.0% | LR 2.31e-07

Epoch   8/30 | Loss 0.6931 | Tr Acc 0.5058 AUC 0.5079 | Val Acc 0.5232 AUC 0.5274 | P 0.5205 R 0.6268 F1 0.5687 | Unc 100.0% | LR 2.64e-07
  ✓ Checkpoint saved (Val AUC = 0.5274)

Epoch   9/30 | Loss 0.6929 | Tr Acc 0.5096 AUC 0.5127 | Val Acc 0.5187 AUC 0.5222 | P 0.5219 R 0.4810 F1 0.5006 | Unc 100.0% | LR 2.97e-07

Epoch  10/30 | Loss 0.6927 | Tr Acc 0.5122 AUC 0.5173 | Val Acc 0.5231 AUC 0.5320 | P 0.5272 R 0.4761 F1 0.5003 | Unc 100.0% | LR 3.30e-07
  ✓ Checkpoint saved (Val AUC = 0.5320)

Epoch  11/30 | Loss 0.6924 | Tr Acc 0.5181 AUC 0.5254 | Val Acc 0.5164 AUC 0.5427 | P 0.5331 R 0.2887 F1 0.3746 | Unc 100.0% | LR 3.63e-07
  ✓ Checkpoint saved (Val AUC = 0.5427)

Epoch  12/30 | Loss 0.6917 | Tr Acc 0.5286 AUC 0.5385 | Val Acc 0.5176 AUC 0.5475 | P 0.5343 R 0.2974 F1 0.3821 | Unc 100.0% | LR 3.96e-07
  ✓ Checkpoint saved (Val AUC = 0.5475)

Epoch  13/30 | Loss 0.6904 | Tr Acc 0.5396 AUC 0.5532 | Val Acc 0.5179 AUC 0.5543 | P 0.5423 R 0.2483 F1 0.3406 | Unc 100.0% | LR 4.29e-07
  ✓ Checkpoint saved (Val AUC = 0.5543)

Epoch  14/30 | Loss 0.6886 | Tr Acc 0.5463 AUC 0.5603 | Val Acc 0.5212 AUC 0.5629 | P 0.5555 R 0.2271 F1 0.3224 | Unc 100.0% | LR 4.62e-07
  ✓ Checkpoint saved (Val AUC = 0.5629)

Epoch  15/30 | Loss 0.6869 | Tr Acc 0.5506 AUC 0.5650 | Val Acc 0.5222 AUC 0.5588 | P 0.5482 R 0.2700 F1 0.3618 | Unc 98.3% | LR 4.95e-07

Epoch  16/30 | Loss 0.6861 | Tr Acc 0.5515 AUC 0.5668 | Val Acc 0.5238 AUC 0.5663 | P 0.5585 R 0.2410 F1 0.3367 | Unc 93.5% | LR 5.28e-07
  ✓ Checkpoint saved (Val AUC = 0.5663)

Epoch  17/30 | Loss 0.6853 | Tr Acc 0.5552 AUC 0.5707 | Val Acc 0.5322 AUC 0.5714 | P 0.5667 R 0.2860 F1 0.3802 | Unc 92.8% | LR 5.61e-07
  ✓ Checkpoint saved (Val AUC = 0.5714)

Epoch  18/30 | Loss 0.6848 | Tr Acc 0.5556 AUC 0.5731 | Val Acc 0.5264 AUC 0.5689 | P 0.5605 R 0.2581 F1 0.3535 | Unc 90.3% | LR 5.94e-07

Epoch  19/30 | Loss 0.6844 | Tr Acc 0.5568 AUC 0.5752 | Val Acc 0.5314 AUC 0.5797 | P 0.5779 R 0.2438 F1 0.3429 | Unc 88.1% | LR 6.27e-07
  ✓ Checkpoint saved (Val AUC = 0.5797)

Epoch 21/30 [train]:  83%|████████▎ | 8362/10100 [30:34<07:03,  4.11it/s, loss=0.7097, samples=267,648]IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)

Epoch 24/30 [train]:  23%|██▎       | 2331/10100 [08:27<21:33,  6.01it/s, loss=0.6907, samples=74,656]IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)

Epoch 24/30 [train]:  49%|████▊     | 4923/10100 [17:54<18:23,  4.69it/s, loss=0.7226, samples=157,536]IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)

Epoch 26/30 [train]:  34%|███▍      | 3417/10100 [12:31<24:03,  4.63it/s, loss=0.6197, samples=109,440]IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)

Epoch 26/30 [val]:  45%|████▍     | 565/1264 [00:24<00:43, 16.22it/s, loss=0.6469, samples=18,168]      IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)

Epoch 27/30 [train]:  26%|██▋       | 2674/10100 [09:44<29:53,  4.14it/s, loss=0.6868, samples=85,568]IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)

Epoch  29/30 | Loss 0.6795 | Tr Acc 0.5703 AUC 0.5950 | Val Acc 0.5651 AUC 0.5905 | P 0.5548 R 0.6731 F1 0.6082 | Unc 88.2% | LR 9.57e-07

Epoch 30/30 [train]:  54%|█████▍    | 5479/10100 [20:07<19:31,  3.94it/s, loss=0.7363, samples=175,392]